### PR TITLE
WIP: create testcluster with kubeadm

### PR DESCRIPTION
**Pull request by cheld**
I have cut out the existing build and just implemented enough to create a cluster with kubeadm

Status
It seems that kubeadm requires Ubuntu 16.04 while Travis supports only Ubuntu 14

I did not try to upgrade package manually, so far

### CODE REVIEW

**Comment by cheld** [comment]
An alternative approach might be https://github.com/Mirantis/kubeadm-dind-cluster

Tested, works quite nice. Not sure if we should use it

**Comment by cheld** [comment]
@floreks , @maciaszczykm WDYT

**Comment by cheld** [comment]
Any opinion how we should continue?

**Comment by floreks** [comment]
I think that for now we do not need to migrate from hyperkube. Dashboard uses cluster for few simple click tests only. Most of tests (frontend and backend) do not require cluster to be present. Once travis upgrades to ubuntu 16 we can think about kubeadm again.

**Comment by cheld** [comment]
Ok, lets postpone until we must migrate...

**Pull request closed without merging**
