### PR TITLE
Introduce angular router and add error handling

### PR DESCRIPTION
**Pull request by floreks**
This PR is far from finished yet :slightly_smiling_face: 

Current changes:
- Refactor error handling on the backend to a single package. All errors should be created using our internal package.
- Start replacement process of `ui-router` to `angular-router`. 

What's missing:
- [x] Proper query params handling. By default, it should at least have `namespace` query set to `default` namespace.
- [x] Proper path params handling for detail views. Only `Cluster Role` details view is working right now.
- [x] Remove usage of old `ui-router` classes i.e. `StateService`, `Transition`, etc. in all places...
- [x] ...and replace them with angular router equivalents.
- [x] Breadcrumbs.
- [x] Exec, logs, search etc.
- [x] Final review. Check every state.

Closes https://github.com/kubernetes/dashboard/issues/3869.

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@floreks I have finally finished my PR, are there any pointers where to start besides:

> Remove usage of old ui-router classes i.e. StateService, Transition, etc. in all places and replace them with angular router equivalents.

**Comment by floreks** [comment]
Breadcrumbs and action services have to be adjusted to work with angular router. This is a good start. I can work on fixing login flow.

**Comment by maciaszczykm** [comment]
I am working on breadcrumbs right now. Have some initial changes, but it is quite a lot to do here 🙂

**Comment by maciaszczykm** [comment]
I am testing it.

**Pull request merged**
