### PR TITLE
Word-break for events and pods tables and logs view

### PR DESCRIPTION
**Pull request by maciaszczykm**
Added small fix for issue mentioned in pull request #263. Now message cells size shouldn't cause anymore problems. However, column widths are still an issue. The only solution which comes to my mind at the moment is making their values fixed (in percents). Do you have any suggestions?

### CODE REVIEW

**Comment by bryk** [comment]
Check lint errors

**Comment by bryk** [comment]
PTAL

**Comment by maciaszczykm** [comment]
Fixed lint errors. PTAL

**Comment by bryk** [comment]
LGTM

**Pull request merged**
