### PR TITLE
align actionbar actions with context actions

### PR DESCRIPTION
**Pull request by ajatprabha**
This PR is to align action-bar actions with context actions in list menu for every resource. WIP towards #3440

### CODE REVIEW

**Comment by maciaszczykm** [comment]
We have a misunderstanding here :) I was not so clear in the issue, so let's rephrase:

To align items from context-menu (list view) and action bars (details view) you need to make sure that in both views we have same actions for every resource.

For example for Pods I'd like to use logs, exec, edit and delete from list view and details view.

It is not about CSS alignment, but if it works you can leave it and we will review. The real issue is a little bit more time consuming :)

**Comment by ajatprabha** [comment]
Okay, got it. I'll see if I can make this work and update the PR.

**Comment by ajatprabha** [comment]
Both menus should have same actions in detail and list views, right?

**Comment by maciaszczykm** [comment]
Thank you for your patience, I am reviewing it 🙂

**Comment by maciaszczykm** [comment]
/lgtm
/approve

Great piece of work. What I like is that it is clean and code is in one place. Thanks a lot! We can iterate on it to make these actions more visible, but it is already good.

**Comment by ajatprabha** [comment]
Thank you @maciazsczykm 🙂

**Comment by ajatprabha** [comment]
Thank you @maciaszczykm 🙂

**Pull request merged**
