### PR TITLE
Update backend kubernetes client dependencies to newest HEAD

### PR DESCRIPTION
**Pull request by floreks**
As we want to support PetSets, kubernetes client dependencies need to be updated. There are issues with `godep` because our import path is different than our backend code path and I couldn't find a way to update them using godep, so I've updated it manually.

Checkout and test it please as also our code needed some changes.

If anyone knows a way to update everything correctly with godeps, it would be great.

~~**Go tests need to be fixed. Do not merge.**~~

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/785)

### CODE REVIEW

**Comment by bryk** [comment]
Reviewed 11 of 2008 files at r1.
Review status: 11 of 1919 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/785)*

**Comment by floreks** [comment]
Tests fixed. Let's wait for travis.

**Comment by bryk** [comment]
LGTM

**Comment by bryk** [comment]
Thanks :)

**Pull request merged**
