### PR TITLE
Fix ts errors

### PR DESCRIPTION
**Pull request by shu-mutou**
Fix ts errors in favor of gts 1.0.0

- [x] fix format errors by `prettier`
- [x] fix `deprecation` errors by `gts`

`ban-ts-ignore` and `interface-over-type-literal` rules for `gts` are remained as ignore.

### CODE REVIEW

**Comment by maciaszczykm** [comment]
This changes a lot. Why do we need this? Previous code format was pretty simple, now it seems a bit custom to me.

cc @floreks WDYT?

**Comment by maciaszczykm** [comment]
Okay, I see. Master is failing since the: https://travis-ci.org/kubernetes/dashboard/builds/525741804 (https://github.com/kubernetes/dashboard/pull/3761)

cc @jeefy

**Comment by shu-mutou** [comment]
> This changes a lot. Why do we need this? Previous code format was pretty simple, now it seems a bit custom to me.
> 
> cc @floreks WDYT?

As you said, simple is the best. :) And I was also seeking the way to fix them little by little, but not found as now, especially the way to avoid `prettier`'s error. This code formatting is default settings of gts, so this might be acceptable for many people, I think. I'm not picky about formatting, so any way is fine for me. Uhm.... but I don't like to use operators without spaces.

**Comment by shu-mutou** [comment]
This PR contains three commits. The 1st one is only formatting typescripts. So could you guys review 2nd and 3rd commits?
[1] Fix typescript formatting in favor of gts 1.0.0 https://github.com/kubernetes/dashboard/pull/3795/commits/fbe1c37dad72a863b5a9ad230babf85dad143de8
[2] Fix deprecated errors in favor of gts 1.0.0 https://github.com/kubernetes/dashboard/pull/3795/commits/5b71890371cb43dcaac0811aa23fd3d1e584bdd9
[3] Ignore version.ts in gts and prettier https://github.com/kubernetes/dashboard/pull/3795/commits/9e4d84e2e593c298a3de4c5155f7ccbefd65297d

**Comment by maciaszczykm** [comment]
@shu-mutou Totally makes sense. We have to use it. Perhaps in the future we will adjust it.

Thanks for fixing the issue.

/lgtm
/approve

**Comment by eloyekunle** [comment]
@shu-mutou Should we consider integrating `prettier` into our workflow?

**Comment by maciaszczykm** [comment]
@eloyekunle I think it woule be better to restore gts < v1.0. It was more readable for me.

cc @floreks

**Comment by shu-mutou** [comment]
@eloyekunle @maciaszczykm @floreks If we keep to use gts and to update in the future, we can use `prettier` that gts integrates and its settings. To update gts to 1.0.0, we need to change so many files and it becomes difficult to merge other PRs. But it would be a good chance to update gts for us, because we would be in `feature freeze` period before new release. Also, I think the formatting of gts 1.0.0 would be acceptable for many people and it looks good for me.

**Comment by jeefy** [comment]
My two cents -- the [Release Notes](https://github.com/kubernetes-sigs/release-notes) Site currently uses `prettier` and I have zero complaints. And I'm always a fan of updating libraries when it's warranted, and this might be warranted.

**Comment by shu-mutou** [comment]
I will try to investigate again how to use gts 1.0.0 with custom `prettier` setting. 😉

**Comment by shu-mutou** [comment]
I'm trying at #4034, please see it. 😉

**Pull request merged**
