### PR TITLE
Correct the resourcechannels comment

### PR DESCRIPTION
**Pull request by donggangcj**

### CODE REVIEW

**Comment by donggangcj** [comment]
I close last pr and create a new pr.

**Comment by maciaszczykm** [comment]
Did you sign it with correct email? Is the commit marked with this email?

**Comment by donggangcj** [comment]
I signed it

**Comment by jeefy** [comment]
Seconding what @maciaszczykm said. There must be something different between the signed CLA and the commit.

If you're certain the emails match up, or there is another issue, please review the CLA document (https://github.com/kubernetes/community/blob/master/CLA.md) and, if necessary, file a ticket with the CNCF (directions at the bottom of the CLA document)

**Comment by donggangcj** [comment]
Thanks! The email of commit is consistent with the CLA  ,I am not sure where the problem is.
image
image

**Comment by shu-mutou** [comment]
In my case (sign up as an employee), I needed to click `Sign up to contribute to this project as an employee` in `https://identity.linuxfoundation.org/projects/cncf` once more after receiving registration confirmation mail and logging into LF page. Then "CNCF-NEC" was shown not only "Authorized CNCF Contributors" in `My Account` page. After that, I could pass CLA check.

**Pull request merged**
