### PR TITLE
Integrate material icons and roboto fonts with gulp build pipeline

### LINKED ISSUE #529: Wrong display of icons in producion
##### Environment
```
Dashboard version: HEAD
Kubernetes version: HEAD
Operating system: Ubuntu 14.04 LTS
Node.js version: v4.2.3
Go version: 1.5.1
```

##### Steps to reproduce
Checkout HEAD of master branch of dashboard. If needed, run `npm install` to get the recent icons changes. Run `gulp serve:prod` to serve in production.

##### Observed result
The icons (e.g. in the deploy form) are not displayed correctly:

dashboard_issue

##### Expected result
The material design icons should be displayed correctly. The text on the screen should not overlap.

##### Comments
I think this was caused by 949f4c976a042ed9728753cf6d89eb803fd96276. When I check out a previous commit (e.g. fed0c9fed7f1a42a416005a7aa4b866999036f1a), there is no issue.

### PR DESCRIPTION
**Pull request by floreks**
Fixes #529

I've reverted my commit on this branch and in result #531 was closed automatically because there were no changes detected in PR. 

This time I've used only bower dependencies and advantages of wiredep. I've only added tasks to copy needed icon/font files to dist.

@bryk @maciaszczykm PTAL

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/548)

### CODE REVIEW

**Comment by bryk** [comment]
:lgtm:

Can you verify that this works when running through in-cluster proxy? I.e., api/v1/proxy/namespaces/.... And then merge. 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/548#-:-KDNfEGL1455Yu3Hh5oM:2029458016)*

**Comment by floreks** [comment]
It runs fine on `kubectl proxy` but I'm not sure how reliable my tests are as I'm running only local cluster.

**Comment by bryk** [comment]
I meant: push it to your private dockerhub, then deploy it and access. If it works, then perfect :) If not, then fix.

**Comment by floreks** [comment]
Yes, that's definitely more reliable test :) I've tested it on local registry and it works. 

zrzut ekranu z 2016-03-22 09-43-11

**Comment by bryk** [comment]
Perfect, shipit :shipit:

**Pull request merged**
