### PR TITLE
Update README.md for new release & URL

### PR DESCRIPTION
**Pull request by TisonKun**
ref #4701

cc @floreks

### CODE REVIEW

**Comment by floreks** [comment]
As most people are using v2 version we might change that already. We need to redesign the readme a bit anyway.

@maciaszczykm are you in favor of merging it?

**Comment by shu-mutou** [comment]
/lgtm
@floreks @maciaszczykm Documentations under `/docs` are already using `v2.0.0-beta8`. Merging this may be good as reminder when updating to new beta or RC.

**Comment by TisonKun** [comment]
@shu-mutou possibly we can introduce a script when bumping version.

**Pull request merged**
