### PR TITLE
Japanese localization of NodeDetail, EventsPage and DeployPage

### PR DESCRIPTION
**Pull request by Yamagami-Takuma**
Japanese localization of NodeDetail, EventsPage and DeployPage.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/927)

### CODE REVIEW

**Comment by Yamagami-Takuma** [comment]
@f-higashi Can you review?

**Comment by f-higashi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[i18n/messages-ja.xtb, line 532 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/927#-KKkZB8MELaOoYZOIYbz:-KKkZB8NhgbgWI5-gEGr:973190732) ([raw file](https://github.com/kubernetes/dashboard/blob/639760c4c6c957bd797141e05d7ea225dc28670f/i18n/messages-ja.xtb#L532)):*
> ```
> 	<translation id="6790809836331060255" key="MSG_NODE_DETAIL_POD_CIDR_LABEL" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Label 'Pod CIDR' for the node external ID displayed on its details page.">ポッド CIDR</translation>
> 	<translation id="3266021684307458699" key="MSG_NODE_DETAIL_PROVIDER_ID_LABEL" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Label 'Provider ID' for the node external ID displayed on its details page.">プロバイダー ID</translation>
> 	<translation id="3231786643565186812" key="MSG_NODE_DETAIL_UNSCHEDULABLE_LABEL" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Label 'Unschedulable' for the node external ID displayed on its details page.">予定不可</translation>
> ```

I cannot understand this.
How about `スケジューリング不可`

---

*[i18n/messages-ja.xtb, line 543 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/927#-KKka2_vjisigbZdKOoA:-KKka2_w2aFXEeNUZd80:-1688115936) ([raw file](https://github.com/kubernetes/dashboard/blob/639760c4c6c957bd797141e05d7ea225dc28670f/i18n/messages-ja.xtb#L543)):*
> ```
> 	<translation id="6413199566846581831" key="MSG_EVENTS_COUNT_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label 'Count' for event count column of the events table (events list page).">回数</translation>
> 	<translation id="2466179008986855362" key="MSG_EVENTS_FIRST_SEEN_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label 'First seen' for the respective column of the events table (events list page).">初回発生</translation>
> 	<translation id="478958642026475488" key="MSG_EVENTS_LAST_SEEN_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label 'Last seen' for the respective column of the events table (events list page).">最終発生</translation>
> ```

I like `初回` and `直近`

---

*[i18n/messages-ja.xtb, line 544 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/927#-KKkay5LRzxrwbQXucht:-KKkay5LRzxrwbQXuchu:945844364) ([raw file](https://github.com/kubernetes/dashboard/blob/639760c4c6c957bd797141e05d7ea225dc28670f/i18n/messages-ja.xtb#L544)):*
> ```
> 	<translation id="2466179008986855362" key="MSG_EVENTS_FIRST_SEEN_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label 'First seen' for the respective column of the events table (events list page).">初回発生</translation>
> 	<translation id="478958642026475488" key="MSG_EVENTS_LAST_SEEN_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label 'Last seen' for the respective column of the events table (events list page).">最終発生</translation>
> 	<translation id="141678852134483176" key="MSG_EVENTS_NO_EVENTS_TITLE" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Title 'No events were found', which appears in the center of the events page when there are no events to display">イベントがありません</translation>
> ```

How about `イベントが見つかりません`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/927)*

**Comment by Yamagami-Takuma** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[i18n/messages-ja.xtb, line 532 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/927#-KKkZB8MELaOoYZOIYbz:-KKlCyOh1vLKnPe4-g-r:1920760566) ([raw file](https://github.com/kubernetes/dashboard/blob/639760c4c6c957bd797141e05d7ea225dc28670f/i18n/messages-ja.xtb#L532)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> I cannot understand this.
> How about `スケジューリング不可`
</details>
I fixed.

---

*[i18n/messages-ja.xtb, line 543 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/927#-KKka2_vjisigbZdKOoA:-KKlCze2ukIStlnatGLt:1920760566) ([raw file](https://github.com/kubernetes/dashboard/blob/639760c4c6c957bd797141e05d7ea225dc28670f/i18n/messages-ja.xtb#L543)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> I like `初回` and `直近`
</details>
I fixed.

---

*[i18n/messages-ja.xtb, line 544 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/927#-KKkay5LRzxrwbQXucht:-KKlCzwRf45ITsGcQLAH:1920760566) ([raw file](https://github.com/kubernetes/dashboard/blob/639760c4c6c957bd797141e05d7ea225dc28670f/i18n/messages-ja.xtb#L544)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> How about `イベントが見つかりません`
</details>
I fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/927)*

**Comment by f-higashi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/927)*

**Comment by f-higashi** [comment]
LGTM

@maciaszczykm 
You can merge this :)

**Pull request merged**
