### PR TITLE
fix(ingress): use web as backend when kong is not enabled

### PR DESCRIPTION
**Pull request by sjoukedv**
It's possible to disable the kong proxy, but the ingress backend is hardcoded to the kong proxy

### CODE REVIEW

**Comment by sjoukedv** [comment]
@desaintmartin do you have time for a quick review?

**Comment by shu-mutou** [comment]
@sjoukedv we fixed ci, so could you rebase to current master branch?

**Comment by sjoukedv** [comment]
> @sjoukedv we fixed ci, so could you rebase to current master branch?

@shu-mutou done, don't know where the invalid commit messages are coming from. I can create an entire new branch if it doesn't work with this one.

**Comment by floreks** [comment]
I think it would be best if you apply your changes to the latest master and create a new branch.

**Comment by sjoukedv** [comment]
Closed in favor of https://github.com/kubernetes/dashboard/pull/8853

**Pull request closed without merging**
