### PR TITLE
persistent volume claims

### PR DESCRIPTION
**Pull request by cheld**
@batikanu 
started with persistent volume claims backend. Basically, the server api calls with pagination. 

Next steps,
- check UI mockup to understand the API requirements
- cleanup and tests
- all endpoints

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1106)

### CODE REVIEW

**Comment by batikanu** [comment]
>  endpoints
Small comment otherwise LGTM

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/backend/resource/common/resourcechannels.go, line 494 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1106#-KOiY7GH7SB3lJkAab5e:-KOiY7GH7SB3lJkAab5f:bt1te3l) ([raw file](https://github.com/kubernetes/dashboard/blob/cd212e7563500efd810ff417d1af9221c0213a93/src/app/backend/resource/common/resourcechannels.go#L494)):*
> ```Go
> 
> 
> func GetPersistentVolumeClaimListChannel(client client.PersistentVolumeClaimsNamespacer, nsQuery *NamespaceQuery, numReads int) PersistentVolumeClaimListChannel {
> ```

No comment for functions and structs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1106#-:-KOiZ25Pexy4urYQQBWX:blfxri7)*

**Comment by maciaszczykm** [comment]
Add comments and use `gofmt` formatter on changed files in order to keep Go report green.

Code looks good.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/backend/resource/common/resourcechannels.go, line 494 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1106#-KOiY7GH7SB3lJkAab5e:-KOibsHYd2Uezd2vkQhQ:bgp1dbw) ([raw file](https://github.com/kubernetes/dashboard/blob/cd212e7563500efd810ff417d1af9221c0213a93/src/app/backend/resource/common/resourcechannels.go#L494)):*
<details><summary><i>Previously, batikanu (Batikan Urcan) wrote…</i></summary>
> No comment for functions and structs?
</details>
Yeah, we need comments for all public functions and structures. Easy to remember, because their names start with capital letters.

---

*[src/app/backend/resource/persistentvolumeclaim/persistentvolumeclaimlist.go, line 40 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1106#-KOicPirxN8jqSW57jap:-KOicPirxN8jqSW57jaq:b-pc81z9) ([raw file](https://github.com/kubernetes/dashboard/blob/cd212e7563500efd810ff417d1af9221c0213a93/src/app/backend/resource/persistentvolumeclaim/persistentvolumeclaimlist.go#L40)):*
> ```Go
> }
> 
> func GetPersistentVolumeClaimList(client *client.Client, nsQuery *common.NamespaceQuery, pQuery *common.PaginationQuery) (*PersistentVolumeClaimList, error) {
> ```

Missing comments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1106#-:-KOicWGcr7rvj4Ep0usW:b-ya3c71)*

**Comment by cheld** [comment]
There is no build step (gulp) that checks formatting or style? (I assume it was easy to spot because I had some very long lines)

BTW: 

> Merging #1106 into master will not change coverage

although I have not added tests yet

**Comment by maciaszczykm** [comment]
> There is no build step (gulp) that checks formatting or style? (I assume it was easy to spot because I had some very long lines)

There is, but only for frontend at the moment.

> BTW:

>>Merging #1106 into master will not change coverage

>although I have not added tests yet

@cheld Yes... Currently codecov works only for frontend.

**Comment by maciaszczykm** [comment]
Only Go code checker, that we have at the moment is https://goreportcard.com/report/github.com/kubernetes/dashboard.

**Comment by cheld** [comment]
Goreport only works on master and not PRs, I assume

**Comment by maciaszczykm** [comment]
> Goreport only works on master and not PRs, I assume

@cheld Yes. You can always use `gofmt`, `golint` and other commands locally on your workstation.

**Comment by bryk** [comment]
@batikanu @maciaszczykm Please keep reviewing this :)

**Comment by cheld** [comment]
According to this UX  ( https://projects.invisionapp.com/share/XZ7RITOQD#/screens ) there will be a top menu entry.

So, we will need 
- a list page and list end-point 
- details end-point and details end-point

Info shown by kubectl
```
$ kubectl get pvc
NAME        STATUS    VOLUME    CAPACITY   ACCESSMODES   AGE
myclaim-1   Bound     pv0001    0                        12s
```

```
$ kubectl describe pvc myclaim-1
Name:		myclaim-1
Namespace:	default
Status:		Bound
Volume:		pv0001
Labels:		<none>
Capacity:	0
Access Modes:	
```

We probably want to enhance the information for the UI. I consider it as a starting point

**Comment by cheld** [comment]
First service done.

PTAL

**Comment by batikanu** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1106#-:-KOsaxeibaL_LoghI0nT:bnfp4nl)*

**Comment by bryk** [comment]
Btw, travis is still broken for us. Ignore it.

**Comment by cheld** [comment]
I ran the test locally. I created a PR that fixes one of the travis issues

**Pull request merged**
