### PR TITLE
Support auto skipping login page

### PR DESCRIPTION
**Pull request by Thearas**
Impl #7572.

Automatically skip the login page when query parameter `skipLoginPage=true` .

### CODE REVIEW

**Review by maciaszczykm — APPROVED** [review]
/lgtm

**Comment by maciaszczykm** [comment]
@Thearas you will need to fix tests before it can be merged.

**Comment by Thearas** [comment]
> @Thearas you will need to fix tests before it can be merged.

@maciaszczykm Done.

**Pull request merged**
