### PR TITLE
Assume valid when name validation errors.

### PR DESCRIPTION
**Pull request by bryk**
Addresses #373

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/393)

### CODE REVIEW

**Comment by bryk** [comment]
@codegoblins

**Comment by bryk** [comment]
@codegoblins can you review?

**Comment by codegoblins** [comment]
With this patch I was able to create a service & RC from the deploy flow called 'runtest':

screen shot 2016-02-18 at 1 28 14 pm

However, I am unable to do anything else from the dashboard e.g. edit pod count, view details:
screen shot 2016-02-18 at 1 30 15 pm

It seems like [kubernetes/kubernetes/21464](https://github.com/kubernetes/kubernetes/issues/21464) is the real culprit here. If we want to fix this from the frontend side, we're just pushing the problem further down the deployment/administration flow.

**Comment by bryk** [comment]
> However, I am unable to do anything else from the dashboard e.g. edit pod count, view details:

True. You'll be able to access it when running the Dashboard inside a cluster.

**Comment by bryk** [comment]
> It seems like kubernetes/kubernetes/21464 is the real culprit here. If we want to fix this from the frontend side, we're just pushing the problem further down the deployment/administration flow.

You're correct. The linked issue is the real problem. This PR, however, addresses problem with our UI where we assume that name is invalid when we cannot determine its correctness. I believe we should assume it is valid because potential problems will be caught later.

**Comment by codegoblins** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/393)*

**Comment by codegoblins** [comment]
Confirmed that the problem is nonexistant when running from within the cluster.

**Comment by maciaszczykm** [comment]
Should it be merged?

**Comment by bryk** [comment]
I say yes :) Merging.

**Pull request merged**
