### PR TITLE
Fix typo: requestes -> requests

### PR DESCRIPTION
**Pull request by kirillDanshin**

### CODE REVIEW

**Comment by kirillDanshin** [comment]
I signed CLA

**Comment by kirillDanshin** [comment]
Travis build is failed, but I don't think it's related to the change

**Comment by shu-mutou** [comment]
/lgtm
I will restart travis job. The errors seem just networking issue.

**Comment by kirillDanshin** [comment]
@shu-mutou Thanks.

Seems like github is currently unstable, maybe that's the reason why Travis build failed last time
Github 504


/assign @konryd

**Pull request merged**
