### PR TITLE
Add labels to workload status charts

### PR DESCRIPTION
**Pull request by maciaszczykm**
Zrzut ekranu 2021-04-15 o 16 22 28

Closes https://github.com/kubernetes/dashboard/issues/5078.

### CODE REVIEW

**Comment by shu-mutou** [comment]
Could you update translation files?

**Comment by maciaszczykm** [comment]
@shu-mutou PTAL

**Comment by shu-mutou** [comment]
@maciaszczykm Thank you! But `Static Check` on CI detects changes for translation files. https://github.com/kubernetes/dashboard/runs/2360849927?check_suite_focus=true#step:8:144

Could you check differences between CI and your environment?

**Comment by maciaszczykm** [comment]
I'm using node v14.11.0. I'll get commits from master and run `npm ci` once more. Perhaps being on Mac also has some impact.

**Comment by maciaszczykm** [comment]
@shu-mutou No changes. It seems that it will not change. My guess would be the operating system difference.

**Comment by maciaszczykm** [comment]
I have plans to setup my workspace once more in the close future, so then I'll verify it closely.

**Comment by maciaszczykm** [comment]
@shu-mutou No changes 😞 At this point I don't have any other idea...

**Comment by floreks** [comment]
Has to be an angular issue with the i18n service.

/lgtm

**Pull request merged**
