### PR TITLE
Add "language/xx" to "labels" in all i18n OWNERS

### PR DESCRIPTION
**Pull request by atoato88**
This PR adds "language/xx" to "labels" key in all `i18n/xx/OWNERS` files.
By this change, if any files in `i18n/xx/` has changed, "language/xx" label is added in automatically.

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Please remove approvers for `zh` for now.

**Comment by atoato88** [comment]
@maciaszczykm 
I've updated commit. Please check this.

**Comment by maciaszczykm** [comment]
Thank you :)

/lgtm

**Pull request merged**
