### PR TITLE
Extract replica set card to a separate directive

### PR DESCRIPTION
**Pull request by bryk**
* this is a refactoring change - no functional changes
* added missing tests
* added missing module dependency (tests found it)
* this is a prerequisite PR for future work on the card

### CODE REVIEW

**Comment by bryk** [comment]
@floreks @maciaszczykm Can you review?

**Comment by maciaszczykm** [comment]
LGTM

**Comment by floreks** [comment]
LGTM too.

**Comment by bryk** [comment]
Thank you!

**Pull request merged**
