### PR TITLE
Support for viewing completed/inactive CronJob jobs 

### PR DESCRIPTION
**Pull request by jeefy**
Hi all! This directly addresses #2786

I created an additional function that pulls only completed Jobs for a given CronJob.
Next I shimmed in "Inactive Jobs" in the CronJobDetail Type as well as in the Angular page under the "Active Jobs" card.

Tested locally via minikube (v1.10, v1.9, v1.8)

Let me know if there's anything I need to change or fix!

### CODE REVIEW

**Comment by bryk** [comment]
@pengx17 Can you also review this and LGTM/comment?

**Comment by pengx17** [comment]
/LGTM, btw @jeefy I do not find changes related to regular Jobs. Do you think it is better to include these to Job detail pages as well?

**Comment by jeefy** [comment]
Thanks for the feedback/merge!

@pengx17 This is to display jobs owned by a CronJob specifically. It wouldn't apply to a Job itself. If there are more use cases of jobs spawning other jobs (a la HPC workflow) it might make sense. 

It might be a good idea to eventually have the ability to display objects that have an OwnerRef of the currently-viewed object. That would probably solve this across the board. :)

**Pull request merged**
