### PR TITLE
Japanese localization of some resource detail page

### PR DESCRIPTION
**Pull request by Yamagami-Takuma**
Japanese localization of some resource detail page.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/868)

### CODE REVIEW

**Comment by Yamagami-Takuma** [comment]
@f-higashi Can you review this?

**Comment by f-higashi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[i18n/messages-ja.xtb, line 183 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtFmPD2gDZT_RNBLTu:-KJtFmPD2gDZT_RNBLTv:-826440900) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L183)):*
> ```
> 	<translation id="58035047264145239" key="MSG_TIME_UNIT_YEAR_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Time units label, a single year.">1 年</translation>
> 	<translation id="270964281826728358" key="MSG_TIME_UNIT_YEARS_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Time units label, many years (plural).">年</translation>
> 	<translation id="6450429370516938913" key="MSG_TIME_NOT_YET_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label saying that a certain action has not happened yet.">起動中</translation>
> ```

`起動中` may mislead.
How about `起動前`

---

*[i18n/messages-ja.xtb, line 184 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtFirjNZSGyyOP82GE:-KJtFirk62hiqYhspO6y:1680285081) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L184)):*
> ```
> 	<translation id="270964281826728358" key="MSG_TIME_UNIT_YEARS_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Time units label, many years (plural).">年</translation>
> 	<translation id="6450429370516938913" key="MSG_TIME_NOT_YET_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label saying that a certain action has not happened yet.">起動中</translation>
> 	<translation id="3299077321377208801" key="MSG_TIME_NOW_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label saying that a certain action happened just now.">今</translation>
> ```

How about `たった今`

---

*[i18n/messages-ja.xtb, line 194 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtHPa0Mzqe-uKuyZrd:-KJtHPa1-9cSW89I4swu:-2006187996) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L194)):*
> ```
> 	<translation id="3935199608753533539" key="MSG_JOB_STATUS" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Job status. Appears in details section.">状態</translation>
> 	<translation id="8414020124021085200" key="MSG_JOB_PODS_SUCCEEDED" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Status of succeeded pods. Appears next to number of succeeded pods.">成功</translation>
> 	<translation id="8886503654312436063" key="MSG_JOB_PODS_ACTIVE" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Status of active pods. Appears next to number of active pods.">アクティブ</translation>
> ```

How about `稼動中`

---

*[i18n/messages-ja.xtb, line 208 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtN1vWUHGpA_kxM53M:-KJtN1vWUHGpA_kxM53N:-1293830141) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L208)):*
> ```
> 	<translation id="120027411367401418" key="MSG_RC_DETAIL_RESOURCE_DETAILS_TITLE" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Title 'Resource details' at the top of the replication controller details page.">リソース詳細</translation>
> 	<translation id="4421278951463952163" key="MSG_RC_DETAIL_DETAILS_SUBTITLE" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Subtitle 'Details' for the left section with general information about a replication controller on the replication controller details page.">詳細</translation>
> 	<translation id="88788676408939710" key="MSG_RC_DETAIL_NAMESPACE_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label 'Namespace' for the replication controller namespace on the replication controller details page.">名前空間</translation>
> ```

It is `ネームスペース`.

---

*[i18n/messages-ja.xtb, line 220 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtR-WMm8DtEFDc1aJR:-KJtR-WMm8DtEFDc1aJS:-615356734) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L220)):*
> ```
> 	<translation id="6107745197793205489" key="MSG_RC_DETAIL_PODS_PENDING_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="The message says that that many pods are pending (replication controller details page)."><ph name="PODS_COUNT" /> 待機中</translation>
> 	<translation id="7172190985346183509" key="MSG_RC_DETAIL_PODS_FAILED_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="The message says that that many pods have failed (replication controller details page)."><ph name="PODS_COUNT" /> の失敗</translation>
> 	<translation id="3147497997693039812" key="MSG_RC_DETAIL_PODS_DESIRED_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="The message says that that many pods are desired to run (replication controller details page)."><ph name="PODS_COUNT" /> の要望</translation>
> ```

I like `要求`.

---

*[i18n/messages-ja.xtb, line 221 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtPBiZxu0aXA2VxX36:-KJtPBi_nXnn2BBr3twB:-1279323219) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L221)):*
> ```
> 	<translation id="7172190985346183509" key="MSG_RC_DETAIL_PODS_FAILED_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="The message says that that many pods have failed (replication controller details page)."><ph name="PODS_COUNT" /> の失敗</translation>
> 	<translation id="3147497997693039812" key="MSG_RC_DETAIL_PODS_DESIRED_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="The message says that that many pods are desired to run (replication controller details page)."><ph name="PODS_COUNT" /> の要望</translation>
> 	<translation id="5232048118282523785" key="MSG_RC_DETAIL_UPDATE_PODS_COUNT_TITLE" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Title for the pod count update dialog (for a replication controller).">要望ポット数の設定</translation>
> ```

It is not `ポット`. 

---

*[i18n/messages-ja.xtb, line 230 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtLhB5_QqdGRkXsmXA:-KJtLhB5_QqdGRkXsmXB:-435715569) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L230)):*
> ```
> 	<translation id="3289893187016519985" key="MSG_RC_DETAIL_UPDATE_PODS_COUNT_CANCEL_ACTION" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Action 'Cancel' for the cancel button on the &quot;update number of pods&quot; dialog.">キャンセル</translation>
> 	<translation id="2995906702672558140" key="MSG_RC_DETAIL_UPDATE_PODS_COUNT_OK_ACTION" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Action 'OK' for the confirmation button on the &quot;update number of pods dialog&quot;.">OK</translation>
> 	<translation id="9073732860292978232" key="MSG_RC_LIST_DEPLOY_TOOLTIP" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Tooltip for the '+' (deploy) button on the replication controller list page.">コンテナアプリの配備</translation>
> ```

You translated `コンテナアプリを配備`  in tooltip before.
You should unify.

---

*[i18n/messages-ja.xtb, line 234 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtNTxKmeKNDuQy0TSi:-KJtNTxLLl3pJVorEfBR:158813675) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L234)):*
> ```
> 	<translation id="214157222227894292" key="MSG_RC_LIST_LOGS_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label 'Logs' at the top of the drop down menu when a user clicks the logs button on a replication controller card.">ログ</translation>
> 	<translation id="5032587768705754610" key="MSG_RC_LIST_LOGS_POD_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label 'Pod' for the column with pods in the logs drop down view (opened from a replication controller card).">ポッド</translation>
> 	<translation id="3105556649819092174" key="MSG_RC_LIST_LOGS_RUNNING_SINCE_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label 'Running since' for the respective column in the logs drop down view (opened from a replication controller card).">開始時間</translation>
> ```

How about `開始日時`

---

*[i18n/messages-ja.xtb, line 240 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtPmxzC-FraK1fOY7Y:-KJtPmxzC-FraK1fOY7Z:-1686485582) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L240)):*
> ```
> 	<translation id="1025887657102167775" key="MSG_RC_LIST_PODS_PENDING_TOOLTIP" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Tooltip saying that some pods in a replication controller are pending.">１つ以上のポッドが待機状態です</translation>
> 	<translation id="4937002308799617006" key="MSG_RC_LIST_VIEW_DETAILS_ACTION" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Action 'View details' on the drop down menu for a single replication controller (replication controller list page).">詳細を見る</translation>
> 	<translation id="4609705063795819625" key="MSG_RC_LIST_EDIT_POD_COUNT_ACTION" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Action 'Edit Pod Count' on the drop down menu for a single replication controller (replication controller list page).">ポッド総数の編集</translation>
> ```

You should remove `総`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/868)*

**Comment by Yamagami-Takuma** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[i18n/messages-ja.xtb, line 183 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtFmPD2gDZT_RNBLTu:-KJtVuxNorM8GVWwqJaH:1920760566) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L183)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> `起動中` may mislead.
> How about `起動前`
> 
</details>
I fixed.

---

*[i18n/messages-ja.xtb, line 184 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtFirjNZSGyyOP82GE:-KJtVxd_9FEulL17Q-6u:1920760566) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L184)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> How about `たった今`
</details>
I fixed.

---

*[i18n/messages-ja.xtb, line 194 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtHPa0Mzqe-uKuyZrd:-KJtVyHJNuYmnXpAKKDX:1920760566) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L194)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> How about `稼動中`
</details>
I fixed.

---

*[i18n/messages-ja.xtb, line 208 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtN1vWUHGpA_kxM53M:-KJtVykT-UZGp6vU1jFG:1920760566) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L208)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> It is `ネームスペース`.
</details>
I fixed.

---

*[i18n/messages-ja.xtb, line 220 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtR-WMm8DtEFDc1aJR:-KJtVzCxtrrGFE4A2SmK:-935588894) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L220)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> I like `要求`.
</details>
OK. There are some `要求` in this PR, so I fixed all of them.

---

*[i18n/messages-ja.xtb, line 221 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtPBiZxu0aXA2VxX36:-KJtWwxjDWTCWRrL8jwU:1920760566) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L221)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> It is not `ポット`. 
</details>
I fixed.

---

*[i18n/messages-ja.xtb, line 230 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtLhB5_QqdGRkXsmXA:-KJtX9CUmwgEN5beds0R:1920760566) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L230)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> You translated `コンテナアプリを配備`  in tooltip before.
> You should unify.
> 
</details>
I fixed.

---

*[i18n/messages-ja.xtb, line 234 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtNTxKmeKNDuQy0TSi:-KJtXA-mHsgvTgG529jY:1920760566) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L234)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> How about `開始日時`
</details>
I fixed.

---

*[i18n/messages-ja.xtb, line 240 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtPmxzC-FraK1fOY7Y:-KJtXAQtLGo4IblhK-Iz:1920760566) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L240)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> You should remove `総`.
</details>
I fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/868)*

**Comment by f-higashi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[i18n/messages-ja.xtb, line 221 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtPBiZxu0aXA2VxX36:-KJtZDkMJyXNWWJjWU0Y:-1167931481) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L221)):*
<details><summary><i>Previously, Yamagami-Takuma wrote…</i></summary>
> I fixed.
</details>
It is better `ポッド要求数の設定`.

---

*[i18n/messages-ja.xtb, line 19 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtYt5Nh5Kcltcz_5rL:-KJtYt5Po8nUu1FitPuS:35776680) ([raw file](https://github.com/kubernetes/dashboard/blob/8655723bce2be6e7f5b16b41e0e1ce058881642a/i18n/messages-ja.xtb#L19)):*
> ```
> 	<translation id="7263428501718162087" key="MSG_IMAGE_PULL_SECRET_NAME_REQUIRED_WARNING" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Warning which tells the user that the image pull secret name is required.">必須項目です</translation>
> 	<translation id="8342519402917559446" key="MSG_IMAGE_PULL_SECRET_CREATE_DIALOG_USER_HELP" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="User help text for the create image pull secret dialog. Directly after this text a specific namespace is specified.">指定した名前のシークレットは、次のネームスペースでクラスターに追加されます: </translation>
> 	<translation id="2983148182170296230" key="MSG_IMAGE_PULL_SECRET_DATA_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/a/pp-dev.js" desc="Label 'Image pull secret data', which appears as a placeholder in an empty input field in the image pull secret creation dialog.">イメージプルシークレット データ</translation>
> ```

You did wrong intput .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/868)*

**Comment by Yamagami-Takuma** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[i18n/messages-ja.xtb, line 221 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtPBiZxu0aXA2VxX36:-KJt_3a371_ALE5gt8kX:-994735356) ([raw file](https://github.com/kubernetes/dashboard/blob/95ef46ad984ae406227dbe73e97d970e7613abd8/i18n/messages-ja.xtb#L221)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> It is better `ポッド要求数の設定`.
</details>
OK. I fixed.

---

*[i18n/messages-ja.xtb, line 19 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJtYt5Nh5Kcltcz_5rL:-KJtZyoOG5VO-lSJ0Hy7:-1868206767) ([raw file](https://github.com/kubernetes/dashboard/blob/8655723bce2be6e7f5b16b41e0e1ce058881642a/i18n/messages-ja.xtb#L19)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> You did wrong intput .
</details>
Thanks. I fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/868)*

**Comment by f-higashi** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kubernetes/dashboard/868#-KJt_rkJ3b4Ge-RcCnba:-KJt_rkJ3b4Ge-RcCnbb:-1460323738) (no related file):*
:lgtm: 

@maciaszczykm 
you can merge this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/868)*

**Pull request merged**
