### PR TITLE
Added secrets frontend

### PR DESCRIPTION
**Pull request by PiotrDabkowski**
List of secrets can now be found under #/secrets?namespace=namespace.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1018)

### CODE REVIEW

**Comment by bryk** [comment]
Can you add tests to the code so that incremental coverage is 100%? 

---

Reviewed 11 of 12 files at r1.
Review status: 11 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/externs/backendapi.js, line 604 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMYlV7H61LvRxbTV_HK:-KMYlV7Imu_23pTXhKBl:-317205941) ([raw file](https://github.com/kubernetes/dashboard/blob/2e6a9129c2609afaa425f90d2df327d616ce9b2b/src/app/externs/backendapi.js#L604)):*
> ```JavaScript
> /**
>  * @typedef {{
>  *   secrets: !Array<string>
> ```

Secret list is now `!Array<!backendApi.Secret>`, isn't it?

---

*[src/app/frontend/secretlist/secretcardlist_component.js, line 25 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMYowYkUCTBD1zJXgvL:-KMYowYkUCTBD1zJXgvM:-971340851) ([raw file](https://github.com/kubernetes/dashboard/blob/2e6a9129c2609afaa425f90d2df327d616ce9b2b/src/app/frontend/secretlist/secretcardlist_component.js#L25)):*
> ```JavaScript
>   constructor($interpolate) {
>     /**
>          * List of secrets. Initialized from the scope.
> ```

Can you format this properly? 

---

*[src/app/frontend/secretlist/secretcardlist_component.js, line 29 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMYoyNN6iFQ28mi8SkG:-KMYoyNN6iFQ28mi8SkH:1228221876) ([raw file](https://github.com/kubernetes/dashboard/blob/2e6a9129c2609afaa425f90d2df327d616ce9b2b/src/app/frontend/secretlist/secretcardlist_component.js#L29)):*
> ```JavaScript
>      */
>     this.secretList;
> ```

Can you add `@type` info here? 

---

*[src/app/frontend/secretlist/secretlist_controller.js, line 29 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMYpEqXtdQOia6WYzMx:-KMYpEqYJtB3B2NiR4kq:-1681377264) ([raw file](https://github.com/kubernetes/dashboard/blob/2e6a9129c2609afaa425f90d2df327d616ce9b2b/src/app/frontend/secretlist/secretlist_controller.js#L29)):*
> ```JavaScript
> 
>   /**
>      * @return {boolean}
> ```

Reformat this? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-:-KMYpKg1EQUttOpO3LTW:-717357183)*

**Comment by PiotrDabkowski** [comment]
Review status: 8 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/externs/backendapi.js, line 604 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMYlV7H61LvRxbTV_HK:-KMZOzuPFEVsBVxIrTFG:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/2e6a9129c2609afaa425f90d2df327d616ce9b2b/src/app/externs/backendapi.js#L604)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Secret list is now `!Array<!backendApi.Secret>`, isn't it?
</details>
Done.

---

*[src/app/frontend/secretlist/secretcardlist_component.js, line 25 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMYowYkUCTBD1zJXgvL:-KMZP1Her5Nvt5PxTNOA:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/2e6a9129c2609afaa425f90d2df327d616ce9b2b/src/app/frontend/secretlist/secretcardlist_component.js#L25)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Can you format this properly? 
</details>
Done.

---

*[src/app/frontend/secretlist/secretcardlist_component.js, line 29 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMYoyNN6iFQ28mi8SkG:-KMZP2D0dJRidwlryQdh:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/2e6a9129c2609afaa425f90d2df327d616ce9b2b/src/app/frontend/secretlist/secretcardlist_component.js#L29)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Can you add `@type` info here? 
</details>
Done.

---

*[src/app/frontend/secretlist/secretlist_controller.js, line 29 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMYpEqXtdQOia6WYzMx:-KMZP3E3ciaiZ0lsgEF0:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/2e6a9129c2609afaa425f90d2df327d616ce9b2b/src/app/frontend/secretlist/secretlist_controller.js#L29)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Reformat this? 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1018)*

**Comment by PiotrDabkowski** [comment]
PTAL

**Comment by bryk** [comment]
@olekzabl Can you review?

**Comment by olekzabl** [comment]
General remark: very good that you use "::", but I have impression it's a little inconsistent.
See example remarks in secretcardlist.html; I've not checked the other files from this side.

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/app/frontend/secretlist/secretcardlist.html, line 31 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMcQSsjJshN4RWKpjBM:-KMcLJGtQzO6MKSJv2wf:157850769) ([raw file](https://github.com/kubernetes/dashboard/blob/53a3f54bf737b0ccac557d5084c60c08ff8ec9b4/src/app/frontend/secretlist/secretcardlist.html#L31)):*
> ```HTML
>             <kd-resource-card-column>
>                 <div>
>                     <kd-middle-ellipsis display-string="{{secret.objectMeta.name}}">
> ```

Add "::"? (I assume the name is immutable)

---

*[src/app/frontend/secretlist/secretcardlist.html, line 39 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMcQaL6FzIIZIOzOUmE:-KMcQaL6FzIIZIOzOUmF:-409924869) ([raw file](https://github.com/kubernetes/dashboard/blob/53a3f54bf737b0ccac557d5084c60c08ff8ec9b4/src/app/frontend/secretlist/secretcardlist.html#L39)):*
> ```HTML
>                     {{::secret.objectMeta.creationTimestamp | relativeTime}}
>                     <md-tooltip>
>                         {{$ctrl.getStartedAtTooltip(secret.objectMeta.creationTimestamp)}}
> ```

Add "::"?

---

*[src/app/frontend/secretlist/secretcardlist.html, line 47 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMcQY_AQwfGiTI0Rjk2:-KMcLPCM02-WrBZGdUqk:-2079616150) ([raw file](https://github.com/kubernetes/dashboard/blob/53a3f54bf737b0ccac557d5084c60c08ff8ec9b4/src/app/frontend/secretlist/secretcardlist.html#L47)):*
> ```HTML
>     </kd-resource-card>
>     <kd-resource-card-list-footer>
>         <kd-resource-card-list-pagination pagination-id="secrets" total-items="$ctrl.secretList.secrets.length">
> ```

Add "::"? (Note that you wrote "::$ctrl.secretList.secrets" above).

---

*[src/app/frontend/secretlist/secretcardlist_component.js, line 68 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMcLsR7BU1oQeX1tNCd:-KMcLsR7BU1oQeX1tNCe:1234352658) ([raw file](https://github.com/kubernetes/dashboard/blob/53a3f54bf737b0ccac557d5084c60c08ff8ec9b4/src/app/frontend/secretlist/secretcardlist_component.js#L68)):*
> ```JavaScript
> const i18n = {
>   /** @export {string} @desc Label 'Name' which appears as a column label in the table of
>    pods (pod list view). */
> ```

A multi-line comment should start with "*" in the second line. (Same below).

---

*[src/app/frontend/secretlist/secretcardlist_component.js, line 68 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMcMJCJX1ICF8WaHcwc:-KMcMJCJX1ICF8WaHcwd:-1375707240) ([raw file](https://github.com/kubernetes/dashboard/blob/53a3f54bf737b0ccac557d5084c60c08ff8ec9b4/src/app/frontend/secretlist/secretcardlist_component.js#L68)):*
> ```JavaScript
> const i18n = {
>   /** @export {string} @desc Label 'Name' which appears as a column label in the table of
>    pods (pod list view). */
> ```

I don't know your style guide, but for me moving @desc to a separate line would be more readable.
+@bryk , what do you think?

---

*[src/test/frontend/secretlist/secretcardlist_component_test.js, line 32 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMcNSV9oE0LOj_a1R4w:-KMcNSVAQ_qLNoNmoH9M:268856011) ([raw file](https://github.com/kubernetes/dashboard/blob/53a3f54bf737b0ccac557d5084c60c08ff8ec9b4/src/test/frontend/secretlist/secretcardlist_component_test.js#L32)):*
> ```JavaScript
> 
>   it('should format the "secret start date" tooltip correctly', () => {
>     expect(ctrl.getStartedAtTooltip('2016-06-06T09:13:12Z')).toBe('Started at 6/6/16 09:13 UTC');
> ```

Treating timezones in other tests was changed by @bryk yesterday (#1020). Please look at this, probably you'll want to follow.

---

*[src/test/frontend/secretlist/secretlist_controller_test.js, line 19 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMcPeld0yNcNXGVko6P:-KMcPeleGN0X6HZ27ljU:575490321) ([raw file](https://github.com/kubernetes/dashboard/blob/53a3f54bf737b0ccac557d5084c60c08ff8ec9b4/src/test/frontend/secretlist/secretlist_controller_test.js#L19)):*
> ```JavaScript
> 
> describe('Secret list controller', () => {
>   /** @type {!secretlist/secretlist_controller.PodListController} */
> ```

Is it really PodListController?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-:-KMcQ-SGIrincbsXOrcL:-1118678892)*

**Comment by PiotrDabkowski** [comment]
Review status: 5 of 21 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/app/frontend/secretlist/secretcardlist.html, line 31 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMcQSsjJshN4RWKpjBM:-KMhaXjG1mkJ1OGleOwd:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/53a3f54bf737b0ccac557d5084c60c08ff8ec9b4/src/app/frontend/secretlist/secretcardlist.html#L31)):*
<details><summary><i>Previously, olekzabl wrote…</i></summary>
> Add "::"? (I assume the name is immutable)
</details>
Done.

---

*[src/app/frontend/secretlist/secretcardlist.html, line 39 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMcQaL6FzIIZIOzOUmE:-KMhaYcUTHs2uh_e8UFR:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/53a3f54bf737b0ccac557d5084c60c08ff8ec9b4/src/app/frontend/secretlist/secretcardlist.html#L39)):*
<details><summary><i>Previously, olekzabl wrote…</i></summary>
> Add "::"?
</details>
Done.

---

*[src/app/frontend/secretlist/secretcardlist.html, line 47 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMcQY_AQwfGiTI0Rjk2:-KMhaZKAiTxBzzGireiG:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/53a3f54bf737b0ccac557d5084c60c08ff8ec9b4/src/app/frontend/secretlist/secretcardlist.html#L47)):*
<details><summary><i>Previously, olekzabl wrote…</i></summary>
> Add "::"? (Note that you wrote "::$ctrl.secretList.secrets" above).
</details>
Done.

---

*[src/app/frontend/secretlist/secretcardlist_component.js, line 68 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMcLsR7BU1oQeX1tNCd:-KMhakFHjsvPONicxewT:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/53a3f54bf737b0ccac557d5084c60c08ff8ec9b4/src/app/frontend/secretlist/secretcardlist_component.js#L68)):*
<details><summary><i>Previously, olekzabl wrote…</i></summary>
> A multi-line comment should start with "*" in the second line. (Same below).
</details>
Done.

---

*[src/app/frontend/secretlist/secretcardlist_component.js, line 68 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMcMJCJX1ICF8WaHcwc:-KMhakjrsCbH7Ph1hvLX:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/53a3f54bf737b0ccac557d5084c60c08ff8ec9b4/src/app/frontend/secretlist/secretcardlist_component.js#L68)):*
<details><summary><i>Previously, olekzabl wrote…</i></summary>
> I don't know your style guide, but for me moving @desc to a separate line would be more readable.
> +@bryk , what do you think?
</details>
Done.

---

*[src/test/frontend/secretlist/secretcard_component_test.js, line 32 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMcNSV9oE0LOj_a1R4w:-KMhaszQgKNap7jw5LHm:1965600039) ([raw file](https://github.com/kubernetes/dashboard/blob/53a3f54bf737b0ccac557d5084c60c08ff8ec9b4/src/test/frontend/secretlist/secretcard_component_test.js#L32)):*
<details><summary><i>Previously, olekzabl wrote…</i></summary>
> Treating timezones in other tests was changed by @bryk yesterday (#1020). Please look at this, probably you'll want to follow.
</details>
UTC time as discussed - no need to change. Will submit an issue regarding our tooltip time consistency.

---

*[src/test/frontend/secretlist/secretlist_controller_test.js, line 19 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMcPeld0yNcNXGVko6P:-KMhbB7nESBvXt5rebWs:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/53a3f54bf737b0ccac557d5084c60c08ff8ec9b4/src/test/frontend/secretlist/secretlist_controller_test.js#L19)):*
<details><summary><i>Previously, olekzabl wrote…</i></summary>
> Is it really PodListController?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1018)*

**Comment by bryk** [comment]
Two last comments and let's merge 

---

Reviewed 3 of 8 files at r2, 14 of 17 files at r3, 1 of 3 files at r4.
Review status: 19 of 20 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/app/frontend/secretlist/secretcard_component.js, line 33 \[r4\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMhhAX7_OEDVXG07DWK:-KMhhAX7_OEDVXG07DWL:-2000583064) ([raw file](https://github.com/kubernetes/dashboard/blob/25c9c7ca8063c4a555d4b070b338cbbb021db114/src/app/frontend/secretlist/secretcard_component.js#L33)):*
> ```JavaScript
> 
> /**
>  * @return {!angular.Component}
> ```

It is not `@return`, but `@type`. 

---

*[src/app/frontend/secretlist/secretcardlist_component.js, line 68 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMcMJCJX1ICF8WaHcwc:-KMhhPTN5NwFusLCS984:-107311047) ([raw file](https://github.com/kubernetes/dashboard/blob/53a3f54bf737b0ccac557d5084c60c08ff8ec9b4/src/app/frontend/secretlist/secretcardlist_component.js#L68)):*
<details><summary><i>Previously, PiotrDabkowski (Piotr Dabkowski) wrote…</i></summary>
> Done.
</details>
This is how we've been doing stuff so far. Generally, if something doesn't look prohibitively bad and linter is happy, I dont complain. 

---

*[src/test/backend/resource/secret/secret_test.go, line 79 \[r4\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMhhilHPZfjgG7Wiv5s:-KMhhilIATa_aTXcngqT:-1011511825) ([raw file](https://github.com/kubernetes/dashboard/blob/25c9c7ca8063c4a555d4b070b338cbbb021db114/src/test/backend/resource/secret/secret_test.go#L79)):*
> ```Go
> 						TypeMeta: common.NewTypeMeta(common.ResourceKindSecret),
> 					},
> 					//{
> ```

Delete this? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-:-KMhhpJwpdc6UP6BGFiW:335777829)*

**Comment by olekzabl** [comment]
Review status: 19 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/secretlist/secretcardlist.html, line 47 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMcQY_AQwfGiTI0Rjk2:-KMhkS0-vg9sGBk_71iw:-1662779309) ([raw file](https://github.com/kubernetes/dashboard/blob/53a3f54bf737b0ccac557d5084c60c08ff8ec9b4/src/app/frontend/secretlist/secretcardlist.html#L47)):*
<details><summary><i>Previously, PiotrDabkowski (Piotr Dabkowski) wrote…</i></summary>
> Done.
</details>
Really done? I don't see any change.

Maybe in GitHub it's just normal to reply "done" when ignoring a suggestion, but for me it's misleading: now I don't know if you knowingly ignored it, or if you forgot to apply. (Or if I've missed something else). 

Same about two other "done"s in this file. If they're no longer applicable because you made a bigger change in the code, you could reply "No longer applicable" or so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1018)*

**Comment by olekzabl** [comment]
Reviewed 1 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1018)*

**Comment by PiotrDabkowski** [comment]
*[src/app/frontend/secretlist/secretcardlist.html, line 47 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMcQY_AQwfGiTI0Rjk2:-KMhoh4xH984VMaoQx1q:-244844667) ([raw file](https://github.com/kubernetes/dashboard/blob/53a3f54bf737b0ccac557d5084c60c08ff8ec9b4/src/app/frontend/secretlist/secretcardlist.html#L47)):*
<details><summary><i>Previously, olekzabl wrote…</i></summary>
> Really done? I don't see any change.
> 
> Maybe in GitHub it's just normal to reply "done" when ignoring a suggestion, but for me it's misleading: now I don't know if you knowingly ignored it, or if you forgot to apply. (Or if I've missed something else). 
> 
> Same about two other "done"s in this file. If they're no longer applicable because you made a bigger change in the code, you could reply "No longer applicable" or so.
</details>
Olek, I changed the file structure a little bit and I think you are talking about my previous commit. You can change the view to the never version by using this toolbar next to the file name.  I split the previous version into 2 - secretcard.html and secretcardlist.html and I follow exact style as in petsetlist. I apologize if that's confusing 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1018)*

**Comment by PiotrDabkowski** [comment]
Review status: 18 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/secretlist/secretcard_component.js, line 33 \[r4\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMhhAX7_OEDVXG07DWK:-KMhq9MdWZEFca5Lvz5b:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/25c9c7ca8063c4a555d4b070b338cbbb021db114/src/app/frontend/secretlist/secretcard_component.js#L33)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> It is not `@return`, but `@type`. 
</details>
Done.

---

*[src/test/backend/resource/secret/secret_test.go, line 79 \[r4\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-KMhhilHPZfjgG7Wiv5s:-KMhqPgUPrZMZGfFNscw:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/25c9c7ca8063c4a555d4b070b338cbbb021db114/src/test/backend/resource/secret/secret_test.go#L79)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Delete this? 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1018)*

**Comment by olekzabl** [comment]
Reviewed 1 of 17 files at r3, 1 of 3 files at r4.
Review status: 18 of 21 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1018)*

**Comment by bryk** [comment]
Reviewed 1 of 3 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1018)*

**Comment by bryk** [comment]
Olek, let me know when this is ready to merge. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1018#-:-KMi-5JWBeJ6YMR5X9gM:2026986574)*

**Comment by olekzabl** [comment]
Reviewed 1 of 17 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1018)*

**Comment by olekzabl** [comment]
For me, it's ready. I marked one more file green; what more should I do?

**Comment by bryk** [comment]
Can you click the "Merge pull request" button? If yes, click it.

**Comment by olekzabl** [comment]
Clicked "Merge & retain branch", this was what I could see.

**Comment by bryk** [comment]
Yep, perfect :)

**Pull request merged**
