### PR TITLE
Explicitly select a JDK version in travis

### PR DESCRIPTION
**Pull request by rf232**
Mostly here for checking why builds are failing on travis now.

### CODE REVIEW

**Comment by rf232** [comment]
4 days ago the travis-ci/travis-build repo pushed a change to the way they generate the build script and while I'm not sure how this change exactly broke our code (as in why did it work before at all) but now explicitly select a JDK version to use.

**Comment by rf232** [comment]
ptal @bryk

**Comment by rf232** [comment]
Hmm, there appears to be more going on, I keep on getting:
```
/home/travis/build/kubernetes/dashboard/node_modules/selenium-webdriver/error.js:26
  constructor(opt_error) {
                         ^
WebDriverError: Connection refused (Connection refused)
```
now, but that appears to be a different problem from the jdk change (or does protratactor use Java, then it might be that we need another JDK than the openjdk actually

Also it might even be that our change is not needed if i look at: https://github.com/travis-ci/travis-ci/issues/6928

**Comment by bryk** [comment]
LGTM again

**Pull request merged**
