### PR TITLE
Apply "goimports -w src/app/backend" in hooks/pre-commit

### PR DESCRIPTION
**Pull request by shu-mutou**
We should apply goimports formatting results according to wiki[1]
[1] https://github.com/kubernetes/dashboard/wiki/Getting-started#committing-changes-to-your-fork

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@shu-mutou Please sign the CLA before we can proceed.

**Comment by shu-mutou** [comment]
@maciaszczykm I have already signed CLA and setup the github, but something wrong. I'm confirming every settings. Please wait. Thanks.

**Comment by shu-mutou** [comment]
I signed it

**Comment by shu-mutou** [comment]
This PR needs lots of changes for fixing test errors. Also, I renamed branch name. So I cancel this PR and created again as follow. Thanks.
https://github.com/kubernetes/dashboard/pull/3315

**Pull request closed without merging**
