### PR TITLE
Increase version to 1.1 in preparation for a release

### PR DESCRIPTION
**Pull request by bryk**
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/941)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm @floreks Please bless this and merge :)

**Comment by edouardKaiser** [comment]
Any chance of a 1.1.1 release soon ? :)

**Comment by floreks** [comment]
It would be good as there were a lot of changes. Still we have to wait for @bryk to come back in order to do the release.

**Comment by bryk** [comment]
@floreks Can you create an issue for the release?

**Comment by edouardKaiser** [comment]
Happy to create the issue if @floreks is busy

**Comment by edouardKaiser** [comment]
#1078

**Pull request merged**
