### PR TITLE
Add additional locale directories for zh

### PR DESCRIPTION
**Pull request by floreks**
I have configured directories for additional Chinese translations. They are ready for translation.

@hwdef @tanjunchen @zehuaiWANG 

Feel free to update the OWNERS files.

### CODE REVIEW

**Comment by hwdef** [comment]
Thank you very much.
Maybe it is better to copy the zh folder to zh-cn and zh-sg, because their contents are the same.
Only zh-tw and zh-hk need translation

**Comment by floreks** [comment]
@hwdef
Unfortunately, it would not be picked up by the backend this way. We have to use translation per directory right now.

**Comment by hwdef** [comment]
@floreks 
I got it, thank you for creating these folders.I will translate zh-cn and zh-sg later.
And keep zh-tw and zh-hk as they are. How about this?

**Comment by floreks** [comment]
Right now they are all templates in English ready to be translated. You can reuse `zh` where it is possible. Just copy translated parts over.

**Pull request merged**
