### PR TITLE
Update version to 1.6.2

### PR DESCRIPTION
**Pull request by maciaszczykm**
Do not merge until testing will be finished.

### CODE REVIEW

**Comment by idealhack** [comment]
Hi, I have some i18n updates, hopefully to be included in this release.

**Comment by floreks** [comment]
That would be great. We'll inform you once we're done with the changes before release.

**Comment by maciaszczykm** [comment]
We are still fixing minor issues found during testing. Most probably we will postpone it till next week.

@idealhack We will let you know.

**Comment by maciaszczykm** [comment]
#2159 has to be merged before release.

**Comment by maciaszczykm** [comment]
@idealhack Could you provide translations over the weekend or on Monday? #2160 should be last commit before release if we won't find anything critical.

**Comment by idealhack** [comment]
@maciaszczykm OK, I'll try to get it done before Monday.

**Comment by maciaszczykm** [comment]
@idealhack Unfortunately, we have to postpone release a bit because of access control issues (we are not proof to nil pointer dereferences). Most of our changes will be in the backend, so you can still work on it.

**Comment by idealhack** [comment]
@maciaszczykm I understand. I’m going to go through all pages in English and Chinese using my cluster of testing environment.

**Comment by idealhack** [comment]
It's done: #2164. PTAL.

**Pull request merged**
