### PR TITLE
feat: add full support for labels and annotations in helm chart

### PR DESCRIPTION
**Pull request by tuunit**
# Motivation
For Operators like ArgoCD or Teleport it is quite useful and sometimes necessary to be able to control and insert annotations and labels into all kinds of resources and especially services.

Furthermore the documentation in the `values.yaml` was wrong in some places. 
- The common labels and annotations aren't applied to all resources.
- Some comments mentioned the wrong resources like "Labels & Annotations for API" despite living in the "Auth" block

# Description
- Remove unnecessary templating function `common.tpl.renders`
- Add new helper function `kubernetes-dashboard.annotations` to apply common annotations to all resources
- Add common `app.labels` to helper function `kubernetes-dashboard.labels`
- Add auth, api, web, and metricsScraper labels and annotation options to all their respective resources
- Add a two new options `serviceLabels` and `serviceAnnotations` to auth, api, web, and metricsScraper services

# What type of PR is this?
/kind cleanup
/kind feature

### CODE REVIEW

**Comment by tuunit** [comment]
@desaintmartin @floreks let me know what you think of this change and if I should increase the Chart version as part of this PR

**Comment by maciaszczykm** [comment]
@tuunit I can see you are still force pushing this branch. I started reviewing but it is hard to track changes. It would be better if you could push new commits. We do squash anyways. Let us know when it will be ready for reviews.

**Review by maciaszczykm — APPROVED** [review]
LGTM, leaving to @floreks for final approval.

**Comment by maciaszczykm** [comment]
Tested deployment locally on kind cluster, everything seems to work. Added some labels as well.

/lgtm

**Comment by floreks** [comment]
Great, codewise lgtm

**Pull request merged**
