### PR TITLE
Refactored the stdio redirection when gulp spawns tasks

### PR DESCRIPTION
**Pull request by taimir**
Hi, I think some boilerplate code can be avoided in some of the gulp tasks (assuming the stdout.on(...) calls are not there on purpose). If you think consider this an improvement, you can check out the small changes :)

### CODE REVIEW

**Comment by taimir** [comment]
I signed it!

**Comment by bryk** [comment]
Thanks, that's a nice improvement! 

If clabot has hiccups with checks you can "git commit --amend" and then "git push --force" the same code  again.

**Comment by taimir** [comment]
I signed it!

**Comment by taimir** [comment]
I signed it!

**Comment by bryk** [comment]
LGTM, merging.

**Pull request merged**
