### PR TITLE
Separate graphs for CPU and Memory. Improved resize.

### PR DESCRIPTION
**Pull request by PiotrDabkowski**
## Before:

graph merged

## Now:

graph_row2

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1216)

### CODE REVIEW

**Comment by bryk** [comment]
PTAL. Will test now. 

---

Reviewed 34 of 40 files at r1.
Review status: 34 of 40 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/common/components/graph/graph_component.js, line 167 at r1](https://reviewable.io:443/reviews/kubernetes/dashboard/1216#-KRXfXmti8E4FeeTDeiK:-KRXfXmti8E4FeeTDeiL:bpw1j63) ([raw file](https://github.com/kubernetes/dashboard/blob/d06f91886016b86cd645abcf0d421a7e36b59b10/src/app/frontend/common/components/graph/graph_component.js#L167)):*
> ```JavaScript
>       let updateUntil = 0;
> 
>       let startChartUpdatePeriod = function(updatePeriod, timeBetweenUpdates) {
> ```

Add `@type` annotations here? 

---

*[src/app/frontend/daemonsetdetail/daemonsetdetail_controller.js, line 71 at r1](https://reviewable.io:443/reviews/kubernetes/dashboard/1216#-KRXfmkY4vKqOStO6CkW:-KRXfmkZGNM5unnH0uA5:b-54egmn) ([raw file](https://github.com/kubernetes/dashboard/blob/d06f91886016b86cd645abcf0d421a7e36b59b10/src/app/frontend/daemonsetdetail/daemonsetdetail_controller.js#L71)):*
> ```JavaScript
>       'as this Daemon Set'),
>   /** @export {string} @desc Title for graph card displaying metrics of one daemon set. */
>   MSG_DAEMON_SET_DETAIL_GRAPH_CARD_TITLE: goog.getMsg('Resource usage history'),
> ```

Delete this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1216#-:-KRXg2nDP26tj6zZPg2D:b-xtiibi)*

**Comment by bryk** [comment]
Can you decrease right margins? 

selection_125

**Comment by bryk** [comment]
Margin is too large: 

selection_126

**Comment by bryk** [comment]
Can you make the height 200px and move "Time" label to the lefr/right?

**Comment by PiotrDabkowski** [comment]
@bryk PTAL

---

Review status: 15 of 43 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/common/components/graph/graph_component.js, line 167 at r1](https://reviewable.io:443/reviews/kubernetes/dashboard/1216#-KRXfXmti8E4FeeTDeiK:-KRY-rJ4zdYZX8WLwWQC:b-896fix) ([raw file](https://github.com/kubernetes/dashboard/blob/d06f91886016b86cd645abcf0d421a7e36b59b10/src/app/frontend/common/components/graph/graph_component.js#L167)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Add `@type` annotations here? 
</details>
Done.

---

*[src/app/frontend/daemonsetdetail/daemonsetdetail_controller.js, line 71 at r1](https://reviewable.io:443/reviews/kubernetes/dashboard/1216#-KRXfmkY4vKqOStO6CkW:-KRY-sFW-peyF0HAhbTM:b-896fix) ([raw file](https://github.com/kubernetes/dashboard/blob/d06f91886016b86cd645abcf0d421a7e36b59b10/src/app/frontend/daemonsetdetail/daemonsetdetail_controller.js#L71)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Delete this?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1216#-:-KRY-tWPTiW5XkOo57Lx:by7e27m)*

**Comment by bryk** [comment]
Please resolve conflicts.

**Comment by bryk** [comment]
:lgtm:

---

Reviewed 2 of 40 files at r1, 26 of 26 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1216#-:-KRYKT9d6oiXBNsAqTQK:bnfp4nl)*

**Comment by bryk** [comment]
@PiotrDabkowski Please add Japanese translations from: https://github.com/kubernetes/dashboard/pull/1225#issuecomment-246934835

**Comment by PiotrDabkowski** [comment]
@bryk done

**Comment by PiotrDabkowski** [comment]
@bryk done

**Comment by bryk** [comment]
:lgtm: Will merge soon. 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1216#-:-KRc8B-RD4EHUoHxSjJS:bowdz3o)*

**Pull request merged**
