### PR TITLE
s/show less foos/show fewer foos/g

### PR DESCRIPTION
**Pull request by anguslees**
("labels" and "attributes" are countable nouns)

### CODE REVIEW

**Comment by digitalfishpond** [comment]
@anguslees the strings need to be changed in the code. The xtb files are generated automatically from the html and JS files. I am currently updating all the strings in the application as part of issue #1223 and I have already planned to include this change in my next PR.

**Comment by maciaszczykm** [comment]
Yeah, my mistake, that's true @digitalfishpond. Totally forgot about auto-generation of XTB entries.

**Comment by digitalfishpond** [comment]
Tell you what, I'll remove my change in my current work, and you can update your pool request in the following way: revert the change to messages-en.xtb, and change the strings directly in frontend/common/components/annotations.html and frontend/common/components/labels.html, then run gulp build and you should see the messages-en.xtb and messages-ja.xtb files changed automatically.

**Comment by anguslees** [comment]
(ack, will do.  thanks!)

**Comment by digitalfishpond** [comment]
Hi @anguslees, any progress on this? Can I help you further in any way?

**Comment by anguslees** [comment]
When I run `gulp build` (actually running it in the container that gets produced by `./build/run-gulp-in-docker.sh`), `messages-en.xtb` contains the expected change but `messages-ja.xtb` has *all* the japanese characters replaced with question marks.  Presumably it's some utf8 encoding issue.  Is there some trick to regenerating this file correctly?

**Comment by digitalfishpond** [comment]
@anguslees , unfortunately, we don't have any automatic translation generation. Our esteemed colleagues in Japan provide the translations manually. So you can just push your changes as they are and we can update the translation subsequently.

**Comment by digitalfishpond** [comment]
Little clarification: do you mean all the japanese characters from _every_ translation in the entire file? in which case don't push, and I'll try to find a solution!

**Comment by digitalfishpond** [comment]
Ok, if it is all the Japanese characters in the entire file, the first step would be to check the encoding of your IDE which should be UTF-8. If you are using Webstorm (IntelliJ), you can find that under File>Settings>Editor>File Encodings. let me know how you get on.

**Comment by anguslees** [comment]
Yes, every japanese character in the entire file was `???`.  I never edited `messages-ja.xtb`, this was just me looking at what output came from `gulp build`, and comparing before/after.

**Comment by digitalfishpond** [comment]
Ah. So it's probably a good idea to fix this so that you don't have similar problems in the future if you want to add or change a string. Ok, my first thought was that maybe the IDE you are using was not using UTF8 encoding, but I just tried building using US-ASCII and then again with ISO-8859-1, and the translations remained intact. 
@taimir @bryk - Any possible ideas why @anguslees ' build is generating a messages-ja.xtb file with every single Japanese character replaced with a question mark?

**Comment by taimir** [comment]
> When I run gulp build (actually running it in the container that gets produced by ./build/run-gulp-in-docker.sh), messages-en.xtb contains the expected change but messages-ja.xtb has all the japanese characters replaced with question marks. 

@bryk If I remember correctly there was a similar issue a couple of months back, the problem was a user was seeing `???` instead of japanese in the production version of dashboard. It turned out that the build server where the dashboard releases were put together was missing localization. I assume this is the same issue, probably something must be installed in the docker container where `gulp` is run. I'll try to find the issue I'm referring to.

**Comment by taimir** [comment]
There it is: https://github.com/kubernetes/dashboard/issues/1025. In this case, I suspect the problem is that the gulp container has no locale support.

**Comment by bryk** [comment]
@taimir @digitalfishpond I remember this happening on one of my machines. I dont know why. Maybe some packages weren't installed. 

@digitalfishpond You are maintainer of this repo. You can "Add more commits by pushing to the patch-1 branch on anguslees/dashboard.". This means that you can fetch this commit, rebuilt locally, push to anguslees/dashboard and merge. Can you do this?

**Comment by taimir** [comment]
@anguslees @digitalfishpond This is just a wild guess, but can one of you guys try adding the following:

```
apt-get install -y locales
locale-gen ja_JP.UTF-8
```

to the Dockerfile for the build container: [this one](https://github.com/taimir/dashboard/blob/master/build/Dockerfile). And then just run `build/run-gulp-in-docker.sh` as usual. Just make sure the build container image is rebuilt.

Maybe that could help...

**Pull request merged**
