### PR TITLE
Status icons for Pods visible on list and resources pages

### PR DESCRIPTION
**Pull request by digitalfishpond**
cards for pods display an icon related to their podPhase property ('Failed', 'Pending' or 'Running') in lists and resources pages

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/784)

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Review status: 0 of 25 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[build/i18n.js, line 40 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/784#-KJ5BnYGscznmAez9m4S:-KJ5BnYGscznmAez9m4T:1588517664) ([raw file](https://github.com/kubernetes/dashboard/blob/8864496917c73a16334316e12a0d6fd9f7eb866c/build/i18n.js#L40)):*
> ```JavaScript
>   let command = `java -jar ${conf.paths.xtbgenerator} --lang ${langKey}` +
>       ` --xtb_output_file ${translationBundle}` +
>       ` --js ${codeSource}`;
> ```

You can move it into one line:
` --xtb_output_file ${translationBundle} --js ${codeSource}`;

---

*[src/app/frontend/common/components/endpoint/endpoint_module.js, line 17 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/784#-KJ5C0nFNYTV6YdWqkBI:-KJ5C0nFNYTV6YdWqkBJ:-492049909) ([raw file](https://github.com/kubernetes/dashboard/blob/8864496917c73a16334316e12a0d6fd9f7eb866c/src/app/frontend/common/components/endpoint/endpoint_module.js#L17)):*
> ```JavaScript
> import {externalEndpointComponent} from './externalendpoint_component';
> import {internalEndpointComponent} from './internalendpoint_component';
> ```

Too many empty lines in a row. Please check other files too.

---

*[src/test/frontend/deploy/createsecret_controller_test.js, line 73 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/784#-KJ5CG2Is3RE9ZQ5wV-v:-KJ5CG2Is3RE9ZQ5wV-w:-1648108147) ([raw file](https://github.com/kubernetes/dashboard/blob/8864496917c73a16334316e12a0d6fd9f7eb866c/src/test/frontend/deploy/createsecret_controller_test.js#L73)):*
> ```JavaScript
>             `vdjEvIjogeyAiYXV0aCI6ICJabUZyWlhCaG` +
>             `MzTjNiM0prTVRJSyIsICJlbWFpbCI6` +
>             `ICJqZG9lQGV4YW1wbGUuY29tIiB9IH0K`)
> ```

You can squeeze it into two lines:
```
expect((`eyAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogeyAiYXV0aCI6ICJabUZyWlhCaG` +
`MzTjNiM0prTVRJSyIsICJlbWFpbCI6ICJqZG9lQGV4YW1wbGUuY29tIiB9IH0K`)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/784)*

**Comment by bryk** [comment]
Reviewed 4 of 7 files at r1, 9 of 20 files at r2.
Review status: 13 of 25 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/podlist/podcardlist.html, line 37 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/784#-KJ5FBKuiwAD22tpfJ1A:-KJ5FBKuiwAD22tpfJ1B:-377539695) ([raw file](https://github.com/kubernetes/dashboard/blob/8864496917c73a16334316e12a0d6fd9f7eb866c/src/app/frontend/podlist/podcardlist.html#L37)):*
> ```HTML
>       <md-icon class="material-icons kd-error" ng-if="::pod.podPhase=='Failed'">
>         error
>         <md-tooltip md-direction="right">One or more pods have errors</md-tooltip>
> ```

This is exacly one pod. Rewrite the message please :)

---

*[src/app/frontend/podlist/podcardlist.html, line 41 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/784#-KJ5FEfpSq7yrOxNfvQv:-KJ5FEfpSq7yrOxNfvQw:1181171353) ([raw file](https://github.com/kubernetes/dashboard/blob/8864496917c73a16334316e12a0d6fd9f7eb866c/src/app/frontend/podlist/podcardlist.html#L41)):*
> ```HTML
>       <md-icon class="material-icons" ng-if="::pod.podPhase=='Pending'">
>         timelapse
>         <md-tooltip md-direction="right">One or more pods are in pending state</md-tooltip>
> ```

This is exacly one pod. Rewrite the message please :)

---

*[src/app/frontend/podlist/podcardlist.html, line 41 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/784#-KJ5FFKUCasvUf0Jg-ep:-KJ5FFKUCasvUf0Jg-eq:203764367) ([raw file](https://github.com/kubernetes/dashboard/blob/8864496917c73a16334316e12a0d6fd9f7eb866c/src/app/frontend/podlist/podcardlist.html#L41)):*
> ```HTML
>       <md-icon class="material-icons" ng-if="::pod.podPhase=='Pending'">
>         timelapse
>         <md-tooltip md-direction="right">One or more pods are in pending state</md-tooltip>
> ```

Btw, can you use MSG_FOO internationalization framework. Consult @taimir if dont know how. 

---

*[src/app/frontend/podlist/podcardlist_component.js, line 66 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/784#-KJ5FQR48Hxe3htCHN6v:-KJ5FQR48Hxe3htCHN6w:1740280682) ([raw file](https://github.com/kubernetes/dashboard/blob/8864496917c73a16334316e12a0d6fd9f7eb866c/src/app/frontend/podlist/podcardlist_component.js#L66)):*
> ```JavaScript
>    */
>   hasWarnings() {
>     console.log(this);
> ```

Remove? 

---

*[src/app/frontend/podlist/podcardlist_component.js, line 67 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/784#-KJ5FV69RP8Hos6WryAr:-KJ5FV69RP8Hos6WryAs:843116586) ([raw file](https://github.com/kubernetes/dashboard/blob/8864496917c73a16334316e12a0d6fd9f7eb866c/src/app/frontend/podlist/podcardlist_component.js#L67)):*
> ```JavaScript
>   hasWarnings() {
>     console.log(this);
>     return pod.running;
> ```

`return pod.running === 0`?  This would be easier to understand :) At first look I thought this was a mistake. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/784)*

**Comment by digitalfishpond** [comment]
Review status: 7 of 24 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/app/frontend/podlist/podcardlist.html, line 41 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/784#-KJ5FFKUCasvUf0Jg-ep:-KJ61eM28PV2u6_J7-QP:1175082909) ([raw file](https://github.com/kubernetes/dashboard/blob/8864496917c73a16334316e12a0d6fd9f7eb866c/src/app/frontend/podlist/podcardlist.html#L41)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Btw, can you use MSG_FOO internationalization framework. Consult @taimir if dont know how. 
</details>
@taimir, could I ask you to have a look and tell me what I'm doing wrong here please? This string is set in .../podlist/podcardlist_component.js 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/784)*

**Comment by taimir** [comment]
Review status: 4 of 9 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/app/frontend/podlist/podcardlist.html, line 41 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/784#-KJ5FFKUCasvUf0Jg-ep:-KJ9oXmzi0YCJ3LxuGYo:609935362) ([raw file](https://github.com/kubernetes/dashboard/blob/8864496917c73a16334316e12a0d6fd9f7eb866c/src/app/frontend/podlist/podcardlist.html#L41)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> @taimir, could I ask you to have a look and tell me what I'm doing wrong here please? This string is set in .../podlist/podcardlist_component.js 
</details>
AFAICS, what's not right is that you don't display any text in your tooltips? 

You are doing nothing wrong with the definition of the MSG variables. The problem is that your controller is not accessible in the tooltip (not sure why, you'll have to investigate this). E.g. {{ctrl == undefined}} displays true at the place where you want to access the MSG_ variables in the html code.

---

*[src/app/frontend/podlist/podcardlist_component.js, line 87 \[r4\]](https://reviewable.io:443/reviews/kubernetes/dashboard/784#-KJ9rIsnrz5h8aRm_ISO:-KJ9rIsnrz5h8aRm_ISP:-1400951345) ([raw file](https://github.com/kubernetes/dashboard/blob/aa32bac2a8230e76551c667c6fda7ac7e01863d9/src/app/frontend/podlist/podcardlist_component.js#L87)):*
> ```JavaScript
> 
> const i18n = {
>   controller: PodCardListController,
> ```

Do you need this here? Normally the const object only contains the message variables.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/784)*

**Comment by digitalfishpond** [comment]
Thanks to @taimir for the pointers :) PTAL

<details><summary><i>Previously, codecov-io wrote…</i></summary>
> ## [Current coverage][cc-pull] is **94.92%**
> > Merging [#784][cc-pull] into [master][cc-base-branch] will increase coverage by **0.41%**
> 
> 1. File `...ereader_directive.js` (not in diff) was modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/d93a3f723b428eefed66e5172750636842c98e83/changes?src=pr#7372632F6170702F66726F6E74656E642F6465706C6F792F66696C657265616465725F6469726563746976652E6A73) 
>   - Misses `-6` 
>   - Partials `0` 
>   - Hits `+6`
> 
> ```diff
> @@             master       #784   diff @@
> ==========================================
>   Files           187        187          
>   Lines          1454       1456     +2   
>   Methods           0          0          
>   Messages          0          0          
>   Branches          0          0          
> ==========================================
> + Hits           1374       1382     +8   
> + Misses           80         74     -6   
>   Partials          0          0          
> ```
> 
> > Powered by [Codecov](https://codecov.io?src=pr). Last updated by [45f56f9...d93a3f7][cc-compare]
> [cc-base-branch]: https://codecov.io/gh/kubernetes/dashboard/branch/master?src=pr
> [cc-compare]: https://codecov.io/gh/kubernetes/dashboard/compare/45f56f976c482a576612db168f8dc80b5bfef0c8...d93a3f723b428eefed66e5172750636842c98e83
> [cc-pull]: https://codecov.io/gh/kubernetes/dashboard/pull/784?src=pr
</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/784#-:-KJ9tYKQShaU1zgAgUsZ:-1666183179)*

**Comment by digitalfishpond** [comment]
Review status: 4 of 9 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/app/frontend/podlist/podcardlist.html, line 41 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/784#-KJ5FFKUCasvUf0Jg-ep:-KJ9tIHBi3LTF567H4GY:-1520011576) ([raw file](https://github.com/kubernetes/dashboard/blob/8864496917c73a16334316e12a0d6fd9f7eb866c/src/app/frontend/podlist/podcardlist.html#L41)):*
<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> AFAICS, what's not right is that you don't display any text in your tooltips? 
> 
> You are doing nothing wrong with the definition of the MSG variables. The problem is that your controller is not accessible in the tooltip (not sure why, you'll have to investigate this). E.g. {{ctrl == undefined}} displays true at the place where you want to access the MSG_ variables in the html code.
</details>
Ah :) Thanks for the clue!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/784)*

**Comment by bryk** [comment]
Reviewed 6 of 7 files at r4, 1 of 2 files at r5.
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/784)*

**Comment by bryk** [comment]
We have conflicts. Please rebase :) :lgtm: 

<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> Thanks to @taimir for the pointers :) PTAL
</details>


---

Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/784#-:-KJANqNIqkUFmst4Qseu:-554313967)*

**Comment by digitalfishpond** [comment]
PTAL

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> We have conflicts. Please rebase :) :lgtm: 
</details>


---

Review status: 6 of 9 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/784#-:-KJAWizrGd591S_VwadM:676965300)*

**Comment by bryk** [comment]
:lgtm:

<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> PTAL
</details>


---

Reviewed 1 of 2 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/784#-:-KJAdV_oO9AbrM5bcJjJ:1417088721)*

**Pull request merged**
