### PR TITLE
Fixed Apache License link and updated badge in README.md

### PR DESCRIPTION
**Pull request by 4leem**
Updated README.md with the following changes:

* Fixed Apache license link, it was redirecting to 404 page. 
* Added Apache license badge along with existing badges, rearranged them based on the color so that it will look clean.

### CODE REVIEW

**Comment by 4leem** [comment]
The CLA has been signed now.

**Comment by maciaszczykm** [comment]
@4leem Let's wait a while for @k8s-ci-robot to pick up changes. If it will not happen then verify if you have signed your commits with correct mail.

**Comment by 4leem** [comment]
@maciaszczykm The email config in git and github is different. I have now add the other email also to the GitHub. Will @k8s-ci-robot pick it up automatically ?

**Comment by maciaszczykm** [comment]
@4leem Well, we have an answer :)

**Comment by maciaszczykm** [comment]
@4leem Thanks!

**Comment by 4leem** [comment]
It my pleasure to contribute to the project, this is just the beginning :)

Thank you @maciaszczykm for all the help.

**Comment by maciaszczykm** [comment]
@4leem We are looking forward to it :)

**Pull request merged**
