### PR TITLE
support force set language in ENV 

### PR DESCRIPTION
**Pull request by joway**
Sometimes, some teams prefer to use english version dashboard when the translation are incomplete or confusing . We need a ENV to force change the language to native english version .

### CODE REVIEW

**Comment by joway** [comment]
enable cla

**Comment by floreks** [comment]
It's a bit too hidden. We need a runtime option that can be changed while using Dashboard without the need to exec into container. While this would work, I believe only very few people would actually use it.

We could probably use cookies to store user preferred language and add some UI option to select supported language.

**Comment by maciaszczykm** [comment]
I think we could accept it only as a temp solution.

**Comment by cheld** [comment]
Maybe an even simpler alternative is to use environment variable (like in PR) to completely disable translations. (Until we have settings page)

**Comment by cheld** [comment]
Similar request https://github.com/kubernetes/dashboard/issues/2240

**Comment by cheld** [comment]
Settings page https://github.com/kubernetes/dashboard/issues/2417

**Pull request merged**
