### PR TITLE
ci(helm): remove remote PR branch if already exists.

### PR DESCRIPTION
**Pull request by desaintmartin**
Otherwise, we can't have several PRs opened by CD, or we can't create new PR if old branch has not been deleted.

### CODE REVIEW

**Comment by floreks** [comment]
To be honest, I am not sure if it will work since branches are protected and only the repo admin can remove them right now.

**Comment by floreks** [comment]
I'll try to do it later today. It would be best if the name of the branch could contain some unique part such as short commit hash or some id so that it would not be blocked by this auto branch protection mechanism. Every time I want to delete the branch I have to first go to repo settings and remove branch protection first.

**Comment by desaintmartin** [comment]
Actually, auto-creating PRs out of order may result in a missing version, and I think using the current way (one single git repository) we can't do much better. Missing a past version is not that much important, but missing a next version is.

Can't you see a "delete branch" from the PR I mentioned?

**Comment by floreks** [comment]
> Can't you see a "delete branch" from the PR I mentioned?

The Kubernetes org has the configuration in place that automatically adds protection to all branches in the repo every couple of minutes. I have to first remove the protection manually before deleting the branch. Unfortunately, it's a bit inconvenient.

**Comment by desaintmartin** [comment]
Okay, I see. Maybe I can actually setup a fork outside of the kubernetes organization so that it really works like a normal PR without any special permission required, but that would mean that CI/CD would push on this one. I suppose this is okay since I would give access from "my" fork to the CI/CD here, but that is a bit... uncommon.

**Pull request closed without merging**
