### PR TITLE
go mod: mark as v2

### PR DESCRIPTION
**Pull request by bengadbois**
For go module versions >1, the version should be marked

See https://github.com/google/go-github/blob/master/go.mod as an example

### CODE REVIEW

**Comment by floreks** [comment]
I am not really a fan of this solution. We do use go modules but Dashboard is not really intended to be used as a dependency and was never designed to follow go standards for creating modules.

**Comment by maciaszczykm** [comment]
I remember there was similar issue in the past and we had some issues with changing all versions to v2. I agree with @floreks that our focus is not to provide backend that can be reused, we focus to make it work for our app. However, if you make it work and it will not be hacky I think we can merge since it will not harm us.

**Comment by floreks** [comment]
Related to https://github.com/kubernetes/dashboard/issues/5086

**Comment by floreks** [comment]
We might rethink that while designing a new API and splitting UI/API into different containers.

/close

**Pull request closed without merging**
