### PR TITLE
Support multi locales in one translation file

### PR DESCRIPTION
**Pull request by shu-mutou**
`zh` is same as `zh-cn`, so maintain `zh` and change `zh-cn` as link to `zh`.

Also, added support for `i18n/locales_not_for_build_local` that keeps locales not for build as local setting for developer. Because building dashboard takes much time.

Ref: #4734 [comment](https://github.com/kubernetes/dashboard/issues/4734#issuecomment-574036444)
Ref: #4763

### CODE REVIEW

**Comment by floreks** [comment]
I am not sure if creating a symbolic link is a correct way of doing this. Every translation file in the header has information about `target-language`

https://github.com/kubernetes/dashboard/blob/14ae7c1f159f218a98aaf6c9e994f0c18da57a40/i18n/zh-cn/messages.zh-cn.xlf#L3

If we create a symbolic link to a different language code, then `target-language` will not be correct.

**Comment by shu-mutou** [comment]
We can use `zh-Hans` representing Simplified Chinese and and `zh-Hant` for Traditional Chinese.
http://www.iana.org/assignments/lang-tags/zh-Hans
http://www.iana.org/assignments/lang-tags/zh-Hant

Firefox and Chrome don't seem to have `zh-Hans` and `zh-Hant`, but we can create them for translation work and link to them from other `zh*`s.

It has inconsistent in `target-language` but reasonable, I think. npm builds dashboard for each languages with symbolic linked `messages.xx.xlf` file and the binary works perfectly as expected.

I'll investigate how not to build `zh-hans` and `zh-hant` that won't be use and update document.

/hold

**Comment by hwdef** [comment]
This may not be the right way.
Although both mainland China and Singapore use simplified Chinese, some words are different.
Although Taiwan and Hong Kong both use traditional Chinese, they are also very different.
So we should use different files for each region

**Comment by shu-mutou** [comment]
/hold
@hwdef I see situations for zh locales. I'll revert zh* reconstructions. Thanks.

**Comment by shu-mutou** [comment]
@hwdef, how about `zh` and `zh-cn` ? Are there deference between them?

**Comment by hwdef** [comment]
@shu-mutou  
zh represents all kinds of Chinese, it is better to make zh consistent with zh-cn, because zh-cn is the most used.

**Comment by shu-mutou** [comment]
@hwdef I got it. I'll make `zh-cn` as link to `zh`.

**Comment by shu-mutou** [comment]
@floreks Changes for this PR are coming back to first situation and inconsistency in `target-language` is back. But `zh` means "all kinds of Chinese" and its contents is same as `zh-cn`, as hwdef said, so it's reasonable doing so, I think.

**Comment by floreks** [comment]
I am not fully sure if keeping target locale that is different than configured locale code will not cause some issues during compiling the translated versions. Having multiple overlapping target languages might cause issues.

**Comment by shu-mutou** [comment]
@floreks No worry, I think. Dashboard is built with `ng build --i18nLocale = [locale]` and the Angular documentation says that the locale specified by this option will be set to the `LOCALE_ID` of the compiled file.
https://github.com/angular/angular/blob/master/aio/content/guide/i18n.md#i18n-pipes

In fact, `LOCALE_ID` in compiled JavaScript files for `zh-cn` that created as a symbolic link to`zh` in this PR is `zh-cn` instead of `zh`.
As same as `zh-cn`, compiled files for `ja` or` fr` that do not have `target-language` in xlf files have each `LOCALE_ID` specified with `--i18nLocale` option.

**Comment by floreks** [comment]
@shu-mutou makes sense.

/lgtm

**Pull request merged**
