### PR TITLE
Create plugin/base branch to act as boilerplate for new plugins

### LINKED ISSUE #1832: Introduce plugin mechanism?
Starting a discussion here. Plugin mechanism should allow all people using their third party resources to customize Dashboard to their needs.

Things to consider:
 - Architecture
 - How would it enhance Dashboard functionalities (dynamically added components?)
 - How would it connect to external APIs
 - Limitations and possibilities (how much can we enhance Dashboard UI with plugins?)

### PR DESCRIPTION
**Pull request by ajatprabha**
This PR is in an early stage to close #1832 

What's Missing:
- [x] Installation and serving mechanism from the backend(#4017)
- [x] Ability to import and mount bundled plugin in the browser based on a config generated by the backend
- [x] Support plugins on the backend as a CRD for easy installation
- [ ] Error Handling
...and a lot of other things which shall be added as progress is made.

### CODE REVIEW

**Comment by ajatprabha** [comment]
PTAL @floreks @maciaszczykm

**Comment by maciaszczykm** [comment]
Checking it.

**Comment by maciaszczykm** [comment]
/approve
/cc @floreks 

LGTM if okay for you.

**Pull request merged**
