### PR TITLE
Japanese localization

### PR DESCRIPTION
**Pull request by Yamagami-Takuma**
@f-higashi Can you review?

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1225)

### CODE REVIEW

**Comment by Yamagami-Takuma** [comment]
@bryk
#1216 is incleded in 1.4 release?
If so, I'll create another PR after it's merged. :)

**Comment by f-higashi** [comment]
:lgtm:

@floreks  @digitalfishpond 
You can merge this.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1225#-:-KRazsjGX7_niSbRiorx:b-11o50p)*

**Comment by bryk** [comment]
@Yamagami-Takuma #1216 will be merged today. Can you provide translations for "CPU usage history" and "Memory usage history"? We'll paste them into the PR :)

**Comment by f-higashi** [comment]
@bryk 

"CPU usage history" : "CPU使用量の履歴"
"Memory usage history" : "メモリー使用量の履歴"

**Pull request merged**
