### PR TITLE
Added graphs and backend data select support to all detail pages.

### PR DESCRIPTION
**Pull request by PiotrDabkowski**
Also I hope this update finally fixes IE 11 tests.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1192)

### CODE REVIEW

**Comment by bryk** [comment]
A few trivial comments. Will test now. PTAL

---

Reviewed 71 of 74 files at r1.
Review status: 71 of 74 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/deploymentdetail/deploymentdetail.html, line 53 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1192#-KQuNkAsfPtxbRmo2GGs:-KQuNkAsfPtxbRmo2GGt:b-qrayql) ([raw file](https://github.com/kubernetes/dashboard/blob/79d11b74235313730567f536144a62c6a470bed4/src/app/frontend/deploymentdetail/deploymentdetail.html#L53)):*
> ```HTML
> </kd-content-card>
> 
> <kd-event-card-list event-list="::ctrl.deploymentDetail.eventList" event-list-resource="::ctrl.petSetEventsResource"></kd-event-card-list>
> ```

Pet set?

---

*[src/app/frontend/nodedetail/nodeinfo.html, line 110 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1192#-KQuO_dQEKKQ9ZG5e4Pw:-KQuO_dQEKKQ9ZG5e4Px:b-7741o) ([raw file](https://github.com/kubernetes/dashboard/blob/32ee6b3506d75684e230eee3f85626f7c00d1a14/src/app/frontend/nodedetail/nodeinfo.html#L110)):*
> ```HTML
> </kd-content-card>
> <kd-content-card>
>   <kd-title>{{::$ctrl.i18n.MSG_NODE_DETAIL_PODS_LABEL}}</kd-title>
> ```

Why removed? 

---

*[src/app/frontend/podlist/podcardlist.html, line 45 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1192#-KQuOkuFiY_bQ8ihZC3j:-KQuOkuFiY_bQ8ihZC3k:b-6bbkvt) ([raw file](https://github.com/kubernetes/dashboard/blob/79d11b74235313730567f536144a62c6a470bed4/src/app/frontend/podlist/podcardlist.html#L45)):*
> ```HTML
>   </kd-resource-card-header-columns>
> 
>   <kd-resource-card ng-if="::$ctrl.podListResource" total-items="::$ctrl.podList.listMeta.totalItems"
> ```

Remove this ng-if? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1192#-:-KQuP2UsHbrjGViocj6h:bjth5ce)*

**Comment by bryk** [comment]
Pagination for replica set events does not work 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1192#-:-KQuQDwB4aBUiq8sT1pj:b-ynexks)*

**Comment by bryk** [comment]
Same with RS pods 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1192#-:-KQuRCpP0w2sYrjTn1oz:b-3mgog8)*

**Comment by PiotrDabkowski** [comment]
@bryk Should work now on prod :)

---

Review status: 67 of 77 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/deploymentdetail/deploymentdetail.html, line 53 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1192#-KQuNkAsfPtxbRmo2GGs:-KQuo2YCCqleeinbpwYB:b-896fix) ([raw file](https://github.com/kubernetes/dashboard/blob/79d11b74235313730567f536144a62c6a470bed4/src/app/frontend/deploymentdetail/deploymentdetail.html#L53)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Pet set?
</details>
Done.

---

*[src/app/frontend/nodedetail/nodeinfo.html, line 110 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1192#-KQuO_dQEKKQ9ZG5e4Pw:-KQuluiQe5M7yD7UkWr3:b-6nipdr) ([raw file](https://github.com/kubernetes/dashboard/blob/32ee6b3506d75684e230eee3f85626f7c00d1a14/src/app/frontend/nodedetail/nodeinfo.html#L110)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Why removed? 
</details>
This was moved to nodedetail.html. Why would pod list be in nodeinfo?

---

*[src/app/frontend/podlist/podcardlist.html, line 45 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1192#-KQuOkuFiY_bQ8ihZC3j:-KQumVoOld_V0MWT7BcB:b-896fix) ([raw file](https://github.com/kubernetes/dashboard/blob/79d11b74235313730567f536144a62c6a470bed4/src/app/frontend/podlist/podcardlist.html#L45)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Remove this ng-if? 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1192#-:-KQunO0KpciohkqaYtlT:bu3sq4m)*

**Comment by bryk** [comment]
Reviewed 2 of 74 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/common/components/graph/tick_values.js, line 23 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1192#-KQyJKZTmabxnT20Nn-c:-KQyJKZTmabxnT20Nn-d:b-qs9rqr) ([raw file](https://github.com/kubernetes/dashboard/blob/2df9d504ef2ccd3e0495ee0b61551bd882e03e8a/src/app/frontend/common/components/graph/tick_values.js#L23)):*
> ```JavaScript
> 
> /**
>  * Returns a nice looking number between a and b.
> ```

Can you define nice? 

---

*[src/app/frontend/nodedetail/nodeinfo.html, line 110 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1192#-KQuO_dQEKKQ9ZG5e4Pw:-KQyJPwCsSoRJUTTpA9v:b-1dcquh) ([raw file](https://github.com/kubernetes/dashboard/blob/32ee6b3506d75684e230eee3f85626f7c00d1a14/src/app/frontend/nodedetail/nodeinfo.html#L110)):*
<details><summary><i>Previously, PiotrDabkowski (Piotr Dabkowski) wrote…</i></summary>
> This was moved to nodedetail.html. Why would pod list be in nodeinfo?
</details>
Correct. 

---

*[src/app/frontend/workloads/workloads.html, line 17 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1192#-KQyKk9oSsgiBTJw3ynI:-KQyKk9oSsgiBTJw3ynJ:b6r03k4) ([raw file](https://github.com/kubernetes/dashboard/blob/2df9d504ef2ccd3e0495ee0b61551bd882e03e8a/src/app/frontend/workloads/workloads.html#L17)):*
> ```HTML
> -->
> 
> <kd-graph-card title="::$ctrl.i18n.MSG_WORKLOADS_GRAPH_CARD_TITLE"
> ```

This should be in `{{::   }}` (Applies to all invocations) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1192)*

**Comment by PiotrDabkowski** [comment]
@bryk also fixed integration tests, PTAL.

---

Review status: 66 of 87 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/common/components/graph/tick_values.js, line 23 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1192#-KQyJKZTmabxnT20Nn-c:-KQybfOBhfrZtbysqFok:b-896fix) ([raw file](https://github.com/kubernetes/dashboard/blob/2df9d504ef2ccd3e0495ee0b61551bd882e03e8a/src/app/frontend/common/components/graph/tick_values.js#L23)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Can you define nice? 
</details>
Done.

---

*[src/app/frontend/workloads/workloads.html, line 17 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1192#-KQyKk9oSsgiBTJw3ynI:-KQybgH6dGbLufzNlTz3:btu5qo2) ([raw file](https://github.com/kubernetes/dashboard/blob/2df9d504ef2ccd3e0495ee0b61551bd882e03e8a/src/app/frontend/workloads/workloads.html#L17)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> This should be in `{{::   }}` (Applies to all invocations) 
</details>
Changed the name of variable title to graphTitle, now works :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1192#-:-KQyn1VDUF63YKfRXIAQ:b-ts42bs)*

**Comment by bryk** [comment]
Please resolve conflicts. Otherwise :lgtm:. I'll do final tests then. 

---

Reviewed 21 of 21 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1192#-:-KQyuJ_qaSge5BW4HS85:b-j3n4ot)*

**Comment by bryk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1192#-:-KQzB-pfbzIg84D9g-mu:bnfp4nl)*

**Pull request merged**
