### PR TITLE
[helm] Add ServiceMonitor relabel Configs

### PR DESCRIPTION
**Pull request by jkroepke**
We have to add relabel configs here to enrich the metrics from the dashboard

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@jkroepke Tests are not passing. You need to merge/rebase and then bump chart version.

**Comment by jkroepke** [comment]
@maciaszczykm added.

**Comment by jkroepke** [comment]
Seems like an issue with codecov, but the tests are red anyways.

**Comment by jkroepke** [comment]
Merged from main (to fix CI issus)

**Review by maciaszczykm — APPROVED** [review]
/lgtm

**Pull request merged**
