### PR TITLE
Add kubernetes.io/cluster-service: "true" label to deploy files

### LINKED ISSUE #565: Run as a cluster-service?
Should this be run as a cluster service?

If the metadata for the RC/Service were annotated with `kubernetes.io/cluster-service: "true"` then it would be treated as a cluster-service, and would appear in the output for `kubectl cluster-info`.

### PR DESCRIPTION
**Pull request by bryk**
Fixes #565

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/570)

### CODE REVIEW

**Comment by bryk** [comment]
@colemickens can you review?

**Comment by colemickens** [comment]
@bryk `true` has to be quoted. Otherwise it's an error:

```
kubectl create -f https://raw.githubusercontent.com/bryk/dashboard/cluster-service/src/deploy/kubernetes-dashboard-canary.yaml
[pos 127]: json: expect char '"' but got char 't'
```

**Comment by bryk** [comment]
Oh, yeah. PTAL

**Comment by colemickens** [comment]
LGTM

**Comment by bryk** [comment]
Thanks!

**Pull request merged**
