### PR TITLE
Fix redirect-loop issue that happens on errors (#1203)

### PR DESCRIPTION
**Pull request by bryk**
Previously to reprodce:
1. Start a proxy and a dev server
2. Kill the proxy
3. Open the UI
4. See that it is in a redirect loop

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1204)

### CODE REVIEW

**Comment by bryk** [comment]
@batikanu @digitalfishpond Can you review this?

**Comment by batikanu** [comment]
Just one question otherwise LGTM

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/common/components/contentcard/contentcard.scss, line 23 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1204#-KR8htzuxASfeHEpvaEU:-KR8htzv8VlWyUCD8khV:b-qtnvla) ([raw file](https://github.com/kubernetes/dashboard/blob/56faf15175e25948ae3d460d71147a17c7a3df18/src/app/frontend/common/components/contentcard/contentcard.scss#L23)):*
> ```SCSS
> 
> kd-content-card {
>   display: block;
> ```

I just wonder why do you have display:block  both in  kd-content-card element and .kd-content-card class?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1204#-:-KR8iGTGPPVr-3Mh_X97:bo4vxzl)*

**Comment by bryk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/common/components/contentcard/contentcard.scss, line 23 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1204#-KR8htzuxASfeHEpvaEU:-KR8ke2bwTydC1nM2cDu:bs70zw7) ([raw file](https://github.com/kubernetes/dashboard/blob/56faf15175e25948ae3d460d71147a17c7a3df18/src/app/frontend/common/components/contentcard/contentcard.scss#L23)):*
<details><summary><i>Previously, batikanu (Batikan Urcan) wrote…</i></summary>
> I just wonder why do you have display:block  both in  kd-content-card element and .kd-content-card class?
</details>
The DOM tree is:
```html
<kd-content-card>
  <div class="kd-content-card">

```

And I want to make kd-content-card display:block (default for custom element is different) and add margin (so that is collapses for adjacent elements).

Is this OKay? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1204)*

**Comment by batikanu** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/common/components/contentcard/contentcard.scss, line 23 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1204#-KR8htzuxASfeHEpvaEU:-KR8l_S6aePMLnLGkKeL:bkwigsp) ([raw file](https://github.com/kubernetes/dashboard/blob/56faf15175e25948ae3d460d71147a17c7a3df18/src/app/frontend/common/components/contentcard/contentcard.scss#L23)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> The DOM tree is:
> ```html
> <kd-content-card>
>   <div class="kd-content-card">
> 
> ```
> 
> And I want to make kd-content-card display:block (default for custom element is different) and add margin (so that is collapses for adjacent elements).
> 
> Is this OKay? 
</details>
Isn't it enough to just use it for "kd-content-card" element rather than duplicating it for both element and class. ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1204)*

**Comment by batikanu** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/common/components/contentcard/contentcard.scss, line 23 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1204#-KR8htzuxASfeHEpvaEU:-KR8pLteejCLqgw3AN8R:b-caopkv) ([raw file](https://github.com/kubernetes/dashboard/blob/56faf15175e25948ae3d460d71147a17c7a3df18/src/app/frontend/common/components/contentcard/contentcard.scss#L23)):*
<details><summary><i>Previously, batikanu (Batikan Urcan) wrote…</i></summary>
> Isn't it enough to just use it for "kd-content-card" element rather than duplicating it for both element and class. ?
</details>
Ok I see the problem in deploy page. There <kd-content class="kd-content-padded ng-scope"> doesn't inherit display:block property by default. It is ok for me now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1204)*

**Comment by bryk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/common/components/contentcard/contentcard.scss, line 23 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1204#-KR8htzuxASfeHEpvaEU:-KR8tcTASTENXS1DHuhF:bdaav7u) ([raw file](https://github.com/kubernetes/dashboard/blob/56faf15175e25948ae3d460d71147a17c7a3df18/src/app/frontend/common/components/contentcard/contentcard.scss#L23)):*
<details><summary><i>Previously, batikanu (Batikan Urcan) wrote…</i></summary>
> Ok I see the problem in deploy page. There <kd-content class="kd-content-padded ng-scope"> doesn't inherit display:block property by default. It is ok for me now.
</details>
Cool, thanks! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1204)*

**Pull request merged**
