### PR TITLE
Add a Service Monitor to the Helm Chart

### PR DESCRIPTION
**Pull request by ashwin153**
- Enables monitoring of the Kubernetes Dashboard by the Prometheus Operator. (e.g., alert when it is down)
- Service monitor is disabled by default, but can be enabled by setting `serviceMonitor.enabled: true`.

### CODE REVIEW

**Comment by ashwin153** [comment]
Signed the CLA.

**Comment by desaintmartin** [comment]
/assign
Thanks for the PR! I think you still miss a signoff to your commits.

**Review by desaintmartin — APPROVED** [review]

**Comment by ashwin153** [comment]
Signed the CLA.

**Comment by desaintmartin** [comment]
Thanks!
/lgtm

**Comment by desaintmartin** [comment]
Could you bump the minor version of the chart.yaml version ?

**Review by desaintmartin — APPROVED** [review]

**Pull request merged**
