### PR TITLE
Change the token login input field to password

### PR DESCRIPTION
**Pull request by farcaller**
This prevents the browsers from caching the value.

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Nice change. I wondering about one thing - masking the token value. Is it needed?

I think we can also set `autocomplete` attribute to solve https://github.com/kubernetes/dashboard/issues/2641. Can you do it?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocomplete

**Comment by farcaller** [comment]
Done (although #2641 would be solved by the previous commit alone—that's the default behavior).

**Comment by farcaller** [comment]
> I wondering about one thing - masking the token value. Is it needed?

I don't expect anyone to type the auth token manually, to be honest. There's very little value in showing a huge "random-looking" string to the end user as they won't be able to parse it in their mind either way.

**Comment by maciaszczykm** [comment]
Fine, thanks. Can you also set input types to other login forms?

**Comment by farcaller** [comment]
Basic auth form is already correct, as is kubeconfig one.

**Comment by floreks** [comment]
From what I have checked autocomplete won't help us with password managers. In my case browser cached last password and used it to autocomplete the field. It can be removed. Password managers integration might be not easily doable here. It will work only partially.

**Comment by farcaller** [comment]
> In my case browser cached last password and used it to autocomplete the field. It can be removed

That was my point too. I'll remove the second commit as the first one will do the job.

**Comment by kachkaev** [comment]
Thanks for this PR @farcaller! Keen to check if password managers work a bit better with the form now 😃 Looking forward to for docker image `v1.8.1` or `v1.9.0`!

**Comment by maciaszczykm** [comment]
@kachkaev Check dev release. You can find more info in our wikis.

**Comment by kachkaev** [comment]
Good point @maciaszczykm! See my thoughts on the new experience here: https://github.com/kubernetes/dashboard/issues/2641#issuecomment-349607302.

**Pull request merged**
