### PR TITLE
Fix metrics

### PR DESCRIPTION
**Pull request by maciaszczykm**
Fixes https://github.com/kubernetes/dashboard/issues/4145.

### CODE REVIEW

**Comment by maciaszczykm** [comment]
I have managed to fix the sparklines that are displayed right now even when there are completed pods:

Zrzut ekranu 2019-11-7 o 11 41 40

The problem with the main graphs still persists though.

**Comment by maciaszczykm** [comment]
The issue is fixed, but still, some improvements need to be done in next PRs:

Zrzut ekranu 2019-11-7 o 13 20 51

**Comment by maciaszczykm** [comment]
I think that in the long run, we have two options:
- do not ask about the resources that don't have metrics
- when a resource doesn't have metrics (sidecar is not returning them) then don't error

I have done the first to show sparklines. The second approach is used to silence the single errors that occur during scraping cumulative metrics.

**Comment by jeefy** [comment]
@maciaszczykm Solution lgtm for now, but CI is squawking on a goimports issue: https://travis-ci.org/kubernetes/dashboard/jobs/608704284#L1314

**Comment by maciaszczykm** [comment]
PTAL

**Comment by jeefy** [comment]
/lgtm

Thanks again for tackling this

**Comment by RedzRedz** [comment]
I use [v2.0.0-beta6](https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta6/aio/deploy/recommended.yaml), but i still can't see cpu and mem usage in dashboard. 
This is some logs in pod kubernetes-dashboard-****.
```
2019/12/03 15:35:36 Cannot get metrics: received 0 resources from sidecar instead of 10
2019/12/03 15:35:36 Cannot get metrics: received 0 resources from sidecar instead of 10
2019/12/03 15:35:36 Cannot get metrics: received 0 resources from sidecar instead of 10
2019/12/03 15:35:36 Cannot get metrics: received 0 resources from sidecar instead of 10
2019/12/03 15:35:36 Cannot get metrics: received 0 resources from sidecar instead of 10
2019/12/03 15:35:36 Cannot get metrics: received 0 resources from sidecar instead of 10
2019/12/03 15:35:36 Cannot get metrics: received 0 resources from sidecar instead of 10
2019/12/03 15:35:36 Cannot get metrics: received 0 resources from sidecar instead of 10
2019/12/03 15:35:36 Cannot get metrics: received 0 resources from sidecar instead of 10
2019/12/03 15:35:36 Cannot get metrics: received 0 resources from sidecar instead of 10
2019/12/03 15:35:36 Skipping metric because of error: Metric label not set.
```

**Comment by pkesso** [comment]
@RedzRedz same on v2.0.0-beta7

**Comment by strainovic** [comment]
Same error on v2.0.0-beta8

2019/12/08 20:32:03 Cannot get metrics: received 34 resources from sidecar instead of 36

**Comment by maciaszczykm** [comment]
The error itself is not a problem if rest of the graphs show up. There is no data for completed resources anymore and that is this "error".

> 2019/12/08 20:32:03 Cannot get metrics: received 34 resources from sidecar instead of 36

In that case you should be able to see graphs for 34 resources which is totally fine.

We will work on improving this later, the message should not be even there and we should not "expect" data for completed resources.

**Comment by strainovic** [comment]
@maciaszczykm 
Unfortunately, I see no graphics if namespace has CronJobs/Jobs.

**Comment by maciaszczykm** [comment]
That is strange, can you open a new issue?

**Comment by pkesso** [comment]
Still getting `Cannot get metrics: received 0 resources from sidecar instead of 10` on v2.0.0b8, no CPU usage and memory usage graphs on dashboard.
Any tips?

**Comment by floreks** [comment]
Have you installed `metrics-server`?

**Comment by pkesso** [comment]
> Have you installed `metrics-server`?

Yes, metrics-server is running.

**Comment by ysaakpr** [comment]
Same with me, running the latest release beta8, Unable to get any metrics on any page, Attached sample logs from dashboard.

`2019/12/17 05:28:18 Getting list of all deployments in the cluster
2019/12/17 05:28:18 [2019-12-17T05:28:18Z] Incoming HTTP/1.1 GET /api/v1/csrftoken/token request from 100.101.0.28:56098: 
2019/12/17 05:28:18 [2019-12-17T05:28:18Z] Outcoming response to 100.101.0.28:56098 with 200 status code
2019/12/17 05:28:18 Cannot get metrics: received 0 resources from sidecar instead of 2
2019/12/17 05:28:18 Cannot get metrics: received 0 resources from sidecar instead of 2
2019/12/17 05:28:18 Cannot get metrics: received 0 resources from sidecar instead of 2
2019/12/17 05:28:18 Cannot get metrics: received 0 resources from sidecar instead of 2`

**Comment by RedzRedz** [comment]
Thank you sir, i fix the problem. Because i dont install&nbsp;metrics server.
After i install&nbsp;metrics server, i can see cpu and memory usage in dashboard.
Its my problem.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Paul K."<notifications@github.com&gt;; 
发送时间: 2019年12月9日(星期一) 晚上11:39
收件人: "kubernetes/dashboard"<dashboard@noreply.github.com&gt;; 
抄送: "1019778654"<1019778654@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [kubernetes/dashboard] Fix metrics (#4506)




Still getting Cannot get metrics: received 0 resources from sidecar instead of 10 on v2.0.0b8, no CPU usage and memory usage graphs on dashboard.
 Any tips?

**Comment by ysaakpr** [comment]
I have confirmed, I have installed the metric-server, in kube-system namespace, following helm charts - https://github.com/helm/charts/tree/master/stable/metrics-server, And updated to latest. Still no metrics on the dashboard. I have verified that kubectl top also working, which means the metric server is working as expected.

**Comment by ysaakpr** [comment]
My metric server is running with `--kubelet-insecure-tls`. Unable to run it without that, since the kubelets are using self-signed certs(Default one created while Kops initialize the cluster)

**Pull request merged**
