### PR TITLE
Cleanup & build system updates

### PR DESCRIPTION
**Pull request by floreks**
Some cleanup stuff and minor fixes for the build system.

After further investigation with @maciaszczykm we found out that there is no native support for the `darwin/arm64` arch in docker on macOS, therefore we've decided to drop the `darwin/arm64` and `darwin/amd64` from officially supported architectures. New docker image releases will be built for `linux/amd64 linux/arm64 linux/arm linux/ppc64le linux/s390x`.

### CODE REVIEW

**Review by maciaszczykm — APPROVED** [review]
Verified, now it works fine on M1 Mac.

**Comment by floreks** [comment]
Fixes #7522

**Comment by FrenchBen** [comment]
Do we still want https://github.com/kubernetes/dashboard/pull/7521 since this made similar changes? @floreks

**Comment by floreks** [comment]
I think it is still valuable to have it merged.

**Pull request merged**
