### PR TITLE
Increase version

### LINKED ISSUE #1873: Prepare new release
Once owner references will be handled, we can make new release. @floreks added sorting and we have fixed few other issues. Is there anything missing for 1.6.1 at the moment?

### PR DESCRIPTION
**Pull request by maciaszczykm**
**Please do not merge yet.**

Testing it using development image on local `kubeadm` node:

- [x] all cluster resource pages
- [x] all workloads resource pages
- [x] all discovery resource pages
- [x] all config resource pages
- [x] search
- [x] filtering
- [x] deployment
- [x] general look
- [x] sorting
- [x] authorization token

Bugs/missing improvements:
- [ ] https://github.com/kubernetes/dashboard/issues/1827#issue-220147725 - no events for deployments
- [x] #1958 - filtering crashes

To be checked:
- [x] #1957

Closes #1873.

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Testing it on development release image.

**Comment by maciaszczykm** [comment]
Test checklist:

- [ ] all resource pages
- [ ] search
- [ ] filtering
- [ ] deployment
- [ ] general look
- [ ] sorting

**Comment by szegedim** [comment]
I get this error, when running 'kubectl create -f https://git.io/kube-dashboard' since this change. Is this an issue? The new version is not available in the repo, yet.
```
Failed to pull image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.1": rpc error: code = 2 desc = Tag v1.6.1 not found in repository gcr.io/google_containers/kubernetes-dashboard-amd64
```

**Comment by maciaszczykm** [comment]
@szegedim Linking to #1961. Images should be available soon.

**Pull request merged**
