### PR TITLE
Clarify how users can change apiserver-host in canary deployment

### LINKED ISSUE #484: Cannot configure apiserver URL
I am instantiating the kubernetes dashboard as described in the README.md.

```
kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard-canary.yaml
```
However when looking at the dashboard I am notified that a 500 error occured:

```
Get http://localhost:8080/api/v1/replicationcontrollers: dial tcp [::1]:8080: getsockopt: connection refused
```

When looking at the logs of the pod I can see the following:

```
2016/03/02 16:10:19 Starting HTTP server on port 9090
2016/03/02 16:10:19 Creating API server client for http://localhost:8080
2016/03/02 16:10:19 Creating in-cluster Heapster client
2016/03/02 16:10:25 Incoming HTTP/1.1 GET /api/v1/replicationcontrollers request from 172.17.35.0:47665
2016/03/02 16:10:25 Getting list of all replication controllers in the cluster
2016/03/02 16:10:25 Get http://localhost:8080/api/v1/replicationcontrollers: dial tcp [::1]:8080: getsockopt: connection refused
2016/03/02 16:10:25 Outcoming response to 172.17.35.0:47665 with 500 status code
2016/03/02 16:10:27 Incoming HTTP/1.1 GET /api/v1/replicationcontrollers request from 172.17.35.0:47664
2016/03/02 16:10:27 Getting list of all replication controllers in the cluster
2016/03/02 16:10:27 Get http://localhost:8080/api/v1/replicationcontrollers: dial tcp [::1]:8080: getsockopt: connection refused
2016/03/02 16:10:27 Outcoming response to 172.17.35.0:47664 with 500 status code
```

My environment consist of a master and 2 nodes setup on CentOS7. I am running the very latest version of Kubernetes (i.e. v1.2.0-alpha.8)

Kubectl is set properly on all nodes as the cluster-info shows:

```
[marcol@kube-master dashboard-canary]$  kubectl cluster-info
Kubernetes master is running at http://10.239.32.77:8080
KubeDNS is running at http://10.239.32.77:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns
KubeUI is running at http://10.239.32.77:8080/api/v1/proxy/namespaces/kube-system/services/kube-ui
```

How can I tell the dashboard where the apiserver resides? I'd like to have the option to do so passing some parameter to its container. Compiling the entire thing doesn't seem as a viable option.

### PR DESCRIPTION
**Pull request by bryk**
Fixes #484

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/489)

### CODE REVIEW

**Comment by bryk** [comment]
@taimir @batikanu  Can you review?

**Comment by batikanu** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/deploy/kubernetes-dashboard-canary.yaml, line 34 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/489#-KC0pTRxVvQUUmHijZcY:-KC0pTRxVvQUUmHijZcZ:-1940552735) ([raw file](https://github.com/kubernetes/dashboard/blob/96305abe4bb1f14b260c6a937d566de2a9728e27/src/deploy/kubernetes-dashboard-canary.yaml#L34)):*
here is the first minus extra or it is ok like that? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/489)*

**Comment by batikanu** [comment]
Just one question. Otherwise LGTM.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/489#-:-KC0pvU6BehrwHMLKRIa:-1489034931)*

**Comment by bryk** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/deploy/kubernetes-dashboard-canary.yaml, line 34 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/489#-KC0pTRxVvQUUmHijZcY:-KC0sg2PVaWSM7WqjAjq:1687084634) ([raw file](https://github.com/kubernetes/dashboard/blob/96305abe4bb1f14b260c6a937d566de2a9728e27/src/deploy/kubernetes-dashboard-canary.yaml#L34)):*
This is YAML. The dash is to indicate a list. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/489)*

**Pull request merged**
