### PR TITLE
Helm Chart: Fix chart-testing, upgrade ingress to networking.k8s.io/v1beta1, set metrics-provider=none if metrics scraper is not enabled.

### PR DESCRIPTION
**Pull request by desaintmartin**
Solve #5442

### CODE REVIEW

**Comment by desaintmartin** [comment]
Hm, increasing version of chart-testing-action seemed to break it...
/hold

**Review by floreks — APPROVED** [review]
/lgtm

**Comment by desaintmartin** [comment]
This is unexpected when I created the PR, the chart-testing tool now requires Ingresses to be `networking.k8s.io/v1beta1`. Does that look okay ?

**Comment by floreks** [comment]
That's a long title :slightly_smiling_face: 

/lgtm

**Comment by desaintmartin** [comment]
Too much things got in the way of simply adding this "else" clause!

**Pull request merged**
