### PR TITLE
Introduce global search

### LINKED ISSUE #1829: Introduce global search

### PR DESCRIPTION
**Pull request by maciaszczykm**
Basic global search implementation. Does not include any kind of advanced features or cache yet.

- [x] add backend
- [x] update toolbar
- [x] fix empty query search
- [x] handle all resources and sort them alphabetically
- [x] adjust search breadcrumb label
- [x] make filtering work on search results page
- [x] move search logic to the frontend
- [x] remove `!important`
- [x] update tests
- [x] test on `serve:prod`

Closes #1829.

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@danielromlein Is [this](https://projects.invisionapp.com/share/3C8BDK9ZD#/screens/182037314) mockup up to date?

**Comment by danielromlein** [comment]
Not seeing your comment anymore for some reason @maciaszczykm, but here's my thinking: since ultimately the direction we're heading with the chrome is this [app bar + light top bar](https://invis.io/XZ7RITOQD#/183042254_Light_Top_Bar_1280_Tabs), even though we don't have IAM at the moment it may make sense to introduce the top bar to accommodate search. Otherwise search could collide with the breadcrumb in certain situations and start to make the app bar cluttered.
WDYT?

**Comment by cheld** [comment]
Nice, looks similar to Inbox. (I assume we are not implementing the hero transition, though)

**Comment by maciaszczykm** [comment]
Current state:

image

Missing some styling tweaks and zoom icon in search bar.

**Comment by maciaszczykm** [comment]
Current state:

image

**Comment by danielromlein** [comment]
@maciaszczykm is there an environment where I could check this out? I have a few recommendations I might recommend and would like to click around with a prototype to get you precise feedback.

**Comment by maciaszczykm** [comment]
@danielromlein Not yet... But I will try to provide something for you.

Sorry for missing SIG UI again, we were busy with our current assignments and totally forgot to call in.

**Comment by danielromlein** [comment]
@maciaszczykm no worries! Thanks for the update.

**Comment by maciaszczykm** [comment]
It's ready for a review.

**Comment by maciaszczykm** [comment]
> Also personally I like what inbox does when we empty search bar and click on the page. It returns to the previous state. Our search behavior is a bit different but we could think about something similar.

It is yet another feature and I would like to merge this first and then work on enhancements. Search is pretty complex topic and we will not be able to do everything at once. This pull request is already big and I don't want it to grow anymore.

Regarding the idea itself I do not agree with it. I do not want to cause confusion and redirect user in described scenario. In my opinion such redirect would make sense only if we would have live updates of search results just like in Inbox. Currently this search is more like GitHub one and it does not have such feature.

> How should it behave on empty search submit? Different pages deal with that differently. Github tries to do a search and shows page that "This search could not be executed". Inbox just stays on current state and does nothing.

Search input is marked as `required`, so it will not allow to submit empty search query. When user will try to do it he will be notified with specific message, that he needs to fill query.

I am looking forward to @danielromlein suggestions, now or after it will be merged. Just like we did with filtering implemented by you.

**Comment by floreks** [comment]
> Regarding the idea itself I do not agree with it. I do not want to cause confusion and redirect user in described scenario. In my opinion such redirect would make sense only if we would have live updates of search results just like in Inbox. Currently this search is more like GitHub one and it does not have such feature.

I didn't mean to have it exactly the same because we do not have live search as u mentioned. Maybe something like `X` clear button that would get user back to previous page when used on search page. Arrow back is also an option. GitHub also is a bit different because it doesn't have to follow material spec guideliness like we should.

> Search input is marked as required, so it will not allow to submit empty search query. When user will try to do it he will be notified with specific message, that he needs to fill query.

For not it's ok. Maybe we'll think about something better later on.

We can merge it and update later after we receive feedback from @danielromlein.

**Pull request merged**
