### PR TITLE
Japanese localization of conditions of NodeDetail

### PR DESCRIPTION
**Pull request by Yamagami-Takuma**
Japanese localization of conditions of NodeDetail.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/914)

### CODE REVIEW

**Comment by Yamagami-Takuma** [comment]
@f-higashi Can you review?

**Comment by f-higashi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[i18n/messages-ja.xtb, line 525 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/914#-KKQkua7wT8GOljJ5hLJ:-KKQkua86eBP1DXK7fHm:530235386) ([raw file](https://github.com/kubernetes/dashboard/blob/7bca8f22a4e2ada5f2ff9cdf460cd1d1dac4b685/i18n/messages-ja.xtb#L525)):*
> ```
> 	<translation id="5537089191512972594" key="MSG_NODE_DETAIL_CONDITION_STATUS_HEADER" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Label 'Status' for the condition table header on the node details page.">状態</translation>
> 	<translation id="950124489847647296" key="MSG_NODE_DETAIL_CONDITION_LAST_HEARTBEAT_TIME_HEADER" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Label 'Last heartbeat time' for the condition table header on the node details page.">最終ハートビート時間</translation>
> 	<translation id="462429506979725356" key="MSG_NODE_DETAIL_CONDITION_LAST_TRANSITION_TIME_HEADER" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Label 'Last transition time' for the condition table header on the node details page.">最終移行時間</translation>
> ```

`最終遷移時間` is better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/914)*

**Comment by f-higashi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[i18n/messages-ja.xtb, line 522 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/914#-KKR7cpVwpiRsLDDHEbT:-KKR7cpVwpiRsLDDHEbU:943860834) ([raw file](https://github.com/kubernetes/dashboard/blob/7bca8f22a4e2ada5f2ff9cdf460cd1d1dac4b685/i18n/messages-ja.xtb#L522)):*
> ```
> 	<translation id="8014136669527475668" key="MSG_NAMESPACE_NOT_SELECTED" source="/usr/local/google/home/bryk/src/github.com/dashboard/.tmp/serve/app-dev.js" desc="Text for dropdown item that indicates that no namespace was selected">すべてのユーザネームスペース</translation>
> 	<translation id="7936401592140494096" key="MSG_NODE_DETAIL_CONDITIONS_LABEL" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Label 'Conditions' for the conditions tab on the node details page.">コンディション</translation>
> 	<translation id="4732177858407681815" key="MSG_NODE_DETAIL_CONDITION_TYPE_HEADER" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Label 'Type' for the condition table header on the node details page.">種類</translation>
> ```

How about `種別`.
I think `種類` is kind.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/914)*

**Comment by Yamagami-Takuma** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[i18n/messages-ja.xtb, line 522 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/914#-KKR7cpVwpiRsLDDHEbT:-KKR952EuZlFYhZPM5QT:1728384761) ([raw file](https://github.com/kubernetes/dashboard/blob/7bca8f22a4e2ada5f2ff9cdf460cd1d1dac4b685/i18n/messages-ja.xtb#L522)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> How about `種別`.
> I think `種類` is kind.
</details>
I fixed. And I also fixed the another line `種類`.

---

*[i18n/messages-ja.xtb, line 525 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/914#-KKQkua7wT8GOljJ5hLJ:-KKR92VfF-IU-LPxdTYV:1920760566) ([raw file](https://github.com/kubernetes/dashboard/blob/7bca8f22a4e2ada5f2ff9cdf460cd1d1dac4b685/i18n/messages-ja.xtb#L525)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> `最終遷移時間` is better.
</details>
I fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/914)*

**Comment by f-higashi** [comment]
:lgtm: 

You can merge this :)

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/914#-:-KKSHGPC2oVFtiAcFnEB:-1827479479)*

**Pull request merged**
