### PR TITLE
Add integration test for create and delete replication controller

### PR DESCRIPTION
**Pull request by maciaszczykm**
Added integration test for create and delete replication controller. Connected to #346. Rebased with @floreks' branch to make code more consistent.

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/429)

### CODE REVIEW

**Comment by bryk** [comment]
:lgtm:, we need a rebase though.

---

Reviewed 3 of 8 files at r1, 1 of 2 files at r2.
Review status: 4 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[build/protractor.conf.js, line 71 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/429#-KBh9fwmQ9yzqFZKywI_:-KBh9fwnSJl0sVokfVYP:2046085177) ([raw file](https://github.com/kubernetes/dashboard/blob/c0f458e0e0849db77b5640042859ec507324eba5/build/protractor.conf.js#L71)):*
Hmm.... Revert? I believe it is already changed on HEAD 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/429#-:-KBhBhcK10uaPo0kP3mP:-531902893)*

**Comment by maciaszczykm** [comment]
Rebased. PTAL

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[build/protractor.conf.js, line 71 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/429#-KBh9fwmQ9yzqFZKywI_:-KBhKEHJydTAWzxmlL0r:1491105269) ([raw file](https://github.com/kubernetes/dashboard/blob/c0f458e0e0849db77b5640042859ec507324eba5/build/protractor.conf.js#L71)):*
Fixed after rebase.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/429#-:-KBhJqLWrpOfMw_svHLF:708365884)*

**Comment by bryk** [comment]
Travis still fails. Fix? 

---

Reviewed 1 of 8 files at r1, 1 of 2 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/429#-:-KBhYOP_Jy0FN8HLJ_vv:-2076645211)*

**Comment by maciaszczykm** [comment]
Wow, it seems, that it was random issue on Travis. Didn't expect that in integration tests, but it worked locally and now it's fixed after commit empty ammend.

**Comment by bryk** [comment]
Travis is a little bit flaky , I know. We should fix this once it starts hurting us. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/429#-:-KBhsme5CnuuSKXps5rp:-884015681)*

**Pull request merged**
