### PR TITLE
Bump angular modules to 8.x latest

### PR DESCRIPTION
**Pull request by shu-mutou**
Almost angular modules are updated to 8.2.14.
This works fine in Chrome 80.0.3987.100, but does not fix login issue in Firefox 73 (#4922).

### CODE REVIEW

**Comment by floreks** [comment]
Actually I wanted to do migration to angular 9. It enables ivy by default, has lots of improvements and should also speed up our build.

**Comment by shu-mutou** [comment]
Agree. But it's time to finish work today. I'll tackle to version 9 tomorrow afternoon. 😉

**Comment by floreks** [comment]
> Agree. But it's time to finish work today. I'll tackle to version 9 tomorrow afternoon.

I am working on this one.

**Pull request merged**
