### PR TITLE
Update German translation.

### PR DESCRIPTION
**Pull request by headcr4sh**
I went through all `state="new"` entries and touched some of the already translated entries as well to improve upon wording here and there...

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@headcr4sh Sorry for long delay! Do you know someone from K8s org that would be able to review it?

**Comment by headcr4sh** [comment]
> @headcr4sh Sorry for long delay! Do you know someone from K8s org that would be able to review it?
No worries. ;-)

I am not sure where to look for support from translators.
Maybe someone in the Slack channel #sig-docs-localizations might be able to help out?
(Sorry -- I am not really familiar with how to gather reviewers for translation changes)

**Comment by maciaszczykm** [comment]
>Maybe someone in the Slack channel #sig-docs-localizations might be able to help out?

@headcr4sh That would be good, can you reach out?

**Comment by headcr4sh** [comment]
> > Maybe someone in the Slack channel #sig-docs-localizations might be able to help out?
> 
> @headcr4sh That would be good, can you reach out?

Sure. Already did that. :)
Let's see if anybody answers my call...

```
[Quote from my message to Slack #sig-docs-localizations]

Hi there,
we are looking for members of the Kubernetes GitHub organization to check on the updated
German translations of the Kubernetes Dashboard that I have provided.
If you want to help out, check out the PR and raise your hand. 😄
```

**Comment by headcr4sh** [comment]
I just left the same message from above in Slack channel #kubernetes-docs-de as "double post" to see if a possible translator who is not reading #sig-docs-localization might turn up. :-)

**Pull request merged**
