### PR TITLE
Update dependencies and regenerate lockfile

### PR DESCRIPTION
**Pull request by floreks**
- Bump min required Go version to `1.17.0`
- Bump used Kubernetes version to `v1.21`
- Bump kind to `v0.11.1`

### CODE REVIEW

**Comment by floreks** [comment]
closes #6367

**Comment by shu-mutou** [comment]
@floreks I also didn't want to write webpack in devDependencies, which I'm not using directly, but removing package-lock.json and recreating it with `npm i` didn't work. How did you recreate the package-lock.json? Thanks!

**Comment by floreks** [comment]
I usually just delete the lockfile, remove node modules directory and the install everything from scratch using `npm i`.

**Comment by shu-mutou** [comment]
Removing `node_modules` may have been missing. Thanks! ❤️

**Pull request merged**
