### PR TITLE
Helm chart: Update dashboard to 2.0.4.

### PR DESCRIPTION
**Pull request by desaintmartin**

### CODE REVIEW

**Comment by desaintmartin** [comment]
/hold
Waiting for https://github.com/kubernetes/dashboard/pull/5516 and https://github.com/kubernetes/dashboard/issues to be solved before.

**Comment by floreks** [comment]
What is this archive file?

`aio/kubernetes-dashboard-2.5.0.tgz`

**Comment by desaintmartin** [comment]
... A failed experiment from previous pr, let me remove it.

**Comment by maciaszczykm** [comment]
Restarted the tests.

**Pull request merged**
