### PR TITLE
fix typo in german translation

### PR DESCRIPTION
**Pull request by ronald**
Systeminforamtion => Systeminformation

### CODE REVIEW

**Comment by mkorbi** [comment]
Hi @ronald thank you for taking this typo into account.
Could you please sign the CLA: https://github.com/kubernetes/community/blob/master/CLA.md#the-contributor-license-agreement

/lgtm
/hold waiting for cla

**Comment by ronald** [comment]
Signed it. What to do next?

**Comment by mkorbi** [comment]
/hold cancel
let's merge it :) (if I have the power to do it...)
/approve

**Pull request merged**
