### PR TITLE
Fix running gulp in docker image 

### LINKED ISSUE #315: dashboard can't build on debian jessie
I have all versions of requirements already, but still can't build dashboard. Maybe I missed something else?

```
root@docker-django:~# docker --version
Docker version 1.9.0, build 76d6bc9
root@docker-django:~# go version
go version go1.5.3 linux/amd64
root@docker-django:~# nodejs --version
v5.5.0
root@docker-django:~# npm --version
3.3.12
root@docker-django:~# javac -version
javac 1.7.0_91
root@docker-django:~# gulp --version
[10:54:03] CLI version 3.9.0
[10:54:03] Local version 3.9.0
```

and the output is like this:
```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: Command failed: java -jar -XX:+TieredCompilation /data/tools/github.com/kubernetes/dashboard/node_modules/google-closure-compiler/compiler.jar --flagfile="/tmp/f9b67634-af70-41bc-8938-9b05f12836f9" --angular_pass --closure_entry_p
oint=module$index_module --compilation_level=ADVANCED_OPTIMIZATIONS --export_local_property_definitions --externs=/data/tools/github.com/kubernetes/dashboard/node_modules/google-closure-compiler/contrib/externs/angular-1.4.js --externs=/
data/tools/github.com/kubernetes/dashboard/node_modules/google-closure-compiler/contrib/externs/angular-1.4-http-promise_templated.js --externs=/data/tools/github.com/kubernetes/dashboard/node_modules/google-closure-compiler/contrib/exte
rns/angular-1.4-q_templated.js --externs=/data/tools/github.com/kubernetes/dashboard/node_modules/google-closure-compiler/contrib/externs/angular-material.js --externs=/data/tools/github.com/kubernetes/dashboard/node_modules/google-closu
re-compiler/contrib/externs/angular_ui_router.js --externs=/data/tools/github.com/kubernetes/dashboard/node_modules/google-closure-compiler/contrib/externs/angular-1.4-resource.js --externs=/data/tools/github.com/kubernetes/dashboard/src
/app/externs/backendapi.js --generate_exports --js_module_root=src/app/frontend --jscomp_error=* --jscomp_off=inferredConstCheck --jscomp_off=lintChecks --language_in=ECMASCRIPT6_STRICT --language_out=ECMASCRIPT3 --manage_closure_depende
ncies=true --use_types_for_optimization --js_output_file="app.js"
src/app/frontend/logs/logstoolbar/logstoolbar_controller.js:80: ERROR - variable goog is undeclared
  isTextColorInverted() { return this.logsColorInversionService_.getInverted(); }
  ^

1 error(s), 0 warning(s), 96.0% typed
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Unexpected variable goog
  Node(NAME goog): src/app/frontend/logs/logstoolbar/logstoolbar_controller.js:80:2
  isTextColorInverted() { return this.logsColorInversionService_.getInverted(); }
  Parent(GETPROP): src/app/frontend/logs/logstoolbar/logstoolbar_controller.js:80:2
  isTextColorInverted() { return this.logsColorInversionService_.getInverted(); }

        at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:202)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:621)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:316)
        at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:142)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
        at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1943)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:700)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:89)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:651)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:648)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Unexpected variable goog
        ... 21 more

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

### PR DESCRIPTION
**Pull request by bryk**
This simplifies Dockerfile and fixes bugs where it would produce errors
on build.

Fixes #315

### CODE REVIEW

**Comment by bryk** [comment]
@luxas @maciaszczykm Can you review?

**Comment by maciaszczykm** [comment]
After running `npm install` I've got no `bower_components` directory, unlike `node_modules`. Don't know why... Maybe it's my environment. Executing `sudo bower install --allow-root` works only directly from command line.

@luxas Can you check?

**Comment by bryk** [comment]
Extended the pull request. PTAL. Now running gulp in docker as well as as sudo should work.

**Comment by luxas** [comment]
I did this too when I was testing, but back then it didn't work, so that's why I added the user instead.
But I'll test it again now...

Why did the travis build fail btw?

**Comment by bryk** [comment]
@luxas Travis flaked while downloading a dependency.

**Comment by bryk** [comment]
Ping?

**Comment by maciaszczykm** [comment]
@bryk After checking out this branch, I've removed `node_modules` and `bower_components` and ran `npm install`. It seems, that it's still not working, because `bower_comnponents` wasn't created.

**Comment by Alasio** [comment]
https://raspberrypicloud.wordpress.com/2016/01/12/kubernetes-dashboard-on-raspberry-pi-2/

I see @millyna had the same issue and in her blog, she had to run `npm install` followed by `bower install –allow-root` to get it working.

Have you tried following the guide @millyna has put above?  Works perfectly and includes all the needed dependencies. 

 - A.

**Comment by bryk** [comment]
@Alasio Thanks for this. I've seen the blog and followed its instructions.

**Comment by bryk** [comment]
@maciaszczykm This PR is about making `./build/run-gulp-in-docker.sh` work. Try it. It works on my machine now. It runs npm with `--allow-root`, which is the trick that makes it work.

**Comment by bryk** [comment]
PTAL

**Comment by maciaszczykm** [comment]
@bryk Ahh, okay, my mistake. Unfortunately, I can't test `./build/run-gulp-in-docker.sh` due to proxy issues with my network:

```
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/f/fonts-dejavu/fonts-dejavu-core_2.34-1_all.deb  Error reading from server. Remote end closed connection [IP: 128.31.0.66 80]

E: Failed to fetch http://httpredir.debian.org/debian/pool/main/libx/libxcb/libxcb-dri3-0_1.10-3+b1_amd64.deb  Error reading from server. Remote end closed connection [IP: 128.31.0.66 80]

E: Failed to fetch http://httpredir.debian.org/debian/pool/main/libs/libsm/libsm6_1.2.2-1+b1_amd64.deb  Error reading from server. Remote end closed connection [IP: 128.31.0.66 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by luxas** [comment]
Testing this right now...

**Comment by luxas** [comment]
@bryk LGTM :)

(`npm install --unsafe-perm` didn't work for me earlier, but now it did)
```
$ build/run-gulp-in-docker.sh docker-image:canary
gcr.io/google_containers/kubernetes-dashboard           canary               9fff5ca1624f        6 minutes ago       35.35 MB
kubernetes-dashboard-build-image                        latest               9fbbb4de3b38        7 minutes ago       1.394 GB
```

**Comment by bryk** [comment]
Awesome, thanks for the review! :) Will merge soon.

**Pull request merged**
