### PR TITLE
Localization of breadcrumb + other missed strings

### PR DESCRIPTION
**Pull request by taimir**
OK, the breadcrumbs had to be localized as well (naturally). And I found some more unlocalized strings for the actionbar buttons.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/887)

### CODE REVIEW

**Comment by bryk** [comment]
Reviewed 12 of 14 files at r1.
Review status: 12 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/replicasetlist/replicasetlist_stateconfig.js, line 67 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/887#-KK8HOMiRda0BDJhdeI5:-KK8HOMiRda0BDJhdeI6:513109861) ([raw file](https://github.com/kubernetes/dashboard/blob/288797a5323f9828bf6aa2d7f01f51182616fe68/src/app/frontend/replicasetlist/replicasetlist_stateconfig.js#L67)):*
> ```JavaScript
> 
> const i18n = {
>   /** @export {string} @desc Label 'Replica Sets' that appears as a breadcrumbs on the action bar. */
> ```

No need to `@export` in stateconfig_.js files. Should we remove this? What do you think? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/887)*

**Comment by taimir** [comment]
Review status: 12 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/replicasetlist/replicasetlist_stateconfig.js, line 67 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/887#-KK8HOMiRda0BDJhdeI5:-KK8NfFQ1_rHXCkrRrqB:1361335637) ([raw file](https://github.com/kubernetes/dashboard/blob/288797a5323f9828bf6aa2d7f01f51182616fe68/src/app/frontend/replicasetlist/replicasetlist_stateconfig.js#L67)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> No need to `@export` in stateconfig_.js files. Should we remove this? What do you think? 
</details>
Uhm yeah, actually that's a good idea. Let me fix this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/887)*

**Comment by taimir** [comment]
Review status: 5 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/replicasetlist/replicasetlist_stateconfig.js, line 67 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/887#-KK8HOMiRda0BDJhdeI5:-KK8izRE5ysJSoecRGEo:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/288797a5323f9828bf6aa2d7f01f51182616fe68/src/app/frontend/replicasetlist/replicasetlist_stateconfig.js#L67)):*
<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> Uhm yeah, actually that's a good idea. Let me fix this.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/887)*

**Comment by bryk** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/887)*

**Comment by bryk** [comment]
:lgtm:

<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> #### Localization of breadcrumb \+ other missed strings
> 
> OK, the breadcrumbs had to be localized as well (naturally). And I found some more unlocalized strings for the actionbar buttons.
> 
> 
> 
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/887#-:-KK90zVfliGISgdj8a3p:1417088721)*

**Pull request merged**
