### PR TITLE
Add conditions to node detail page

### LINKED ISSUE #903: Add conditions to node details
Add conditions to node details page, like in `kubectl`:

image

### PR DESCRIPTION
**Pull request by maciaszczykm**
Added conditions to node detail page:

image

Closes #903.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/906)

### CODE REVIEW

**Comment by bryk** [comment]
I'm wondering whether to put this in a separate tab, or just in the overview details view. Do you have any opinions?

 I think it should be in the overview. We can paginate if there is a lot of conditions. 

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/906#-:-KKJNo5KHIqWqOURokTq:1448615073)*

**Comment by maciaszczykm** [comment]
After moving it to overview tab it looks a lot better, so I agree. There is not too much info to split it into 2 tabs. After update:



PTAL

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/906#-:-KKJTG0QZpL_d1Yj9Ipc:1065589930)*

**Comment by maciaszczykm** [comment]
@bryk Pagination is already applied.

**Comment by floreks** [comment]
Small comments. Other than that :lgtm:

---

Reviewed 7 of 11 files at r1, 3 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/externs/backendapi.js, line 603 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/906#-KKN-f5HXmL_oPRLIO_4:-KKN-f5HXmL_oPRLIO_5:2021503831) ([raw file](https://github.com/kubernetes/dashboard/blob/6f02d8a556d9cc0fa95f66b9fad57c889e1a4d3a/src/app/externs/backendapi.js#L603)):*
> ```JavaScript
> /**
>  * @typedef {{
>  *   nodes: !Array<!backendApi.Node>
> ```

s/backendapi.Node/backendApi.NodeCondition

---

*[src/app/frontend/common/components/resourcecard/resourcecard_component.js, line 83 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/906#-KKN-kkxmnBR2e9LhBPZ:-KKN-kkxmnBR2e9LhBP_:1328302101) ([raw file](https://github.com/kubernetes/dashboard/blob/6f02d8a556d9cc0fa95f66b9fad57c889e1a4d3a/src/app/frontend/common/components/resourcecard/resourcecard_component.js#L83)):*
> ```JavaScript
>   bindings: {
>     /** type {boolean} Should be set to true if there is no object metadata. */
>     'omitMeta': '=',
> ```

One time binding should be fine.

---

*[src/app/frontend/nodedetail/nodeinfo.html, line 93 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/906#-KKN-talNs1VAu1XtniX:-KKN-talNs1VAu1XtniY:-787596679) ([raw file](https://github.com/kubernetes/dashboard/blob/6f02d8a556d9cc0fa95f66b9fad57c889e1a4d3a/src/app/frontend/nodedetail/nodeinfo.html#L93)):*
> ```HTML
>     <kd-node-conditions conditions="::$ctrl.node.conditions"></kd-node-conditions>
>   </kd-content>
> </kd-content-card>
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/906#-:-KKN-wrIHvn38iDvEbm2:-1237818150)*

**Comment by maciaszczykm** [comment]
PTAL

---

Review status: 5 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/externs/backendapi.js, line 603 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/906#-KKN-f5HXmL_oPRLIO_4:-KKN8qIOR083nUcjFSou:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/6f02d8a556d9cc0fa95f66b9fad57c889e1a4d3a/src/app/externs/backendapi.js#L603)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> s/backendapi.Node/backendApi.NodeCondition
</details>
Done.

---

*[src/app/frontend/common/components/resourcecard/resourcecard_component.js, line 83 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/906#-KKN-kkxmnBR2e9LhBPZ:-KKN8qtjU2SmtK-RIaXY:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/6f02d8a556d9cc0fa95f66b9fad57c889e1a4d3a/src/app/frontend/common/components/resourcecard/resourcecard_component.js#L83)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> One time binding should be fine.
</details>
Done.

---

*[src/app/frontend/nodedetail/nodeinfo.html, line 93 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/906#-KKN-talNs1VAu1XtniX:-KKN8rZrHEzqnx2uK4L5:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/6f02d8a556d9cc0fa95f66b9fad57c889e1a4d3a/src/app/frontend/nodedetail/nodeinfo.html#L93)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> new line
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/906#-:-KKN8sZpbppdTPBL64Vc:676965300)*

**Comment by floreks** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/906#-:-KKNDthjwC4czPRYkHka:1417088721)*

**Pull request merged**
