### PR TITLE
Update Traditional Chinese translations and fix typo

### PR DESCRIPTION
**Pull request by ydFu**
* The commit fixed some words ,sentences and typo for Traditional Chinese translations(zh-Hant)

Signed-off-by: ydFu <ader.ydfu@gmail.com>

### CODE REVIEW

**Review by helight — APPROVED** [review]
LGTM

**Comment by ydFu** [comment]
/assign @helight
I tear off the label of needs-rebase,
Please help to review this PR.
If there has any question, please don't hesitate to let me know. Thanks.

**Review by helight — APPROVED** [review]
/lgtm

**Review by tanjunchen — COMMENTED** [review]
/approve

**Pull request merged**
