### PR TITLE
Add frontend for Daemon Set

### LINKED ISSUE #765: List and details page for daemon sets
I'm starting to work on this. Generic details page template:

Design template

### PR DESCRIPTION
**Pull request by maciaszczykm**
Added frontend (list and detail views) for Daemon Sets. 

- [x] add details and list view for Daemon Sets
- [x] add tests
- [x] update JSDocs
- [x] fix minor issues
- [x] test on `gulp serve:prod`
- [x] apply `gulp format-javascript` and `gofmt` to whole project

Closes #765.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/772)

### CODE REVIEW

**Comment by bryk** [comment]
Looks nice, a few cosmetic comments. Finish your todo list and let's merge :) 

<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> #### Add frontend for Daemon Set
> 
> Added frontend (list and detail views) for Daemon Sets. 
> 
> 
> 
> - [ ] add tests
> 
> - [ ] update JSDocs
> 
> - [ ] fix minor issues
> 
> 
> 
> Closes #765.
> 
> 
> 
> 
</details>


---

Reviewed 16 of 18 files at r1.
Review status: 16 of 18 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/app/externs/backendapi.js, line 362 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/772#-KJ-LoSwSIIHgJDCbccp:-KJ-LoSwSIIHgJDCbccq:1573941767) ([raw file](https://github.com/kubernetes/dashboard/blob/5cce412c2bc6bfd59fa9d4646b9ce71c04cca70c/src/app/externs/backendapi.js#L362)):*
> ```JavaScript
> 
> /**
>  * @typedef {{}}
> ```

Finish this? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/772#-:-KJ-MY_H5GntshJzGS1Q:806159633)*

**Comment by maciaszczykm** [comment]
@bryk Could you take a look on CI? I'm not sure why it hangs after backend tests...

**Comment by bryk** [comment]
@maciaszczykm You have to update backend tests the same way you updated the number of reads in the channels code. I know, this solution is really not intuitive. We should fix it after 1.1 release...

**Comment by bryk** [comment]
Reviewed 27 of 30 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/772)*

**Comment by maciaszczykm** [comment]
Added tests. PTAL

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> @maciaszczykm You have to update backend tests the same way you updated the number of reads in the channels code. I know, this solution is really not intuitive. We should fix it after 1.1 release...
</details>


---

Review status: 38 of 50 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/772#-:-KJ6FKFSlhl9dwy27Jgz:1464873373)*

**Comment by bryk** [comment]
:lgtm: :) 

<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> Added tests. PTAL
</details>


---

Reviewed 12 of 12 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/772#-:-KJ9We3-i6QHUV4fjmEl:298887426)*

**Pull request merged**
