### PR TITLE
Localization of Deploy, EnvVariables and Upload

### PR DESCRIPTION
**Pull request by taimir**
Localization of the base deploy page, the environment variables section
and the deployment file upload section.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/777)

### CODE REVIEW

**Comment by taimir** [comment]
@maciaszczykm @floreks can one of you guys review this?

**Comment by bryk** [comment]
Ping?

**Comment by floreks** [comment]
I'll check it.

**Comment by floreks** [comment]
Is it supposed to work on `serve` or only on `serve:prod`? I'm not up to date here.

Overall :lgtm:

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> I'll check it.
</details>


---

Reviewed 4 of 8 files at r1, 2 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[i18n/messages-en.xtb, line 70 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/777#-KJ9sjh3yo9DbqnlbE9n:-KJ9sjh3yo9DbqnlbE9o:-2033843323) ([raw file](https://github.com/kubernetes/dashboard/blob/cdd47681767309c7f9f30459cef0d220d0759bd8/i18n/messages-en.xtb#L70)):*
> ```
> 	<translation id="7560440547757208994" key="MSG_DEPLOY_SETTINGS_ENV_VARIABLES_USER_HELP" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="User help for the &quot;Environment variables&quot; section on the deploy from settings page.">Environment variables available for use in the container. Values can reference other variables using $(VAR_NAME) syntax.</translation>
> 	<translation id="7026295428726247109" key="MSG_DEPLOY_SETTINGS_NUMBER_OF_PODS_INT_WARNING" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Appears to tell the user that the number of pods on the deploy from settings page must be non-negative or integer.">Number of pods must be a positive integer</translation>
> 	<translation id="750172492346654392" key="MSG_DEPLOY_PAGE_TITLE" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Title text which appears on top of the deploy page.">Deploy a Containerized App</translation>
> ```

Just wondering if we could get rid of `source` key here? Path is not valid for anyone else and still i18n works for me, so unless it is transformed on the fly then I think it is no used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/777#-:-KJ9tK7WL7WJ2B2xofhp:-1483686429)*

**Comment by taimir** [comment]
Right, so in `serve` you should only see the default text that is in the code where the messages are defined.
In `serve:prod` the text should change based on the locale, given that there is a translation in the .xtb bundles. Right now there are no translations yet ( so the Japanese content is the same as English).  But if you want to test it out, you can manually edit some text in `i18n/messages-ja.xtb` and see that it changes to it in `serve:prod` when you change your locale to `ja` in the browser.

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Is it supposed to work on `serve` or only on `serve:prod`? I'm not up to date here.
> 
> Overall :lgtm:
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[i18n/messages-en.xtb, line 70 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/777#-KJ9sjh3yo9DbqnlbE9n:-KJ9tn08xDoeblRVSpbi:318737324) ([raw file](https://github.com/kubernetes/dashboard/blob/cdd47681767309c7f9f30459cef0d220d0759bd8/i18n/messages-en.xtb#L70)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Just wondering if we could get rid of `source` key here? Path is not valid for anyone else and still i18n works for me, so unless it is transformed on the fly then I think it is no used.
</details>
You are reading my thoughts just now :D I noticed this detail a minute ago. That's correct, the source does not matter at all. But it might cause trouble eventually, so it would be best to resolve this.

I'll have to investigate this in another pull request.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/777#-:-KJ9uPY1OISn0vW9rdZi:-425035684)*

**Comment by floreks** [comment]
That's exactly how I've tested it :) Quick Locale Switcher + Chrome and messing around with translations.

<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> Right, so in `serve` you should only see the default text that is in the code where the messages are defined.
> In `serve:prod` the text should change based on the locale, given that there is a translation in the .xtb bundles. Right now there are no translations yet ( so the Japanese content is the same as English).  But if you want to test it out, you can manually edit some text in `i18n/messages-ja.xtb` and see that it changes to it in `serve:prod` when you change your locale to `ja` in the browser.
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[i18n/messages-en.xtb, line 70 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/777#-KJ9sjh3yo9DbqnlbE9n:-KJ9zNPfIrN-okFpv1IR:-1994926329) ([raw file](https://github.com/kubernetes/dashboard/blob/cdd47681767309c7f9f30459cef0d220d0759bd8/i18n/messages-en.xtb#L70)):*
<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> You are reading my thoughts just now :D I noticed this detail a minute ago. That's correct, the source does not matter at all. But it might cause trouble eventually, so it would be best to resolve this.
> 
> I'll have to investigate this in another pull request.
</details>
Perfect :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/777#-:-KJ9zR85giX3ohEiKkWH:2076165445)*

**Pull request merged**
