### PR TITLE
Add node resource frontend

### LINKED ISSUE #821: Node list / details pages

### PR DESCRIPTION
**Pull request by maciaszczykm**
Added node frontend. Closes #821.

Added more `TODO` comments in the code, which will be resolved later, because I'm trying to avoid one big commit.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/891)

### CODE REVIEW

**Comment by bryk** [comment]
Reviewed 17 of 19 files at r1.
Review status: 17 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/backend/resource/node/nodelist.go, line 40 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/891#-KK92Fvj2bJy5wFz3sWL:-KK92Fvj2bJy5wFz3sWM:-26157364) ([raw file](https://github.com/kubernetes/dashboard/blob/d47a7b2b116f9f40c3efaf7fab764c000bb82d95/src/app/backend/resource/node/nodelist.go#L40)):*
> ```Go
> 
> 	// Container images of the node.
> 	ContainerImages []string `json:"containerImages"`
> ```

Hmm... Why this? 

---

*[src/app/frontend/nodedetail/nodeinfo.html, line 34 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/891#-KK91cxA95-n3MgVejiB:-KK91cxA95-n3MgVejiC:-2109054000) ([raw file](https://github.com/kubernetes/dashboard/blob/4930bb4f340c6247990b496a303ffbc9cc379752/src/app/frontend/nodedetail/nodeinfo.html#L34)):*
> ```HTML
>     </kd-info-card-entry>
>     <kd-info-card-entry title="{{::$ctrl.i18n.MSG_NODE_DETAIL_CAPACITY_LABEL}}" >
>       {{$ctrl.node.cpuCapacity}} cores, {{$ctrl.node.memoryCapacity / (1024*1024) | number : 0}} MiB
> ```

We have kdMemoryFormatter for this

---

*[src/app/frontend/nodelist/nodecard_component.js, line 52 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/891#-KK91z7k1yTlwI5GLxwt:-KK91z7k1yTlwI5GLxwu:1290465195) ([raw file](https://github.com/kubernetes/dashboard/blob/4930bb4f340c6247990b496a303ffbc9cc379752/src/app/frontend/nodelist/nodecard_component.js#L52)):*
> ```JavaScript
>   getNodeDetailHref() {
>     // TODO(maciaszczykm): 2 state params cause 2 slashes in link. I.E. #/node//127.0.0.1.
>     return this.state_.href(stateName, new StateParams(null, this.node.objectMeta.name));
> ```

Can you maybe create a new state params class that has no namespace? E.g., GlobalResourceStateParams. This will fix the problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/891)*

**Comment by maciaszczykm** [comment]
Sample views:

image

image

**Comment by maciaszczykm** [comment]
Tests still need adjustments.

---

Review status: 12 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/backend/resource/node/nodelist.go, line 40 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/891#-KK92Fvj2bJy5wFz3sWL:-KKD7LDexcZwqurUS19w:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/d47a7b2b116f9f40c3efaf7fab764c000bb82d95/src/app/backend/resource/node/nodelist.go#L40)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Hmm... Why this? 
</details>
Done.

---

*[src/app/frontend/nodedetail/nodeinfo.html, line 34 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/891#-KK91cxA95-n3MgVejiB:-KKD7LsrvyUNjFiHrPC0:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/4930bb4f340c6247990b496a303ffbc9cc379752/src/app/frontend/nodedetail/nodeinfo.html#L34)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> We have kdMemoryFormatter for this
</details>
Done.

---

*[src/app/frontend/nodelist/nodecard_component.js, line 52 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/891#-KK91z7k1yTlwI5GLxwt:-KKD7MfTtphMbb-zLlK_:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/4930bb4f340c6247990b496a303ffbc9cc379752/src/app/frontend/nodelist/nodecard_component.js#L52)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Can you maybe create a new state params class that has no namespace? E.g., GlobalResourceStateParams. This will fix the problem.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/891#-:-KKD7D53QHq3MQtLnx9K:1033680662)*

**Comment by maciaszczykm** [comment]
PTAL

**Comment by floreks** [comment]
Reviewed 1 of 6 files at r3, 3 of 7 files at r4, 5 of 7 files at r5.
Review status: 20 of 26 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/frontend/common/resource/globalresourcedetail.js, line 20 \[r5\]](https://reviewable.io:443/reviews/kubernetes/dashboard/891#-KKDuiBgwg3NkkCNziaw:-KKDuiBgwg3NkkCNziax:1289682581) ([raw file](https://github.com/kubernetes/dashboard/blob/9570da901183954a13185092ff591962f03025f9/src/app/frontend/common/resource/globalresourcedetail.js#L20)):*
> ```JavaScript
>  * All properties are @exported and in sync with URL param names.
>  */
> export class GlobalStateParams {
> ```

We could use this class and extend already existing `resourcedatail.StateParams` similar to what's done for logs view `StateParams`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/891)*

**Comment by maciaszczykm** [comment]
PTAL

---

Review status: 20 of 27 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/frontend/common/resource/globalresourcedetail.js, line 20 \[r5\]](https://reviewable.io:443/reviews/kubernetes/dashboard/891#-KKDuiBgwg3NkkCNziaw:-KKDx1yGLcXjuax1ZxVi:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/9570da901183954a13185092ff591962f03025f9/src/app/frontend/common/resource/globalresourcedetail.js#L20)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> We could use this class and extend already existing `resourcedatail.StateParams` similar to what's done for logs view `StateParams`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/891#-:-KKDx3GMXqw5O3bEnBvT:676965300)*

**Comment by floreks** [comment]
:lgtm:

---

Reviewed 1 of 7 files at r4, 1 of 1 files at r6.
Review status: 22 of 27 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/891#-:-KKDxTa8VpUBqMFUcuDB:1417088721)*

**Comment by bryk** [comment]
Just asking, didn't check: is a list of nodes in the workloads page?

**Comment by marians** [comment]
How can the list of nodes be accessed? From the Workloads page I can't find it.

**Comment by maciaszczykm** [comment]
@bryk @marians At the moment list of nodes can be accessed only via `#/node` adress. There is no link to this page yet.

Further updates are in my plans so if you want to see them on workloads page then please let me know.

**Comment by bryk** [comment]
> Further updates are in my plans so if you want to see them on workloads page then please let me know.

Nodes don't belong to workloads page. We need menu for them. For 1.1 release this will not come in. But we can do another release, like, two weeks after and include menu and nodes for it :) What do you think?

**Comment by maciaszczykm** [comment]
@bryk Yes, I'm aware of categorization in menu :) If I'd add nodes to workloads it'd be only temporary. I agree that we can skip that and wait for menu.

**Pull request merged**
