### PR TITLE
Adding unit tests for login component (#3865)

### PR DESCRIPTION
**Pull request by toddbaert**
I've added some fairly comprehensive unit tests for the login component... I figured that was a good place to start.

### CODE REVIEW

**Comment by toddbaert** [comment]
I signed it

**Comment by toddbaert** [comment]
I signed it

**Comment by toddbaert** [comment]
Looks like something went wrong with the cypress tests (timeout)... I only added a unit test (no cypress tests and no changes to prod code) so I think we have a race-condition with our e2e suite. I just pushed a comment change to trigger a new e2e suite...

**Comment by eloyekunle** [comment]
@toddbaert Do you have the link to the last failed test?

**Comment by toddbaert** [comment]
> @toddbaert Do you have the link to the last failed test?

After my reset push to trigger rebuild I can't seem to find the failed build.

**Comment by floreks** [comment]
Code looks good. This is a good start. Thanks!

/lgtm

**Pull request merged**
