### PR TITLE
[zh-Hans] translate some place

### LINKED ISSUE #6618: [zh-Hans] translate some place in src/app/frontend/common/components/container/template.html
Hello, some places in src/app/frontend/common/components/container/template.html are not translated, I would like to translate them.
As below:
截图_选择区域_20211108164913

/language zh

### PR DESCRIPTION
**Pull request by qlijin**
fix #6618

### CODE REVIEW

**Review by helight — APPROVED** [review]
LGTM

**Comment by qlijin** [comment]
Thank @helight and @maciaszczykm !

**Pull request merged**
