### PR TITLE
metricsScraper use logrus instead of klog

### PR DESCRIPTION
**Pull request by pierluigilenoci**
Ref: https://github.com/sirupsen/logrus

https://github.com/kubernetes-sigs/dashboard-metrics-scraper/blob/master/server.go#L9

### CODE REVIEW

**Comment by pierluigilenoci** [comment]
@desaintmartin I didn't do a chart bump because I only changed a comment inside a YAML file, there is no actual difference in functionality. It seemed to me that it didn't make sense. But now the test fails. 😢 

How do we solve?

**Comment by floreks** [comment]
From what I see metrics scraper uses glog
https://github.com/kubernetes/dashboard/blob/f06f78d395e0ff331afdda6f895144ae4327133f/go.mod#L8

and glog uses a `--v=N` where N is a number related to the log level.

**Comment by floreks** [comment]
Any change in any chart file requires a version bump of the chart. It is a strict requirement.

**Comment by pierluigilenoci** [comment]
@floreks bump done.

**Comment by floreks** [comment]
Could you please change the last commit message to simple `helm chart version bump`? :slightly_smiling_face:

**Comment by pierluigilenoci** [comment]
@floreks done 😆

**Comment by pierluigilenoci** [comment]
@desaintmartin @maciaszczykm could you please `lgtm` me?

**Review by floreks — APPROVED** [review]
/lgtm

**Pull request merged**
