### PR TITLE
Materialized resource card framework

### PR DESCRIPTION
**Pull request by bryk**
* Now resource cards are in a list and have columns
* Columns are sized according to spec
* Tell me whether something needs more documentation

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/656)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you review?

**Comment by bryk** [comment]
Sample screenshot done using this framework: 

selection_063

**Comment by floreks** [comment]
Of course. It might take some time though :)

**Comment by bryk** [comment]
Yeah, this PR got large, sorry for this. It was tough to split it further, though. It is only the framework here.

**Comment by floreks** [comment]
Looks great. I've tried it and it's easy to use. Also it scales nicely.  You've used some angular magic with components and controller binding that are new for me and I like them a lot.

Just some minor cosmetic comments and :lgtm_strong: 

---

Reviewed 18 of 22 files at r1.
Review status: 18 of 22 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/app/frontend/common/components/resourcecard/resourcecardcolumn_component.js, line 26 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/656#-KFOigyyeoIVn2huKTB-:-KFOigyyeoIVn2huKTB0:771212085) ([raw file](https://github.com/kubernetes/dashboard/blob/28666f7f03d7bf06d8c2694608ae47361d25ec1a/src/app/frontend/common/components/resourcecard/resourcecardcolumn_component.js#L26)):*
Typos in `called` in components.

---

*[src/app/frontend/common/components/resourcecard/resourcecardcolumn_component.js, line 29 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/656#-KFOmtXya_VZjrUItFIH:-KFOmtXya_VZjrUItFII:-2040909570) ([raw file](https://github.com/kubernetes/dashboard/blob/28666f7f03d7bf06d8c2694608ae47361d25ec1a/src/app/frontend/common/components/resourcecard/resourcecardcolumn_component.js#L29)):*
This is something new. Nice.

---

*[src/app/frontend/common/components/resourcecard/resourcecardcolumns_component.js, line 25 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/656#-KFOiZOQuKlLc1c5z3Rz:-KFOiZOQuKlLc1c5z3S-:-963168660) ([raw file](https://github.com/kubernetes/dashboard/blob/28666f7f03d7bf06d8c2694608ae47361d25ec1a/src/app/frontend/common/components/resourcecard/resourcecardcolumns_component.js#L25)):*
Shouldn't it be `... addAndSizeColumn is called`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/656#-:-KFOnMTgSI7dEPMOPFbs:-1723505328)*

**Comment by floreks** [comment]
@maciaszczykm you can also take a look.

**Comment by floreks** [comment]
I think `gulp check` failed.

**Comment by bryk** [comment]
`gulp check` fixed

**Comment by bryk** [comment]
Thanks for review, will merge soon. 

---

Review status: 17 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/common/components/resourcecard/resourcecardcolumn_component.js, line 26 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/656#-KFOigyyeoIVn2huKTB-:-KFc_tTN-h7PBfWlnHO3:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/28666f7f03d7bf06d8c2694608ae47361d25ec1a/src/app/frontend/common/components/resourcecard/resourcecardcolumn_component.js#L26)):*
Done.

---

*[src/app/frontend/common/components/resourcecard/resourcecardcolumn_component.js, line 29 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/656#-KFOmtXya_VZjrUItFIH:-KFc_uAsNrwbWku_vWoA:5172980) ([raw file](https://github.com/kubernetes/dashboard/blob/28666f7f03d7bf06d8c2694608ae47361d25ec1a/src/app/frontend/common/components/resourcecard/resourcecardcolumn_component.js#L29)):*
:)

---

*[src/app/frontend/common/components/resourcecard/resourcecardcolumns_component.js, line 25 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/656#-KFOiZOQuKlLc1c5z3Rz:-KFckTBfpqdkV3tZXZ-j:-1773978095) ([raw file](https://github.com/kubernetes/dashboard/blob/28666f7f03d7bf06d8c2694608ae47361d25ec1a/src/app/frontend/common/components/resourcecard/resourcecardcolumns_component.js#L25)):*
No, it is $onInit always. I've added this method and perform state checks now. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/656#-:-KFckvfeiW5b1UPlXP0x:1874355278)*

**Comment by bryk** [comment]
Reviewed 17 of 22 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/656)*

**Pull request merged**
