### PR TITLE
Add support for multiarch docker build and deploy

### PR DESCRIPTION
**Pull request by floreks**
- Some cleanup work for the makefiles. Still, there are some leftovers that should be migrated/checked if they are needed.
- Added 2 new global make targets `make deploy` and `make deploy-dev` that will build binaries for all supported architectures and then build and push containers to configured container registries. We should now be able to easily deploy to multiple registries if needed.
- Updated `cross-build` to actually produce `os/arch` directories in the dist directory.
- Fixed an issue with the angular build since the `outputPath` argument was replaced by the `output-path` and the build was failing.

Tested all important targets: `make build`, `make build-cross`, `make run`, `make serve`, `make deploy-dev`.

## Supported architectures
We are cross-building go binaries and using `docker buildx` to build and push the images for the listed architectures.

Here are our test dev images: [dashboard-api](https://hub.docker.com/repository/registry-1.docker.io/kubernetesdashboarddev/dashboard-api/tags?page=1&ordering=last_updated), [dashboard-web](https://hub.docker.com/repository/registry-1.docker.io/kubernetesdashboarddev/dashboard-web/tags?page=1&ordering=last_updated)

**Note:** Do not try to run them manually as they need some kind of gateway that will "connect" them properly. For the local prod run we are using `nginx`. Our deployment files will be updated soon to support new architecture.
| OS     | ARCH    |
|--------|---------|
| darwin | amd64   |
| darwin | arm64   |
| linux  | amd64   |
| linux  | arm64   |
| linux  | arm     |
| linux  | ppc64le |
| linux  | s390x   |

### CODE REVIEW

**Comment by goafabric** [comment]
@floreks 
after once in while i created this issue: https://github.com/kubernetes/dashboard/issues/6597
which fixed the dashboard .. metrics scrapper and server are still amd64 on apple silicon until dashboard 2.7.0 and its adherent helm charts

does this mean that this merge request will resolve this ?
and when and in which version will it be available ?

thank you

**Comment by floreks** [comment]
@goafabric the metrics scraper has its' own repository but we can also manage it so I will definitely try to update the build system there to provide native images. Unfortunately, when it comes to the `metrics-server` it is out of our control. It is handled by other kubernetes sig and you would have to ask them to provide support. We are only using it as a general metrics provider.

**Comment by goafabric** [comment]
@floreks ok thank you

**Pull request merged**
