### PR TITLE
Limit ranges backend implementation

### PR DESCRIPTION
**Pull request by batikanu**

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Could you also run gofmt on all backend code? It has dropped recently https://goreportcard.com/report/github.com/kubernetes/dashboard.

**Comment by batikanu** [comment]
@maciaszczykm  I have formatted the whole backend code with a separated pull request #1282 to make this one easier to review. If you merge it first I will rebase my pull requests.

**Comment by maciaszczykm** [comment]
Remember to update this and other PR and format files before commiting :)

**Comment by maciaszczykm** [comment]
@batikanu Done, ping when ready for review.

**Comment by batikanu** [comment]
@maciaszczykm done

**Pull request merged**
