### PR TITLE
Fix: update the CREATE button action to create a deployment

### PR DESCRIPTION
**Pull request by Sn0rt**
Hi,  @maciaszczykm  @bryk , the #1330 was fixed, please review, thanks.

### CODE REVIEW

**Comment by Sn0rt** [comment]
I am update test.

**Comment by Sn0rt** [comment]
@bryk ok, doing..

**Comment by bryk** [comment]
@Sn0rt Comment "PTAL" when this is ready for another round of reviews :)

**Comment by Sn0rt** [comment]
PTAL

**Comment by bryk** [comment]
LGTM :) This is super important PR, thanks for it! 

Do you need any assistance with future contributions? If yes, let us know. We're more than happy to help.

**Pull request merged**
