### PR TITLE
Add container image validation

### PR DESCRIPTION
**Pull request by f-higashi**
Added container image validation. #422 

Image reference format is very complicated. I think it is hard to write and maintain it.
So I used docker library in backend. 

What do you think? 

@bryk 

BTW 
How do I update Godep.json?
When I executed 'godep save ./src/app/backend', all dependencies are removed.

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/474)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm You've recently updated Godeps. Can you help @f-higashi with this?

**Comment by maciaszczykm** [comment]
@bryk @f-higashi I can do it on Monday, because till end of the week I'm on sick leave.

**Comment by bryk** [comment]
@f-higashi 

Try:
* 'godep restore ./src/app/backend'
* Then `go get ...` deps that you want to update
* 'godep save ./src/app/backend'

**Comment by f-higashi** [comment]
Thanks for information.
Sorry. My repository path and GOPATH was wrong.

**Comment by f-higashi** [comment]
Hmm.
Travis build does not start.
In my repository travis build works.

@bryk  
Do you have an idea?
or
Can you cancel the following build? This build process task is broken? 
- https://travis-ci.org/kubernetes/dashboard/builds/113315560

**Comment by bryk** [comment]
I've cancelled the build.

**Comment by bryk** [comment]
Let me know when this is ready for review.

**Comment by f-higashi** [comment]
Thank you to cancel jobs.
But travis build does not start too.
Hmm..

**Comment by bryk** [comment]
Hmm.... I dont know. Maybe drop this PR and create a new one?

**Comment by f-higashi** [comment]
Yes.
It's better.
Please cancel existing build job.

**Comment by f-higashi** [comment]
After closing this pull request, the build started...
It's strange.
I open this.

**Comment by f-higashi** [comment]
After reopen, new build is registered and stopped.
I'll create new pull request.

**Pull request closed without merging**
