### PR TITLE
Bump typescript-eslint/eslint-plugin from 5.61.0 to 6.1.0

### PR DESCRIPTION
**Pull request by shu-mutou**
Also, fixed duplicated enum member error.

### CODE REVIEW

**Comment by shu-mutou** [comment]
Rebased and recreated yarn.lock

**Comment by shu-mutou** [comment]
@floreks @maciaszczykm PTAL, Thanks!

**Comment by shu-mutou** [comment]
/retitle Bump typescript-eslint/eslint-plugin from 5.61.0 to 6.1.0

**Comment by maciaszczykm** [comment]
@shu-mutou Can you solve conflicts?

**Comment by shu-mutou** [comment]
@maciaszczykm PTAL, thanks!!

**Pull request merged**
