### PR TITLE
Support CRD v1 and v1beta1

### LINKED ISSUE #4530: Cannot fetch api/v1/settings/pinner - breaks listing elements
```
Installation method: cli kubectl
Kubernetes version: v1.15.3
Dashboard version: v2.0.0-beta5+0.g93474e5
Operating system: Ubuntu 18.04.2 LTS
Node.js version ('node --version' output): n/a
Go version ('go version' output): n/a
```

##### Steps to reproduce
1. Use incognito mode to force fresh session opening
2. Login with the config
3. Go to Custom Resources Definition
4. Go to overview

##### Observed result
Missing items in the lists

##### Expected result
Lists containing all the items

##### Comments
After first login, there's query /api/v1/settings/pinner with 401 response, which triggers script exception:

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at t.isPinned (main.d9fca64efc90054cfeab.js:1)
    at t.isPinned (main.d9fca64efc90054cfeab.js:1)
    at Object.updateDirectives (main.d9fca64efc90054cfeab.js:1)
    at Object.updateDirectives (main.d9fca64efc90054cfeab.js:1)
    at Eb (main.d9fca64efc90054cfeab.js:1)
    at Pb (main.d9fca64efc90054cfeab.js:1)
    at Ib (main.d9fca64efc90054cfeab.js:1)
    at Eb (main.d9fca64efc90054cfeab.js:1)
    at Pb (main.d9fca64efc90054cfeab.js:1)
    at Rb (main.d9fca64efc90054cfeab.js:1)
```
After refreshing website everything comes back to normal.

Screenshot_20191112_145847

### PR DESCRIPTION
**Pull request by floreks**
Additionally fixes #4530

### CODE REVIEW

**Comment by zehuaiWANG** [comment]
Hi ~ frorek, I wonder if there will be such a problem. We use kubeconfig to create clients. The permissions of clients should be the same as those of admin. In that way, can we still get a CRD through `client. Apixtensionsv1(). Customresourcedefinitions(). Get (name, metav1. Getoptions {})`? If you do not modify the permissions of admin, there should be no CRD in his yaml.

**Comment by floreks** [comment]
If both `v1` and `v1beta1` for extensions API are enabled, first one is taken. Users should have access to both, not only one of them. The issue here was that up to K8S `v1.15.X` extensions API has only `v1beta1` and in `v1.16` it graduated to `v1` and `v1beta1` was deprecated. In most cases, there should be only 1 API version enabled at a time.

**Comment by zehuaiWANG** [comment]
OK, it looks good. Thank you.

**Pull request merged**
