### PR TITLE
Disable `go mod` once in travis

### PR DESCRIPTION
**Pull request by shu-mutou**
We need to investigate to use `go mod` in travis.
For now, change `GO111MODULE` to off in travis.

### CODE REVIEW

**Comment by shu-mutou** [comment]
`npm ci` seems to update go.mod file to use latest. Also, prometheus/client-golang was bumped latest to 1.0.0 few days ago, then prometheus.Handler() removed.

**Comment by maciaszczykm** [comment]
Hmm, @eloyekunle can you help us there?

**Comment by shu-mutou** [comment]
I updated this PR as disabling `go mod` in travis.
Also, I posted Issue #3936. @eloyekunle Could you investigate this issue?

**Comment by maciaszczykm** [comment]
cc @floreks AFAIK you enabled Go modules. We need them, arent we?

**Comment by shu-mutou** [comment]
Basically, I agree with using `go mod`, but we need to investigate it more.  😉

**Comment by eloyekunle** [comment]
I will look into it.

**Comment by eloyekunle** [comment]
`go get` for `golangci-lint` in the `postinstall` script was updating some packages. In #3934, we download `golangci-lint` via `curl` instead.

**Comment by shu-mutou** [comment]
@eloyekunle Thank you for your help! I understand we should not use `go get` to install tools.

**Pull request closed without merging**
