### PR TITLE
update zh i18n

### PR DESCRIPTION
**Pull request by hwdef**
Ref: https://github.com/kubernetes/dashboard/issues/4259

Ref: https://github.com/kubernetes/dashboard/issues/4705

### CODE REVIEW

**Comment by hwdef** [comment]
/assign
@shu-mutou 
@maciaszczykm

**Comment by tanjunchen** [comment]
/lgtm /hold
@shu-mutou  @maciaszczykm

**Comment by tanjunchen** [comment]
/lgtm
@shu-mutou
@maciaszczykm

**Comment by shu-mutou** [comment]
Could you resolve inconsistency between navigation items[1] and titles[2] in each view?
[1] https://github.com/kubernetes/dashboard/blob/255025ad4a7ee0468049d7dc479e6c75c5e78fcf/i18n/zh/messages.zh.xlf#L2368-L2611
[2] https://github.com/kubernetes/dashboard/blob/255025ad4a7ee0468049d7dc479e6c75c5e78fcf/i18n/zh/messages.zh.xlf#L342-L459
At least, please decide to translate or not in navigation items[1].
Also, "设置" for Daemon Sets does not seem correct. This may be "组", "集" or "集合".

**Comment by shu-mutou** [comment]
Also Replica Sets and Stateful Sets. Especially followings:
https://github.com/kubernetes/dashboard/blob/255025ad4a7ee0468049d7dc479e6c75c5e78fcf/i18n/zh/messages.zh.xlf#L2498-L2500
https://github.com/kubernetes/dashboard/blob/255025ad4a7ee0468049d7dc479e6c75c5e78fcf/i18n/zh/messages.zh.xlf#L438-L439

**Comment by hwdef** [comment]
@shu-mutou 
Thanks for your suggestions. I will fix it in this PR,
There may be other translations that need improvement ,and English needs to be translated into Chinese. I will create a new PR to improve them.

**Comment by hwdef** [comment]
@shu-mutou 
I updated this PR, and I improved it by following the word list in the #4705 . 
Please review it again. THX

**Comment by shu-mutou** [comment]
/lgtm
We don't have conclusions for translation of k8s terms, and we can improve that in future.
But I hope final approvement by @tanjunchen.

**Comment by tanjunchen** [comment]
Sure , we will improve this if everybody has a better idea . so now 
/lgtm
/hold cancel

**Pull request merged**
