### PR TITLE
Deployment details frontend

### PR DESCRIPTION
**Pull request by Draiken**
Initial implementation of the deployment details frontend
Part of #595 

Based off #750

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/759)

### CODE REVIEW

**Comment by bryk** [comment]
Looks nice. A few comments. 

<details><summary><i>Previously, Draiken (Luiz Felipe G. Pereira) wrote…</i></summary>
> #### Deployment details frontend
> 
> Initial implementation of the deployment details frontend
> 
> Part of #595 
> 
> 
> 
> Based off #750
> 
> 
> 
</details>


---

Reviewed 3 of 14 files at r1.
Review status: 3 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/deploymentdetail/deploymentdetail_controller.js, line 9 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/759#-KIRhNH3ljVIg4Ko5rF9:-KIRhNH3ljVIg4Ko5rFA:1071370284) ([raw file](https://github.com/kubernetes/dashboard/blob/2b79081e7c6accc729b1c32c8364d3278c4b468b/src/app/frontend/deploymentdetail/deploymentdetail_controller.js#L9)):*
> ```JavaScript
>    * @param {!backendApi.DeploymentDetail} deploymentDetail
>    */
>   constructor(deploymentDetail) {
> ```

You need `@ngInject` annotation here. Look for other code for how it is done. 

---

*[src/app/frontend/deploymentdetail/deploymentinfo_component.js, line 17 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/759#-KIRhhJ4VYws214UtVL1:-KIRhhJ4VYws214UtVL2:-494447772) ([raw file](https://github.com/kubernetes/dashboard/blob/2b79081e7c6accc729b1c32c8364d3278c4b468b/src/app/frontend/deploymentdetail/deploymentinfo_component.js#L17)):*
> ```JavaScript
> 
>   /**
>    * @return {boolean}
> ```

Please document what this does :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/759#-:-KIRi4SJ5cA9yW5PemvR:1401994573)*

**Comment by bryk** [comment]
Review status: 3 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/frontend/deploymentdetail/deploymentdetail_stateconfig.js, line 55 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/759#-KIRlgbkzRtfRJRHr3BM:-KIRlgbl3RtfxZH2cKle:-1207186187) ([raw file](https://github.com/kubernetes/dashboard/blob/2b79081e7c6accc729b1c32c8364d3278c4b468b/src/app/frontend/deploymentdetail/deploymentdetail_stateconfig.js#L55)):*
> ```JavaScript
>  * @param {!angular.$resource} $resource
>  * @return {!angular.Resource<!backendApi.DeploymentDetail>}
>  */
> ```

Missing `@ngInject` here.

---

*[src/app/frontend/deploymentdetail/deploymentdetail_stateconfig.js, line 63 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/759#-KIRlk4gz-d_l62CdgL0:-KIRlk4gz-d_l62CdgL1:-1207186187) ([raw file](https://github.com/kubernetes/dashboard/blob/2b79081e7c6accc729b1c32c8364d3278c4b468b/src/app/frontend/deploymentdetail/deploymentdetail_stateconfig.js#L63)):*
> ```JavaScript
>  * @param {!angular.Resource<!backendApi.DeploymentDetail>} deploymentDetailResource
>  * @return {!angular.$q.Promise}
>  */
> ```

Missing `@ngInject` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/759)*

**Comment by bryk** [comment]
Review status: 3 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/deploymentdetail/deploymentdetail_stateconfig.js, line 16 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/759#-KIRmFtNrYJ7GMSkE1yT:-KIRmFtO8Mfm1l58biJl:1726513033) ([raw file](https://github.com/kubernetes/dashboard/blob/2b79081e7c6accc729b1c32c8364d3278c4b468b/src/app/frontend/deploymentdetail/deploymentdetail_stateconfig.js#L16)):*
> ```JavaScript
> 
> import {actionbarViewName} from 'chrome/chrome_state';
> import {breadcrumbsConfig} from 'common/components/breadcrumbs/breadcrumbs_component';
> ```

Please rebase and import from breadcrumbs_service 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/759)*

**Comment by Draiken** [comment]
Review status: 3 of 14 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/deploymentdetail/deploymentdetail_stateconfig.js, line 16 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/759#-KIRmFtNrYJ7GMSkE1yT:-KIUjsu0-7Wt-fHra122:-1137442911) ([raw file](https://github.com/kubernetes/dashboard/blob/2b79081e7c6accc729b1c32c8364d3278c4b468b/src/app/frontend/deploymentdetail/deploymentdetail_stateconfig.js#L16)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Please rebase and import from breadcrumbs_service 
</details>
Okay... Wasn't sure about rebasing/force pushing. Not sure how Reviewable deals with this stuff

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/759)*

**Comment by Draiken** [comment]
Review status: 2 of 16 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/deploymentdetail/deploymentdetail_controller.js, line 9 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/759#-KIRhNH3ljVIg4Ko5rF9:-KIUteZ7DJzZzamwdh_d:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/2b79081e7c6accc729b1c32c8364d3278c4b468b/src/app/frontend/deploymentdetail/deploymentdetail_controller.js#L9)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> You need `@ngInject` annotation here. Look for other code for how it is done. 
</details>
Done.

---

*[src/app/frontend/deploymentdetail/deploymentdetail_stateconfig.js, line 16 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/759#-KIRmFtNrYJ7GMSkE1yT:-KIUth_91VjK_ai3c_1J:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/2b79081e7c6accc729b1c32c8364d3278c4b468b/src/app/frontend/deploymentdetail/deploymentdetail_stateconfig.js#L16)):*
<details><summary><i>Previously, Draiken (Luiz Felipe G. Pereira) wrote…</i></summary>
> Okay... Wasn't sure about rebasing/force pushing. Not sure how Reviewable deals with this stuff
</details>
Done.

---

*[src/app/frontend/deploymentdetail/deploymentdetail_stateconfig.js, line 55 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/759#-KIRlgbkzRtfRJRHr3BM:-KIUtiAlLJuedL-qOifR:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/2b79081e7c6accc729b1c32c8364d3278c4b468b/src/app/frontend/deploymentdetail/deploymentdetail_stateconfig.js#L55)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Missing `@ngInject` here.
</details>
Done.

---

*[src/app/frontend/deploymentdetail/deploymentdetail_stateconfig.js, line 63 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/759#-KIRlk4gz-d_l62CdgL0:-KIUtiqIS-h_TVTPB_lL:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/2b79081e7c6accc729b1c32c8364d3278c4b468b/src/app/frontend/deploymentdetail/deploymentdetail_stateconfig.js#L63)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Missing `@ngInject` here.
</details>
Done.

---

*[src/app/frontend/deploymentdetail/deploymentinfo_component.js, line 17 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/759#-KIRhhJ4VYws214UtVL1:-KIUtjmq9XyAtVrps0-S:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/2b79081e7c6accc729b1c32c8364d3278c4b468b/src/app/frontend/deploymentdetail/deploymentinfo_component.js#L17)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Please document what this does :) 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/759)*

**Comment by bryk** [comment]
:lgtm: Thank you a lot! Will merge soon.

<details><summary><i>Previously, codecov-io wrote…</i></summary>
> ## [Current coverage][cc-pull] is **95.14%**
> > Merging [#759][cc-pull] into [master][cc-base-branch] will increase coverage by **0.34%**
> 
> 1. File `...ereader_directive.js` (not in diff) was modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/5f3d0bbe696c158e8d3df7d538480bbe6028ebcb/changes?src=pr#7372632F6170702F66726F6E74656E642F6465706C6F792F66696C657265616465725F6469726563746976652E6A73) 
>   - Misses `-6` 
>   - Partials `0` 
>   - Hits `+6`
> 
> ```diff
> @@             master       #759   diff @@
> ==========================================
>   Files           175        177     +2   
>   Lines          1361       1378    +17   
>   Methods           0          0          
>   Messages          0          0          
>   Branches          0          0          
> ==========================================
> + Hits           1290       1311    +21   
> + Misses           71         67     -4   
>   Partials          0          0          
> ```
> 
> > Powered by [Codecov](https://codecov.io?src=pr). Last updated by [d19f802...5f3d0bb][cc-compare]
> [cc-base-branch]: https://codecov.io/gh/kubernetes/dashboard/branch/master?src=pr
> [cc-compare]: https://codecov.io/gh/kubernetes/dashboard/compare/d19f80288bac3ca34295ea9a72f89041065531c3...5f3d0bbe696c158e8d3df7d538480bbe6028ebcb
> [cc-pull]: https://codecov.io/gh/kubernetes/dashboard/pull/759?src=pr
</details>


---

Reviewed 6 of 14 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/deploymentdetail/deploymentdetail_stateconfig.js, line 16 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/759#-KIRmFtNrYJ7GMSkE1yT:-KIWRLT39w2p82maT4fd:571060875) ([raw file](https://github.com/kubernetes/dashboard/blob/2b79081e7c6accc729b1c32c8364d3278c4b468b/src/app/frontend/deploymentdetail/deploymentdetail_stateconfig.js#L16)):*
<details><summary><i>Previously, Draiken (Luiz Felipe G. Pereira) wrote…</i></summary>
> Done.
</details>
Force pushing is OKay. Others (and me) do this all the time. Reviewable deals with easily. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/759#-:-KIWRraqtXd5fAkJCsbV:1337410312)*

**Comment by bryk** [comment]
:lgtm:

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> :lgtm: Thank you a lot! Will merge soon.
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/759#-:-KIW_WuYXGKUbEsczx82:1417088721)*

**Pull request merged**
