### PR TITLE
fix health check error handling

### PR DESCRIPTION
**Pull request by cheld**
In rare conditions the command `gulp local-up-cluster` failed. Reasons:

- The health check url was not updated after upgrading to heapster 0.20
- Error handling was buggy and continued most of times.

@zreigz please review

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/575)

### CODE REVIEW

**Comment by cheld** [comment]
Fixes #549

**Comment by cheld** [comment]
BTW: Happy Easter :)

**Comment by zreigz** [comment]
Yes sure, I will check it

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/575#-:-KDgkS90zIN5MTh8G2uf:1949105047)*

**Comment by zreigz** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/575#-:-KDgyD_8arsER7WAzBgQ:1417088721)*

**Comment by zreigz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/575)*

**Comment by bryk** [comment]
Merging.

**Pull request merged**
