### PR TITLE
Left nav menu (almost) spec-compatible

### PR DESCRIPTION
**Pull request by bryk**
* moved namespace select
* made namespace select default to 'default'
* changed "all *user* namespaces" to "all namespaces"
* added selected menu item highlighting

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1145)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm @floreks Are you able to review this?

**Comment by floreks** [comment]
Sure. I'll take a look at this today.

**Comment by floreks** [comment]
Reviewed 11 of 18 files at r1.
Review status: 11 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/chrome/nav/nav.scss, line 51 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1145#-KPwFV0ay79T2gaqi-0I:-KPwFV0bLSS-1DPwp9QY:b-fbx9i9) ([raw file](https://github.com/kubernetes/dashboard/blob/4abb822c79a20054402b4f2c9209bd8dc3d5dd72/src/app/frontend/chrome/nav/nav.scss#L51)):*
> ```SCSS
> .kd-nav-group-divider {
>   border-top: 1px solid $border;
>   height: 1px;
> ```

Is it needed? It looks fine without specifying height.

---

*[src/app/frontend/chrome/nav/navitem.scss, line 42 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1145#-KPwH8TTdNRkPpN3vkIC:-KPwH8TTdNRkPpN3vkID:bd797xc) ([raw file](https://github.com/kubernetes/dashboard/blob/4abb822c79a20054402b4f2c9209bd8dc3d5dd72/src/app/frontend/chrome/nav/navitem.scss#L42)):*
> ```SCSS
>     color: $primary;
> 
>     &:visited {
> ```

Above color settings should be enough. Nothing changes if I delete this part. Still primary color is used.

---

*[src/app/frontend/common/namespace/namespace_module.js, line 47 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1145#-KPwJ5FkfKwCn6gDu2V1:-KPwJ5FlHSg3Iu7_lqKq:b-wouzp7) ([raw file](https://github.com/kubernetes/dashboard/blob/4abb822c79a20054402b4f2c9209bd8dc3d5dd72/src/app/frontend/common/namespace/namespace_module.js#L47)):*
> ```JavaScript
>    */
>   function replaceUrlIfNeeded(namespace) {
>     if (namespace === undefined) {
> ```

If user selects option `All namespaces` then anyway `default` namespace param will be set. Selecting `All namespaces` option does not work and it points to `default` anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1145)*

**Comment by maciaszczykm** [comment]
:lgtm_strong: 




***

Few things still need refactoring, but it's good that not all changes are done at one time. For example top bars need update, especially on details pages (where tabs look strange). 



Namespace selector after opening could be also updated:



---

Reviewed 15 of 18 files at r1.
Review status: 18 of 19 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1145#-:-KPwDjzepRNyHL5_fw9X:bhi7ffo)*

**Comment by bryk** [comment]
> Few things still need refactoring, but it's good that not all changes are done at one time. For example top bars need update, especially on details pages (where tabs look strange). 
 
I have a PR that addresses this. I'll send it just after this one. 

> Namespace selector after opening could be also updated:

Yep. But let's keep it for future work :) 

---

Reviewed 1 of 41 files at r3.
Review status: 12 of 53 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/chrome/nav/nav.scss, line 51 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1145#-KPwFV0ay79T2gaqi-0I:-KPwKd_TmktAtNUaNQ73:b-vh5r1l) ([raw file](https://github.com/kubernetes/dashboard/blob/4abb822c79a20054402b4f2c9209bd8dc3d5dd72/src/app/frontend/chrome/nav/nav.scss#L51)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Is it needed? It looks fine without specifying height.
</details>
Yeah, you're right. Done.

---

*[src/app/frontend/chrome/nav/navitem.scss, line 42 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1145#-KPwH8TTdNRkPpN3vkIC:-KPwKuBY91BVCHak2-vF:b-ggn5mt) ([raw file](https://github.com/kubernetes/dashboard/blob/4abb822c79a20054402b4f2c9209bd8dc3d5dd72/src/app/frontend/chrome/nav/navitem.scss#L42)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Above color settings should be enough. Nothing changes if I delete this part. Still primary color is used.
</details>
Correct. Removed. 

---

*[src/app/frontend/common/namespace/namespace_module.js, line 47 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1145#-KPwJ5FkfKwCn6gDu2V1:-KQ-aBtIaOsr0S-TbcdW:b-jxfjel) ([raw file](https://github.com/kubernetes/dashboard/blob/4abb822c79a20054402b4f2c9209bd8dc3d5dd72/src/app/frontend/common/namespace/namespace_module.js#L47)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> If user selects option `All namespaces` then anyway `default` namespace param will be set. Selecting `All namespaces` option does not work and it points to `default` anyway.
</details>
Fixed. This required adding `_all` pseudo param and a lot of boilerplate changes. But otherwise was easy :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1145#-:-KQ-a-NzNgAr_0-oZZbO:bp2kb6v)*

**Comment by bryk** [comment]
Reviewed 1 of 41 files at r3.
Review status: 13 of 53 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1145)*

**Comment by bryk** [comment]
PTAL 

---

Review status: 13 of 53 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1145#-:-KQ-aa7Bh02cEME5JY_j:b-833310)*

**Comment by floreks** [comment]
Still I've small issue with namespace selector.

anim

**Comment by bryk** [comment]
> Still I've small issue with namespace selector.

Hmm... What's the issue? :D

**Comment by maciaszczykm** [comment]
@bryk I think the issue is, that view on the right is not updated after selecting namespace in the menu. For example after @floreks selected `All namespaces` there was nothing to display in workloads till he changed view. After selecting `default` namespace not all contents were displayed too.

**Comment by bryk** [comment]
@maciaszczykm @floreks Ok, fixed the glitch. The issue was the fact that code in $resolve needs to use the state params passed to it, not global ones :) 

PTAL

---

Review status: 12 of 53 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1145#-:-KQ0dG_OQz9CrweRXbmD:b6a381k)*

**Comment by floreks** [comment]
Great! :lgtm:

---

Reviewed 3 of 18 files at r1, 1 of 1 files at r2, 32 of 41 files at r3, 5 of 7 files at r4.
Review status: 50 of 53 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1145#-:-KQ1CBkK_QTDgYkWO5_q:b5wq1o3)*

**Comment by floreks** [comment]
Reviewed 1 of 41 files at r3, 2 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1145)*

**Comment by bryk** [comment]
Thanks! Merging :)

**Pull request merged**
