### PR TITLE
Bump nodejs to 16

### PR DESCRIPTION
**Pull request by shu-mutou**
NodeJS 16 becomes ACTIVE LTS from 16.13.0. So update to 16.13.0 or later.

https://nodejs.org/en/about/releases/

### CODE REVIEW

**Comment by shu-mutou** [comment]
/hold
Checks, tests, build and built binary works well in our development container. But in not CI.

**Comment by floreks** [comment]
E2E do not work for some time now. We have to investigate that. I also see that angular has finally fixed their node/npm engine restrictions and it is now allowed to be used with the new node v16.13 and npm v8. Great :slightly_smiling_face:

**Comment by maciaszczykm** [comment]
I've fixed static check in my PR. Some of dependencies need updates.

**Comment by shu-mutou** [comment]
/close
in favor of #6351 .

**Pull request closed without merging**
