### PR TITLE
Added roadmap image from KubeCon presentation to roadmap.md

### PR DESCRIPTION
**Pull request by danielromlein**
Roadmap image from my KubeCon talk with @bryk.

### CODE REVIEW

**Comment by rf232** [comment]
hmm, apparently you didn't sign the linuxfoundation cla yet, could you do that, and then I think you can click somewhere on this page to let the check verify you again.

**Comment by bryk** [comment]
Click "details" here:
 
selection_147

**Comment by danielromlein** [comment]
Hm, yeah I thought I had that signed. I wonder if that was from changing my GitHub username from @romlein to @danielromlein. Having trouble logging into my CNCF account, but I'll sync up with someone here at Apprenda and get this sorted out – sorry about that!

**Comment by bryk** [comment]
@danielromlein Yep, try to debug this problem with someone at Apprenda who contributes to GitHub. I bet this is something about your email settings in git client or so.

**Comment by danielromlein** [comment]
OK! I'm authorized under Apprenda.

**Comment by maciaszczykm** [comment]
CI flakes again. I'll merge when it will pass.

**Comment by bryk** [comment]
Juhuu, I think this is ready to merge :)

**Pull request merged**
