### PR TITLE
Switch from godeps to govendor

### PR DESCRIPTION
**Pull request by bryk**
Now it is easy to update the dependencies and we use standard tools

This PR is separated into two commits. One which changes code and is reviewable and the other which is godep to govendor swithc.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/987)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you review?

**Comment by floreks** [comment]
Awesome! I'll check it soon.

**Comment by floreks** [comment]
Travis fails to recognize vendor deps?

**Comment by floreks** [comment]
Let me know when ready :)

**Comment by bryk** [comment]
Yes. Travis has some problems. Trying to fix this.

**Comment by floreks** [comment]
Reviewable died because of this PR :) I've checked it on github. LGTM.

**Comment by bryk** [comment]
Perfect, thanks! Merging.

**Pull request merged**
