### PR TITLE
Add Job resource frontend

### LINKED ISSUE #564: Feature request: Display Jobs
We run lots of jobs on K8S, and it'd be awesome to see them all in the dashboard (with status, sparkline metrics etc..).

### LINKED ISSUE #788: Job resource support
I'll add Job resource support to the dashboard. 

- [x] backend - #792
- [ ] list and details view - #806

Generic details page template:

Design template

### PR DESCRIPTION
**Pull request by maciaszczykm**
Add Job resource frontend.

Closes #788.
Closes #564.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/806)

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Closes #564 issue.

**Comment by bryk** [comment]
1. We have conflicts.
2. Can you add a few more test?

**Comment by bryk** [comment]
Reviewed 18 of 22 files at r1, 6 of 6 files at r2.
Review status: 24 of 25 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/jobdetail/jobdetail_stateconfig.js, line 39 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/806#-KJZxLdVznhi7Z92ec26:-KJZxLdW80mZCPIjW50R:127523943) ([raw file](https://github.com/kubernetes/dashboard/blob/24ec4df457a38f3c7b4988db4b5d089b268c03a7/src/app/frontend/jobdetail/jobdetail_stateconfig.js#L39)):*
> ```JavaScript
>     data: {
>       [breadcrumbsConfig]: {
>         'label': '{{$stateParams.job}}',
> ```

Please use common $stateparams and have objectName here 

---

*[src/app/frontend/jobdetail/jobinfo.html, line 18 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/806#-KJZxWPamzSxEFBtpZ1S:-KJZxWPamzSxEFBtpZ1T:1318180978) ([raw file](https://github.com/kubernetes/dashboard/blob/24ec4df457a38f3c7b4988db4b5d089b268c03a7/src/app/frontend/jobdetail/jobinfo.html#L18)):*
> ```HTML
> 
> <kd-info-card>
>   <kd-info-card-header>Resource details</kd-info-card-header>
> ```

Can you add i18n for this page?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/806)*

**Comment by maciaszczykm** [comment]
`Succeeded` pods don't have status icon displayed, will be fixed in #831.

**Comment by maciaszczykm** [comment]
PTAL

<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> `Succeeded` pods don't have status icon displayed, will be fixed in #831.
</details>


---

Review status: 15 of 31 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/jobdetail/jobdetail_stateconfig.js, line 39 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/806#-KJZxLdVznhi7Z92ec26:-KJ_t-8EcAsQaAgWoZ3Y:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/24ec4df457a38f3c7b4988db4b5d089b268c03a7/src/app/frontend/jobdetail/jobdetail_stateconfig.js#L39)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Please use common $stateparams and have objectName here 
</details>
Done.

---

*[src/app/frontend/jobdetail/jobinfo.html, line 18 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/806#-KJZxWPamzSxEFBtpZ1S:-KJ_szSDlFBv8bpZKwov:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/24ec4df457a38f3c7b4988db4b5d089b268c03a7/src/app/frontend/jobdetail/jobinfo.html#L18)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Can you add i18n for this page?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/806#-:-KJ_t0FxVKcpCfNDnCpt:676965300)*

**Comment by bryk** [comment]
Last comment. PTAL :) 

<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> PTAL
</details>


---

Reviewed 5 of 7 files at r3, 7 of 11 files at r4, 8 of 8 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/backend/resource/job/jobdetail.go, line 49 \[r5\]](https://reviewable.io:443/reviews/kubernetes/dashboard/806#-KJdb8_3g1Cfbeg3yvvR:-KJdb8_3g1Cfbeg3yvvS:794493112) ([raw file](https://github.com/kubernetes/dashboard/blob/4fd17a7e9101c2458c602e47fd230525c40f0dae/src/app/backend/resource/job/jobdetail.go#L49)):*
> ```Go
> 	// Parallelism specifies the maximum desired number of pods the job should run at any given
> 	// time.
> 	Parallelism int32 `json:"paralleism"`
> ```

Should this be `int32` or `*int32`? The spec has pointer. Maybe it is something different to when parallelism is null.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/806#-:-KJdbbvZezwqRY6A-eOZ:194801676)*

**Comment by maciaszczykm** [comment]
Review status: 27 of 36 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/backend/resource/job/jobdetail.go, line 49 \[r5\]](https://reviewable.io:443/reviews/kubernetes/dashboard/806#-KJdb8_3g1Cfbeg3yvvR:-KJeQdXU83_8nCMHIVhS:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/4fd17a7e9101c2458c602e47fd230525c40f0dae/src/app/backend/resource/job/jobdetail.go#L49)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Should this be `int32` or `*int32`? The spec has pointer. Maybe it is something different to when parallelism is null.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/806)*

**Comment by bryk** [comment]
Reviewed 9 of 10 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/806)*

**Pull request merged**
