### PR TITLE
doc: minor grammar/clarity fixes

### PR DESCRIPTION
**Pull request by egeland**

### CODE REVIEW

**Comment by bryk** [comment]
Hey @egeland :) I'd love to merge it, but we need Linux foundation CLA here...

**Comment by egeland** [comment]
Hey, it's weird that it's not showing - I signed the CLA, both LF and Google..

**Comment by bryk** [comment]
What's your email in the github commit? This is the thing that matters.

**Comment by egeland** [comment]
`Author: Frode Egeland <egeland@gmail.com>`

**Comment by bryk** [comment]
Click the "Details" link in the "egeland needs CLA" row. Log in. Go to "My account" and verify that your mail there is "egeland@gmail.com".

**Comment by egeland** [comment]
The details link only lets me resend verification email, it won't let me log in or see any details:
image

**Comment by digitalfishpond** [comment]
Hi @egeland ! So clicking on the link in the email clearly hasn't worked. The blue box mentions another option of pasting the code from the email onto the blue box, maybe try that to unlock the details page if you haven't tried that already?

**Comment by egeland** [comment]
@digitalfishpond I don't get the email at all - I've checked spam folder and everywhere else, but nothin'...

**Comment by digitalfishpond** [comment]
So sorry @egeland, I didn't read properly. Now I feel stupid! :D I'd assume you're right about '.REMOVETHISBIT' causing confusion for the system. Have you tried removing that bit (ba-dum!) temporarily and trying again?

**Comment by egeland** [comment]
I've done that now, and I got registered.. LOL, should have just tried it straight away..

**Pull request merged**
