### PR TITLE
Add namespace restriction option

### PR DESCRIPTION
**Pull request by titilambert**
Hello,
I just add a new option to dashboard backend to be able to limit queries to a specified namespace.
With this option we can provide a pod of kubernetes dashboard with all new k8s namespace.
Kuberntes Dashboard can be the user GUI for each namespaces.

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/363)

### CODE REVIEW

**Comment by bryk** [comment]
Hey @titilambert, thanks for the contribution! Hold on a while with the implementation. We're discussing this issue at the moment and are thinking about best solution. Please join the discussion at https://github.com/kubernetes/dashboard/issues/348

**Comment by titilambert** [comment]
@bryk Hello ! Any news on this one ?

**Comment by bryk** [comment]
Yes, I'm here - just returned from vacation.

**Comment by bryk** [comment]
First thought: cannot you achieve this by just configuring your installation? I.e., when you deploy Dashboard UI to namespace `foo`, then it has access only to resources in namespace `foo`? This would be much better solution that doing this on the UI side. 
What do you think?

**Comment by titilambert** [comment]
> when you deploy Dashboard UI to namespace foo, then it has access only to resources in namespace foo ?

How can I do that ? (Because the objective of this PR is to to that !)
Maybe I missed something, but, for now, It has access to resources in all namespaces.
Also, I want to limit users to be able to edit/delete/create resources in other namespace.

**Comment by bryk** [comment]
@titilambert Yes, you can definitely do this. It is much better solution than baking it into UI. Check out this: http://kubernetes.io/docs/admin/authorization/. You can basically say that pods (or only the UI) in namespace `foo` can only access resources in namespace `foo`. 

Does this solve your problem?

@kubernetes/sig-auth

**Comment by erictune** [comment]
For some use cases, @bryk's solution will work.  However, it is definitely possible to write authorization policies that are incompatible with the current Dashboard design (in the sense that the Dashboard will allow users to do things they could not do otherwise).

**Comment by erictune** [comment]
https://github.com/kubernetes/kubernetes/issues/23201

**Comment by bryk** [comment]
@titilambert I think this problem is solved. Please reopen if you need any help.

**Pull request closed without merging**
