### PR TITLE
Angular migration

### PR DESCRIPTION
**Pull request by maciaszczykm**
## Development

Requirements:
- Running Kubernetes cluster.
- `ng-migration` branch checked out.
- Deps should be up-to-date. Use `rm -rf node_modules && npm i` after switching branches to ensure that.

The application can be started with `npm start` and accessed at [localhost:8080](localhost:8080).

## Progress
My suggestion is to merge to master after we will create last tag/release from AngularJS (~December). Then we can start releasing RC versions and fix existing problems (~January).

- [ ] manual tests and final code review
- [ ] solving all TODOs from the code
- [ ] tests
- [ ] localization
- [ ] check `frontend_old` for any leftovers
- [ ] align actionbar actions with context actions in list menu for every resource
- [ ] graphs for cluster, nodes, overview, workloads, daemon sets, deployments, pods, rc, rs, and stateful sets
- [ ] workload statuses for workload and overview page
- [ ] deployment list and details (85% done; missing: hpa list in details)
- [ ] cron job list and details (80% done; missing: inactive job list, trigger option in list, pause action)
- [x] system banner
- [x] sparklines for pods
- [x] rebase master
- [x] auth
- [x] resource context actions
- [x] namespace list and details
- [x] fix styling issues caused by Angular and Material updates
- [x] persistent volume list and details
- [x] storage class list and details
- [x] update Angular and other modules to newest versions 
- [x] JSON/YAML editor
- [x] filtering, sorting and pagination
- [x] logs
- [x] exec into pod
- [x] action menu on every row in all list views
- [x] toolbar
- [x] breadcrumbs
- [x] menu
- [x] notification panel
- [x] create from input, file and form
- [x] search
- [x] cluster
- [x] cluster role list and details
- [x] node list and details
- [x] namespace selector
- [x] overview
- [x] workloads
- [x] daemon set list and details
- [x] job list and details
- [x] pod list and details
- [x] replica set list and details
- [x] replication controller list and details
- [x] stateful set list and details
- [x] discovery and load balancing
- [x] ingress list and details
- [x] service list and details
- [x] config and storage
- [x] config map list and details
- [x] persistent volume claim list and details
- [x] secret list and details
- [x] settings
- [x] local settings stored in browser's cookies including dark theme
- [x] open logs/exec in the same window
- [x] about
- [x] and many more of UX, code improvements etc.

## Test deployment

https://gist.github.com/floreks/7bafe96d835237ae645a2a5f38872581

**Deploy command**: `kubectl apply -f https://gist.githubusercontent.com/floreks/7bafe96d835237ae645a2a5f38872581/raw/7040b129597bc5d5720b781e5a5da1f2714cdf81/kubernetes-dashboard-v2.0.0-alpha0.yaml`

**Access it using `kubectl proxy` at**: http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard-v2:/proxy/

**To grant cluster admin privileges for tests use**: `kubectl apply -f https://gist.githubusercontent.com/floreks/d1bff5386b07b4e3690eed2fb136c94f/raw/2d59ebd9e58ad3f748bb1de1ecd3f5ef07d46531/kubernetes-dashboard-v2.0.0-alpha0-admin-binding.yaml`

## Sneak peek of current changes

zrzut ekranu 2018-12-13 o 13 41 
43

image
zrzut ekranu 2018-11-29 o 15 11 40
image
image
zrzut ekranu z 2018-02-21 11-15-03
zrzut ekranu z 2018-02-21 11-15-29
zrzut ekranu z 2018-03-05 16-14-17

Continues and closes #2727.

### CODE REVIEW

**Comment by yinhaijiao** [comment]
@maciaszczykm Hi, I want to help @pengx17  to finish the [CREATE AN APP] tab of the create page. Please assign me.

**Comment by maciaszczykm** [comment]
@yinhaijiao Okay, but first you should discuss it with him.

**Comment by maciaszczykm** [comment]
@yinhaijiao Does @pengx17 know about it?

**Comment by pengx17** [comment]
@maciaszczykm Yes @yinaojiao has contacted me about it privately and he will take the remaining work from me. By the way I believe he is available to devote on the Dashboard project for some time.

**Comment by kororo** [comment]
@maciaszczykm and @pengx17, hi there, is there anything that I could help on this?

**Comment by kororo** [comment]
Hi @maciaszczykm, I would like to help to increase the code coverage for either Angular or Go. Let me know if you could point me any specific features/files to focus on. I have slow pace to contribute, I could start from low -> high profile features. Any documentations/pointers to follow the standard procedure and how-to commit/contribute would be appreciated.

Thanks

**Comment by kororo** [comment]
@maciaszczykm ok no probs! i will look around and let you know when I have question, just to confirm. I will start from the "ng-migration" branch.

**Comment by maciaszczykm** [comment]
@kororo Sure 👍

**Comment by yinhaijiao** [comment]
@maciaszczykm 
Sorry, the company has been very busy recently. It has been suspended for a while. But it will continue soon. Now it's about 60%.

**Comment by danielromlein** [comment]
Chatted with @StephenFluin from the Angular team today and he was was interested in more about what specific challenges stand in the way of getting the Dashboard migration completed. @maciaszczykm or @floreks could you possibly expound on what those are to see if something like a Q&A session with the Angular team or having them reach out to their network to solicit contributors would be helpful to us?

**Comment by maciaszczykm** [comment]
@yinhaijiao @pengx17 @kororo @austbot Is anyone of you interested in taking care of one of the missing functionalities?

**Comment by yinhaijiao** [comment]
@maciaszczykm 

- create from input, file and form (90% done; missing: styling fixes in form)
- service list and details (90% done, missing: custom info in detail)

These two parts are what I did before. I'll do this first, and then I'll do something else.
But can you tell me in detail about `styling fixes in form`?

**Comment by maciaszczykm** [comment]
@yinhaijiao Actually I wanted to review on my own and I have noticed that there might be few places where minor CSS fixes can be applied. Perhaps you can work on workload statuses, sparklines or about page?

**Comment by yinhaijiao** [comment]
@maciaszczykm   OK. I do [workload statuses] first.

**Comment by pengx17** [comment]
@maciaszczykm I have a colleague (@frozenwings) who is interested in contributing the migration. Can you point out something he can start with?

**Comment by maciaszczykm** [comment]
@pengx17 @frozenwings Perhaps workload statuses for workload and overview page? I can share some ideas and tips via Slack.

**Comment by yinhaijiao** [comment]
@maciaszczykm Do I still work on [workload statuses]? Or work on something else?

**Comment by maciaszczykm** [comment]
@yinhaijiao Oh sorry, yes you should if you have started.

@pengx17 @frozenwings Perhaps you can switch to sparklines for pods or anything else from the list? Just let us know what is in progress.

**Comment by pengx17** [comment]
> @yinhaijiao Oh sorry, yes you should if you have started.
> 
> @pengx17 @frozenwings Perhaps you can switch to sparklines for pods or anything else from the list? Just let us know what is in progress.

Sure, sparklines should be a good starting point :D

**Comment by anvithks** [comment]
@maciaszczykm I would like to contribute to this migration. What would be a good starting point.

**Comment by maciaszczykm** [comment]
@anvithks Good to hear that! To name a few:

- writing some tests for existing components
- system banner functionality (https://github.com/kubernetes/dashboard/wiki/Dashboard-arguments)
- pause action for cron jobs
- trigger option in cron job list (it should create a new job based on cron job template)

In all cases backend is ready and you should just reuse it. You can look into current master to see current implementation. It would be nice if you would let us know about your pick. We are available at #sig-ui Slack to discuss any issues and answer questions.

**Comment by maciaszczykm** [comment]
I have started looking into system banner feature.

**Comment by anvithks** [comment]
@maciaszczykm thanks for the above.
I am currently going through the developer guide and the code. 
I have joined the #sig-ui channel and will post any queries there. 
I will get back to you after I understand which of the tasks I will be able to pick up.

**Comment by RothAndrew** [comment]
Copying from [here](https://github.com/kubernetes/dashboard/pull/3443#issuecomment-449049441) since this seems like the better place to put it:

WHOA NELLY! This is gonna break (read: IS BREAKING) all kinds of stuff. The official aws docs has pointed to the .../src/ directory for AGES. IT STILL IS POINTING TO .../src/!!!!!

**Pull request merged**
