### PR TITLE
Persistent Volumes backend

### PR DESCRIPTION
**Pull request by batikanu**
Persistent Volumes backend implementation. I have included the data shown in kubectl as persistent volume detail which can be discussed and changed if needed.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1091)

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@digitalfishpond Can you take a look?

**Comment by digitalfishpond** [comment]
1 comment you might choose to ignore, and the rest :lgtm: 

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/backend/resource/common/resourcechannels.go, line 78 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1091#-KOJNumiRkY7ZOGy5dHf:-KOJNumiRkY7ZOGy5dHg:2070209902) ([raw file](https://github.com/kubernetes/dashboard/blob/af255f1fffaae3e724dc12d2f25a795a9d8d22e7/src/app/backend/resource/common/resourcechannels.go#L78)):*
> ```Go
> 
> 	// List and error channels to PersistentVolumes
> 	PersistentVolumeList PersistentVolumeListChannel
> ```

Not even sure if it's worth mentioning, feel free to ignore: I would have kept PodMetrics at the bottom of this list as all others are Lists (including PersistenVolumeList) for future clarity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1091#-:-KOJQoAL48rK8FzFXjbI:1916867329)*

**Comment by batikanu** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/backend/resource/common/resourcechannels.go, line 78 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1091#-KOJNumiRkY7ZOGy5dHf:-KOJRHM1sKeLtT7mThX5:-1088365365) ([raw file](https://github.com/kubernetes/dashboard/blob/af255f1fffaae3e724dc12d2f25a795a9d8d22e7/src/app/backend/resource/common/resourcechannels.go#L78)):*
> dMetrics at the bottom of this list as all others are L
Thanks, it makes sense

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1091)*

**Comment by batikanu** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/backend/resource/common/resourcechannels.go, line 78 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1091#-KOJNumiRkY7ZOGy5dHf:-KOJSYpckxPGZwmF32aC:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/af255f1fffaae3e724dc12d2f25a795a9d8d22e7/src/app/backend/resource/common/resourcechannels.go#L78)):*
<details><summary><i>Previously, batikanu (Batikan Urcan) wrote…</i></summary>
> > dMetrics at the bottom of this list as all others are L
> Thanks, it makes sense
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1091)*

**Comment by digitalfishpond** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1091)*

**Comment by floreks** [comment]
:lgtm:. Small comment. I'll test it quickly a bit later and we can merge.

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/app/backend/resource/persistentvolume/persistentvolumelist.go, line 41 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1091#-KOOQew_jmWH6Vr9C01d:-KOOQew_jmWH6Vr9C01e:b-2khv1e) ([raw file](https://github.com/kubernetes/dashboard/blob/f8dbebec352283c2a53c9f31d0812dfd1e7a9219/src/app/backend/resource/persistentvolume/persistentvolumelist.go#L41)):*
> ```Go
> }
> 
> // PersistentVolumeList returns a list of all Persistent Volumes in the cluster.
> ```

s/PersistentVolumeList/GetPersistentVolumeList - golint requires to start comment with exact name of public function/structure

---

*[src/app/backend/resource/persistentvolume/persistentvolumelist.go, line 51 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1091#-KOOR-KA2E-o0b_q0Jd4:-KOOR-KBFRxWVrR2vB8A:buo9nmt) ([raw file](https://github.com/kubernetes/dashboard/blob/f8dbebec352283c2a53c9f31d0812dfd1e7a9219/src/app/backend/resource/persistentvolume/persistentvolumelist.go#L51)):*
> ```Go
> }
> 
> // PersistentVolumeList returns a list of all Persistent Volumes in the cluster
> ```

Same here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1091#-:-KOORIJvXncaiEv6j9EI:boqk4fj)*

**Comment by batikanu** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/backend/resource/persistentvolume/persistentvolumelist.go, line 41 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1091#-KOOQew_jmWH6Vr9C01d:-KOOkKDcwgpDAkfmfO2S:b-896fix) ([raw file](https://github.com/kubernetes/dashboard/blob/f8dbebec352283c2a53c9f31d0812dfd1e7a9219/src/app/backend/resource/persistentvolume/persistentvolumelist.go#L41)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> s/PersistentVolumeList/GetPersistentVolumeList - golint requires to start comment with exact name of public function/structure
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1091)*

**Comment by floreks** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1091)*

**Pull request merged**
