### PR TITLE
Fix namespace reset on details page

### LINKED ISSUE #1056: Links from namespaced list views don't include namespace
Links from namespaced views are broken. They don't include the current namespace. To try this out, open UI at HEAD, navigate to kube-system workloads and click on a link to details. Notice that namespace has changed to "all user namespaces". 

This was introduced in https://github.com/kubernetes/dashboard/pull/1032 by modifying globalresourcedetail.js. 

@floreks Can you fix this?

### PR DESCRIPTION
**Pull request by floreks**
Fixes #1056

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1058)

### CODE REVIEW

**Comment by bryk** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/common/resource/globalresourcedetail.js, line 21 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1058#-KNB5JmgJGYG0Zn6h7us:-KNB5JmgJGYG0Zn6h7ut:2137913699) ([raw file](https://github.com/kubernetes/dashboard/blob/258b7eadd02f357dd66bbe2e2767579a66d992b8/src/app/frontend/common/resource/globalresourcedetail.js#L21)):*
> ```JavaScript
>  *
>  * It is added to satisfy dependency but not override base namespace selected by the user.
>  * @extends {../../chrome/chrome_state.StateParams}
> ```

Hmm... Once more. Why do we need this? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1058)*

**Comment by floreks** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/common/resource/globalresourcedetail.js, line 21 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1058#-KNB5JmgJGYG0Zn6h7us:-KNB6c0uikggZ4CYIrGx:-578114410) ([raw file](https://github.com/kubernetes/dashboard/blob/258b7eadd02f357dd66bbe2e2767579a66d992b8/src/app/frontend/common/resource/globalresourcedetail.js#L21)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Hmm... Once more. Why do we need this? 
</details>
It is to satisfy JSDOc and not override base namespace parameter coming from chrome StateParams class.

Do you have any other ideas how to fix that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1058)*

**Comment by bryk** [comment]
*[src/app/frontend/common/resource/globalresourcedetail.js, line 21 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1058#-KNB5JmgJGYG0Zn6h7us:-KNB72YOykSNb3qa-nW3:689457120) ([raw file](https://github.com/kubernetes/dashboard/blob/258b7eadd02f357dd66bbe2e2767579a66d992b8/src/app/frontend/common/resource/globalresourcedetail.js#L21)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> It is to satisfy JSDOc and not override base namespace parameter coming from chrome StateParams class.
> 
> Do you have any other ideas how to fix that?
</details>
Where do we need to satisfy the JSDoc? Let me check that place to see whether there are other options.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1058)*

**Comment by floreks** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/common/resource/globalresourcedetail.js, line 21 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1058#-KNB5JmgJGYG0Zn6h7us:-KNB7QLg6s-IAXi1g9eQ:1286634448) ([raw file](https://github.com/kubernetes/dashboard/blob/258b7eadd02f357dd66bbe2e2767579a66d992b8/src/app/frontend/common/resource/globalresourcedetail.js#L21)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Where do we need to satisfy the JSDoc? Let me check that place to see whether there are other options.
</details>
In [here](https://github.com/kubernetes/dashboard/blob/c8f10239275258f9e49d8c3f853d2d65bc4f3279/src/app/frontend/common/components/resourcecard/resourcecardlistpagination_component.js#L109). StateParams type is set to `{!./../../resource/resourcedetail.StateParams}` and it doesn't have namespace property. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1058)*

**Comment by bryk** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/common/resource/globalresourcedetail.js, line 21 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1058#-KNB5JmgJGYG0Zn6h7us:-KNB8XHSGyq_FaXfaRlE:-1527033863) ([raw file](https://github.com/kubernetes/dashboard/blob/258b7eadd02f357dd66bbe2e2767579a66d992b8/src/app/frontend/common/resource/globalresourcedetail.js#L21)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> In [here](https://github.com/kubernetes/dashboard/blob/c8f10239275258f9e49d8c3f853d2d65bc4f3279/src/app/frontend/common/components/resourcecard/resourcecardlistpagination_component.js#L109). StateParams type is set to `{!./../../resource/resourcedetail.StateParams}` and it doesn't have namespace property. 
</details>
You can update the annotation there to:
```js
    /** @private {!./../../resource/resourcedetail.StateParams|!./../../chrome/chrome_state.StateParams} */
```
Should work.

The benefit of that is correctness. This does not inherit (correct) and we expect either of the sate params (correct). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1058)*

**Comment by floreks** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/common/resource/globalresourcedetail.js, line 21 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1058#-KNB5JmgJGYG0Zn6h7us:-KNBC_qVt5U3igVTxzpK:2018239455) ([raw file](https://github.com/kubernetes/dashboard/blob/258b7eadd02f357dd66bbe2e2767579a66d992b8/src/app/frontend/common/resource/globalresourcedetail.js#L21)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> You can update the annotation there to:
> ```js
>     /** @private {!./../../resource/resourcedetail.StateParams|!./../../chrome/chrome_state.StateParams} */
> ```
> Should work.
> 
> The benefit of that is correctness. This does not inherit (correct) and we expect either of the sate params (correct). 
</details>
Nice! So simple. Thanks :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1058)*

**Comment by bryk** [comment]
:lgtm: Please merge when travis is happy :) 

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1058#-:-KNBEerx55NIxh4o4MIG:-1175932025)*

**Pull request merged**
