### PR TITLE
Japanese localization of NodeDetail page

### PR DESCRIPTION
**Pull request by Yamagami-Takuma**
Japanese localization of NodeDetail page.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/901)

### CODE REVIEW

**Comment by Yamagami-Takuma** [comment]
@f-higashi Can you review?

**Comment by f-higashi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[i18n/messages-ja.xtb, line 407 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/901#-KKGwJXLqt14hjt4AAXG:-KKGwJXNDhlb_u7psXXJ:-1402466848) ([raw file](https://github.com/kubernetes/dashboard/blob/d581356e1a571f36a8e0311e4283d15a8100d0e5/i18n/messages-ja.xtb#L407)):*
> ```
> 	<translation id="8850385723131973875" key="MSG_NODE_DETAIL_LABELS_LABEL" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Label 'Label selector' for the node's labels list on the node details page.">ラベル</translation>
> 	<translation id="4128274310143949044" key="MSG_NODE_DETAIL_SYSTEM_SUBTITLE" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Subtitle 'System info' for the right section with general information about node system on the node details page.">システム情報</translation>
> 	<translation id="6810581903764403092" key="MSG_NODE_DETAIL_ARCHITECTURE_LABEL" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Label 'Architecture' for the node architecture displayed on its details page.">構成</translation>
> ```

`アーキテクチャ`  is better in this case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/901)*

**Comment by Yamagami-Takuma** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[i18n/messages-ja.xtb, line 407 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/901#-KKGwJXLqt14hjt4AAXG:-KKHGsl6LFWn-fjAzfjo:1920760566) ([raw file](https://github.com/kubernetes/dashboard/blob/d581356e1a571f36a8e0311e4283d15a8100d0e5/i18n/messages-ja.xtb#L407)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> `アーキテクチャ`  is better in this case.
</details>
I fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/901)*

**Comment by f-higashi** [comment]
:lgtm:

you can merge this :)
@maciaszczykm

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/901#-:-KKHIk_gCOa-OAcQ0d4J:68082739)*

**Comment by maciaszczykm** [comment]
Done, translation process is very quick :)

**Pull request merged**
