### PR TITLE
Ingress list and details page (initial version)

### PR DESCRIPTION
**Pull request by bryk**
* List page misses statuses
* details page misses some infor and status details

This will be done in a next PR.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1176)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm Can you review this? 

I'll add tests and resolve conflicts tomorrow.

**Comment by maciaszczykm** [comment]
Minor comments. PTAL

There is one minor issue, when all namespaces are selected:



As you can see, there is no namespace in the cell. It should be `default`.

---

Reviewed 29 of 30 files at r1.
Review status: 29 of 30 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/backend/resource/ingress/ingresslist.go, line 68 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1176#-KQZxzdxCFWl2fyBXuxB:-KQZxzdxCFWl2fyBXuxC:bvkx5uk) ([raw file](https://github.com/kubernetes/dashboard/blob/3441cd3c64fbd5c74cbe52080125478c622f4234/src/app/backend/resource/ingress/ingresslist.go#L68)):*
> ```Go
> 		for _, status := range ingress.Status.LoadBalancer.Ingress {
> 			endpoint := common.Endpoint{Host: status.IP}
> 			modelIngress.Endpoints = append(modelIngress.Endpoints, endpoint)
> ```

What about exporting it to a new function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1176#-:-KQZwkxGaByc2oj5TlZT:byy95fx)*

**Comment by bryk** [comment]
Fixed namespace column across a few other views.

PTAL

---

Review status: 29 of 30 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/backend/resource/ingress/ingresslist.go, line 68 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1176#-KQZxzdxCFWl2fyBXuxB:-KQdxGIt9rjq1caxHAwW:b-8xfznn) ([raw file](https://github.com/kubernetes/dashboard/blob/3441cd3c64fbd5c74cbe52080125478c622f4234/src/app/backend/resource/ingress/ingresslist.go#L68)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> What about exporting it to a new function?
</details>
Hmm... What do you mean? Lines 67-68 are not worth it, since it'd be more work with a function than inline code here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1176#-:-KQdxPcaZTdTUZO6ZcN4:b-lzy97x)*

**Comment by maciaszczykm** [comment]
PTAL

---

Review status: 21 of 42 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/backend/resource/ingress/ingresslist.go, line 68 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1176#-KQZxzdxCFWl2fyBXuxB:-KQe4J1bxZgz8nYNP94s:b116ir7) ([raw file](https://github.com/kubernetes/dashboard/blob/3441cd3c64fbd5c74cbe52080125478c622f4234/src/app/backend/resource/ingress/ingresslist.go#L68)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Hmm... What do you mean? Lines 67-68 are not worth it, since it'd be more work with a function than inline code here. 
</details>
I was thinking about lines 65-70. Function, that would collect all Endpoints from Ingress and return array. It could be used directly in line 62.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1176#-:-KQe4nMl-Cy9k4Y-Rggn:bb71pro)*

**Comment by bryk** [comment]
PTAL 

---

Review status: 21 of 42 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/backend/resource/ingress/ingresslist.go, line 68 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1176#-KQZxzdxCFWl2fyBXuxB:-KQelT_S1iECZAHEBMOX:brp7g5p) ([raw file](https://github.com/kubernetes/dashboard/blob/3441cd3c64fbd5c74cbe52080125478c622f4234/src/app/backend/resource/ingress/ingresslist.go#L68)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> I was thinking about lines 65-70. Function, that would collect all Endpoints from Ingress and return array. It could be used directly in line 62.
</details>
Oh, yeah. Now this makes sense. PTAL 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1176#-:-KQelXmUodoxjwcYkstD:b-833310)*

**Comment by maciaszczykm** [comment]
:lgtm:

---

Reviewed 1 of 21 files at r2.
Review status: 22 of 42 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1176#-:-KQemA8SEUThte999IZl:bnfp4nl)*

**Comment by bryk** [comment]
Thanks! Will merge soon. 

---

Reviewed 21 of 30 files at r1, 18 of 21 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1176#-:-KQepQfoMgIWRGXyh3n8:b-jzg4oa)*

**Pull request merged**
