### PR TITLE
Add frontend and backend for pet set list view

### LINKED ISSUE #734: Implement error handling for replica sets and deployments
So that it displays errors from pods the same way we currently do for replication controllers

cc @floreks @digitalfishpond

### LINKED ISSUE #790: The "Age" on workloads/deployments is always "a year"
#### Issue details
No matter what age ``kubectl get deployments`` shows in the dashboard it is always "a year". 

##### Environment

We run a Kubernetes 1.2.4 on AWS instances. 

```
Dashboard version: v1.1.0-beta1 (published image) / master @b5263fc (build with  ``build/run-gulp-in-docker.sh docker-image:canary``
Kubernetes version: 1.2.4
Operating system:  CoreOS stable (899.17.0)
```

##### Steps to reproduce

Deploy the dashboard and a deployment in the cluster. Look at the 'workloads'  page.

##### Observed result

The age of the deployments is always "a year"
##### Expected result

The actual age of the deployment. 

##### Comments

Thanks for developing this nice tool!

Best wishes,
Matthias

### PR DESCRIPTION
**Pull request by floreks**
Related to #779 

First part adds pet set list view and pet set list to workloads page.

Minor changes:
- fixes #790 with incorrect age on deployment list
- closes #734 and adds error handling for deployment, replicaset and petset
- adjusted delete verber to be able to support more clients (needed i.e. for petset as it uses apps client)
- fixed daemon set and replica set not beeing filtered by multiple namespaces

~~Todo~~:
 - [x] ~~add frontend tests~~

View:
zrzut ekranu z 2016-06-01 14-35-38

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/791)

### CODE REVIEW

**Comment by floreks** [comment]
@maciaszczykm @bryk could you review?

**Comment by bryk** [comment]
A few comments and we're ready to go :) 

<details><summary><i>Previously, codecov-io wrote…</i></summary>
> ## [Current coverage][cc-pull] is **95.05%**
> > Merging [#791][cc-pull] into [master][cc-base-branch] will increase coverage by **0.52%**
> 
> 1. File `...ereader_directive.js` (not in diff) was modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/6f1c958c9e1d6385300b2bd793d5ae998d513356/changes?src=pr#7372632F6170702F66726F6E74656E642F6465706C6F792F66696C657265616465725F6469726563746976652E6A73) 
>   - Misses `-6` 
>   - Partials `0` 
>   - Hits `+6`
> 
> ```diff
> @@             master       #791   diff @@
> ==========================================
>   Files           187        194     +7   
>   Lines          1462       1495    +33   
>   Methods           0          0          
>   Messages          0          0          
>   Branches          0          0          
> ==========================================
> + Hits           1382       1421    +39   
> + Misses           80         74     -6   
>   Partials          0          0          
> ```
> 
> > Powered by [Codecov](https://codecov.io?src=pr). Last updated by [25dac01...6f1c958][cc-compare]
> [cc-base-branch]: https://codecov.io/gh/kubernetes/dashboard/branch/master?src=pr
> [cc-compare]: https://codecov.io/gh/kubernetes/dashboard/compare/25dac017c001b170a4facc67e8b206971e5070e4...6f1c958c9e1d6385300b2bd793d5ae998d513356
> [cc-pull]: https://codecov.io/gh/kubernetes/dashboard/pull/791?src=pr
</details>


---

Reviewed 33 of 35 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/app/backend/resource/common/verber.go, line 50 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/791#-KJBRsVO9pl4i2IUp9DX:-KJBRsVO9pl4i2IUp9DY:53625872) ([raw file](https://github.com/kubernetes/dashboard/blob/0f2cfc6cfb3f0e5936b0a00c2e4ac6101fe4393c/src/app/backend/resource/common/verber.go#L50)):*
> ```Go
> 
> 	var client RESTClient
> 	switch resourceSpec.ClientType {
> ```

Can you extract client selection to a common function? I have a PR that will use the common function right away. 

---

*[src/app/frontend/petsetlist/petsetcard.html, line 21 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/791#-KJBSYA41VMycuqQ0raW:-KJBSYA5XHSxqs3AXKkh:2002120261) ([raw file](https://github.com/kubernetes/dashboard/blob/0f2cfc6cfb3f0e5936b0a00c2e4ac6101fe4393c/src/app/frontend/petsetlist/petsetcard.html#L21)):*
> ```HTML
>     <md-icon class="material-icons kd-error" ng-if="::$ctrl.hasWarnings()">
>       error
>       <md-tooltip md-direction="right">One or more pods have errors</md-tooltip>
> ```

Create MSG_s here?

---

*[src/app/frontend/petsetlist/petsetcardlist.html, line 20 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/791#-KJBSbFnE1T0rMkAstoU:-KJBSbFnE1T0rMkAstoV:2062154088) ([raw file](https://github.com/kubernetes/dashboard/blob/0f2cfc6cfb3f0e5936b0a00c2e4ac6101fe4393c/src/app/frontend/petsetlist/petsetcardlist.html#L20)):*
> ```HTML
>   <kd-resource-card-header-columns>
>     <kd-resource-card-header-column grow="2">
>       Name
> ```

Create MSG_s? Here? 

---

*[src/app/frontend/workloads/workloads.html, line 44 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/791#-KJBSlK-oZedomMl96N6:-KJBSlK-oZedomMl96N7:-1255085362) ([raw file](https://github.com/kubernetes/dashboard/blob/0f2cfc6cfb3f0e5936b0a00c2e4ac6101fe4393c/src/app/frontend/workloads/workloads.html#L44)):*
> ```HTML
>   <kd-title>
>     <a ui-sref="petset">
>       Pet Sets
> ```

MSG_ here? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/791#-:-KJBSuZyGlQMRMwhh0UM:105501476)*

**Comment by floreks** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/app/backend/resource/common/verber.go, line 50 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/791#-KJBRsVO9pl4i2IUp9DX:-KJF0mhot1xHsfBCpY3m:-570310886) ([raw file](https://github.com/kubernetes/dashboard/blob/0f2cfc6cfb3f0e5936b0a00c2e4ac6101fe4393c/src/app/backend/resource/common/verber.go#L50)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Can you extract client selection to a common function? I have a PR that will use the common function right away. 
</details>
hmm... I'd like to pass only `client.Interface` to verber and initialize clients based on that but it is not updated yet and doesn't support `AppsClient`. I'd have to use `client.Client` and it is harder to test.

In order to make common function we'd need `client.Client` and `ClientType` to return correct `RESTClient` interface. I can redesign it this way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/791)*

**Comment by bryk** [comment]
LGTM after you extract the common function. Please merge then :) 

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> A few comments and we're ready to go :) 
</details>


---

Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/petsetlist/petsetcard_component.js, line 32 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/791#-KJFkaUDgcEdA9MYGx87:-KJFkaUDgcEdA9MYGx88:-286398817) ([raw file](https://github.com/kubernetes/dashboard/blob/04463bb5acb3ae619c687d10abdb3538b64e6015/src/app/frontend/petsetlist/petsetcard_component.js#L32)):*
> ```JavaScript
> 
>     /**
>      * @export
> ```

Compact? 

---

*[src/app/frontend/petsetlist/petsetcardlist_component.js, line 26 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/791#-KJFkZENh40MvTjKhiTH:-KJFkZENh40MvTjKhiTI:-286398817) ([raw file](https://github.com/kubernetes/dashboard/blob/04463bb5acb3ae619c687d10abdb3538b64e6015/src/app/frontend/petsetlist/petsetcardlist_component.js#L26)):*
> ```JavaScript
>   constructor() {
>     /**
>      * @export
> ```

Compact? 

---

*[src/app/frontend/workloads/workloads_controller.js, line 29 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/791#-KJFkPlTdJXtNL6HFtUo:-KJFkPlTdJXtNL6HFtUp:-1040151562) ([raw file](https://github.com/kubernetes/dashboard/blob/04463bb5acb3ae619c687d10abdb3538b64e6015/src/app/frontend/workloads/workloads_controller.js#L29)):*
> ```JavaScript
>     /**
>      * @export
>      * {!Object}
> ```

No need for this {!Object}. But if you want it here, please compact this to one line :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/791#-:-KJFkdPnzwh5nVaFxuUY:1845391239)*

**Pull request merged**
