### PR TITLE
Fix RC's podstatus

### PR DESCRIPTION
**Pull request by riverzhang**
Fix RC's podstatus

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Why did you change Chinese and Japanese translations? You said, that you don't know Japanese.

**Comment by riverzhang** [comment]
I can modify the Chinese translation, Japanese unchanged.

**Comment by maciaszczykm** [comment]
@riverzhang I think you can leave translations are they are and modify only thing, that you actually fix.

**Comment by maciaszczykm** [comment]
image

It should be: `{{::$ctrl.replicationController.podInfo.current}} 作成済`

**Comment by riverzhang** [comment]
@maciaszczykm

**Pull request merged**
