### PR TITLE
Generic YAML editor for all resources

### PR DESCRIPTION
**Pull request by bryk**
To test this edit a pod in a list.

Missing things that will be done in next PR:
* make the menu and popup look pretty
* make json editor work on serve:prod (now images are missing)

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/807)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you review?

**Comment by edouardKaiser** [comment]
Is it gonna land in the next beta ? Would LOVE to test that.

**Comment by bryk** [comment]
> Is it gonna land in the next beta ? Would LOVE to test that.

Awesome. Expect it later today or on Monday :) I'll let you know.

**Comment by floreks** [comment]
Awesome feature. Just few comments about i18n. Overall :lgtm:

I've noticed that travis job for this PR takes about 2x longer than other jobs. We should investigate that before merging. It looks like it hangs for some time on backend tests.

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> > Is it gonna land in the next beta ? Would LOVE to test that.
> 
> 
> 
> Awesome. Expect it later today or on Monday :) I'll let you know. 
</details>


---

Reviewed 14 of 18 files at r1, 1 of 1 files at r2.
Review status: 14 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/common/components/resourcecard/resourcecardeditmenuitem.html, line 19 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/807#-KJL4_5I2qkodsPwdI7W:-KJL4_5I2qkodsPwdI7X:2049532904) ([raw file](https://github.com/kubernetes/dashboard/blob/a0cd030074557c96ba3e941ef0da7039ce4c6eac/src/app/frontend/common/components/resourcecard/resourcecardeditmenuitem.html#L19)):*
> ```HTML
> <md-menu-item>
>   <md-button ng-click="$ctrl.edit()">
>     Edit
> ```

i18n please :)

---

*[src/app/frontend/common/resource/deleteresource.html, line 19 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/807#-KJL56MN3kjE9ttY-qOW:-KJL56MN3kjE9ttY-qOX:-466874372) ([raw file](https://github.com/kubernetes/dashboard/blob/bc3c542f5e167bda8463a456e23dce8713ffb30e/src/app/frontend/common/resource/deleteresource.html#L19)):*
> ```HTML
> <md-dialog aria-label="Delete Replication Controller" layout="column">
>   <md-dialog-content layout-padding>
>     <h4 class="md-title">Delete a {{$ctrl.resourceKindName}}</h4>
> ```

i18n?

---

*[src/app/frontend/common/resource/editresource.html, line 25 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/807#-KJL58a7E-T1VSE1hXy9:-KJL58a7E-T1VSE1hXyA:-466874372) ([raw file](https://github.com/kubernetes/dashboard/blob/a0cd030074557c96ba3e941ef0da7039ce4c6eac/src/app/frontend/common/resource/editresource.html#L25)):*
> ```HTML
>     </div>
>     <md-dialog-actions>
>       <md-button class="md-primary kd-cancel-btn" ng-click="$ctrl.cancel()">Cancel</md-button>
> ```

i18n?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/807#-:-KJL6UKxL-tY0vRe3e-B:-657283057)*

**Comment by bryk** [comment]
> I've noticed that travis job for this PR takes about 2x longer than other jobs. We should investigate that before merging. It looks like it hangs for some time on backend tests.

It is frontend-copies task that takes long. I'll investigate. It is slow because we include new bower dep. 



---

Review status: 14 of 18 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/807#-:-KJL7mtIm-t88BIPIRur:-653215164)*

**Comment by bryk** [comment]
All done. Will merge soon. 

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> > I've noticed that travis job for this PR takes about 2x longer than other jobs. We should investigate that before merging. It looks like it hangs for some time on backend tests.
> 
> It is frontend-copies task that takes long. I'll investigate. It is slow because we include new bower dep. 
</details>


---

Review status: 12 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/common/components/resourcecard/resourcecardeditmenuitem.html, line 19 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/807#-KJL4_5I2qkodsPwdI7W:-KJLF9YECEcv6DvqslQ2:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/a0cd030074557c96ba3e941ef0da7039ce4c6eac/src/app/frontend/common/components/resourcecard/resourcecardeditmenuitem.html#L19)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> i18n please :)
</details>
Done.

---

*[src/app/frontend/common/resource/editresource.html, line 25 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/807#-KJL58a7E-T1VSE1hXy9:-KJLKJzJwi-qvG1HJ_ZF:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/a0cd030074557c96ba3e941ef0da7039ce4c6eac/src/app/frontend/common/resource/editresource.html#L25)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> i18n?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/807#-:-KJLMpyjbfXaWqZeaWc_:-542696821)*

**Comment by bryk** [comment]
Reviewed 12 of 18 files at r1, 15 of 15 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/807)*

**Pull request merged**
