### PR TITLE
Left nav progress version 2

### PR DESCRIPTION
**Pull request by bryk**
Based on: https://projects.invisionapp.com/share/3C8BDK9ZD

Updates from previous version:
* menu has spacing and styling as in spec
* menu items are buttons
* menu is scrollabe

Demo:
selection_112

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1141)

### CODE REVIEW

**Comment by bryk** [comment]
@digitalfishpond Can you review?

**Comment by digitalfishpond** [comment]
Couple questions and :lgtm: 

---

Reviewed 27 of 28 files at r1.
Review status: 27 of 28 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/chrome/nav/nav.html, line 22 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1141#-KPlCuLwoewdeKOaf3iY:-KPlCuLxf_PabAFFNhH2:b-qlcpnm) ([raw file](https://github.com/kubernetes/dashboard/blob/aa64adf339f0bd79db9151d2b37aa87cd7ff7065/src/app/frontend/chrome/nav/nav.html#L22)):*
> ```HTML
>     <kd-nav-item class="kd-nav-item" state="{{::$ctrl.states.namespace}}">Namespaces</kd-nav-item>
>     <kd-nav-item class="kd-nav-item" state="{{::$ctrl.states.node}}">Nodes</kd-nav-item>
>     <kd-nav-item class="kd-nav-item" state="{{::$ctrl.states.persistenVolume}}">Persistent Volumes</kd-nav-item>
> ```

missing 't' in 'persistenVolume'?

---

*[src/app/frontend/chrome/nav/nav.html, line 38 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1141#-KPlDGkHGu6JQ2B29YYC:-KPlDGkHGu6JQ2B29YYD:bz9lqv9) ([raw file](https://github.com/kubernetes/dashboard/blob/aa64adf339f0bd79db9151d2b37aa87cd7ff7065/src/app/frontend/chrome/nav/nav.html#L38)):*
> ```HTML
>   </div>
>   <div class="kd-nav-group">
>     <kd-nav-item class="kd-nav-group-item" state="{{::$ctrl.states.servicediscovery}}">Services and discovery</kd-nav-item>
> ```

camelCase servicediscovery?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1141#-:-KPlGirTqU5GFvSYUJID:brm4fy5)*

**Comment by floreks** [comment]
Looks nice. LGTM

I know it is not part of nav menu but tab bar on details page needs some work also :)

**Comment by bryk** [comment]
Thanks. Addressed comments and will merge soon :) 

---

Review status: 27 of 28 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/chrome/nav/nav.html, line 22 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1141#-KPlCuLwoewdeKOaf3iY:-KPqNoJNo_qOJ9bVWDgh:b-896fix) ([raw file](https://github.com/kubernetes/dashboard/blob/aa64adf339f0bd79db9151d2b37aa87cd7ff7065/src/app/frontend/chrome/nav/nav.html#L22)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> missing 't' in 'persistenVolume'?
</details>
Done.

---

*[src/app/frontend/chrome/nav/nav.html, line 38 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1141#-KPlDGkHGu6JQ2B29YYC:-KPqO-tbkXUOQYw-k0Y_:b-896fix) ([raw file](https://github.com/kubernetes/dashboard/blob/aa64adf339f0bd79db9151d2b37aa87cd7ff7065/src/app/frontend/chrome/nav/nav.html#L38)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> camelCase servicediscovery?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1141#-:-KPqOavFjZyWTsHDoWBk:baed3ve)*

**Comment by bryk** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1141)*

**Comment by bryk** [comment]
Reviewed 1 of 28 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1141)*

**Pull request merged**
