### PR TITLE
Resource card framework skeleton

### PR DESCRIPTION
**Pull request by bryk**
This is initial PR on this. It uses quite a few interesting new
techniques, so I want throughful feedback.

1. This uses angular 1.5 Components and multiple transclusion
2. I propose here the way of writing Components. Basically you create
foo_component.js file and add component config and controller there.
3. See multiple transclusion - it is awesome

Re #630 

Sample:
selection_060

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/631)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm @floreks @digitalfishpond Can you review and take a look?

**Comment by bryk** [comment]
@maciaszczykm @digitalfishpond Ping?

**Comment by digitalfishpond** [comment]
currently learning more about multiple transclusion to be in a better position to review. Will review today though.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/631#-:-KF8UEFKs7hfDNEHFsYV:-1564733246)*

**Comment by digitalfishpond** [comment]
*[src/app/frontend/common/components/resourcecard/resourcecard.html, line 25 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/631#-KF8_XwLyczuha5V6mk2:-KF8_XwNjhfmYG3jZ8KJ:-1100633070) ([raw file](https://github.com/kubernetes/dashboard/blob/0dad916fc522e8f77c655ef4577dcd8f37b9a0d4/src/app/frontend/common/components/resourcecard/resourcecard.html#L25)):*
doesn't the "?" in front of the value ?ngTranscludeFooter in the directive make the ng-if statement here redundant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/631)*

**Comment by digitalfishpond** [comment]
Other than the one minor comment, I think this is a really nice implementation, very scalable, very easy to use. @maciaszczykm, what do you think?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/631#-:-KF8jntTjfugkSmWQs3I:-1604515945)*

**Comment by bryk** [comment]
Will wait a while for @maciaszczykm and then submit. This is a skeleton. Can be changed later. 

---

Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/common/components/resourcecard/resourcecard.html, line 25 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/631#-KF8_XwLyczuha5V6mk2:-KF9jGdhbb56HDt55XZ7:-2000121832) ([raw file](https://github.com/kubernetes/dashboard/blob/0dad916fc522e8f77c655ef4577dcd8f37b9a0d4/src/app/frontend/common/components/resourcecard/resourcecard.html#L25)):*
You're correct. Removed the ng-if. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/631#-:-KF9jUqw8_61CXBjnGv0:540870442)*

**Comment by maciaszczykm** [comment]
Reviewed and tested. 

:lgtm:

---

Reviewed 13 of 13 files at r1, 3 of 10 files at r2.
Review status: 9 of 16 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/631#-:-KF9qe7sylW7YG6tPk_B:-1472964452)*

**Comment by maciaszczykm** [comment]
Reviewed 7 of 10 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/631)*

**Comment by bryk** [comment]
Reviewed 6 of 13 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/631)*

**Pull request merged**
