### PR TITLE
Fix issue where devs couldn't run serve:prod

### PR DESCRIPTION
**Pull request by bryk**
This was caused by the wait-for-cluster rule which never finished.
I've moved it to local-up-cluster. Everything works now as expected.

### CODE REVIEW

**Comment by bryk** [comment]
@zreigz Can you review?

**Comment by zreigz** [comment]
yes

**Comment by zreigz** [comment]
Looks good for me. Just some problem on Travis

**Comment by bryk** [comment]
Yeah, I'll try to fix the travis issue soon.

**Pull request merged**
