### PR TITLE
Inline edit secret enhancements

### PR DESCRIPTION
**Pull request by greggbjensen**
- Completed toggling between visible read-only and edit for inline secret.
- Changed inline edit button for secret to blue with border.
- Added auto-size textarea for multi-line and input for single line secret editing.
- Added enableEdit flag to HiddenPropertyComponent.

image

image

### CODE REVIEW

**Comment by greggbjensen** [comment]
@floreks this is updates for:

**Implemented inline editing for data entries on Secrets page.** #5040

**Comment by greggbjensen** [comment]
It looks like the code coverage is flagging a file I didn't change.  Not sure if I need to do anything about this.  I did not see any tests for secret components yet.

**Comment by floreks** [comment]
Looks better. Thanks! I'll check tomorrow or the day after that. Don't worry about the coverage. Codecov often calculates coverage differently on every try. Not sure why it is not consistent.

**Comment by floreks** [comment]
I have made couple of minor changes to speed up the process. This is very useful! @maciaszczykm can you test it?

**Comment by maciaszczykm** [comment]
Very nice feature :)

/lgtm

**Comment by greggbjensen** [comment]
Thanks @floreks.

**Pull request merged**
