### PR TITLE
[WIP] Namespace separation in RC list view

### PR DESCRIPTION
**Pull request by bryk**
Do not review - for discussion only

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/487)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks @cheld @f-higashi I did a demo on how RC list view can be separated by namespaces.
Can you look at it? To do this, all you need is:
```
git checkout -b bryk-namespaces-show master
git pull https://github.com/bryk/dashboard.git namespaces-show
```

**Comment by bryk** [comment]
I have mixed feelings about this and I'm leaning towards namespace selector.

**Comment by floreks** [comment]
I've just briefly checked it and I'm starting to think that selector is a better way to go. Clearly this is not so user friendly when there are many apps deployed and can quickly cause performance issues.

**Comment by cheld** [comment]
In general I like it. Visually, it could be improved I guess - but, I am not sure what.

**Comment by cheld** [comment]
If you prefer the selector, then I would suggest to keep the implementation and add an all option

**Comment by f-higashi** [comment]
I like it.
And I would like RC list page of each namespaces and to open deploy RC dialog which is set same namespace as default from this page.

**Pull request closed without merging**
