### PR TITLE
Add backend coverage reports

### LINKED ISSUE #357: Setup codecov for backend code
At in title. Setup codecov coverage for backend code. We already have this for frontend.

CC @floreks ?

### PR DESCRIPTION
**Pull request by maciaszczykm**
Running backend tests now will produce also coverage report:

```
$ gulp backend-test
[17:14:36] Requiring external module babel-register
[17:14:36] Working directory changed to ~/workspace/go/src/github.com/kubernetes/dashboard
[17:14:38] Using gulpfile ~/workspace/go/src/github.com/kubernetes/dashboard/gulpfile.babel.js
[17:14:38] Starting 'clean-packaged-backend-source'...
[17:14:38] Finished 'clean-packaged-backend-source' after 41 ms
[17:14:38] Starting 'package-backend-source'...
[17:14:38] Finished 'package-backend-source' after 96 ms
[17:14:38] Starting 'link-vendor'...
[17:14:38] Finished 'link-vendor' after 193 μs
[17:14:38] Starting 'package-backend'...
[17:14:38] Finished 'package-backend' after 17 μs
[17:14:38] Starting 'backend-test'...
?   	github.com/kubernetes/dashboard/src/app/backend	[no test files]
?   	github.com/kubernetes/dashboard/src/app/backend/client	[no test files]
ok  	github.com/kubernetes/dashboard/src/app/backend/handler	0.046s	coverage: 3.3% of statements
?   	github.com/kubernetes/dashboard/src/app/backend/resource/admin	[no test files]
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/common	0.046s	coverage: 32.0% of statements
?   	github.com/kubernetes/dashboard/src/app/backend/resource/config	[no test files]
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/configmap	0.045s	coverage: 43.8% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/container	0.044s	coverage: 10.3% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/daemonset	0.042s	coverage: 30.4% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/daemonset/detail	0.043s	coverage: 27.6% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/daemonset/list	0.060s	coverage: 46.4% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/dataselect	0.046s	coverage: 46.7% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/deployment	0.064s	coverage: 72.8% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/event	0.047s	coverage: 73.0% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/horizontalpodautoscaler	0.062s	coverage: 88.9% of statements
?   	github.com/kubernetes/dashboard/src/app/backend/resource/ingress	[no test files]
?   	github.com/kubernetes/dashboard/src/app/backend/resource/job	[no test files]
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/job/detail	0.092s	coverage: 78.9% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/job/list	0.043s	coverage: 82.9% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/limitrange	0.040s	coverage: 100.0% of statements
?   	github.com/kubernetes/dashboard/src/app/backend/resource/logs	[no test files]
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/metric	0.654s	coverage: 87.4% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/namespace	0.043s	coverage: 23.8% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/node	0.045s	coverage: 40.4% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/persistentvolume	0.042s	coverage: 52.6% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/persistentvolumeclaim	0.043s	coverage: 45.5% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/pod	0.056s	coverage: 33.0% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/replicaset	0.045s	coverage: 6.7% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/replicaset/detail	0.048s	coverage: 78.1% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/replicaset/list	0.043s	coverage: 80.6% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/replicationcontroller	0.046s	coverage: 35.7% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/replicationcontroller/detail	0.043s	coverage: 9.5% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/replicationcontroller/list	0.042s	coverage: 50.0% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/resourcequota	0.125s	coverage: 100.0% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/secret	0.111s	coverage: 35.7% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/service	0.042s	coverage: 80.0% of statements
?   	github.com/kubernetes/dashboard/src/app/backend/resource/servicesanddiscovery	[no test files]
?   	github.com/kubernetes/dashboard/src/app/backend/resource/statefulset	[no test files]
?   	github.com/kubernetes/dashboard/src/app/backend/resource/statefulset/detail	[no test files]
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/statefulset/list	0.045s	coverage: 81.2% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/storageclass	0.048s	coverage: 62.5% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/thirdpartyresource	0.110s	coverage: 21.9% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/resource/workload	0.059s	coverage: 85.5% of statements
ok  	github.com/kubernetes/dashboard/src/app/backend/validation	0.046s	coverage: 90.6% of statements

[17:16:05] Finished 'backend-test' after 1.43 min
```

Closes #357.

### CODE REVIEW

**Comment by maciaszczykm** [comment]
It's still WIP, I'll add pushing report to Codecov soon.

**Comment by maciaszczykm** [comment]
Run times:
https://travis-ci.org/kubernetes/dashboard/builds/210907723 ~16m
https://travis-ci.org/kubernetes/dashboard/builds/210926890 ~17m
https://travis-ci.org/kubernetes/dashboard/builds/210967313 >50m

It's probably connected to Travis CI traffic.

**Comment by rf232** [comment]
Looking at the CI logs it looks like the test hangs, after slightly under 15 minutes we get to https://travis-ci.org/kubernetes/dashboard/builds/210967313#L561, my assumption is that the tests are run quickly (also looking at the timings) but we don't do anything after that it seems for 35 minutes

**Comment by maciaszczykm** [comment]
@rf232 It was okay (<17m) until we tried to use pipes to pass result asynchronously (don't know why...). We need to do it, because on CI backend tests with coverage could take >10m and then Travis will exit.

@floreks is checking multi-job build right now, it could speed up build 2 times.

**Pull request merged**
