### PR TITLE
Fix a bug where recreate deployments would fail to display

### PR DESCRIPTION
**Pull request by bryk**
Fixes: #881

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/886)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you review?

**Comment by floreks** [comment]
Maybe our deployment structure should be similar to what k8s offers?

https://github.com/kubernetes/dashboard/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apis/extensions/types.go#L154

It has `DeploymentStrategy` which can be either `Recreate` or `RollingUpdate`. It's more complex than ours and right now we don't support `Recreate` type. What do you think?

**Comment by bryk** [comment]
Yes. AFAIU it is currently very similar to what core deployments have. Recreate deployments do not have additional info. Am I correct?

**Comment by floreks** [comment]
Yes, `Recreate` is just strategy type without additional info. I saw some data that is not taken but it is also not displayed using `kubectl describe` (Paused, RollbackConfig). For now it can stay as it is. I'm not aware how important this additional information are.

**Comment by floreks** [comment]
:lgtm:

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Yes, `Recreate` is just strategy type without additional info. I saw some data that is not taken but it is also not displayed using `kubectl describe` (Paused, RollbackConfig). For now it can stay as it is. I'm not aware how important this additional information are.
</details>


---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/886#-:-KK85DrkbVvYyI9J97eb:1417088721)*

**Pull request merged**
