### PR TITLE
update helm installation commands

### PR DESCRIPTION
**Pull request by dallasmarlow**

### CODE REVIEW

**Comment by desaintmartin** [comment]
Thanks! Could you bump chart version and signoff your commit?
/assign

**Comment by maciaszczykm** [comment]
We need you to sign CLA to merge this. You can find manual here: https://github.com/kubernetes/dashboard/pull/5695#issuecomment-733086383

**Comment by almo-ltoeroek** [comment]
FYI https://kubernetes.github.io/dashboard/ returns 404

**Review by thomastvedt — APPROVED** [review]

**Comment by maciaszczykm** [comment]
@dallasmarlow Please reopen after signing the CLA.

**Pull request closed without merging**
