### PR TITLE
Display metrics usage and connect to in-cluster heapster

### PR DESCRIPTION
**Pull request by bryk**
Now the data is correctly fetched from heapster if you run inside the cluster. 

TODO that is left: format CPU usage. Now raw number is displayed.

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm Can you review?

**Comment by maciaszczykm** [comment]
@bryk Yes, of course.

**Comment by maciaszczykm** [comment]
I've some troubles with heapster, because it seems to be not starting with `gulp local-up-cluster` anymore. Do you know something about it?

**Comment by bryk** [comment]
It does work for me. You have to wait a while, however. To heapster to go up. 

If this does not help, do you have any stacktrace? Try accessing http://localhost:8082

**Comment by maciaszczykm** [comment]
> It does work for me. You have to wait a while, however. To heapster to go up.

>If this does not help, do you have any stacktrace? Try accessing http://localhost:8082

I've removed my comment, because it has already started.

**Comment by maciaszczykm** [comment]
image

LGTM

**Pull request merged**
