### PR TITLE
Add more ESLint rules for JavaScript linting

### PR DESCRIPTION
**Pull request by bryk**
With this change I've gone through all ESLint rules at:
http://eslint.org/docs/rules/ and added all of them that I feel make
sense to the project.

This will allow us to focus on business logic of our code, rather than
on style discussions, which are now better guarded thanks to ESLint and
clang-format.

On the final note: it does not matter what concrete lint rules are
enforced (e.g., semicolons or nor). The important part is that they are
enforced by a tool and we do not spend time dicussing about them.

Addresses: #66

### CODE REVIEW

**Comment by bryk** [comment]
@SebastianM @cheld Can you take a look?

**Comment by cheld** [comment]
LGTM. I suggest to merge in order to reduce conflicts.

@taimir 

You spent a bit of time collecting common review comments and converting to lint rules. Can you have a look?

BTW: I think the most common problem not covered is alphabetical ordering. However, no rule exists for that.

**Comment by cheld** [comment]
As far as I remember, clean code principles recommend no empty lines inside methods and 2 empty lines between methods - code is easier to read.

**Comment by bryk** [comment]
> As far as I remember, clean code principles recommend no empty lines inside methods and 2 empty lines between methods - code is easier to read.

Yes, but no ESLint nor clang-format can enforce such formatting. On the other hand, one newline can be enforced by ESLint, because people tend to separate code blocks that need to be separated by at least one newline.

I could include gjslint linter to enforce newlines between code blocks, but this would be 3rd JS style tool we have, which becomes dangerous. On the other hand, 1 newline between code blocks is what golang has, so frontend would be more aligned with the backend.

**Comment by bryk** [comment]
> BTW: I think the most common problem not covered is alphabetical ordering. However, no rule exists for that.

Yes, I know this is an unsolved problem.

**Pull request merged**
