### PR TITLE
Angular migration service detail

### PR DESCRIPTION
**Pull request by yinhaijiao**
@maciaszczykm Hi, I switched the commit to ng-migration branch.
#3102

### CODE REVIEW

**Comment by yinhaijiao** [comment]
@maciaszczykm 
Hi, Why does CI failed? I did not modify those go files.

**Comment by maciaszczykm** [comment]
@pengx17 Please rebase to make CI green.

**Comment by pengx17** [comment]
@maciaszczykm you pinged the wrong person 😈

**Comment by maciaszczykm** [comment]
@pengx17 Sorry for that! :)

**Pull request merged**
