### PR TITLE
Limit ranges frontend

### PR DESCRIPTION
**Pull request by batikanu**
Implementation of Limit ranges frontend. 
It includes also small fixes in backend.

### CODE REVIEW

**Comment by floreks** [comment]
'Limit Ranges' section is missing on admin page. Please add.

**Comment by batikanu** [comment]
'Limit Ranges' section is added on admin page. PTAL

**Comment by batikanu** [comment]
@bryk I think it should be like resource quotas only in namespace details. I will move limit range detail to namespace detail and post some screen shots.

**Comment by batikanu** [comment]
test comment

**Comment by bryk** [comment]
@batikanu Awesome, thanks!

**Pull request closed without merging**
