### PR TITLE
Add Job resource backend

### PR DESCRIPTION
**Pull request by maciaszczykm**
Added Job resource support in the backend.

Connected to #788.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/792)

### CODE REVIEW

**Comment by bryk** [comment]
Looks nice. Add more tests and we're ready to go 

<details><summary><i>Previously, codecov-io wrote…</i></summary>
> ## [Current coverage][cc-pull] is **94.94%**
> > Merging [#792][cc-pull] into [master][cc-base-branch] will increase coverage by **0.39%**
> 
> 1. File `...ereader_directive.js` (not in diff) was modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/df91ceb57dac311028cb7d79a706bfe8adfc6569/changes?src=pr#7372632F6170702F66726F6E74656E642F6465706C6F792F66696C657265616465725F6469726563746976652E6A73) 
>   - Misses `-6` 
>   - Partials `0` 
>   - Hits `+6`
> 
> ```diff
> @@             master       #792   diff @@
> ==========================================
>   Files           187        187          
>   Lines          1462       1462          
>   Methods           0          0          
>   Messages          0          0          
>   Branches          0          0          
> ==========================================
> + Hits           1382       1388     +6   
> + Misses           80         74     -6   
>   Partials          0          0          
> ```
> 
> > Powered by [Codecov](https://codecov.io?src=pr). Last updated by [25dac01...df91ceb][cc-compare]
> [cc-base-branch]: https://codecov.io/gh/kubernetes/dashboard/branch/master?src=pr
> [cc-compare]: https://codecov.io/gh/kubernetes/dashboard/compare/25dac017c001b170a4facc67e8b206971e5070e4...df91ceb57dac311028cb7d79a706bfe8adfc6569
> [cc-pull]: https://codecov.io/gh/kubernetes/dashboard/pull/792?src=pr
</details>


---

Reviewed 2 of 6 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/backend/resource/common/types.go, line 110 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/792#-KJBO2x2aTJYPg2IOXSt:-KJBO2x3ZqOKIopc6Poi:-1812225055) ([raw file](https://github.com/kubernetes/dashboard/blob/d3204200b7ee79f4966055562ca6bc4dff3dbc29/src/app/backend/resource/common/types.go#L110)):*
> ```Go
> 	Extension bool
> }{
> 	ResourceKindService:               {"services", false},
> ```

@floreks We need PetSets here, remember :) 

---

*[src/app/backend/resource/common/types.go, line 117 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/792#-KJBOeNFNn-ViHk2DaCY:-KJBOeNFNn-ViHk2DaCZ:507771625) ([raw file](https://github.com/kubernetes/dashboard/blob/d3204200b7ee79f4966055562ca6bc4dff3dbc29/src/app/backend/resource/common/types.go#L117)):*
> ```Go
> 	ResourceKindReplicaSet:            {"replicasets", true},
> 	ResourceKindDaemonSet:             {"daemonsets", false},
> 	ResourceKindJob:                   {"job", false},
> ```

Should this be `true`? I think so. 

---

*[src/app/backend/resource/job/joblist.go, line 35 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/792#-KJBOrroMC4CeDMf9DAU:-KJBOrroMC4CeDMf9DAV:1022218508) ([raw file](https://github.com/kubernetes/dashboard/blob/d3204200b7ee79f4966055562ca6bc4dff3dbc29/src/app/backend/resource/job/joblist.go#L35)):*
> ```Go
> // Job is a presentation layer view of Kubernetes Job resource. This means
> // it is Job plus additional augumented data we can get from other sources
> // (like services that target the same pods).
> ```

(like services that target the same pods). <- this is probably to remove :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/792#-:-KJBPEenCx03mIiEFUFo:782022200)*

**Comment by floreks** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/backend/resource/common/types.go, line 117 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/792#-KJBOeNFNn-ViHk2DaCY:-KJF9q3aMP0n68Rmq9Pn:-691945928) ([raw file](https://github.com/kubernetes/dashboard/blob/d3204200b7ee79f4966055562ca6bc4dff3dbc29/src/app/backend/resource/common/types.go#L117)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Should this be `true`? I think so. 
</details>
Also it should be `jobs` i think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/792)*

**Comment by maciaszczykm** [comment]
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/backend/resource/common/types.go, line 117 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/792#-KJBOeNFNn-ViHk2DaCY:-KJFVQQ4ixyzgzX6KUpy:1197659276) ([raw file](https://github.com/kubernetes/dashboard/blob/d3204200b7ee79f4966055562ca6bc4dff3dbc29/src/app/backend/resource/common/types.go#L117)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Also it should be `jobs` i think.
</details>
Updated to `"jobs", true`. Still I think extension client won't work, because jobs use batch client.

---

*[src/app/backend/resource/job/joblist.go, line 35 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/792#-KJBOrroMC4CeDMf9DAU:-KJFVcEq5eKmG7C0AdSB:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/d3204200b7ee79f4966055562ca6bc4dff3dbc29/src/app/backend/resource/job/joblist.go#L35)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> (like services that target the same pods). <- this is probably to remove :) 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/792)*

**Comment by floreks** [comment]
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/backend/resource/common/types.go, line 117 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/792#-KJBOeNFNn-ViHk2DaCY:-KJFW6L89FFRaeClHtLM:-2080640753) ([raw file](https://github.com/kubernetes/dashboard/blob/d3204200b7ee79f4966055562ca6bc4dff3dbc29/src/app/backend/resource/common/types.go#L117)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> Updated to `"jobs", true`. Still I think extension client won't work, because jobs use batch client.
</details>
Yep, this uses batch client and needs new design which I've introduced in my PetSet PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/792)*

**Comment by bryk** [comment]
Reviewed 1 of 2 files at r3.
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/backend/resource/common/types.go, line 117 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/792#-KJBOeNFNn-ViHk2DaCY:-KJFnnayXQWvLuyiVhiQ:1332726443) ([raw file](https://github.com/kubernetes/dashboard/blob/d3204200b7ee79f4966055562ca6bc4dff3dbc29/src/app/backend/resource/common/types.go#L117)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Yep, this uses batch client and needs new design which I've introduced in my PetSet PR
</details>
Can you @floreks merge and then rebase this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/792)*

**Comment by floreks** [comment]
We established with @maciaszczykm that I will merge first and then he can use new code in his PR.

**Comment by bryk** [comment]
Perfect. Fix travis and merge

**Comment by maciaszczykm** [comment]
Added tests. Fixed JS & Go files formatting (it seems people still forget about it).

**Pull request merged**
