### PR TITLE
Added detailed steps for installing requirements

### PR DESCRIPTION
**Pull request by Lukenickerson**
I took these notes while running through the installation process myself, and ended up with a working dashboard. Please correct the doc if I got anything wrong or if the steps can be improved.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/907)

### CODE REVIEW

**Comment by Lukenickerson** [comment]
My company has a CLA setup now under **Apprenda, Inc.**.

**Comment by bryk** [comment]
@floreks @maciaszczykm Can you guide @Lukenickerson through the process of submitting and reviewing PRs? Luke is new here and would like to contribute regularly :)

**Comment by floreks** [comment]
Of course we'll help him tomorrow morning :)

**Comment by preillyme** [comment]
The CLA is signed for Apprenda, Inc. and on-file with the Open Source Programs Office | Google Developers.

**Comment by floreks** [comment]
Most common issue with bot is that `git config user.mail` is not on the signed Personal/Company CLA list. Make sure that mail you are committing with is on that list and then try to poke bot again with `I signed it!` message.

**Comment by Lukenickerson** [comment]
I switched the email in `git config user.email`, but I don't think that impacts past commits, so I may need to make a new commit. I also signed the CLA with my personal email in case that does the trick for this one.

@googlebot I signed it!

**Comment by maciaszczykm** [comment]
Since your CLAs look good it's time for review :) I can do it tommorow.

One remark at this point - we basically tend to squash our commits if they are similar. Generally we have one commit per pull request, but not always.

**Comment by floreks** [comment]
These commit messages are meaningful, so I believe they can stay. During merge they will be squashed automatically into 1 commit anyway, just messages will be combined into 1.

**Comment by preillyme** [comment]
LGTM :+1:

**Comment by floreks** [comment]
One comment. Other than that :lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/devel/requirements-installation.md, line 182 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/907#-KKS9wYuygMjPDmbY0sz:-KKS9wYuygMjPDmbY0t-:820276129) ([raw file](https://github.com/kubernetes/dashboard/blob/e32ed3ecb39cbf3bc29d062880b97bcaf934e5eb/docs/devel/requirements-installation.md#L182)):*
> ```Markdown
> $ gulp local-up-cluster
> ```
> If you need to stop the cluster you can run `$ docker kill $(docker ps -aq)`
> ```

I'd be careful with `stop the cluster` as it actually kills all docker containers not only cluster related. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/907#-:-KKSBCAGBAx19EP0683a:1308796392)*

**Comment by maciaszczykm** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/devel/requirements-installation.md, line 182 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/907#-KKS9wYuygMjPDmbY0sz:-KKSBMZQ9pydGpiv2-7v:-822419479) ([raw file](https://github.com/kubernetes/dashboard/blob/e32ed3ecb39cbf3bc29d062880b97bcaf934e5eb/docs/devel/requirements-installation.md#L182)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> I'd be careful with `stop the cluster` as it actually kills all docker containers not only cluster related. 
</details>
Agree with @floreks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/907)*

**Comment by bryk** [comment]
:lgtm: From me. @floreks @maciaszczykm Please merge when done with review :) 

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/907#-:-KKgyu9jbSJZ9JtpD_nW:1712023170)*

**Comment by floreks** [comment]
Just add some note to part of text I've commented. Just inform user what may happen if he uses this while his own containers are working.

Also squash commits to keep only meaningful messages and we can merge. :)

**Comment by bryk** [comment]
Should we merge this? And maybe fix problems later?

**Comment by maciaszczykm** [comment]
Okay.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/907#-:-KKreMHUmdOXt7AjPxHU:-489118315)*

**Pull request merged**
