### PR TITLE
Fix deployment detail not loading and showing wrong old replica sets

### LINKED ISSUE #812: View deployment details: runtime error: invalid memory address or nil pointer dereference
#### Issue details

I just updated my dashboard with the latest beta2. And I'm trying to visualize the details of a deployment.

##### Environment
```
Dashboard version: v1.1.0-beta2
Kubernetes version: v1.2.4
Operating system: CoreOS
```

##### Steps to reproduce
Click on a deployment resource.
For information, my deployment is pretty simple and looks like this:

```
apiVersion: v1
kind: Service
metadata:
  name: myimage-svc
  labels:
    app: myimage
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9000
  selector:
    app: myimage
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myimage-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myimage
    spec:
      containers:
      - name: myimage
        image: repository/myimage   
        imagePullPolicy: Always
        env:
        - name: PLAY_CRYPTO_SECRET
          value: "XXXXXXXXXXXX"
        ports:
        - containerPort: 9000
          protocol: TCP
      imagePullSecrets:
      - name: dockerhub
```
##### Stack trace
```
[restful] 2016/06/03 13:59:53 log.go:26: [restful] recover from panic situation: - runtime error: invalid memory address or nil pointer dereference
    /usr/local/go/src/runtime/asm_amd64.s:472
    /usr/local/go/src/runtime/panic.go:426
    /usr/local/go/src/runtime/panic.go:45
    /usr/local/go/src/runtime/sigpanic_unix.go:24
    /dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/resource/deployment/deploymentdetail.go:117
    /dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/resource/deployment/deploymentdetail.go:110
    /dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/handler/apihandler.go:530
    /dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/handler/apihandler.go:204
    /dashboard/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:244
    /dashboard/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21
    /dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/handler/apihandler.go:66
    /dashboard/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19
    /dashboard/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:246
    /dashboard/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:95
    /usr/local/go/src/net/http/server.go:1618
    /usr/local/go/src/net/http/server.go:1910
    /dashboard/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:264
    <autogenerated>:32
    /usr/local/go/src/net/http/server.go:1910
    /usr/local/go/src/net/http/server.go:2081
    /usr/local/go/src/net/http/server.go:1472
    /usr/local/go/src/runtime/asm_amd64.s:1998
```

### LINKED ISSUE #833: Deployment details displaying wrong replica sets
zrzut ekranu z 2016-06-06 13-43-26

### PR DESCRIPTION
**Pull request by floreks**
This closes #833 and closes #812.

Replica sets and pods were not filtered by deployment selector. Now we are searching for old/new replica sets as it is done in k8s.

Main issue was caused by null pointer when new replica set was not created.

Update: Changed the look a bit and moved related replica sets to lists
zrzut ekranu z 2016-06-06 16-15-42

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/835)

### CODE REVIEW

**Comment by edouardKaiser** [comment]
Could we get a quick beta3 release after this fix ?

**Comment by bryk** [comment]
@edouardKaiser Yeah, why not. How about tomorrow?

**Comment by edouardKaiser** [comment]
Awesome. It will really make my life easier.

**Comment by bryk** [comment]
:lgtm:

<details><summary><i>Previously, edouardKaiser wrote…</i></summary>
> Awesome. It will really make my life easier.
</details>


---

Reviewed 2 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/835#-:-KJdd0rdysKYKu3r0TKp:1417088721)*

**Comment by edouardKaiser** [comment]
Any chance of a beta3 today? :)

**Comment by bryk** [comment]
We decided to move it to tomorrow. We'll have pagination and new look and feel by then.

**Comment by edouardKaiser** [comment]
No worries, thanks for the information !

**Pull request merged**
