### PR TITLE
Update OWNERS_ALIASES

### PR DESCRIPTION
**Pull request by shu-mutou**
Move jeefy from dashboard-maintainers to emeritus like follow https://github.com/kubernetes/kubernetes/blob/master/OWNERS_ALIASES#L147-L148

### CODE REVIEW

**Comment by shu-mutou** [comment]
@maciaszczykm @floreks Should we add historical emeritus maintainers?

**Comment by maciaszczykm** [comment]
@shu-mutou As you want. I think it's also somewhere in other Kubernetes repo.

**Comment by shu-mutou** [comment]
I want to respect also past maintainers, so I'll check the past OWNERS file and add them.

**Comment by shu-mutou** [comment]
@maciaszczykm Done. PTAL. Thanks!!

**Comment by maciaszczykm** [comment]
Great.

/lgtm

**Pull request merged**
