### PR TITLE
Refactor go code and fix link to go report card

### PR DESCRIPTION
**Pull request by maciaszczykm**
Continuation of #500. Didn't resolve issues like:

```
Line 136: warning: can probably use "var result []Event" instead (golint)
```

Because simple change of declaration break tests. 

Moreover, issues like:

```
Line 76: warning: struct field CpuRequirement should be CPURequirement (golint)
```

Weren't fixed, because it's probably too much changes.

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/504)

### CODE REVIEW

**Comment by floreks** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/backend/deploy.go, line 32 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/504#-KCLEUkgnv9-vlqzKcaI:-KCLEUkgnv9-vlqzKcaJ:-1218858372) ([raw file](https://github.com/kubernetes/dashboard/blob/a61e8afa8ef99d3493dd71b4fb654574c3a2aced/src/app/backend/deploy.go#L32)):*
for the/a description?

---

*[src/app/backend/heapsterclient.go, line 32 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/504#-KCLFGnu_O2nJgnbWziJ:-KCLFGnu_O2nJgnbWziK:1483492570) ([raw file](https://github.com/kubernetes/dashboard/blob/a61e8afa8ef99d3493dd71b4fb654574c3a2aced/src/app/backend/heapsterclient.go#L32)):*
InClusterHeapsterClient is **an** in-cluster

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/504)*

**Comment by floreks** [comment]
Small comments. Rest :lgtm: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/504#-:-KCLGVxTcf5vis2qT6Xp:-1682489236)*

**Comment by maciaszczykm** [comment]
PTAL

**Comment by floreks** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/504#-:-KCLHLaA9alKeTLsMJgo:980077423)*

**Comment by maciaszczykm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/backend/deploy.go, line 32 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/504#-KCLEUkgnv9-vlqzKcaI:-KCLHnkvboG09RJkHH_H:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/a61e8afa8ef99d3493dd71b4fb654574c3a2aced/src/app/backend/deploy.go#L32)):*
Done.

---

*[src/app/backend/heapsterclient.go, line 32 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/504#-KCLFGnu_O2nJgnbWziJ:-KCLHoqpQDrEZgq1UK17:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/a61e8afa8ef99d3493dd71b4fb654574c3a2aced/src/app/backend/heapsterclient.go#L32)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/504)*

**Pull request merged**
