### PR TITLE
Add logs page to ng-migration branch

### PR DESCRIPTION
**Pull request by yinhaijiao**

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@yinhaijiao Can you solve conflicts?

**Comment by maciaszczykm** [comment]
It's caused by not formatted files.

**Comment by yinhaijiao** [comment]
@maciaszczykm I mean, the unformatted files have been revised(ref: #3156) before, but now it has been changed back(ref: #3159 ).

**Comment by maciaszczykm** [comment]
Ah, okay then.

**Comment by maciaszczykm** [comment]
Almost everything seems to work fine, only few minor fixes needed but we can do them later. Thanks a lot! :)

/lgtm

**Pull request merged**
