### PR TITLE
Make middle ellipsis directive responsive to window changes

### LINKED ISSUE #625: ellipsis on long name not applied on window re-size
##### Issue Description
on details page, when starting with a small-sized window, when increasing the window size to the point of triggering the full-sized UI, the ellipsis is not applied to the app name.

##### Environment
Dashboard version: 1.0.1
Kubernetes version: v1.2.0
Operating system: Ubuntu 15.10
Node.js version: v5.9.1
Go version: 1.5.3
Browser: chrome, firefox, IE

##### Steps to reproduce
1. deploy a new application with a very long app name via yaml or json
2. make browser window small enough to trigger the small screen layout
3. click on the new application to go to its details page
kubernetes dashboard - google chrome_003

4. maximise the screen
kubernetes dashboard - google chrome_004

##### Observed result
the app name in the title and in the details section do not have the ellipsis applied
the screen has to be reloaded in order to trigger the ellipsis.
once it has been triggered once, it scales gracefully when screen is resized.

##### Expected result
ellipsis should be applied to name on re-size, even when starting from a small window view.

### PR DESCRIPTION
**Pull request by bryk**
Now this directive works on window resize and on all pages (RC details
in particular)

Fixes #625

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/644)

### CODE REVIEW

**Comment by bryk** [comment]
@digitalfishpond Can you review?

**Comment by digitalfishpond** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetail.html, line 44 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/644#-KFDV2EKpgJzz4VgE9K-:-KFDV2EKpgJzz4VgE9K0:-1111072107) ([raw file](https://github.com/kubernetes/dashboard/blob/682f84cf73a522192005e18fbc44986cace8117a/src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetail.html#L44)):*
the elipsis is not applied to the name on a reduced-sized screen causing the table below it to stretch out to match the name's length:
 


---

*[src/app/frontend/replicationcontrollerdetail/replicationcontrollerinfo.html, line 25 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/644#-KFDSZDdnuA2ZOSI4mkp:-KFDSZDdnuA2ZOSI4mkq:2029559314) ([raw file](https://github.com/kubernetes/dashboard/blob/682f84cf73a522192005e18fbc44986cace8117a/src/app/frontend/replicationcontrollerdetail/replicationcontrollerinfo.html#L25)):*
this seems to be having the effect of keeping the original length of the name, hiding the portion that overflows under the details area, and then reappear on the other side:



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/644)*

**Comment by digitalfishpond** [comment]
currently using this file for tests:
[MAX_LENGTH.yaml.txt](https://github.com/kubernetes/dashboard/files/216554/MAX_LENGTH.yaml.txt)

**Comment by bryk** [comment]
Thanks, will reverify.

**Comment by bryk** [comment]
PTAL @digitalfishpond I've make details page work on all cases much better now. Please reverify. 

---

Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/644#-:-KFE9dY44j5vDHNG2z9A:1983256860)*

**Comment by digitalfishpond** [comment]
Nice fix for the title, unfortunately, the issue with the name in replicationcontrollerinfo.html overflowing 'under' the details pane persists...

---

Reviewed 9 of 15 files at r1, 2 of 5 files at r2, 1 of 5 files at r3, 2 of 2 files at r4.
Review status: 13 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetail.html, line 44 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/644#-KFDV2EKpgJzz4VgE9K-:-KFEai2OqxKxr3UGJe-7:-707124028) ([raw file](https://github.com/kubernetes/dashboard/blob/682f84cf73a522192005e18fbc44986cace8117a/src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetail.html#L44)):*
this is much nicer with the table width behaving much more gracefully. 

---

*[src/app/frontend/replicationcontrollerdetail/replicationcontrollerinfo.html, line 25 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/644#-KFDSZDdnuA2ZOSI4mkp:-KFEbvbGiGD2_lX41Jog:-121082630) ([raw file](https://github.com/kubernetes/dashboard/blob/682f84cf73a522192005e18fbc44986cace8117a/src/app/frontend/replicationcontrollerdetail/replicationcontrollerinfo.html#L25)):*
this still behaves this way

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/644#-:-KFE_xy4R6A5ECBKnEXY:-1021699285)*

**Comment by bryk** [comment]
Review status: 13 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/app/frontend/replicationcontrollerdetail/replicationcontrollerinfo.html, line 25 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/644#-KFDSZDdnuA2ZOSI4mkp:-KFF6cMDUh73aZVqDRlK:278100854) ([raw file](https://github.com/kubernetes/dashboard/blob/682f84cf73a522192005e18fbc44986cace8117a/src/app/frontend/replicationcontrollerdetail/replicationcontrollerinfo.html#L25)):*
Hmm... I cannot reproduce. Works for me on Chrome. Can you maybe delete old code and refetch master and this branch? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/644)*

**Comment by digitalfishpond** [comment]
works beautifully :) :lgtm: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/644#-:-KFIQAI5CwBXbOWuS22n:-2168696)*

**Comment by digitalfishpond** [comment]
Reviewed 2 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/644)*

**Comment by bryk** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/644)*

**Pull request merged**
