### PR TITLE
Details page for secrets

### PR DESCRIPTION
**Pull request by bryk**
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1060)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm Can you review?

**Comment by maciaszczykm** [comment]
Few minor questions:

1. What about `TYPE` and `DATA` columns displayed by `kubectl get secret` command? Is there a possibility to add them to the list (I know that is not correct pull request to ask)?
2. In details there are `Type` and `Annotations` missing from `kubectl describe secret ...`. How about it?
3. When there is a lot of data following style issue occurs:



As you can see there is scrollbar at the bottom of the page. Can we avoid it?

I'll take a look at the code now.

---

Reviewed 2 of 27 files at r1.
Review status: 2 of 27 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1060#-:-KNCOovK_BmHQ2kWH9tm:1067991473)*

**Comment by maciaszczykm** [comment]
Few minor comments.

PTAL

---

Reviewed 24 of 27 files at r1.
Review status: 26 of 27 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/secretlist/secretcard_component.js, line 18 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1060#-KNCS_PYsXwr3HIgQn4M:-KNCS_PYsXwr3HIgQn4N:1195401783) ([raw file](https://github.com/kubernetes/dashboard/blob/508cfcca29c313f8015c6ef39e253cf014047dbd/src/app/frontend/secretlist/secretcard_component.js#L18)):*
> ```JavaScript
> import {stateName} from 'secretdetail/detail_state';
> 
> class SecretCardController {
> ```

What about simplifying file name like it's done for `secretdetail` contents?

---

*[src/app/frontend/secretlist/secretcard_component.js, line 34 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1060#-KNCSEl9H4NoWI2EMjZb:-KNCSEl9H4NoWI2EMjZc:311234373) ([raw file](https://github.com/kubernetes/dashboard/blob/508cfcca29c313f8015c6ef39e253cf014047dbd/src/app/frontend/secretlist/secretcard_component.js#L34)):*
> ```JavaScript
>     this.state_ = $state;
> 
>     this.injector_ = $injector;
> ```

Is it used anywhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1060#-:-KNCT2EXtTxp7o0zhati:2030514481)*

**Comment by maciaszczykm** [comment]
Closes #524.

**Comment by maciaszczykm** [comment]
Needs rebase.

**Comment by bryk** [comment]
> What about TYPE and DATA columns displayed by kubectl get secret command? Is there a possibility to add them to the list (I know that is not correct pull request to ask)?

How about adding them later? To have this merged faster. 

> When there is a lot of data following style issue occurs:

Fixed. 

---

Reviewed 4 of 6 files at r2.
Review status: 25 of 27 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/secretlist/secretcard_component.js, line 18 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1060#-KNCS_PYsXwr3HIgQn4M:-KOdesgNEuzzAzAn8t4Z:b-lp6xy) ([raw file](https://github.com/kubernetes/dashboard/blob/508cfcca29c313f8015c6ef39e253cf014047dbd/src/app/frontend/secretlist/secretcard_component.js#L18)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> What about simplifying file name like it's done for `secretdetail` contents?
</details>
Yep, sure. 

---

*[src/app/frontend/secretlist/secretcard_component.js, line 34 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1060#-KNCSEl9H4NoWI2EMjZb:-KOder0jJXQE8OFuIP6T:b-v6s1o3) ([raw file](https://github.com/kubernetes/dashboard/blob/508cfcca29c313f8015c6ef39e253cf014047dbd/src/app/frontend/secretlist/secretcard_component.js#L34)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> Is it used anywhere?
</details>
Removed. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1060#-:-KOdfeTAh1SRBZru3ToS:by237qi)*

**Comment by maciaszczykm** [comment]
> How about adding them later? To have this merged faster.

Sure.

Fix CI and let's merge. 

:lgtm: 

---

Review status: 19 of 39 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1060#-:-KOj-JqvTFUrZZc08-96:bcvqg04)*

**Comment by maciaszczykm** [comment]
Reviewed 3 of 8 files at r2, 29 of 29 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1060)*

**Comment by bryk** [comment]
Yep, fixing travis....

---

Reviewed 16 of 29 files at r1, 27 of 29 files at r3, 10 of 10 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1060#-:-KOj66MAMb2VS4_K9mYL:bm8vj0d)*

**Pull request merged**
