### PR TITLE
Navigation progress 4

### PR DESCRIPTION
**Pull request by bryk**
* merged app abr, top bar and tabs into one bar
* improved navigation highlighting (now menu item is highlighted when,
  e.g., a RC is selected)
* Fixed zerostate pages for RCs
* Moved events tables out from tabs to just a card

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1154)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm @floreks Can you review this?

**Comment by bryk** [comment]
Screenshot: 
selection_116

**Comment by maciaszczykm** [comment]
I like the idea of getting rid off tabs at the moment (even permanently), it makes navigation easier. Also moving breadcrumbs to top bar looks good at the moment.

Code looks good, not too many changes in application logic. Progress is really big :+1: 

:lgtm: 

---

Reviewed 38 of 38 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1154#-:-KQ587sQaOq9R3zVH3S6:b-4pkjd2)*

**Comment by floreks** [comment]
How about making Logs also a content card?

```html
<kd-content-card>
  <kd-content>
      <md-content layout-padding flex="auto" layout-fill ng-class=ctrl.getStyleClass()>
        <div ng-repeat="n in ctrl.logsSet track by $index" ng-class=ctrl.getLogsClass()>
          <pre ng-bind-html="n"></pre>
        </div>
      </md-content>
  </kd-content>
</kd-content-card>
```

zrzut ekranu z 2016-08-26 11-25-47

**Comment by floreks** [comment]
One more thing regarding events. If we filter them by warnings and there is nothing to display, empty table witll be visible. Should zerostate be displayed instead?

It's easy to change.
`src/app/frontend/events/eventcardlist_component.js:65`
s/`this.filteredEventList.listMeta.totalItems`/`this.filteredEventList.events.length`
and just remove one time binding in html.

In result we get
zrzut ekranu z 2016-08-26 11-39-58
instead of
zrzut ekranu z 2016-08-26 11-40-31

Besides that I haven't found any issues. LGTM.

**Comment by bryk** [comment]
Re logs and events: agree and done :) Will merge once travis is happy. 

---

Review status: 36 of 39 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1154#-:-KQ5FbGg8_UdhfhzdpHV:bp1alqt)*

**Comment by bryk** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1154)*

**Pull request merged**
