### PR TITLE
Add webpack and bump jest-preset-angular

### PR DESCRIPTION
**Pull request by shu-mutou**
jest-preset-angular removed webpack from its dependency in v9.0.5.
So we need to add webpack into own dependency.

### CODE REVIEW

**Comment by floreks** [comment]
I don't think we need to import webpack directly as angular already does and we do not use it directly anyway.

**Comment by shu-mutou** [comment]
Sure, `@angular-devkit/build-angular` installs `webpack`, but it's underneath `node_modules/@angular-devkit/build-angular/node_modules/` folder. So we need to install `webpack` to keep to use `jest-preset-angular`.

**Comment by floreks** [comment]
Since `jest-preset-angular` dropped webpack as a dependency then it makes no sense that we'd have to install it in order to use it. You should always only install dependencies that are directly used in the project and all peer dependencies should be installed by those direct dependencies silently.

The issue here is that most probably angular versions were bumped in an incorrect way and `package-lock.json` was not properly regenerated. I have bumped only the `jest-preset-angular` and regenerated whole `package-lock.json` and `webpack` is not required. The application builds just fine.

**Comment by floreks** [comment]
Closing in favor of #6375

/close

**Pull request closed without merging**
