### PR TITLE
Update to build and push multi-arch manifests

### PR DESCRIPTION
**Pull request by jeefy**
This allows us to publish v2.2 registry manifests allowing end-users to consume a single container image rather than specifying their architecture. This will directly address and resolve several issues (including #3137 and #2811)

Example:
`docker pull kubernetes-dashboard` 
Instead of
`docker pull kubernetes-dashbaord-amd64`

- Update travis-ci.yml to use a newer version of Docker
- Update build/Dockerfile to use a newer version of Docker
- pushToDocker now creates and pushes manifests 

Tested and verified on both [Docker Hub](https://hub.docker.com/r/jeefy/kubernetes-dashboard/) and GCR (Only had access to a private repo sorry)

If/When this is accepted, there will be additional work updating other repos and documentation to use the Manifest image (kubernetes-dashboard) instead of individual images (kubernetes-dashboard-amd64)

Any questions or comments are appreciated!

### CODE REVIEW

**Comment by floreks** [comment]
I have one concern regarding this change. As it requires edge docker client with manually enabled experimental flag, it might be a problem for users to use this instead of the current installation methods. At first, we should keep it only as an addition to current deployment methods and not make it the default.

**Comment by floreks** [comment]
Great, if this will work without additional changes to docker then I am ok with it.

**Comment by jeefy** [comment]
/hold

Awesome! I think we're waiting till after the next release to merge this in.

Once the angular migration is done we can merge this and update everything surrounding it in future PRs.

**Comment by maciaszczykm** [comment]
> Once the angular migration is done we can merge this and update everything surrounding it in future PRs.

@jeefy Are we planning to something about it?

**Comment by jeefy** [comment]
I'd like to get this in the next release, yes. I want to revisit this once
metrics server support is solid.

**Comment by jeefy** [comment]
@floreks @maciaszczykm PTAL, I think it's in a good place.

**Comment by maciaszczykm** [comment]
@jeefy Can you solve conflicts?

**Comment by mkumatag** [comment]
what else pending part of this pr? can we merge this?

**Comment by maciaszczykm** [comment]
@mkumatag Nothing :)

/lgtm

**Pull request merged**
