### PR TITLE
Workloads page with RCs and Replica Sets

### PR DESCRIPTION
**Pull request by bryk**
This is initial version of this view. Will iterate.

Screenshot: 
selection_077

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/707)

### CODE REVIEW

**Comment by bryk** [comment]
@digitalfishpond Can you review?

**Comment by digitalfishpond** [comment]
I think it looks really neat :) 

Couple of initial comments:

- Would it be a good idea to have tooltips for the logs and menu icons confirming what they are?

- The logs pop-up drops off the edge of the window when the name is long and it is the first time that has been clicked (subsequent clicks make the whole pop-up appear correctly):

logs_pop_up

- reducing the screen size to small enough for the horizontal scroll-bar to appear causes a box to appear on the far right hand side like this: 

right_side_box

**Comment by bryk** [comment]
> reducing the screen size to small enough for the horizontal scroll-bar to appear causes a box to appear on the far right hand side like this:

I'll do this the following way. The table has horizontal (Y axis) scroll that you can use on mobiles. It is a typical solution to have tables that are still tables (sortable, editable, etc) and work on mobile. 
selection_078

**Comment by bryk** [comment]
> The logs pop-up drops off the edge of the window when the name is long and it is the first time that has been clicked (subsequent clicks make the whole pop-up appear correctly):

Yeah, this is a problem with the logs menu. Can we solve it in another pull request? The menu is likely to be used in all workloads pages, so it'll be easy to fix as long as we use the common component.

**Comment by bryk** [comment]
All addressed. PTAL

**Comment by digitalfishpond** [comment]
> Would it be a good idea to have tooltips for the logs and menu icons confirming what they are?

**Comment by digitalfishpond** [comment]
:lgtm: This looks great as far as I can see :)

---

Reviewed 15 of 15 files at r1, 4 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/707#-:-KH-nQlHdgzeHgvwDjdG:-1488498164)*

**Pull request merged**
