### PR TITLE
manual test for deploy-from-file

### PR DESCRIPTION
**Pull request by cheld**
I created a test sheet for the deploy from file dialog. This test-sheet is rather simple. It is intended for initial discussion and to serve as a template for further test-sheets. I simplified the document as much as possible.

TBD: 
* which format should the test-sheet have? xls, openoffice, google docs
* where to store the documents?

@maciaszczykm please have a first review

### CODE REVIEW

**Comment by cheld** [comment]
Any factor missing?

**Comment by bryk** [comment]
Hmm.... Maybe we can use plain old markdown? You can convert your excel to it: https://github.com/mplewis/csvtomd

**Comment by maciaszczykm** [comment]
What I like about this file is, that it's simple and testing it should take minutes/hours instead of days. It should also help us to not forget about any of standard use cases. 

Regarding format I would also try to use markdown, because we can view all files directly on GitHub. 

Regarding test cases, is there any `?` tooltip on deploy page? It works on mouse over, there is no need to click. Moreover, at the moment we do not have any success message for validation. Proof, that deploy succeded is presence of application on replication controller list I think.

**Comment by cheld** [comment]
Ok, I convert to markdown.

About factors:
The last four lines are more like reminders, not real factors. These are the same for all sheets. I suggest to copy and paste them to all sheets. I change the wording a bit to make clear.

We don't have a success message - yes, but this is a bug :) 

> Proof, that deploy succeeded is presence of application on replication controller list I think.

What about if the yaml just contains a namespace? In this case no feedback at all...

**Comment by maciaszczykm** [comment]
> What about if the yaml just contains a namespace? In this case no feedback at all...

That's true. It seems to be another bug.

**Comment by cheld** [comment]
PTAL

**Comment by maciaszczykm** [comment]
LGTM, markdown will be good when it will come to merging these files.

**Comment by cheld** [comment]
Right. I was wondering if there is a good way to create big tables in md. Any idea?

**Comment by bryk** [comment]
Re editing markdown tables: http://www.tablesgenerator.com/markdown_tables

**Comment by bryk** [comment]
Can you remove trailing empty columns? You can use http://www.tablesgenerator.com/markdown_tables#

**Comment by bryk** [comment]
Other than that, LGTM :) Very nice

**Comment by cheld** [comment]
1. I cleaned up the tables
2. I moved the documents from src/test/manual to docs/test

PTAL

**Comment by maciaszczykm** [comment]
@cheld It seems, that trailing empty columns are still there.

**Comment by cheld** [comment]
Ah, now I understand...ok

**Comment by cheld** [comment]
Sorry, once again. I left the comments field for the special factors, because we used this field frequently in the past. So everyone is aware of the field and feels tempted to enter something.

**Comment by cheld** [comment]
PTAL

**Comment by bryk** [comment]
LGTM :)

**Pull request merged**
