### PR TITLE
add conform dialog WIP

### PR DESCRIPTION
**Pull request by DanielUche**
@eloyekunle check this out https://ui-router.github.io/sample-app-angular/#/home

### CODE REVIEW

**Comment by floreks** [comment]
We are actually in the middle of transition to angular router and we will drop the ui-router completely from the project.

**Comment by DanielUche** [comment]
@floreks this makes sense @angular/router canActivate would work well for this

**Comment by DanielUche** [comment]
I would also like to contribute to the transitioning

**Comment by jeefy** [comment]
I don't think this PR is valid anymore and should be closed. The work migrating from ui-router is being done in another PR (#3615) already. @DanielUche If you're still looking to contribute to the migration effort, look in that PR and work with @floreks to coordinate efforts. :)

/close

**Pull request closed without merging**
