### PR TITLE
Update gulp-sass dependency so that it compiles on OSX

### PR DESCRIPTION
**Pull request by bryk**
There was an issue with the package that prevented it from compilation on OSX, see: https://github.com/sass/node-sass/issues/1086

### CODE REVIEW

**Comment by markogresak** [comment]
AFAIK the linked issue was related to io.js v3.x only. It didn't occur in node v0.12 and was fixed for v4.0.0 release.

**Comment by bryk** [comment]
@markogresak That's interesting. Previous version did not compile on osx yosemite with xcode 7, node 5  and npm 3. But anyway, this PR fixes the issue.

**Comment by markogresak** [comment]
There is a chance that the previous gulp-sass version was using an older version of node-sass, I remember that there were some issues in the past. 
But it's nice to see that sometimes fix is as easy as updating the version, although that's very rare in my experience :smile:

**Comment by PeWu** [comment]
LGTM

**Pull request merged**
