### PR TITLE
Ignore updates for angular staffs

### PR DESCRIPTION
**Pull request by shu-mutou**
Angular staffs should be manually updated at once.
So, add a setting to ignore updating angular staffs by dependabot.

### CODE REVIEW

**Comment by floreks** [comment]
We should switch to renovate since it can bump multiple packages at once and is more flexible. Right now we are getting way too many dependency PRs

**Comment by shu-mutou** [comment]
@floreks 
For now, I added a setting to ignore Angular which is too much and needs to be updated manually.

**Comment by maciaszczykm** [comment]
/lgtm

It's good for now. We can reopen https://github.com/kubernetes/dashboard/issues/7470 but we will need to get approval for Renovate bot as we cannot do it on our own.

**Pull request merged**
