### PR TITLE
Add chenrui333 to reviewer list

### PR DESCRIPTION
**Pull request by chenrui333**
Here is my pitch, I am the sig-docs-zh-owner, and I did contribute/help manage bunch of PRs in the past (full list, https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Achenrui333+is%3Aclosed), I am trying to help with dashboard translation work in here too. 

Hence, adding myself to the reviewer list.

/cc @hwdef

### CODE REVIEW

**Comment by hwdef** [comment]
/lgtm
/approve

Welcome to dashboard/i18n/

**Comment by tanjunchen** [comment]
Welcome

**Pull request merged**
