### PR TITLE
Display running/failed/waiting pods in the RC cards

### LINKED ISSUE #247: Wrong number of running and pending pods
Hi,

Number of running and pending pods in replicasets view shows number of 'current' and 'desired - current' of replicas currently.
So even when pods status is failed, it is counted as running.

I think it is better to change display (e.g. 'x pods created, y desired') 
or to get pods of replicaset and count them such as 'kubectl describe' command.

```
$ kubectl describe rc noimage
...
...
Replicas:       2 current / 2 desired
Pods Status:    0 Running / 2 Waiting / 0 Succeeded / 0 Failed
...
```

Actual view

wrongnumber

Proposal

```
0 pods running, 2 waiting
```

Other case

```
$ kubectl describe rc jenkins
...
Replicas:       2 current / 3 desired
Pods Status:    2 Running / 0 Waiting / 0 Succeeded / 0 Failed
...
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Reason          Message

  1d            17s             2879    {replication-controller }                       FailedCreate    Error creating: Pod "jenkins-" is forbidden: limited to 5 pods
```

Actual view

limit

Proposal:

```
2 pods created, 3 desired
2 pods running
```
If some pods is not created, show number of created and desired too.

What do you think?

### PR DESCRIPTION
**Pull request by bryk**
This gives way more information than just current/desired numbers as it
was previously. Fixes #247.

### CODE REVIEW

**Comment by bryk** [comment]
@zreigz Can you review?

**Comment by zreigz** [comment]
Yes sure, my environment now is ready

**Comment by zreigz** [comment]
Sorry for delay. LGTM

**Comment by bryk** [comment]
No problems, thanks for the review! :)

**Pull request merged**
