### PR TITLE
Sort namespaces in selector menu alphabetically

### LINKED ISSUE #6674: Namespaces in selector menu should be sorted alphabetically
##### What would you like to be added

Namespaces in dropdown selector menu located at the top should be sorted alphabetically (ascending).

##### Why is this needed
In order to navigate the list of namespaces more easily / naturally.

##### Comments

The namespaces in the dropdown menu follow the order as returned by the Kubernetes API, i.e. based on their creation order.
There can be some merit to it, but I think an alphabetical order is more natural.

### PR DESCRIPTION
**Pull request by dalbani**
Fixes #6674.

### CODE REVIEW

**Comment by dalbani** [comment]
I am wondering: should the sorting be made case-insensitive? (Probably not)

**Comment by maciaszczykm** [comment]
@dalbani I think it should, "a" should be next to "A".

**Comment by dalbani** [comment]
> @dalbani I think it should, "a" should be next to "A".

OK, if you think that it's better, I've changed the implementation.

**Comment by dalbani** [comment]
By the way, I don't know why the CLA is still marked as "required", as I signed it already.

**Comment by floreks** [comment]
1. Make sure that you have signed it with the same email as configured in your `git config user.email`
2. Make sure that your commits are signed with the same email
3. Write "I signed it" comment to trigger the recheck.

**Comment by dalbani** [comment]
I signed it

**Comment by maciaszczykm** [comment]
I signed it

**Comment by dalbani** [comment]
I have just signed the second CLA, for the LinuxFoundation. I thought only the EasyCLA one was necessary.

**Comment by maciaszczykm** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
