### PR TITLE
backend: ingress will now use the networking/v1beta1 API instead of extensions/v1beta1

### LINKED ISSUE #5558: New Ingress API support (networking.k8s.io/v1beta1)
##### Environment

```
Kubernetes version: v1.14+
Dashboard version: 2.*
```

##### Expected result

The dashboard uses non-deprecated versions of the APIs

Considering that the new APIs are available from version 1.14, the Dashboard fully supports 1.19 (and partially from 1.15) could it be time for the dashboard to migrate to the new API for ingresses?

To date, the APIs used are hard-coded in the code [1][2][3]. Might it make sense to parameterize the APIs based on the underlying k8s version?

[1] https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/ingress/common.go#L19
[2] https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/ingress/detail.go#L21
[3] https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/ingress/list.go#L24

### PR DESCRIPTION
**Pull request by marcosdiez**
Just like https://github.com/kubernetes/dashboard/pull/5741, except that this one works in k8s 1.14+ instead 1.18+ :)

closes #5558

### CODE REVIEW

**Comment by pierluigilenoci** [comment]
@floreks @maciaszczykm @jeefy @shu-mutou could you please take a look? Thanks ❤️

**Comment by pierluigilenoci** [comment]
@marcosdiez thank you!!!

**Comment by jeefy** [comment]
/approve
:taco:

**Comment by maciaszczykm** [comment]
/lgtm

Thanks :)

**Comment by pierluigilenoci** [comment]
@jeefy @maciaszczykm thank you a lot!

**Comment by 0x4139** [comment]
is this released in the latest helm chart? I still get
```
W0125 15:00:13.713614    6247 warnings.go:67] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0125 15:00:14.343444    6247 warnings.go:67] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

**Comment by marcosdiez** [comment]
We recently changed the k8s dashboard to use networking.k8s.io/v1beta1,
although it's deprecated on 1.19+, it does work "eveyrwhere" (since 1.14 I believe)

The change to networking.k8s.io/v1 is trivial (I've actually done it here: https://github.com/kubernetes/dashboard/pull/5741 ) but it would break any version of k8s < 1.19, which is not something desirable.

In other words, this warning message is expected and non problematic. Before k8s 1.22 get's released, we will merge the other PR.

**Comment by LeoVS09** [comment]
@marcosdiez 
k8s 1.22 already released, please add at least alpha release of chart for `networking.k8s.io/v1`

**Pull request merged**
