### PR TITLE
add hpa list and detail front-end

### PR DESCRIPTION
**Pull request by zehuaiWANG**
refer to issue #3867 , I add the list/detail frontend for the hpa resource

hpa-list
hpa-detail
deployment

After adjusting:
image

### CODE REVIEW

**Comment by zehuaiWANG** [comment]
I will add HPA list to deployments detail view in this pr later.

**Comment by zehuaiWANG** [comment]
I had added it.

**Comment by maciaszczykm** [comment]
Please adjust name in the breadcrumbs (`horizontalpodsautoscaler`).

**Comment by zehuaiWANG** [comment]
@maciaszczykm I had adjusted it, is that what you said?

**Comment by floreks** [comment]
HPA should be only displayed on a resource detail view as it can't exist without a related object. Similar to how it was done in `v1.10`. If there is HPA defined for i.e. deployment then display it on the detail view.

This is how our sidebar looks like: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/

Metadata objects are skipped.

**Comment by maciaszczykm** [comment]
I've applied the necessary changes.

**Comment by zehuaiWANG** [comment]
@maciaszczykm thank you~ Sorry but I'm busy these days. Please feel free to change anything.

**Comment by maciaszczykm** [comment]
Normally I'd left them to you but we want to have this for RC today.

**Comment by zehuaiWANG** [comment]
@maciaszczykm It doesn't matter, we all want to make dashboard better and better :)

**Comment by davidtseng** [comment]
I don't see HPA in release 2.0.1, is something blocking?

**Comment by floreks** [comment]
It's not a resource so there is no hpa entry in the sidebar. If hpa is defined it will be displayed on a resource details view.

**Comment by davidtseng** [comment]
I see HPA now after clicking on the individual resource. Thanks!

**Pull request merged**
