### PR TITLE
Fix layout issues on Safari plus make logs toolbar work

### LINKED ISSUE #828: UI misalignment on Safari
Workloads page has a couple of glitches os Safari. Open to see.

### PR DESCRIPTION
**Pull request by bryk**
The issues were all around Safari. The logs toolbar didn't display pod name; now it displays.

Fixes #828

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/928)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you review this? :)

**Comment by floreks** [comment]
Nothing changed on Chrome, and I can't test on safari, so :lgtm: :)

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/928#-:-KKmOZUMnhhdS0hbwj5G:-529846828)*

**Comment by floreks** [comment]
Fix travis and we can merge.

**Comment by bryk** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/928)*

**Pull request merged**
