### PR TITLE
Disabled validation fix

### PR DESCRIPTION
**Pull request by maciaszczykm**
It fixes issue caused by code from pull request #239. There was some strange behavior during logging of request body for validation. It blocked validation on all pages, so it's critical fix. At the moment I've removed logging of request body as it was done with response content. When I'll have good solution for it I'll create pull request. Sorry, for not testing it before merge of #239, but didn't expected such problems in this area.

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@bryk PTAL, as it's very important.

**Comment by bryk** [comment]
LGTM

**Comment by bryk** [comment]
Do you know why is this happening? Can you write a short explanation?

**Comment by maciaszczykm** [comment]
> Do you know why is this happening? Can you write a short explanation?

It seems, that there is some problem with request body content for validation, but unfortunately I'm not sure what is wrong. 

```
reqBody := make([]byte, req.Request.ContentLength)
if req.Request.Body != nil {
	req.Request.Body.Read(reqBody)
}
```

This code causes the issue, exacly it's `req.Request.Body.Read(reqBody)` method call. I guess, there is a problem with length of request body or with unexpected/missing EOF. Is there any preparation needed in Go to perform I/O operations?

**Comment by bryk** [comment]
I don't have any top of my head answer for your question.

**Pull request merged**
