### PR TITLE
Allow replication controller to have zero replicas

### LINKED ISSUE #1048: Allow replication controller to have zero replicas
Replication controller view should allow to set zero replicas, since we can turn off service, without deleting actual replication controller.

https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/replicationcontrollerdetail/updatereplicas.html#L29

### PR DESCRIPTION
**Pull request by bryk**
Fixes #1048

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1051)

### CODE REVIEW

**Comment by bryk** [comment]
@digitalfishpond Can you review?

**Comment by digitalfishpond** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/replicationcontrollerdetail/updatereplicas_controller.js, line 150 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1051#-KN6UYibCoVsGukvXPmu:-KN6UYic381Uq9CuNeJG:1949351908) ([raw file](https://github.com/kubernetes/dashboard/blob/b2a311a3932401541b0318178f608e7c26365b93/src/app/frontend/replicationcontrollerdetail/updatereplicas_controller.js#L150)):*
> ```JavaScript
>         the "update number of pods" dialog is not positive or non-integer.*/
>     MSG_RC_DETAIL_NUMBER_OF_PODS_INTEGER_WARNING:
>         goog.getMsg('Number of replicas must be greater than zero'),
> ```

Isn't the idea that the number of replicas can actually be zero?  In which case the previous message was better, wasn't it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1051)*

**Comment by floreks** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/replicationcontrollerdetail/updatereplicas_controller.js, line 150 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1051#-KN6UYibCoVsGukvXPmu:-KN6Y8VTRhrWwDVyvJ7r:-644186038) ([raw file](https://github.com/kubernetes/dashboard/blob/b2a311a3932401541b0318178f608e7c26365b93/src/app/frontend/replicationcontrollerdetail/updatereplicas_controller.js#L150)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> Isn't the idea that the number of replicas can actually be zero?  In which case the previous message was better, wasn't it?
</details>
Both 'positive integer' and 'greater than zero' indicate range of numbers <1,+inf>.IMO it should be `greater or equal`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1051)*

**Comment by bryk** [comment]
PTAL

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/replicationcontrollerdetail/updatereplicas_controller.js, line 150 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1051#-KN6UYibCoVsGukvXPmu:-KN6h5NqDrsbnvUQR_pk:-1308918178) ([raw file](https://github.com/kubernetes/dashboard/blob/b2a311a3932401541b0318178f608e7c26365b93/src/app/frontend/replicationcontrollerdetail/updatereplicas_controller.js#L150)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Both 'positive integer' and 'greater than zero' indicate range of numbers <1,+inf>.IMO it should be `greater or equal`.
</details>
Yeah, my mistake... Fixed. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1051#-:-KN6hz8Ro6s0zE3hYMGT:676965300)*

**Comment by digitalfishpond** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1051#-:-KN6o6n9KD2n7MDnPyfw:1417088721)*

**Comment by bryk** [comment]
Reviewed 1 of 4 files at r1, 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1051)*

**Pull request merged**
