### PR TITLE
Implemented inline editing for data entries on Secrets page.

### PR DESCRIPTION
**Pull request by greggbjensen**
I updated the read only Data entries on the Decrets page to make them a text box with the ability to quickly update a single unencoded entry.

image

### CODE REVIEW

**Comment by floreks** [comment]
Seems better. I'll review when I'll have some time.

**Comment by shu-mutou** [comment]
/lgtm
This  works fine. Great!

**Comment by floreks** [comment]
Why was it merged? I did not review it yet and it is not done as I have said. Entries should not be editable by default. There should be view/edit mode available. Eye icon should only show read-only inline value. Text box is too big and does not scale to single-line values.

**Comment by floreks** [comment]
@greggbjensen will you work on improving that or should I revert for now?

**Comment by maciaszczykm** [comment]
Let's revert if there will no answer today.

**Comment by greggbjensen** [comment]
@floreks I can get those changes in.  I'll submit another pull request.  Sorry I'm in a GMT-7.

**Comment by greggbjensen** [comment]
Can you re-merge if I update this pull request? 

@floreks you would like the eye and the pencil icons, leaving the eye with the same behavior and the pencil with the new behavior?

**Comment by floreks** [comment]
Yes, edit icon instead of edit by default. Also, you can check if entry is a single line or multi-line value and use input/text area accordingly. I'd also try to scale the text area, because it takes too much space for small files.

**Comment by greggbjensen** [comment]
Okay, will do.  I'll update this pull request.

**Comment by maciaszczykm** [comment]
> Can you re-merge if I update this pull request?

I am not sure if this is possible. Opening the pull request is on your side so you can check and if not do it from the new branch.

**Comment by greggbjensen** [comment]
@maciaszczykm no problem, I will do a new branch and pull request as an enhancement to this.  Then I will link it back here.

**Comment by greggbjensen** [comment]
@floreks and @maciaszczykm here are all the requested changes:

**Inline edit secret enhancements** #5046

**Pull request merged**
