### PR TITLE
Fix validation messages for service ports

### LINKED ISSUE #979: Incorrect validation message during deploy app by form
##### Environment
```
Dashboard version: latest
Operating system: Ubuntu 16.04 4.4.0-28-generic
Node.js version: v6.1.0
Go version: go1.6.2 linux/amd64
```

##### Steps to reproduce
I try deploy app by form. I fill up App name, Container image, Number of pods, next I choose Service other than None, don't complete fields: Port and target Port and I click to Deploy button

##### Observed result
I see 2 validation messages under Port and Target port which are incorrect (in this situation):
"Port can't be empty when target port is specified." and "Target port can't be empty when port is specified."
zrzut ekranu z 2016-06-30 12-45-52

##### Expected result
Message should be for example "Port and Target port must be completed"

##### Comments
Validation messages, which in this situation are displayed, suggest that one of those fields is filled up, but really we have two empty fields

### PR DESCRIPTION
**Pull request by bryk**
Fixes #979

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/981)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you review?

**Comment by floreks** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/981#-:-KLWHoYGqe_uR48vRp3f:1417088721)*

**Comment by bryk** [comment]
Will merge soon. 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/981#-:-KL_BIotxrqTVeygXo1w:-1749170146)*

**Comment by bryk** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/981)*

**Pull request merged**
