### PR TITLE
Fix broken link in deploy from settings wizard

### PR DESCRIPTION
**Pull request by tomkerkhove**

### CODE REVIEW

**Comment by tomkerkhove** [comment]
CLA ✅

**Comment by tomkerkhove** [comment]
Not sure why code coverage changed on a file that I didn't change to be honest..

**Comment by maciaszczykm** [comment]
> Not sure why code coverage changed on a file that I didn't change to be honest..

@tomkerkhove Sometimes it has minor distortions. 

Thanks for it!

**Pull request merged**
