### PR TITLE
Fix typo of Japanese localization

### PR DESCRIPTION
**Pull request by tk3fftk**
"なめ" maybe mean typing alphabet "name" as  Japanese.
It has no meaning so I fix same as other words. (but we laugh when I found it.)

### CODE REVIEW

**Comment by bryk** [comment]
@Yamagami-Takuma Can you take a look at this? :)

**Comment by Yamagami-Takuma** [comment]
@tk3fftk  
Exactly. This is my typo. (why I tried to type "name" here...) 
Thanks for fix this!

LGTM

**Comment by rf232** [comment]
@tk3fftk, it might sound a bit over done for a typo fox, but for all pull requests we need the author to sign the CLA. If you could do that we can merge the PR

**Comment by tk3fftk** [comment]
Thank you for review!
I signed the CLA. (Does it have any delay?)

**Pull request merged**
