### PR TITLE
Add Rolling Update endpoint for RC

### PR DESCRIPTION
**Pull request by titilambert**
[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/413)

### CODE REVIEW

**Comment by bryk** [comment]
cc @cheld @floreks @maciaszczykm

**Comment by bryk** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/backend/replicationcontrollerupdate.go, line 147 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/413#-KBDZI_aCHIlIKu1cwJI:-KBDZI_bOqlbmeFmKWoI:1422504310) ([raw file](https://github.com/kubernetes/dashboard/blob/b5d63345979ab0f0dd15a613d8b2d92d458cd4f3/src/app/backend/replicationcontrollerupdate.go#L147)):*
Is this a long lasting operation? Does this return immediately and execute in the background? 

cc @floreks

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/413)*

**Comment by floreks** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/backend/replicationcontrollerupdate.go, line 147 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/413#-KBDZI_aCHIlIKu1cwJI:-KBD_qBxXaY-BeG4v6DY:1480130494) ([raw file](https://github.com/kubernetes/dashboard/blob/b5d63345979ab0f0dd15a613d8b2d92d458cd4f3/src/app/backend/replicationcontrollerupdate.go#L147)):*
Looking at the code: https://github.com/kubernetes/contrib/blob/master/Ingress/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/rolling_updater.go#L155
I'd say that this is a long lasting operation. I'm not sure if we should run it in parallel. Error handling would be hard.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/413)*

**Comment by titilambert** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/backend/replicationcontrollerupdate.go, line 147 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/413#-KBDZI_aCHIlIKu1cwJI:-KBDhbPl3t3tn0Nc8Toc:-1896447515) ([raw file](https://github.com/kubernetes/dashboard/blob/b5d63345979ab0f0dd15a613d8b2d92d458cd4f3/src/app/backend/replicationcontrollerupdate.go#L147)):*
This function is blocking. Do you prefer a none blocking function ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/413)*

**Comment by bryk** [comment]
@titilambert Give us some time. This week is really busy. Please ping if you feel this PR is jammed.

**Comment by titilambert** [comment]
@bryk Thanks for your reply !

**Comment by titilambert** [comment]
@bryk Hello ! Any news on this one ?

**Comment by floreks** [comment]
@bryk will be unavailable for the next few days. We'll check and prioritize all issues and PR once he's back. You've got to wait few more days :)

**Comment by titilambert** [comment]
@floreks ok, thanks !

**Comment by bryk** [comment]
@titilambert Thanks for your patience. Let's move forward with this.

**Comment by bryk** [comment]
So, this PR would be a breeze, except for one problem that we haven't solved yet. This is; how do we handle long-lasting operations? E.g., rolling update that may take 10+ minutes.

How do we handle this in the UI? There are a few options.

1. One is to ignore this fact and just block the UI. But is is like in 90s where you had these modals saying "DO NOT REFRESH THIS PAGE WHEN SPINNER IS ON".
1. The next option is to implement a framework for the UI to handle the operations and save them somewhere and then handle this on the client somehow. This is a large and non-trivial task.
1. The last option I see is to avoid doing this on the UI side and just call what API allows us to call. In this case we'd support rolling updates only for deployments: https://github.com/kubernetes/kubernetes/blob/release-1.2/docs/proposals/deployment.md. This would simplify *a lot* of things on the UI side, but will allow for rolling updates only for deployments. 

@olekzabl @floreks @cheld @maciaszczykm @titilambert I need your opinions on this.

**Comment by bryk** [comment]
CC @bgrant0607-cc @kubernetes/sig-api-machinery Rolling updates in UI: Embed kubectl? Implement long operations handling? Or use what apiserver provides? See previous comment

**Comment by titilambert** [comment]
@bryk Why just launch rolling update in a go routine server-side ?
The UI could just list all running jobs.

**Comment by bryk** [comment]
> @bryk Why just launch rolling update in a go routine server-side ?
The UI could just list all running jobs.

We could do this, sure. But such design has serious flaws, which we should not be ignoring. Basically, everything boils down to the fact that the UI is a stateless distributed system. For example, you can have two replicas of the UI. Then one would have the running goroutine and the other would not. How would you sync this? Other thing: what to do when the UI crashes/is killed in the middle of a rolling update? This happens often in K8s world. 
We can, of course, solve all these problems. This has been done many times in the past. But this requires a lot of work, which I'm not sure we should be doing.

**Comment by titilambert** [comment]
@bryk I'agree with you, but it's kubectl issue not UI.
In my opinion, the UI acts as a kubectl (with a beautiful web UI :)) ( but maybe I should not to ? )
So if a rolling update crashes, you just have to relaunch the rolling update, like with kubectl.

And of course, I'm agree with you, all these issues will be fixed with deployment stuff, but this PR could be the first rolling update implementation before switching to the server-side one...

**Comment by lavalamp** [comment]
Why not use deployment for this?

**Comment by lavalamp** [comment]
We need to move more items to be done server-side for exactly the reason you want. But we can't just simply run kubectl from a server. Deployment solves the particular use case here, so I'd actually prefer not to have rolling-update as a primitive at all any more.

**Comment by bgrant0607** [comment]
Yes, we should move the UI to Deployment.

I didn't want to block on that for the initial version, because Deployment wasn't ready, but now it is. Rolling update should only be supported via Deployment.

cc @janetkuo @pwittrock

**Comment by bgrant0607** [comment]
How does the UI handle multiple replication controllers for the same service?

FYI, we've moved `kubectl run` to Deployment by default in 1.2.

Also, something that may or may not be useful for other things:
https://github.com/rancher/kubectld

**Comment by bgrant0607** [comment]
FYI: https://github.com/kubernetes/kubernetes/issues/12143

**Comment by bryk** [comment]
@kubernetes/dashboard-maintainers Comments?

**Comment by floreks** [comment]
In my opinion we should avoid adding functionalities that would be removed soon anyway. It's best to work on good solution which rolling update via deployments seems to be. This PR is really nice but it introduces some major problems with UI handling which we're trying to avoid.

**Comment by maciaszczykm** [comment]
I agree with you, first and second option seem to be risky, so we should go for rolling update via deployments. Now the question is how we will support them and other kind of objects?

**Comment by titilambert** [comment]
Oki, I'm agree with all of you.
I just wanted this PR to be able to do rolling updates from UI.
So the actual stuff to do, is to implement deployment object handler. So do have any comments before I starts this stuff ?

**Comment by bgrant0607** [comment]
@titilambert 

@janetkuo just updated the Deployment documentation for 1.2:
http://kubernetes.io/docs/user-guide/deployments/

Let us know if you have questions.

**Comment by cheld** [comment]
We could put the rolling update in a job ;-). If we use deployments, what happens if dashboard is deployed in a old cluster? (There are a lot of old clusters, because Kubernetes upgrades are not easy, yet)

**Comment by bgrant0607** [comment]
kubectl run uses the discovery API to determine whether Deployment is supported by the apiserver or not.

**Comment by bgrant0607** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/run.go#L162

**Comment by bryk** [comment]
> So, the actual stuff to do is to implement deployment object handler. So do have any comments before I start this stuff ?

We need to come up with a proposal on how to scale the UX to handle many new types of resources to display (e.g., deployments, daemon sets, etc.). We should have a proposal next week. Can you wait till then?

**Comment by titilambert** [comment]
@bryk Yeah ! of course ! :) I would love see the next UI/UX designs :)

**Comment by bryk** [comment]
So the final outcome is: rolling update will be implemented for deployments. Deployments support will be added soon to the UI.

Closing. Please comment if this needs further discussion.

**Pull request closed without merging**
