### PR TITLE
Fix overlaping error message and remove huge padding under name input

### LINKED ISSUE #477: App name validation message overlaps character counter
Validation message for wrong pattern on Deploy --> Specify app details below --> App name overlaps the character counter 

validationoverlap

##### Steps to reproduce
- Deploy
- select "Specify app details below"
- In App name field, type a string with illegal characters (capitals, underscores, etc)
- focus out 

##### Observed result
Message overlaps character counter

##### Expected result
Character counter should be separate from message

### PR DESCRIPTION
**Pull request by bryk**
With this there is no jitter and overlap

Fixes #477

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/490)

### CODE REVIEW

**Comment by bryk** [comment]
@digitalfishpond Can you review this?

**Comment by digitalfishpond** [comment]
Unfortunately Firefox still causes jitter on first error:

- Open in Firefox, 
- start typing a valid name (lowercase):

image

- add

 an invalid character (uppercase or invalid)

image

the line stays blue (no focus out yet), but the rest of the page shifts down by a line (maybe in anticipation of the error message to be shown?)

This behaviour is unlikely to change with the planned revert to default Material validation, only the line will be red and the message will be shown after the debounce delay. 
Maybe this is acceptable?

**Comment by digitalfishpond** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/490)*

**Comment by bryk** [comment]
Yes, I've also found this problem. But AFAIK this is just how angular material works and the way to fix this is to make the error message shorter or fit it in one line.

How about we stay go with what is there? Most of the problems will be fixed, except one, which is fine. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/490#-:-KC0HpsnREdxRNT7Yri2:1135021453)*

**Comment by digitalfishpond** [comment]
LGTM :)

**Pull request merged**
