### PR TITLE
Created Folder Structure for Developer Docu

### PR DESCRIPTION
**Pull request by cheld**
@floreks @maciaszczykm 

I created the initial folder structure similar to the core project.

I will add content in separate PR

### CODE REVIEW

**Comment by floreks** [comment]
It's good to have same structure as k8s core. LGTM.

**Comment by bryk** [comment]
LGTM, can you rebase or add me to collaborators to your repo so that I can merge this?

**Comment by cheld** [comment]
I did both

**Comment by bryk** [comment]
Awesome :)

**Pull request merged**
