### PR TITLE
Set timeout in terminalSessions

### PR DESCRIPTION
**Pull request by xuziheng1002**
Set timeout in terminalSessions

### CODE REVIEW

**Comment by floreks** [comment]
Fixes #7315

**Comment by floreks** [comment]
Please fix the static code check and we can merge.

**Comment by floreks** [comment]
/hold

The license file is missing in `basic_test.go`

**Comment by xuziheng1002** [comment]
> /hold
> 
> The license file is missing in `basic_test.go`. This might be a result of some other PR. Let me fix that for you.
> 
> EDIT: I don't have permission to update your PR. Please rebase/merge latest master and run `npm run fix:license`. That will fix it. Sorry for the trouble.

Sorry, I don't known how to run npm in this project, I add permission to you on my fork, can you try to do it?

**Comment by xuziheng1002** [comment]
> /hold
> 
> The license file is missing in `basic_test.go`. This might be a result of some other PR. Let me fix that for you.
> 
> EDIT: I don't have permission to update your PR. Please rebase/merge latest master and run `npm run fix:license`. That will fix it. Sorry for the trouble.

Sorry, I don't known how to run npm in this project, I add permission to you on my fork, can you try to do it? 
if you can't, is there any document that tell me how to fix this issue?

**Review by floreks — APPROVED** [review]

**Pull request merged**
