### PR TITLE
Make card titles consistent across the UI

### LINKED ISSUE #1451: Unify card headers across the UI
Some cards have such headers:

image

Some such:

image

Should we unify this? Is this for 1.5? @maciaszczykm @rf232

### PR DESCRIPTION
**Pull request by bryk**
Fixes #1451

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm Can you review this?

**Comment by maciaszczykm** [comment]
Config map details:

image

Secret details:

image

And just a thought about zerostates - at the moment we don't display headers for them:

image

I'm not saying that's bad, but what do you think about adding headers to it and making them more specific to resource. Suggestions like `You can deploy a containerized app...` or `select other namespace` may confuse users viewing persistent volume page...

**Comment by bryk** [comment]
Fixed secrets and config maps. PTAL

**Comment by maciaszczykm** [comment]
Secrets look good, there is still an issue with config maps :-)

image

**Comment by bryk** [comment]
Yeah, done. PTAL :)

**Pull request merged**
