### PR TITLE
Improve dashboard state transitions and fix dependency issues

### PR DESCRIPTION
**Pull request by floreks**
I've also fixed some states not working on server prod due to missing `ngInject`.

zrzut ekranu z 2016-05-19 15-57-04

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/749)

### CODE REVIEW

**Comment by bryk** [comment]
Hmmm.... Weren't services supposed to be under services menu item?

**Comment by bryk** [comment]
Can you split this so that we can talk about whether services belong to workloads asynchronously and merge other important fixes that you made here? :)

**Comment by floreks** [comment]
Yes, totally. Services should be in different section. I've completely forgotten about that. I'll remove this part asap.

**Comment by floreks** [comment]
PTAL

**Comment by bryk** [comment]
Awesome, awesome, awesome. This was super needed for the beta release. Thanks. Merging. 

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> PTAL
</details>


---

Reviewed 13 of 17 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/749#-:-KICHrGy5j8dwbmHBhAQ:-922932800)*

**Pull request merged**
