### PR TITLE
Localization of the Pod List and -Details pages

### PR DESCRIPTION
**Pull request by taimir**
Localization batch for the PodList and PodDetails views.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/840)

### CODE REVIEW

**Comment by bryk** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/frontend/podlist/podcardlist_component.js, line 74 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/840#-KJdhT8mLmxEryeiOoaM:-KJdhT8mLmxEryeiOoaN:-993370899) ([raw file](https://github.com/kubernetes/dashboard/blob/8530a65873e231caa46f6d2c3f04bb9fe1881352/src/app/frontend/podlist/podcardlist_component.js#L74)):*
> ```JavaScript
>    * @return {string} localized tooltip with the formated creation date
>    */
>   getStartedAtTooltip(startDate) {
> ```

A quick test for this? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/840)*

**Comment by taimir** [comment]
PTAL

<details><summary><i>Previously, codecov-io wrote…</i></summary>
> ## [Current coverage][cc-pull] is **94.51%**
> > Merging [#840][cc-pull] into [master][cc-base-branch] will increase coverage by **0.17%**
> 
> 1. 7 files (not in diff) in `...app/frontend/joblist` were deleted. [more](https://codecov.io/gh/kubernetes/dashboard/commit/9fc1b6ec5309321e37455e87f7f16f72b0e73473/changes?src=pr#7372632F6170702F66726F6E74656E642F6A6F626C697374)
> 1. 5 files (not in diff) in `...p/frontend/jobdetail` were deleted. [more](https://codecov.io/gh/kubernetes/dashboard/commit/9fc1b6ec5309321e37455e87f7f16f72b0e73473/changes?src=pr#7372632F6170702F66726F6E74656E642F6A6F6264657461696C)
> 1. 2 files (not in diff) in `...components/actionbar` were deleted. [more](https://codecov.io/gh/kubernetes/dashboard/commit/9fc1b6ec5309321e37455e87f7f16f72b0e73473/changes?src=pr#7372632F6170702F66726F6E74656E642F636F6D6D6F6E2F636F6D706F6E656E74732F616374696F6E626172)
> 1. 7 files (not in diff) in `src/app/frontend` were deleted. [more](https://codecov.io/gh/kubernetes/dashboard/commit/9fc1b6ec5309321e37455e87f7f16f72b0e73473/changes?src=pr#7372632F6170702F66726F6E74656E64)
> 1. 3 files (not in diff) in `...cationcontrollerlist` were modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/9fc1b6ec5309321e37455e87f7f16f72b0e73473/changes?src=pr#7372632F6170702F66726F6E74656E642F7265706C69636174696F6E636F6E74726F6C6C65726C697374)
> 1. 2 files (not in diff) in `...tioncontrollerdetail` were modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/9fc1b6ec5309321e37455e87f7f16f72b0e73473/changes?src=pr#7372632F6170702F66726F6E74656E642F7265706C69636174696F6E636F6E74726F6C6C657264657461696C)
> 1. 10 files (not in diff) in `.../app/frontend/deploy` were modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/9fc1b6ec5309321e37455e87f7f16f72b0e73473/changes?src=pr#7372632F6170702F66726F6E74656E642F6465706C6F79) 
>   - Misses `-6` 
>   - Hits `+4`
> 1. 2 files (not in diff) in `...ponents/resourcecard` were modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/9fc1b6ec5309321e37455e87f7f16f72b0e73473/changes?src=pr#7372632F6170702F66726F6E74656E642F636F6D6D6F6E2F636F6D706F6E656E74732F7265736F7572636563617264)
> 1. 2 files (not in diff) in `...components/actionbar` were modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/9fc1b6ec5309321e37455e87f7f16f72b0e73473/changes?src=pr#7372632F6170702F66726F6E74656E642F636F6D6D6F6E2F636F6D706F6E656E74732F616374696F6E626172) 
>   - Hits `-1`
> 1. 1 files (not in diff) in `.../app/frontend/common` were modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/9fc1b6ec5309321e37455e87f7f16f72b0e73473/changes?src=pr#7372632F6170702F66726F6E74656E642F636F6D6D6F6E)
> 
> ```diff
> @@             master       #840   diff @@
> ==========================================
>   Files           225        205    -20   
>   Lines          1785       1696    -89   
>   Methods           0          0          
>   Messages          0          0          
>   Branches          0          0          
> ==========================================
> - Hits           1684       1603    -81   
> + Misses          101         93     -8   
>   Partials          0          0          
> ```
> 
> > Powered by [Codecov](https://codecov.io?src=pr). Last updated by [d08ed26...9fc1b6e][cc-compare]
> [cc-base-branch]: https://codecov.io/gh/kubernetes/dashboard/branch/master?src=pr
> [cc-compare]: https://codecov.io/gh/kubernetes/dashboard/compare/d08ed2675a3805ba11d0515aae4fa9a0707ebee7...9fc1b6ec5309321e37455e87f7f16f72b0e73473
> [cc-pull]: https://codecov.io/gh/kubernetes/dashboard/pull/840?src=pr
</details>


---

Review status: 6 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/podlist/podcardlist_component.js, line 74 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/840#-KJdhT8mLmxEryeiOoaM:-KJjdZurmuxGF-CCZi1L:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/8530a65873e231caa46f6d2c3f04bb9fe1881352/src/app/frontend/podlist/podcardlist_component.js#L74)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> A quick test for this? 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/840#-:-KJjdaLquDZ26oygi4o5:676965300)*

**Comment by bryk** [comment]
:lgtm: Perfect! 

<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> PTAL
</details>


---

Reviewed 3 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/840#-:-KJk7xNrBKnLQWqVvrwt:-1729251779)*

**Comment by bryk** [comment]
We have conflicts :( Can you rebase? 

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> :lgtm: Perfect! 
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/840#-:-KJk800pYyKh9W570jSl:1581849182)*

**Comment by taimir** [comment]
Done

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> We have conflicts :( Can you rebase? 
</details>


---

Review status: 9 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/840#-:-KJk9BFwNx8WZ1OG_-GB:676635175)*

**Comment by bryk** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/840)*

**Comment by bryk** [comment]
:lgtm:

<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> Done
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/840#-:-KJkFLf7TZIqjQqF5AND:1417088721)*

**Pull request merged**
