### PR TITLE
Add issue template

### PR DESCRIPTION
**Pull request by maciaszczykm**
Added issue template. It's only draft, so I'm open to all suggestions. I think we can save a lot of time with it. We can also prepare template for pull requests, but issues seem to be more important at the moment.

It was mentioned in #373 issue: https://github.com/blog/2111-issue-and-pull-request-templates.

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/408)

### CODE REVIEW

**Comment by bryk** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ISSUE_TEMPLATE.md, line 12 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/408#-KB8S9xYe87g18CpwlJ8:-KB8S9xYe87g18CpwlJ9:-740644876) ([raw file](https://github.com/kubernetes/dashboard/blob/254b3414e1f5201bc0766485843b1d8c9b36f443/ISSUE_TEMPLATE.md#L12)):*
I'm wondering whether we should prefill this. I think not. Because with this lazy reporters will just leave it as without checking. It is better to have no info rather than wrong info. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/408)*

**Comment by maciaszczykm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ISSUE_TEMPLATE.md, line 12 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/408#-KB8S9xYe87g18CpwlJ8:-KB8XXGb0REr90u9wfpg:-1991074459) ([raw file](https://github.com/kubernetes/dashboard/blob/254b3414e1f5201bc0766485843b1d8c9b36f443/ISSUE_TEMPLATE.md#L12)):*
You're right. It'll be fixed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/408)*

**Comment by maciaszczykm** [comment]
@bryk PTAL

**Comment by bryk** [comment]
A few wording comments. Please push back if you think I'm wrong. PTAL. 

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[ISSUE_TEMPLATE.md, line 4 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/408#-KBC0mRcP5DT4LDpqW0v:-KBC0mRd-eFGl6_hMSiT:-882896424) ([raw file](https://github.com/kubernetes/dashboard/blob/f61c186f1985846869922f0a78702e47e220be33/ISSUE_TEMPLATE.md#L4)):*
Hmm.... What do you think about changing "Please describe" to "Describe"? Sounds better to me. 

---

*[ISSUE_TEMPLATE.md, line 19 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/408#-KBC0ym_iromnrgLNyaO:-KBC0ym_iromnrgLNyaP:-194678163) ([raw file](https://github.com/kubernetes/dashboard/blob/f61c186f1985846869922f0a78702e47e220be33/ISSUE_TEMPLATE.md#L19)):*
"It is *a* good place" 

---

*[ISSUE_TEMPLATE.md, line 22 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/408#-KBC195kyjjBFKuf4kIH:-KBC195kyjjBFKuf4kII:-550062561) ([raw file](https://github.com/kubernetes/dashboard/blob/f61c186f1985846869922f0a78702e47e220be33/ISSUE_TEMPLATE.md#L22)):*
"as precisely as possible". Without "it's"

---

*[ISSUE_TEMPLATE.md, line 25 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/408#-KBC1E8xjQsD68vtPkeT:-KBC1E8xjQsD68vtPkeU:-550062561) ([raw file](https://github.com/kubernetes/dashboard/blob/f61c186f1985846869922f0a78702e47e220be33/ISSUE_TEMPLATE.md#L25)):*
"as precisely as possible". Without "it's"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/408#-:-KBC1FbyACpAZvV9V4UV:-2075815284)*

**Comment by bryk** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/408)*

**Comment by maciaszczykm** [comment]
I agree. Updated template. PTAL

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/408#-:-KBCGlClf8uTNZACnvCx:1519831202)*

**Comment by bryk** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/408)*

**Pull request merged**
