### PR TITLE
Frontend for generic delete menu on list views

### PR DESCRIPTION
**Pull request by bryk**
Please sync and test this :)

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/735)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you review?

**Comment by floreks** [comment]
Sure. I'll test tomorrow morning.

**Comment by bryk** [comment]
Hmm... Travis does not want to rerun this...

**Comment by floreks** [comment]
Looks great! Just 2 comments. Add some tests and we can merge.

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Hmm... Travis does not want to rerun this...</details>


---

Review status: 0 of 33 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/common/components/resourcecard/resourcecarddeletemenuitem_component.js, line 61 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/735#-KHctZu384WyEvTfnG8q:-KHctZu384WyEvTfnG8r:-650172802) ([raw file](https://github.com/kubernetes/dashboard/blob/a2e742d495a568effe05f369635cd5c6d570870a/src/app/frontend/common/components/resourcecard/resourcecarddeletemenuitem_component.js#L61)):*
> ```JavaScript
>               this.mdDialog_.show(this.mdDialog_.alert()
>                                       .ok('Ok')
>                                       .title(err.statusText || 'Internal server error')
> ```

On delete cancel console error is thrown that `statusText` is undefined.

---

*[src/app/frontend/podlist/podcardlist.html, line 67 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/735#-KHctJcVsbsJbDay2QUt:-KHctJcW3bWjegaLCPcJ:566691994) ([raw file](https://github.com/kubernetes/dashboard/blob/a2e742d495a568effe05f369635cd5c6d570870a/src/app/frontend/podlist/podcardlist.html#L67)):*
> ```HTML
>       <kd-resource-card-column class="kd-row-layout-column kd-icon-column">
>         <kd-resource-card-menu>
>           <kd-resource-card-delete-menu-item>
> ```

Missing `resource-kind-name`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/735#-:-KHctNKC4VPBXqviGrxE:1590937200)*

**Comment by bryk** [comment]
All done. Will merge soon.

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Looks great! Just 2 comments. Add some tests and we can merge.</details>


---

Reviewed 27 of 36 files at r1, 1 of 1 files at r2, 5 of 7 files at r3, 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/common/components/resourcecard/resourcecarddeletemenuitem_component.js, line 61 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/735#-KHctZu384WyEvTfnG8q:-KHsc1dZINd8CzLXMSrZ:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/a2e742d495a568effe05f369635cd5c6d570870a/src/app/frontend/common/components/resourcecard/resourcecarddeletemenuitem_component.js#L61)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> On delete cancel console error is thrown that `statusText` is undefined.</details>
Done.

---

*[src/app/frontend/podlist/podcardlist.html, line 67 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/735#-KHctJcVsbsJbDay2QUt:-KHsc2gt1xI_Ax9zK4ud:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/a2e742d495a568effe05f369635cd5c6d570870a/src/app/frontend/podlist/podcardlist.html#L67)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Missing `resource-kind-name`</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/735#-:-KHsc4B5n1E9KFIY2myK:-987337675)*

**Comment by bryk** [comment]
Will merge when travis is happy. 

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> All done. Will merge soon.</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/735#-:-KHtHwZ0rIWmNFbm0xgQ:-2024641910)*

**Pull request merged**
