### PR TITLE
Run tests that require a browser on saucelabs (FF/Chrome/IE)

### PR DESCRIPTION
**Pull request by bryk**
Sample report from an integration test:
https://saucelabs.com/beta/tests/7e6958fd51d44abfbb7a5e7a1efe132a/commands
See, e.g., screencast that you can play or see history.

### CODE REVIEW

**Comment by bryk** [comment]
@floreks @cheld Take a look.

**Comment by maciaszczykm** [comment]
Is it possible to display link/results in pull requests like in codecov case?

**Comment by floreks** [comment]
Report looks great. Very detailed. Just fix travis and LGTM

**Comment by bryk** [comment]
> Is it possible to display link/results in pull requests like in codecov case?

When you open travis build logs you can find the links there. That's all I know.

**Comment by bryk** [comment]
I think I need to merge this PR manually. Saucelabs does not start from a fork.

**Comment by bryk** [comment]
Wish me luck... :)

**Comment by bryk** [comment]
It worked, you can see the output here: https://travis-ci.org/kubernetes/dashboard/builds/108497768

**Comment by floreks** [comment]
Doesn't it mean that all our PRs will also fail?

**Comment by bryk** [comment]
They shouldn't. The problem was that I was adding new addon to travis from an external pull request. Now that it is there, it should work.

**Pull request merged**
