### PR TITLE
Fixing LocaleHandler

### PR DESCRIPTION
**Pull request by f-higashi**
Now  LocaleHandler does not work when Accept-Language has multi language;ex) 'ja,en-US'.
I fixed it.

And defer is used in for loop at localehandler_test.go. It is not good, because defer is executed at the end of function.
So I added anonymous function to execute it each loop.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/769)

### CODE REVIEW

**Comment by taimir** [comment]
Review status: 0 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/backend/handler/localehandler.go, line 91 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/769#-KIb8oLUJNKPztzv5xLI:-KIb8oLUJNKPztzv5xLJ:-132481625) ([raw file](https://github.com/kubernetes/dashboard/blob/9931913cd91ded23f1d74d2b9571e57d18654fbe/src/app/backend/handler/localehandler.go#L91)):*
> ```Go
> 
> func (handler *LocaleHandler) determineLocalizedDir(locale string) string {
> 	tags, _, err := language.ParseAcceptLanguage(locale)
> ```

I love this! Much more robust than my ad-hoc implementation :D

---

*[src/test/backend/handler/localehandler_test.go, line 37 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/769#-KIb7Z653plJS9fbKFkE:-KIb7Z653plJS9fbKFkF:-277281706) ([raw file](https://github.com/kubernetes/dashboard/blob/9931913cd91ded23f1d74d2b9571e57d18654fbe/src/test/backend/handler/localehandler_test.go#L37)):*
> ```Go
> 				t.Fatalf("%s", err)
> 			}
> 			defer os.Remove(configFile.Name())
> ```

Here, I am not convinced the `func()` wrapper is actually needed. Defer calls are stacked, and then all are executed at the end of the function call. [ioutils.TempFile](https://golang.org/src/io/ioutil/tempfile.go?s=1288:1345#L37) actually creates different temp files, with the specified name as a prefix. I do not see a reason to delete them directly after each test case.

---

*[src/test/backend/handler/localehandler_test.go, line 111 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/769#-KIb7NUlEqQMxYlfJ65V:-KIb7NUlEqQMxYlfJ65W:-62658433) ([raw file](https://github.com/kubernetes/dashboard/blob/9931913cd91ded23f1d74d2b9571e57d18654fbe/src/test/backend/handler/localehandler_test.go#L111)):*
> ```Go
>                         "af,en-US;q=0.8,en;q=0.6",
>                         "./public/en",
>                 },
> ```

The above test case has strange formatting (identation). Can you fix this?

---

*[src/test/backend/handler/localehandler_test.go, line 123 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/769#-KIb72WLtIvoqSviTjRE:-KIb72WLtIvoqSviTjRF:-507586391) ([raw file](https://github.com/kubernetes/dashboard/blob/9931913cd91ded23f1d74d2b9571e57d18654fbe/src/test/backend/handler/localehandler_test.go#L123)):*
> ```Go
> 
> 	for _, c := range cases {
> 		func(){
> ```

Nice catch. It is correct to clean up the `./public` on each test case. Otherwise unexpected things might occur.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/769)*

**Comment by taimir** [comment]
PTAL, a few comments from my side :)

<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> #### Fixing LocaleHandler
> 
> Now  LocaleHandler does not work when Accept-Language has multi language;ex) 'ja,en-US'.
> 
> I fixed it.
> 
> 
> 
> 
> 
> And defer is used in for loop at localehandler_test.go. It is not good, because defer is executed at the end of function.
> 
> So I added anonymous function to execute it each loop.
> 
> 
> 
</details>


---

Review status: 0 of 21 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/769#-:-KIb92GRhzjgffJxPfuF:1155953981)*

**Comment by f-higashi** [comment]
Review status: 0 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/test/backend/handler/localehandler_test.go, line 37 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/769#-KIb7Z653plJS9fbKFkE:-KIbAZPXbTeS4K5bU7Qg:-335228335) ([raw file](https://github.com/kubernetes/dashboard/blob/9931913cd91ded23f1d74d2b9571e57d18654fbe/src/test/backend/handler/localehandler_test.go#L37)):*
<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> Here, I am not convinced the `func()` wrapper is actually needed. Defer calls are stacked, and then all are executed at the end of the function call. [ioutils.TempFile](https://golang.org/src/io/ioutil/tempfile.go?s=1288:1345#L37) actually creates different temp files, with the specified name as a prefix. I do not see a reason to delete them directly after each test case.
</details>
Thanks.
I misunderstood to create same name file.
I'll fix it. 

---

*[src/test/backend/handler/localehandler_test.go, line 111 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/769#-KIb7NUlEqQMxYlfJ65V:-KIbBpB9CpFoe13Baxd5:1756469165) ([raw file](https://github.com/kubernetes/dashboard/blob/9931913cd91ded23f1d74d2b9571e57d18654fbe/src/test/backend/handler/localehandler_test.go#L111)):*
<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> The above test case has strange formatting (identation). Can you fix this?
</details>
Thanks.
I'll fix this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/769)*

**Comment by taimir** [comment]
Reviewed 2 of 21 files at r1.
Review status: 2 of 21 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/769)*

**Comment by f-higashi** [comment]
PTAL

**Comment by taimir** [comment]
Reviewed 1 of 21 files at r1, 1 of 1 files at r2.
Review status: 3 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[Godeps/Godeps.json, line 514 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/769#-KIbJZQJm1vF-tmqP7QI:-KIbJZQJm1vF-tmqP7QJ:-1292154362) ([raw file](https://github.com/kubernetes/dashboard/blob/8d58850ea2dbd47e81a5499b8e1233817fd02eae/Godeps/Godeps.json#L514)):*
> ```JSON
> 		},
> 		{
> 			"ImportPath": "k8s.io/kubernetes/pkg/controller/framework",
> ```

Were those packages missing in the `Godeps.json` file before? Do we need them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/769)*

**Comment by taimir** [comment]
PTAL, one last question - otherwise LGTM

<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> PTAL
</details>


---

Review status: 3 of 21 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/769#-:-KIbK51JfOMsT0IsJc1L:-581939835)*

**Comment by f-higashi** [comment]
Review status: 3 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[Godeps/Godeps.json, line 514 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/769#-KIbJZQJm1vF-tmqP7QI:-KIbLfA6912qcpZ_GKbr:-712940902) ([raw file](https://github.com/kubernetes/dashboard/blob/8d58850ea2dbd47e81a5499b8e1233817fd02eae/Godeps/Godeps.json#L514)):*
<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> Were those packages missing in the `Godeps.json` file before? Do we need them?
</details>
Godeps.json is updated automatically by `godep save ./src/app/backend`.
Maybe it works without 'k8s.io/kuberentes/pkg/controller/framework'.
But I think it is better not to modify created file automatically unless it occurs critical issue. 

BTW, 
When I executed `godev save ./src/app/backend`at first, I met the following error.
```
godep: Package (github.com/kubernetes/dashboard/client) not found
```

So I added .tmp/backend to GOPATH to avoid error.
It works. But I think it is not good way.
This way might add the needless line.

I cannot find other way.
Do you know any good way?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/769)*

**Comment by bryk** [comment]
@taimir, me or @floreks @maciaszczykm @cheld when this is ready to merge :)

**Comment by taimir** [comment]
LGTM

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> @taimir, me or @floreks @maciaszczykm @cheld when this is ready to merge :)
</details>


---

Reviewed 18 of 21 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Godeps/Godeps.json, line 514 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/769#-KIbJZQJm1vF-tmqP7QI:-KIb_oLRxaTxS2lRnY49:-1531191604) ([raw file](https://github.com/kubernetes/dashboard/blob/8d58850ea2dbd47e81a5499b8e1233817fd02eae/Godeps/Godeps.json#L514)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> Godeps.json is updated automatically by `godep save ./src/app/backend`.
> Maybe it works without 'k8s.io/kuberentes/pkg/controller/framework'.
> But I think it is better not to modify created file automatically unless it occurs critical issue. 
> 
> BTW, 
> When I executed `godev save ./src/app/backend`at first, I met the following error.
> ```
> godep: Package (github.com/kubernetes/dashboard/client) not found
> ```
> 
> So I added .tmp/backend to GOPATH to avoid error.
> It works. But I think it is not good way.
> This way might add the needless line.
> 
> I cannot find other way.
> Do you know any good way?
> 
</details>
First of all, LGTM as it is right now, and thanks for updating the Godeps. I just wanted to get the picture here.

It looks like we need to do a `godep save ./src/app/backend` more often, otherwise the content of the Godeps.json becomes obsolete. I guess the `Godeps/_workspace` is just populated with more than just the specific packages in the Godeps.json (e.g. whole kubernetes /src), hence why we don't get any problems. 

However, the `_workspace` was definitely not in sync with the Godeps.json before this commit.

@floreks, @maciaszczykm what is your take on this? I guess just doing `godep save ./src/app/backend` often will keep the Godeps.json updated.

About your second point: well I see no better solution besides what you did. It does not add an additional line to the `Godeps.json`, so that's fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/769#-:-KIbcTXLLdlLsn1rDQrw:676834233)*

**Comment by taimir** [comment]
@floreks, @maciaszczykm Can one of you just quickly check my last comment about the Godeps.json, and see if you agree?

Apart from that: LGTM , you can merge this :)

**Comment by bryk** [comment]
I guess I'll merge this :)

**Pull request merged**
