### PR TITLE
Move check and test script to pre-push git hook

### PR DESCRIPTION
**Pull request by damingerdai**
`check` and `test` scripts should be in `pre-push` git hook.

### CODE REVIEW

**Comment by floreks** [comment]
Any particular reason tests should be executed before push instead of commit? Seems like a personal preference to me.

**Comment by damingerdai** [comment]
> Any particular reason why tests should be executed before push instead of commit? Seems like a personal preference to me.

I admit that there is a personal preference. but i think pre-push is better than pre-commit. It will takes a lot of time in run `check` and `test` script when we commit code.Usually, there will be multiple commits in a pr. So I suggest that we should use pre-push, this is just to submit the code to execute the check and test commands.

**Comment by shu-mutou** [comment]
/lgtm
Agree. When rebasing own PR to master to resolve conflicts, checks and tests run for each commit and it takes lots of time.

**Comment by damingerdai** [comment]
@shu-mutou thanks for your support

**Pull request merged**
