### PR TITLE
Add admin category page

### PR DESCRIPTION
**Pull request by bryk**
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1206)

### CODE REVIEW

**Comment by bryk** [comment]
@digitalfishpond Can you review?

**Comment by digitalfishpond** [comment]
Would it be nice to show a card for Persistent Volumes with a zerostate when there are none to show here to show that this page can show Persistent Volumes?

**Comment by digitalfishpond** [comment]
Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/admin/module.js, line 46 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1206#-KRDel4vHNu_GydOfq-U:-KRDel4vHNu_GydOfq-V:b-bccsdx) ([raw file](https://github.com/kubernetes/dashboard/blob/f19ef4b7b28e2e39dcca3e1e1e417d6046911b6d/src/app/frontend/admin/module.js#L46)):*
> ```JavaScript
>  */
> function resource($resource) {
>   return $resource('api/v1/admin');
> ```

Codecov says this is not yet covered by tests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1206)*

**Comment by digitalfishpond** [comment]
Couple comments

---

Reviewed 17 of 20 files at r1.
Review status: 17 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/admin/admin.html, line 42 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1206#-KRDkLi5Ism8lKwkoKYY:-KRDkLi5Ism8lKwkoKYZ:b-l7sgmv) ([raw file](https://github.com/kubernetes/dashboard/blob/f19ef4b7b28e2e39dcca3e1e1e417d6046911b6d/src/app/frontend/admin/admin.html#L42)):*
> ```HTML
>     </kd-content>
>   </kd-content-card>
>   <kd-content-card ng-if="$ctrl.admin.persistentVolumeList.items.length">
> ```

I could make a new issue to add zerostate card in the event of !$ctrl.admin.persistentVolumeList.items.length ? What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1206#-:-KRDlRQUKYfxw8_5-DVX:b-ffwar5)*

**Comment by digitalfishpond** [comment]
Reviewed 1 of 20 files at r1.
Review status: 18 of 20 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1206)*

**Comment by bryk** [comment]
PTAL 

---

Review status: 18 of 21 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/admin/admin.html, line 42 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1206#-KRDkLi5Ism8lKwkoKYY:-KRE0P5lXs-MvTNnD7c-:b-amtkh2) ([raw file](https://github.com/kubernetes/dashboard/blob/f19ef4b7b28e2e39dcca3e1e1e417d6046911b6d/src/app/frontend/admin/admin.html#L42)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> I could make a new issue to add zerostate card in the event of !$ctrl.admin.persistentVolumeList.items.length ? What do you think?
</details>
Hmm... Workloads page does not do this. Can we leave it as it is and fix the problem later? We're on tight schedule due to the release 

---

*[src/app/frontend/admin/module.js, line 46 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1206#-KRDel4vHNu_GydOfq-U:-KRECDm8MKyj4GBd2bY9:b-896fix) ([raw file](https://github.com/kubernetes/dashboard/blob/f19ef4b7b28e2e39dcca3e1e1e417d6046911b6d/src/app/frontend/admin/module.js#L46)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> Codecov says this is not yet covered by tests
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1206#-:-KREDG1WZ5833xmomLhK:b-833310)*

**Comment by digitalfishpond** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1206#-:-KRS0ZGz3s5YQk8AcotG:bnfp4nl)*

**Comment by digitalfishpond** [comment]
Reviewed 2 of 20 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1206)*

**Pull request merged**
