### PR TITLE
Localization of DaemonSetList and -Details views

### PR DESCRIPTION
**Pull request by taimir**
One more localization batch.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/834)

### CODE REVIEW

**Comment by taimir** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/daemonsetlist/daemonsetlist_component.js, line 83 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/834#-KJ_nMWX9gNSy32FhInl:-KJ_nMWX9gNSy32FhInm:-1769362368) ([raw file](https://github.com/kubernetes/dashboard/blob/eca4e8065193455386710a5d0c34adb326c70470/src/app/frontend/daemonsetlist/daemonsetlist_component.js#L83)):*
> ```JavaScript
>    */
>   getCreatedAtTooltip(creationDate) {
>     let filter = this.interpolate_(`{{date | date:'short'}}`);
> ```

@bryk here's another small bump: I had to localize an expression with a filter. Any better ideas for handling this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/834)*

**Comment by taimir** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/daemonsetdetail/daemonsetinfo_component.js, line 30 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/834#-KJa2rsr7iHSnBc-baxU:-KJa2rsr7iHSnBc-baxV:522816460) ([raw file](https://github.com/kubernetes/dashboard/blob/3000dc26b1bd46fbfd9c9b2c8e800c69e1c8a3be/src/app/frontend/daemonsetdetail/daemonsetinfo_component.js#L30)):*
> ```JavaScript
> 
>     /** @export */
>     this.i18n = i18n(this.daemonSet);
> ```

What do you think, is it O.K. to pass the injected (from `html`) daemonSet like that? It works fine, but I had to add additional checks below so that the unit-tests could pass (there the controller is constructed in javascript, so this object is actually not set).

Should I maybe ditch the checks and rely on a "contract" that daemonSet will not be null?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/834)*

**Comment by bryk** [comment]
Reviewed 5 of 8 files at r1, 2 of 2 files at r3.
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/daemonsetdetail/daemonsetinfo_component.js, line 30 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/834#-KJa2rsr7iHSnBc-baxU:-KJdgi35QEM3RhFvHnD2:-796996965) ([raw file](https://github.com/kubernetes/dashboard/blob/3000dc26b1bd46fbfd9c9b2c8e800c69e1c8a3be/src/app/frontend/daemonsetdetail/daemonsetinfo_component.js#L30)):*
<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> What do you think, is it O.K. to pass the injected (from `html`) daemonSet like that? It works fine, but I had to add additional checks below so that the unit-tests could pass (there the controller is constructed in javascript, so this object is actually not set).
> 
> Should I maybe ditch the checks and rely on a "contract" that daemonSet will not be null?
</details>
This is a very good way of doing this. 

In unit tests you don't have to do big changes. When testing this controller, we always call `$componentController`. First argument is name of component, second injection overrides and last is controller bindings, so you can call this:
`$componentController('kdFoo', null, {daemonSet: bar});`.

Does this help? 

---

*[src/app/frontend/daemonsetlist/daemonsetlist_component.js, line 83 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/834#-KJ_nMWX9gNSy32FhInl:-KJdgaFsyv1JkKpYRdsi:-266523046) ([raw file](https://github.com/kubernetes/dashboard/blob/eca4e8065193455386710a5d0c34adb326c70470/src/app/frontend/daemonsetlist/daemonsetlist_component.js#L83)):*
<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> @bryk here's another small bump: I had to localize an expression with a filter. Any better ideas for handling this?
</details>
This is perfect, imo :) I like the way you're handling this. LGMT 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/834)*

**Comment by taimir** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/daemonsetdetail/daemonsetinfo_component.js, line 30 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/834#-KJa2rsr7iHSnBc-baxU:-KJixKKHcm5Qyyq6QL2d:-87716204) ([raw file](https://github.com/kubernetes/dashboard/blob/3000dc26b1bd46fbfd9c9b2c8e800c69e1c8a3be/src/app/frontend/daemonsetdetail/daemonsetinfo_component.js#L30)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> This is a very good way of doing this. 
> 
> In unit tests you don't have to do big changes. When testing this controller, we always call `$componentController`. First argument is name of component, second injection overrides and last is controller bindings, so you can call this:
> `$componentController('kdFoo', null, {daemonSet: bar});`.
> 
> Does this help? 
</details>
Yeah, that's what I thought I should do here, just wanted to confirm :) will update this in a second.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/834)*

**Comment by taimir** [comment]
PTAL

**Comment by bryk** [comment]
:lgtm:

<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> PTAL
</details>


---

Reviewed 4 of 6 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/834#-:-KJnoJR4C4k-9GXn_yEd:1417088721)*

**Pull request merged**
