### PR TITLE
Add logs zerostate info and clean up log controller

### PR DESCRIPTION
**Pull request by floreks**
zrzut ekranu z 2016-08-30 23-34-46

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1172)

### CODE REVIEW

**Comment by digitalfishpond** [comment]
*[src/app/frontend/logs/logs_controller.js, line 117 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1172#-KQUEDJBkBmr8gKqGcC9:-KQUEDJBkBmr8gKqGcCA:b-yoljrv) ([raw file](https://github.com/kubernetes/dashboard/blob/20b3af48d25445fb48e24db23f95bc360b7b3540/src/app/frontend/logs/logs_controller.js#L117)):*
> ```JavaScript
>   /** @export {string} @desc Text for logs card zerostate in logs page. */
>   MSG_LOGS_ZEROSTATE_TEXT:
>       goog.getMsg('There are currently no messages logged by selected container.'),
> ```

'...logged FOR THE selected...' would be my preference here. 
'...logged BY THE selected...' would work grammatically, though I'd argue that if it is very important to imply that the selected container is doing the logging (achieved with 'by'), then the active voice would be clearer, something like: 
'The selected container has not logged any messages yet.' or
'There are currently no logged messages from the selected container'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1172)*

**Comment by digitalfishpond** [comment]
small comment

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1172#-:-KQUHGtaz_NPMAQE36cv:bi7zejl)*

**Comment by floreks** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/logs/logs_controller.js, line 117 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1172#-KQUEDJBkBmr8gKqGcC9:-KQUTQ8oB-cAxDk9-PwT:bfa1i8c) ([raw file](https://github.com/kubernetes/dashboard/blob/20b3af48d25445fb48e24db23f95bc360b7b3540/src/app/frontend/logs/logs_controller.js#L117)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> '...logged FOR THE selected...' would be my preference here. 
> '...logged BY THE selected...' would work grammatically, though I'd argue that if it is very important to imply that the selected container is doing the logging (achieved with 'by'), then the active voice would be clearer, something like: 
> 'The selected container has not logged any messages yet.' or
> 'There are currently no logged messages from the selected container'.
</details>
I agree. `The selected container has not logged any messages yet` sounds better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1172)*

**Comment by bryk** [comment]
@digitalfishpond Please merge when done reviewing :)

**Comment by digitalfishpond** [comment]
:lgtm:  I will merge when Travis passes

---

Reviewed 4 of 4 files at r1, 3 of 3 files at r2.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1172#-:-KQUcdoqnAL4K5pP91Ti:bty9te2)*

**Comment by digitalfishpond** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1172)*

**Pull request merged**
