### PR TITLE
Mocks for navigation and UX that scales for all K8s resources

### PR DESCRIPTION
**Pull request by bryk**
* this will be used later in a design doc proposal
* also renamed old mocks folder to tell more than just date

See: #584

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/585)

### CODE REVIEW

**Comment by bryk** [comment]
@olekzabl Can you review?

**Comment by olekzabl** [comment]
A few issues:

- navigation.png: "togheder" -> "together"
- manu-extended.png: "manu" -> "menu" (in the file name)
- rc-details-page-events.png: tooltips disagree with pic! section
"Properties of the object" does not exist
- some inconsistencies between details pages:
  - "Properties in structurized form" in {pod,rc}-details-page-overview.png
look different (no "State" on the latter)
  - Headers of link sections are named by object types in
{pod,rc}-d-p-o.png while by roles in details-page-template.png
    (ideally, the header should perhaps combine the role and the target
object type)

**Comment by floreks** [comment]
> - rc-details-page-events.png: tooltips disagree with pic! section
Ups, I will fix that.

> - some inconsistencies between details pages:
  - "Properties in structurized form" in {pod,rc}-details-page-overview.png
look different (no "State" on the latter)

This is just a proposal. Should we actually group properties by some common purpose? Tell me which one you like better and I'll adjust other.

>  - Headers of link sections are named by object types in
{pod,rc}-d-p-o.png while by roles in details-page-template.png
    (ideally, the header should perhaps combine the role and the target
object type)

I'm not sure I know what you mean. Are you referring to the `Pod > <name>` section on top near action buttons? Is it wrong? On the template we've got `Resource 1 > foo instance` which I believe is correct. Could you elaborate?

**Comment by floreks** [comment]
Please find update rc - events mock [here](https://drive.google.com/open?id=0B4DGVEQHPRToSVA0Zk9vWVZmMGM)

**Comment by bryk** [comment]
> Please find update rc - events mock here

Can you post the source?

**Comment by floreks** [comment]
[Here](https://drive.google.com/open?id=0B4DGVEQHPRToT2s5WFVUN2ROTEk) is the link to balsamiq project

**Comment by bryk** [comment]
All addressed. PTAL. 

@floreks You can delete the links you've posted.

**Comment by bryk** [comment]
I'll merge to base design doc on this. Any comments can be addressed in follow up PRs.

**Pull request merged**
