### PR TITLE
Japanese localization of some other resource detail page

### PR DESCRIPTION
**Pull request by Yamagami-Takuma**
Japanese localization of some other resource detail page.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/883)

### CODE REVIEW

**Comment by Yamagami-Takuma** [comment]
@f-higashi Can you review this?

**Comment by f-higashi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[i18n/messages-ja.xtb, line 344 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/883#-KK7pdqplz3chFodYTqj:-KK7pdqqElJij4859qpk:638413187) ([raw file](https://github.com/kubernetes/dashboard/blob/d3e433ac750454c6cca4e92d92b0e588e39b3646/i18n/messages-ja.xtb#L344)):*
> ```
> 	<translation id="2597227860468168985" key="MSG_DEPLOYMENT_DETAIL_NAME_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label 'Name' for the deployment name on the deployment details page.">名前</translation>
> 	<translation id="8073815784825425871" key="MSG_DEPLOYMENT_DETAIL_LABELS_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label 'Label selector' for the deployment's labels list on the deployment details page.">ラベル</translation>
> 	<translation id="284479654293253491" key="MSG_DEPLOYMENT_DETAIL_LABEL_SELECTOR_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label 'Label selector' for the deployment's selector on the deployment details page.">ラベルセクター</translation>
> ```

It is wrong.
`ラベルセレクター`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/883)*

**Comment by Yamagami-Takuma** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[i18n/messages-ja.xtb, line 344 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/883#-KK7pdqplz3chFodYTqj:-KK7uPxVFZzG1miFm93Z:1920760566) ([raw file](https://github.com/kubernetes/dashboard/blob/d3e433ac750454c6cca4e92d92b0e588e39b3646/i18n/messages-ja.xtb#L344)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> It is wrong.
> `ラベルセレクター`
</details>
I fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/883)*

**Comment by f-higashi** [comment]
:lgtm: 

you can merge this :)
@maciaszczykm

<details><summary><i>Previously, Yamagami-Takuma wrote…</i></summary>
> @f-higashi Can you review this?
</details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/883#-:-KKBMA9XOYpxQ--tdJXB:-1510127019)*

**Comment by maciaszczykm** [comment]
@Yamagami-Takuma Please rebase.

**Comment by Yamagami-Takuma** [comment]
@maciaszczykm It's done :)

**Comment by maciaszczykm** [comment]
@Yamagami-Takuma Thanks, I'll merge as soon as CI will be finished :)

**Pull request merged**
