### PR TITLE
Remove endpoints from RCs and add them to services

### LINKED ISSUE #836: service object doesn't have ExternalEndpoints data
src/app/backend/resource/service/servicecommon.go doesn't have ExternalEndpoints implemented

### LINKED ISSUE #854: Remove endpoints from RC lists; just show them for services
Remove endpoints from RC lists; just show them for services. This will add one click, but make things more consistent and aligned with what we have in kubectl and docs.

### PR DESCRIPTION
**Pull request by bryk**
Fixes #854, Fixes #836

This PR has also a nice benefit of speeding things up, as I removed
calls to Nodes and Services from most pages.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/864)

### CODE REVIEW

**Comment by bryk** [comment]
@olekzabl @maciaszczykm Can you review?

**Comment by bryk** [comment]
Removing @olekzabl

**Comment by maciaszczykm** [comment]
Travis needs fixing.

**Comment by bryk** [comment]
PTAL

**Comment by maciaszczykm** [comment]
:lgtm:

<details><summary><i>Previously, codecov-io wrote…</i></summary>
> ## [Current coverage][cc-pull] is **93.91%**
> > Merging [#864][cc-pull] into [master][cc-base-branch] will increase coverage by **0.32%**
> 
> 1. File `...ereader_directive.js` (not in diff) was modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/cf62226e19128a3806068826db6cf58948618306/changes?src=pr#7372632F6170702F66726F6E74656E642F6465706C6F792F66696C657265616465725F6469726563746976652E6A73) 
>   - Misses `-6` 
>   - Partials `0` 
>   - Hits `+6`
> 
> ```diff
> @@             master       #864   diff @@
> ==========================================
>   Files           223        223          
>   Lines          1874       1874          
>   Methods           0          0          
>   Messages          0          0          
>   Branches          0          0          
> ==========================================
> + Hits           1754       1760     +6   
> + Misses          120        114     -6   
>   Partials          0          0          
> ```
> 
> > Powered by [Codecov](https://codecov.io?src=pr). Last updated by [1c659b2...cf62226][cc-compare]
> [cc-base-branch]: https://codecov.io/gh/kubernetes/dashboard/branch/master?src=pr
> [cc-compare]: https://codecov.io/gh/kubernetes/dashboard/compare/1c659b22e8ddfe13e769ea6fdc872a982a0b585a...cf62226e19128a3806068826db6cf58948618306
> [cc-pull]: https://codecov.io/gh/kubernetes/dashboard/pull/864?src=pr
</details>


---

Reviewed 19 of 23 files at r1, 3 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/864#-:-KJt_c194CAglK2WPsRW:1417088721)*

**Pull request merged**
