### PR TITLE
show pvc storage capacity when it is pending

### PR DESCRIPTION
**Pull request by helight**
show the pvc storage capacity when it is pending, 
I think it is useful to know the pvc storage capacity whether it is pending or not.

### CODE REVIEW

**Comment by floreks** [comment]
This changes the underneath logic and displays something else than the actual capacity. If anything, it should be conditionally determined based on status, not changed like that.

/close

**Comment by helight** [comment]
> This changes the underneath logic and displays something else than the actual capacity. If anything, it should be conditionally determined based on status, not changed like that.
> 
> /close

I think the status of pvc and the property of pvc is different,  
status is for running time, 
property is some attribute that the pvc should have wether it is running or not.

**Comment by helight** [comment]
image

**Comment by helight** [comment]
image

**Comment by shu-mutou** [comment]
+1 for @helight
Capacity of PV might be changed by status, i.e. bound PVC, but capacity fo PVC would not be changed, I think.
If this merged, we would not need to memorize PVC capacity anymore.

**Comment by shu-mutou** [comment]
How about simply adding Spec.Resources.Requests. If so, it is easy to notice about difference in PVC request and capacity of bound PV.

**Pull request closed without merging**
