### PR TITLE
Updated OWNERS file to include link to docs

### PR DESCRIPTION
**Pull request by rlenferink**

### CODE REVIEW

**Comment by floreks** [comment]
I don't see such comment at i.e. kubernetes repo `OWNERS` file.

**Comment by rlenferink** [comment]
I'm still working through the repos to get them included:
https://github.com/kubernetes-sigs/cluster-api/pull/729
https://github.com/kubernetes/cloud-provider-gcp/pull/81
https://github.com/kubernetes-client/go/pull/20
https://github.com/kubernetes/utils/pull/79
https://github.com/kubernetes/test-infra/pull/11044
https://github.com/kubernetes/community/pull/3172
https://github.com/kubernetes/org/pull/435

A PR with k/k is still open and needs some fine-tuning before getting merged:
https://github.com/kubernetes/kubernetes/pull/73540

It is not necessarily a thing we _require_ to have. It is more of a convenience link for contributors looking for the documentation of our processes.

**Pull request merged**
