### PR TITLE
remove some useless code in handler/apihandler.api

### PR DESCRIPTION
**Pull request by zehuaiWANG**
remove some useless code in handler/apihandler.api

### CODE REVIEW

**Comment by zehuaiWANG** [comment]
@maciaszczykm @floreks I am not sure why the codecov test is wrong， could you help me to modefied it， thanks a lot.

**Comment by zehuaiWANG** [comment]
Is it mean I should add some code to test the function in aggregation.go?

**Comment by maciaszczykm** [comment]
> Is it mean I should add some code to test the function in aggregation.go?

It would be great.

**Pull request merged**
