### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by shu-mutou**
Bump ngx-cookie-service and angular staffs.
This also fixes errors in dependabot.

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@shu-mutou We have to disable the CodeQL check for logging user inputs for now. It was added because of log4j vulnerability but we are not using Java. Can you do it so we can merge this pull request? Also, it would be nice to create an issue for restoring this check once we will improve logging.

**Comment by shu-mutou** [comment]
@maciaszczykm As of now, I dismissed all of alert for logging in this PR and create issue #6663, Also, I'm investigating how to configure CodeQL.

**Comment by shu-mutou** [comment]
dependency error between ngx-cookie-service and angular on dependabot was fixed, but version conflicts in nodejs and npm remain.
we need to wait for nodejs v16 support in dependabot https://github.com/dependabot/dependabot-core/issues/4359

**Comment by shu-mutou** [comment]
dependabot supports npm v6 and v7 for now.
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem

**Comment by shu-mutou** [comment]
Ref. https://github.com/dependabot/dependabot-core/pull/4537

**Comment by shu-mutou** [comment]
We need to wait for support nodejs v16 and npm v8.
https://github.com/dependabot/dependabot-core/pull/4531

**Pull request merged**
