### PR TITLE
[helm] Add tpl function to config and ingress for supporting umbrella charts

### PR DESCRIPTION
**Pull request by jkroepke**
Having the tpl function in place here is a real benefit, since a central helm value can be used for ingress hostname across all subscharts.

Various other helm charts like kube-prometheus-stack, grafana, blackbox_exporter, grafana loki are supporting this style, too.

### CODE REVIEW

**Comment by desaintmartin** [comment]
Thanks! Could you bump chart version? From experience, this is indeed beneficial, but can be hard to properly setup.

**Comment by jkroepke** [comment]
Rebased and bumped

**Comment by desaintmartin** [comment]
@floreks
- what is the policy now? Is it okay to merge / bump?
- Could you trigger tests?

**Comment by jkroepke** [comment]
How we can proceed here?

**Comment by jkroepke** [comment]
Merged from main (to fix CI issues)

**Pull request closed without merging**
