### PR TITLE
Frontend for pods list and workloads section

### PR DESCRIPTION
**Pull request by bryk**
After this is merged I'll be working on "commonization" of things.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/724)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you review?

**Comment by floreks** [comment]
1 comment and :lgtm:

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> @floreks Can you review? </details>


---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetail.html, line 27 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/724#-KHK_DH-wu5V9gyD20FA:-KHK_DH-wu5V9gyD20FB:1195020953) ([raw file](https://github.com/kubernetes/dashboard/blob/c29880eaec6c1720cd8589c61fc57265529f7e4b/src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetail.html#L27)):*
> ```HTML
>         </kd-replication-controller-services>
> 
>         <kd-content-card>
> ```

Title missing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/724#-:-KHK_d46EaDcpHNKLOzJ:-1292453590)*

**Comment by bryk** [comment]
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetail.html, line 27 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/724#-KHK_DH-wu5V9gyD20FA:-KHOaZVdg-V840ajYb6n:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/c29880eaec6c1720cd8589c61fc57265529f7e4b/src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetail.html#L27)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Title missing</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/724)*

**Comment by bryk** [comment]
Reviewed 1 of 13 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/724)*

**Pull request merged**
