### PR TITLE
Fix a FailedMount error

### PR DESCRIPTION
**Pull request by zhoudongyan**
The Message of this error: `MountVolume.SetUp failed for volume "kubernetes-dashboard-certs" : secrets "kubernetes-dashboard-certs" not found`

### CODE REVIEW

**Comment by zhoudongyan** [comment]
Have signed license agreement.

**Comment by floreks** [comment]
Great catch! We can't actually change name of the cert as it is hard dependency in our code. I have reverted the name change and it will be fixed on monday when we merge #2516 and release 1.8.0. Thanks!

**Comment by floreks** [comment]
Fixed by #2516.

**Comment by zhangjianweibj** [comment]
hilo,@zhoudongyan how to sign license agreement.
thanks

**Comment by zhangjianweibj** [comment]
I have a similar problem.intergeration test run error,"Error: License headers need to be present in all files."

"Header not present /home/travis/build/kubernetes/dashboard/src/app/frontend/networkpolicy/list/list.html
/home/travis/build/kubernetes/dashboard/build/check.js:193
      throw new Error('License headers need to be present in all files.');
      ^
Error: License headers need to be present in all files."

**Comment by zhoudongyan** [comment]
@zhangjianweibj To sign a license agreement, please read the comment of `k8s-ci-robot` under this issue.

**Comment by zhangjianweibj** [comment]
image
yeah,i hava signed the CLA,but integration test alse error.
" License headers need to be present in all files."

**Comment by zhoudongyan** [comment]
@zhangjianweibj You need make sure that `License headers` is present in all files you added.

**Comment by zhangjianweibj** [comment]
very thanks

**Pull request closed without merging**
