### PR TITLE
Add xliffmerge to update translated files

### PR DESCRIPTION
**Pull request by shu-mutou**
To apply differences of `i18n/messages.xlf` into treanslated files, i.e. `messages.[locale].xlf` like `messages.fr.xlf` and `messages.ja.xlf`, introduce `xliffmerge` and run it after `ng xi18n`.

**documentation for i18n will be added by #4012**

### CODE REVIEW

**Comment by shu-mutou** [comment]
@feloy Could you review too this PR and [draft for wiki](https://github.com/shu-mutou/dashboard/wiki/Internationalization)?

**Comment by feloy** [comment]
I fixed some typo on the wiki

/approve

**Comment by shu-mutou** [comment]
@feloy Thanks!!

**Comment by shu-mutou** [comment]
@maciaszczykm @floreks If this PR looks good to you, please add i18n wiki for 2.0.0 (or later) from [my draft](https://github.com/shu-mutou/dashboard/wiki/Internationalization).

**Comment by shu-mutou** [comment]
We have changed i18n file format and dropped i18n files for former version. But now, this PR and updating wiki page would complete new pipeline for i18n. So I'm considering to inform Chinese and Korean i18n team that their language files have already removed from master branch, and ask them to re-create i18n files before 2.0.0 release (this summer?).

**Comment by floreks** [comment]
Looks nice! We should be doing an alpha release somewhere this week. You can also do some high level manual tests of development image to see if there are no major blockers. We should be ready for beta in a month.

PS. Can you resolve conflicts?

**Comment by shu-mutou** [comment]
Rebased and resolved conflicts. Alpha release is very nice timing to start translate! 😄

**Comment by shu-mutou** [comment]
@maciaszczykm @floreks Documentation for i18n will be added by #4012. BTW, do we need more review?

**Comment by maciaszczykm** [comment]
No, thank you.

/lgtm
/approve

**Pull request merged**
