### PR TITLE
Remove inactive members from OWNERS

### PR DESCRIPTION
**Pull request by jeefy**
Ref: https://github.com/kubernetes/org/issues/2013

/assign @floreks @maciaszczykm 
/cc @mrbobbytables

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Looks good to me. IIRC @konryd and @danielromlein are also inactive.

@floreks do you have any input?

**Comment by maciaszczykm** [comment]
https://github.com/kubernetes/dashboard/blob/e71222aaf5e555dcf794f071f27e54fe99996096/ROLES.md has also be updated.

**Comment by maciaszczykm** [comment]
https://github.com/kubernetes/kubernetes/blob/4923292161e77d5b52303481d62fc9810b6e37fc/cluster/addons/dashboard/OWNERS and this.

**Comment by maciaszczykm** [comment]
https://github.com/kubernetes/dashboard/blob/c9a6895a8f7cd572d992ec04e244fceeaaeb9e98/SECURITY_CONTACTS and this.

**Comment by floreks** [comment]
I'd propose to do a full cleanup. Most people are already inactive for at least a year or more.

**Pull request merged**
