### PR TITLE
feat: added additional rules option to role

### PR DESCRIPTION
**Pull request by elizaitsev**
I wanted to add an option to add additional rules to role, the same way clusterrole has it.

Issue: https://github.com/kubernetes/dashboard/issues/7369

### CODE REVIEW

**Comment by desaintmartin** [comment]
Thanks! Could you bump minor version of chart in CharT.yaml, document the value in values.yaml?
/assign

**Comment by desaintmartin** [comment]
Thanks!
/assign
@floreks, could you trigger tests?

**Comment by maciaszczykm** [comment]
@desaintmartin Done.

**Pull request merged**
