### PR TITLE
Frontend for deployment list and workloads

### PR DESCRIPTION
**Pull request by bryk**
This looks much like a compy&paste (which is mostly true), but that's
the plan. I want to implement the list pages now and then extract common
patterns, if any.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/717)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you review?

**Comment by floreks** [comment]
Just 1 small comment. Otherwise :lgtm:

---

Reviewed 21 of 22 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/deploymentlist/deploymentcard.html, line 30 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/717#-KH4xv5DoNEEtlCHl270:-KH4xv5DoNEEtlCHl271:-636898172) ([raw file](https://github.com/kubernetes/dashboard/blob/1e35bfb3e20d4c00d7d4c9b254d09338b48ca46d/src/app/frontend/deploymentlist/deploymentcard.html#L30)):*
Needs css class. I've noticed the same thing in replica set list

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/717#-:-KH4ywKJMkRF-AVhGoNC:65262418)*

**Comment by floreks** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/workloads/workloads.html, line 17 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/717#-KH4zcVniIimQgRkggbS:-KH4zcVniIimQgRkggbT:942079866) ([raw file](https://github.com/kubernetes/dashboard/blob/1e35bfb3e20d4c00d7d4c9b254d09338b48ca46d/src/app/frontend/workloads/workloads.html#L17)):*
What about adding `ng-if=$ctrl.workloads.deploymentList.deployments`? This doesn't need to be displayed if there are no resources to display. Also it would be good to add this check to all card list components.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/717)*

**Comment by floreks** [comment]
What about this one?

**Comment by bryk** [comment]
This got lost. I'll merge it soon. Sounds good?

**Comment by floreks** [comment]
Perfect

**Comment by bryk** [comment]
Rebased. Will merge soon. 

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Perfect</details>


---

Review status: 17 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/workloads/workloads.html, line 17 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/717#-KH4zcVniIimQgRkggbS:-KHe7Ct0diO044rncoy-:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/1e35bfb3e20d4c00d7d4c9b254d09338b48ca46d/src/app/frontend/workloads/workloads.html#L17)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> What about adding `ng-if=$ctrl.workloads.deploymentList.deployments`? This doesn't need to be displayed if there are no resources to display. Also it would be good to add this check to all card list components.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/717#-:-KHe9tjMq3QlAEYgA2bV:1255735958)*

**Comment by bryk** [comment]
Didn't finish. Will merge Monday morning.

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Rebased. Will merge soon. </details>


---

Review status: 17 of 22 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/717#-:-KHeC7D3sp3ssqhrYne0:-2073151640)*

**Comment by bryk** [comment]
Reviewed 1 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: 18 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/deploymentlist/deploymentcard.html, line 30 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/717#-KH4xv5DoNEEtlCHl270:-KHsY-aFimQ4X-oDnHSc:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/1e35bfb3e20d4c00d7d4c9b254d09338b48ca46d/src/app/frontend/deploymentlist/deploymentcard.html#L30)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Needs css class. I've noticed the same thing in replica set list</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/717)*

**Comment by bryk** [comment]
Reviewed 3 of 5 files at r3.
Review status: 21 of 22 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/717)*

**Comment by bryk** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/717)*

**Pull request merged**
