### PR TITLE
Add generic delete actionbar item component

### PR DESCRIPTION
**Pull request by floreks**
This component can provide delete button to actionbar on all resource pages.

Directive name, we could change item to button/resource if it fits better in your opinion.

Regarding this part `ng-class="$ctrl.isFabButton ? 'md-fab md-raised md-mini' : 'md-icon-button'`. Should it be moved to controller method? I'm not sure.

@bryk could you review?

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/752)

### CODE REVIEW

**Comment by bryk** [comment]
Nice! Almost LGTM - a few comments. 

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> #### Add generic delete actionbar item component
> 
> This component can provide delete button to actionbar on all resource pages.
> 
> 
> 
> Directive name, we could change item to button/resource if it fits better in your opinion.
> 
> 
> 
> Regarding this part `ng-class="$ctrl.isFabButton ? 'md-fab md-raised md-mini' : 'md-icon-button'`. Should it be moved to controller method? I'm not sure.
> 
> 
> 
> @bryk could you review?
> 
> 
> 
</details>


---

Reviewed 17 of 23 files at r1.
Review status: 17 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/frontend/common/components/actionbar/actionbardeleteitem.html, line 17 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-KICLhGk6cuFnP3z_GHU:-KICLhGk6cuFnP3z_GHV:1241874095) ([raw file](https://github.com/kubernetes/dashboard/blob/05af5872e2adb3bfe30fd40e0e33c78b8ee2a565/src/app/frontend/common/components/actionbar/actionbardeleteitem.html#L17)):*
> ```HTML
> -->
> 
> <md-button ng-class="$ctrl.isFabButton ? 'md-fab md-raised md-mini' : 'md-icon-button'"
> ```

I'd move this to ctrl :) 

---

*[src/app/frontend/common/components/actionbar/actionbardeleteitem_component.js, line 67 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-KICL_tpSwe3IPz_cina:-KICL_tpSwe3IPz_cinb:1963165272) ([raw file](https://github.com/kubernetes/dashboard/blob/05af5872e2adb3bfe30fd40e0e33c78b8ee2a565/src/app/frontend/common/components/actionbar/actionbardeleteitem_component.js#L67)):*
> ```JavaScript
>                 // Show dialog if there was an error, not user canceling dialog.
>                 this.mdDialog_.show(this.mdDialog_.alert()
>                                         .ok('Ok')
> ```

This is copy paste from list pages. How about moving this to the verber service? 

---

*[src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetailactionbar.html, line 26 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-KICL5gBfEv3bdQjn-rO:-KICL5gBfEv3bdQjn-rP:1502631992) ([raw file](https://github.com/kubernetes/dashboard/blob/05af5872e2adb3bfe30fd40e0e33c78b8ee2a565/src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetailactionbar.html#L26)):*
> ```HTML
>     <md-tooltip md-direction="bottom">Edit number of pods</md-tooltip>
>   </md-button>
>   <kd-actionbar-delete-item resource-kind-name="Pod" type-meta="ctrl.details.typeMeta"
> ```

="Pod"?

---

*[src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetailactionbar.html, line 26 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-KICL785qLTvU9MiyJwu:-KICL785qLTvU9MiyJwv:42201724) ([raw file](https://github.com/kubernetes/dashboard/blob/05af5872e2adb3bfe30fd40e0e33c78b8ee2a565/src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetailactionbar.html#L26)):*
> ```HTML
>     <md-tooltip md-direction="bottom">Edit number of pods</md-tooltip>
>   </md-button>
>   <kd-actionbar-delete-item resource-kind-name="Pod" type-meta="ctrl.details.typeMeta"
> ```

Btw, I have an idea what to do about this. Basically, to register resource kind names in one place so that directives can use it. But this is for later :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-:-KICLz5i7fzqzMIh_MlV:440990171)*

**Comment by floreks** [comment]
Review status: 17 of 23 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/common/components/actionbar/actionbardeleteitem.html, line 17 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-KICLhGk6cuFnP3z_GHU:-KICOyN_6ZCNiOLGU4Ru:913370832) ([raw file](https://github.com/kubernetes/dashboard/blob/05af5872e2adb3bfe30fd40e0e33c78b8ee2a565/src/app/frontend/common/components/actionbar/actionbardeleteitem.html#L17)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> I'd move this to ctrl :) 
</details>
Ye, I wasn't sure about this one

---

*[src/app/frontend/common/components/actionbar/actionbardeleteitem_component.js, line 67 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-KICL_tpSwe3IPz_cina:-KICPDGS0kw3tb7BJYrI:-1849656075) ([raw file](https://github.com/kubernetes/dashboard/blob/05af5872e2adb3bfe30fd40e0e33c78b8ee2a565/src/app/frontend/common/components/actionbar/actionbardeleteitem_component.js#L67)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> This is copy paste from list pages. How about moving this to the verber service? 
</details>
Good idea

---

*[src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetailactionbar.html, line 26 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-KICL5gBfEv3bdQjn-rO:-KICPJuI-Dyv2dwIT4zT:2022270146) ([raw file](https://github.com/kubernetes/dashboard/blob/05af5872e2adb3bfe30fd40e0e33c78b8ee2a565/src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetailactionbar.html#L26)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> ="Pod"?
</details>
Ops :)

---

*[src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetailactionbar.html, line 26 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-KICL785qLTvU9MiyJwu:-KICPScSHp3Bw5UQL0LD:2087902425) ([raw file](https://github.com/kubernetes/dashboard/blob/05af5872e2adb3bfe30fd40e0e33c78b8ee2a565/src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetailactionbar.html#L26)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Btw, I have an idea what to do about this. Basically, to register resource kind names in one place so that directives can use it. But this is for later :) 
</details>
It would  be great.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/752)*

**Comment by floreks** [comment]
Review status: 17 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/frontend/common/components/actionbar/actionbardeleteitem.html, line 17 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-KICLhGk6cuFnP3z_GHU:-KICPtGxFRMMMCAFSM4W:-282594370) ([raw file](https://github.com/kubernetes/dashboard/blob/05af5872e2adb3bfe30fd40e0e33c78b8ee2a565/src/app/frontend/common/components/actionbar/actionbardeleteitem.html#L17)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Ye, I wasn't sure about this one
</details>
Move it all or just expose variable through controller method?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/752)*

**Comment by bryk** [comment]
Reviewed 2 of 23 files at r1.
Review status: 19 of 23 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/common/components/actionbar/actionbardeleteitem.html, line 17 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-KICLhGk6cuFnP3z_GHU:-KICUQ6p8snZRq25DV6N:-846550608) ([raw file](https://github.com/kubernetes/dashboard/blob/05af5872e2adb3bfe30fd40e0e33c78b8ee2a565/src/app/frontend/common/components/actionbar/actionbardeleteitem.html#L17)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Move it all or just expose variable through controller method?
</details>
How about just add a binding to this component called, e.g., `button-classes`? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/752)*

**Comment by bryk** [comment]
PTAL

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Nice! Almost LGTM - a few comments. 
</details>


---

Review status: 19 of 23 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-:-KICU_iXLFKbk8_R9drB:676965300)*

**Comment by floreks** [comment]
Review status: 19 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/common/components/actionbar/actionbardeleteitem.html, line 17 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-KICLhGk6cuFnP3z_GHU:-KICUo904visSR0Drkoj:2138075003) ([raw file](https://github.com/kubernetes/dashboard/blob/05af5872e2adb3bfe30fd40e0e33c78b8ee2a565/src/app/frontend/common/components/actionbar/actionbardeleteitem.html#L17)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> How about just add a binding to this component called, e.g., `button-classes`? 
</details>
Great idea. It will be more flexible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/752)*

**Comment by floreks** [comment]
PTAL

I'll start writing tests

**Comment by bryk** [comment]
Reviewed 3 of 14 files at r2.
Review status: 12 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/common/components/actionbar/actionbardeleteitem_component.js, line 59 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-KICfRsvhgBdWzy1hkrP:-KICfRswgG2vR4mwtWIP:579859002) ([raw file](https://github.com/kubernetes/dashboard/blob/753e8d9f114850a23640497bfc50767edb4f9af3/src/app/frontend/common/components/actionbar/actionbardeleteitem_component.js#L59)):*
> ```JavaScript
>         .then(() => {
>           this.state_.go(this.getFallbackStateName_());
>         }, this.kdResourceVerberService_.deleteErrorCallback.bind(this.kdResourceVerberService_));
> ```

Instead of this you can in the showDeleteDialog do:

```js
return showDeleteDialog(this.mdDialog_, resourceKindName, typeMeta, objectMeta).catch((err) => {this.deleteErrorCallback(err); return err;});
```

This is promise chaining. Then, users of this method can only register for success handlers and ignore error handlers if they like default behavior of alert window.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/752)*

**Comment by floreks** [comment]
PTAL

**Comment by floreks** [comment]
Review status: 9 of 27 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/common/components/actionbar/actionbardeleteitem_component.js, line 59 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-KICfRsvhgBdWzy1hkrP:-KIDBc0GQRkXhKJ1a6QW:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/753e8d9f114850a23640497bfc50767edb4f9af3/src/app/frontend/common/components/actionbar/actionbardeleteitem_component.js#L59)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Instead of this you can in the showDeleteDialog do:
> 
> ```js
> return showDeleteDialog(this.mdDialog_, resourceKindName, typeMeta, objectMeta).catch((err) => {this.deleteErrorCallback(err); return err;});
> ```
> 
> This is promise chaining. Then, users of this method can only register for success handlers and ignore error handlers if they like default behavior of alert window.  
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/752)*

**Comment by bryk** [comment]
Reviewed 1 of 1 files at r3, 1 of 9 files at r4.
Review status: 11 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/common/components/resourcecard/resourcecarddeletemenuitem_component.js, line 51 \[r4\]](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-KIDD2EtatkdQ6v8pdgk:-KIDD2EtatkdQ6v8pdgl:1685149066) ([raw file](https://github.com/kubernetes/dashboard/blob/1c2d4f5635ca42e7e0b112d57ae9bdc71801ffeb/src/app/frontend/common/components/resourcecard/resourcecarddeletemenuitem_component.js#L51)):*
> ```JavaScript
>         .then((data) => {
>           // Do not execute if cancel was clicked
>           if (data) {
> ```

Hey, do you really need this? I think not. Success callback is only called when there were no errors. 

I.e., delete the `if (data)` part. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/752)*

**Comment by bryk** [comment]
Reviewed 8 of 14 files at r2, 6 of 9 files at r4.
Review status: 25 of 27 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/752)*

**Comment by floreks** [comment]
Review status: 25 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/common/components/resourcecard/resourcecarddeletemenuitem_component.js, line 51 \[r4\]](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-KIDD2EtatkdQ6v8pdgk:-KIDGGCCy29teD_l192l:-117487382) ([raw file](https://github.com/kubernetes/dashboard/blob/1c2d4f5635ca42e7e0b112d57ae9bdc71801ffeb/src/app/frontend/common/components/resourcecard/resourcecarddeletemenuitem_component.js#L51)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Hey, do you really need this? I think not. Success callback is only called when there were no errors. 
> 
> I.e., delete the `if (data)` part. 
</details>
Yeah, it is called when there were no errors, that's why it's called when cancel is clicked :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/752)*

**Comment by bryk** [comment]
Review status: 25 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/common/components/resourcecard/resourcecarddeletemenuitem_component.js, line 51 \[r4\]](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-KIDD2EtatkdQ6v8pdgk:-KIDP0hhe0BRZErpQpEN:1327249469) ([raw file](https://github.com/kubernetes/dashboard/blob/1c2d4f5635ca42e7e0b112d57ae9bdc71801ffeb/src/app/frontend/common/components/resourcecard/resourcecarddeletemenuitem_component.js#L51)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Yeah, it is called when there were no errors, that's why it's called when cancel is clicked :)
</details>
Oh yeah, I forgot to hint you that the veber service should return with `return $q.reject(err);`, otherwise it calls the success callback. Can you change this?


Useful docs: http://www.html5rocks.com/en/tutorials/es6/promises/#toc-promises-queues

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/752)*

**Comment by floreks** [comment]
Review status: 23 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/common/components/resourcecard/resourcecarddeletemenuitem_component.js, line 51 \[r4\]](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-KIDD2EtatkdQ6v8pdgk:-KIDZP6kjF0Cv4Ip7FqZ:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/1c2d4f5635ca42e7e0b112d57ae9bdc71801ffeb/src/app/frontend/common/components/resourcecard/resourcecarddeletemenuitem_component.js#L51)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Oh yeah, I forgot to hint you that the veber service should return with `return $q.reject(err);`, otherwise it calls the success callback. Can you change this?
> 
> 
> Useful docs: http://www.html5rocks.com/en/tutorials/es6/promises/#toc-promises-queues
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/752)*

**Comment by bryk** [comment]
LGTM

<details><summary><i>Previously, codecov-io wrote…</i></summary>
> ## [Current coverage][cc-pull] is **95.29%**
> > Merging [#752][cc-pull] into [master][cc-base-branch] will increase coverage by **0.50%**
> 
> 1. File `...ereader_directive.js` (not in diff) was modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/60fc84a85ea58059dc42adddfaaccc2dc2b5355e/changes?src=pr#7372632F6170702F66726F6E74656E642F6465706C6F792F66696C657265616465725F6469726563746976652E6A73) 
>   - Misses `-6` 
>   - Partials `0` 
>   - Hits `+6`
> 
> ```diff
> @@             master       #752   diff @@
> ==========================================
>   Files           173        175     +2   
>   Lines          1338       1358    +20   
>   Methods           0          0          
>   Messages          0          0          
>   Branches          0          0          
> ==========================================
> + Hits           1268       1294    +26   
> + Misses           70         64     -6   
>   Partials          0          0          
> ```
> 
> > Powered by [Codecov](https://codecov.io?src=pr). Last updated by [e70b59c...60fc84a][cc-compare]
> [cc-base-branch]: https://codecov.io/gh/kubernetes/dashboard/branch/master?src=pr
> [cc-compare]: https://codecov.io/gh/kubernetes/dashboard/compare/e70b59c12ad84495779bbbd8230f18552c16919d...60fc84a85ea58059dc42adddfaaccc2dc2b5355e
> [cc-pull]: https://codecov.io/gh/kubernetes/dashboard/pull/752?src=pr
</details>


---

Review status: 23 of 27 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/752#-:-KIRd_A0d5ZQLER0Hefo:676834233)*

**Comment by bryk** [comment]
Reviewed 1 of 4 files at r5.
Review status: 24 of 27 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/752)*

**Comment by bryk** [comment]
Reviewed 3 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/752)*

**Pull request merged**
