### PR TITLE
Disable deploy from file tests until they're fixed.

### PR DESCRIPTION
**Pull request by bryk**
Partially addresses #494

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/501)

### CODE REVIEW

**Comment by bryk** [comment]
@f-higashi @maciaszczykm Can you review?

It is important now for us to have green tests, so I'm doing this.

**Comment by floreks** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/501#-:-KCKUy7Vr7Zd1ElWAfYs:980077423)*

**Comment by maciaszczykm** [comment]
:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/501#-:-KCKVUyS2Jdt4DbgxzDC:980077423)*

**Comment by f-higashi** [comment]
I checked failed  log.
I don't think it is related to #494.
Maybe It is related to  the sauce temporary storage. 
https://support.saucelabs.com/customer/portal/questions/14330476-file-upload-or-download-

But I agree with skipping these test now. 

:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/501#-:-KCKV4GyBtN-CRuXrYh2:442933121)*

**Pull request merged**
