### PR TITLE
Include Angular ESLint recommended rules

### PR DESCRIPTION
**Pull request by romdhanisam**
Fixes https://github.com/kubernetes/dashboard/issues/8393

> 1. apply angular-eslint/component-class-suffix
> 2. apply angular-eslint/no-output-on-prefix
> 3. apply angular-eslint/use-lifecycle-interface
> 4. disable angular-eslint/no-host-metadata-property

### CODE REVIEW

**Comment by romdhanisam** [comment]
@maciaszczykm 
This specific issue cannot be resolved without updating the `yarn.lock` file, which requires IMMUTABLE_INSTALLS.
Am I able to make changes in CI files ?
```yaml
env:
  YARN_ENABLE_IMMUTABLE_INSTALLS: false
```
Screenshot 2023-10-19 at 12 49 37

**Comment by romdhanisam** [comment]
@maciaszczykm 
This issue cannot be resolved without updating the `yarn.lock` file, which requires IMMUTABLE_INSTALLS.
```shell
➤ YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
```

**Comment by maciaszczykm** [comment]
@romdhanisam It happens because you didn't update lock file in your PR. Add it and then CI should pass.

**Comment by romdhanisam** [comment]
> @romdhanisam It happens because you didn't update lock file in your PR. Add it and then CI should pass.

@maciaszczykm  could you trigger the CI workflow?

**Pull request merged**
