### PR TITLE
Fix compatibility issues on Firefox, Safari and IE

### PR DESCRIPTION
**Pull request by bryk**
1. Nav was shrinking
2. Nav background was white
3. Scrolling didn't work

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1228)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you review?

**Comment by floreks** [comment]
I can check IE and Firefox :)

**Comment by bryk** [comment]
@floreks Any progress? I'd like to proceed with the release :)

**Comment by floreks** [comment]
Ok, then I'll do it now :)

**Comment by floreks** [comment]
1. It's still shrinking a bit on IE (horizontally).
2 and 3 are fixed though

I think we can merge as main issues are fixed and iterate after the release.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1228#-:-KRcXrXKob6bEJci0hNB:b-qgpx05)*

**Comment by bryk** [comment]
Cool, thanks!

**Pull request merged**
