### PR TITLE
Added directive to validate different types on input field values

### LINKED ISSUE #433: Floating number can be entered as pod count
##### Steps to reproduce
1. Open deploy from settings
2. enter 1.5 as number of pods

##### Observed result
no validation error

##### Expected result
validation error

### PR DESCRIPTION
**Pull request by floreks**
Fixes #433

I've prepared some generic solution for input field data validation. Later on we can refactor it and add more 'types' recognition i.e.: pullSecret, appName... Basically all input fields with some regex or other restrictions.

Review this for now and I'll add some tests in the meantime.

@maciaszczykm @bryk

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/472)

### CODE REVIEW

**Comment by bryk** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/common/validators/validate_directive.js, line 17 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqPUJHW1WjB4fFI2iJ:-KBqPUJIGpAcQz7sgl3b:-1903761338) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/validate_directive.js#L17)):*
Hmm... Did you take these annotations from core angular? How about dropping most of them and just using plain old text. The reason is that angular core does postprocessing and validation on them so they may give more troubles than value to us.

E.g., `@restrict A` This one is likely to get out of sync with what the configuration says, unless we test this during our build process. 

What do you think? 

---

*[src/app/frontend/common/validators/validate_directive.js, line 42 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqQQM4Az3B9h43SH1_:-KBqQQM4Az3B9h43SH1a:1384028639) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/validate_directive.js#L42)):*
Add `@type` information to the ctrl. 

---

*[src/app/frontend/common/validators/types/integertype.js, line 23 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqQblVHgf3Xtg6ygw0:-KBqQblVHgf3Xtg6ygw1:1024341597) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/integertype.js#L23)):*
`@constructs`?  There's noo such annotation, I believe 

---

*[src/app/frontend/common/validators/types/integertype.js, line 34 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqRufnjwTI-NzrhPyP:-KBqRufoiI9Z5z3y0o04:1364104381) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/integertype.js#L34)):*
Shouldn't this be `@override`? 

---

*[src/app/frontend/common/validators/types/type.js, line 40 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqRViyCXzEpTlaoZOz:-KBqQzrZ89yD7iu0mdKO:-1514045448) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/type.js#L40)):*
Hmm... I think this should take `{*}` as param. This is because otherwise, the inheritance does not work. Child classes would have different method signatures, when, e.g., coercing to `{number}`. 

Opinion? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/472)*

**Comment by floreks** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/common/validators/validate_directive.js, line 17 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqPUJHW1WjB4fFI2iJ:-KBqS5uq6WVB84JpSdAH:-1765779889) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/validate_directive.js#L17)):*
Yes, I've taken that from angular externs. I'm fine with removing JSDoc '@' if that's not useful for us.

---

*[src/app/frontend/common/validators/types/integertype.js, line 23 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqQblVHgf3Xtg6ygw0:-KBqTAbDF89DB_fb0rbv:-1669714098) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/integertype.js#L23)):*
I'm using this site for JSDoc. Gulp check is fine with this annotation and if it would not be recognized then it would fail i think.
http://usejsdoc.org/tags-constructs.html

---

*[src/app/frontend/common/validators/types/integertype.js, line 34 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqRufnjwTI-NzrhPyP:-KBqTPZaSxMEJs37UbLG:308751157) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/integertype.js#L34)):*
I'll check. I've tried some options but not all of them work.

---

*[src/app/frontend/common/validators/types/type.js, line 40 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqRViyCXzEpTlaoZOz:-KBqTcdmypcab89u7-hz:1184504321) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/type.js#L40)):*
I'll check that. That was the only way I've found to make gulp check pass.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/472)*

**Comment by floreks** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/common/validators/types/integertype.js, line 34 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqRufnjwTI-NzrhPyP:-KBqVDQpFjeKtkqrFKcn:1908836641) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/integertype.js#L34)):*
`@override` works fine. Great. Thanks.

---

*[src/app/frontend/common/validators/types/type.js, line 40 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqRViyCXzEpTlaoZOz:-KBqUhdqIjHky_Dwei2F:1215310010) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/type.js#L40)):*
Removing `@template T` and changing param type to `{*}` makes `gulp scripts:prod` fail because of incompatibile types. `T, V` template parameters are generic and can be overriden with different types in child classes.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/472)*

**Comment by bryk** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/common/validators/types/type.js, line 40 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqRViyCXzEpTlaoZOz:-KBqXJ0vPyLvtSC1ZHW_:108940885) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/type.js#L40)):*
That's what I mean. You cannot change method signature in child class. The signature must be exactly the same. Imagine how this would work in other OO language of your choice (Java, C#?) and realize that this inheritance just cannot work. When I have an object of type `Type`, I expect it to accept everything, whereas `IntegerType` accepts only `numbers`. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/472)*

**Comment by floreks** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/common/validators/types/type.js, line 40 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqRViyCXzEpTlaoZOz:-KBqd3I9tTio2TrpmSYa:1550315750) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/type.js#L40)):*
Well in C++ we have template functions and classes which basically can have  many specific implementations for different types. In java we have generic classes with template parameters also. This is pretty much similar case. We have class with function that accepts template parameter and in child classes we have specific implementation that can accept number, string, boolean.  It would be good to have some option to directly tell in JSDoc that class Type<T> is overriden as IntegerType<number> so it would know that parameter in this method will be of type number, but I think there is no option for that yet.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/472)*

**Comment by floreks** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/common/validators/types/type.js, line 40 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqRViyCXzEpTlaoZOz:-KBqkUD8ub3aMBDfkgNE:1131708972) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/type.js#L40)):*
Let me check this documentation and maybe I'll come up with something better. https://github.com/google/closure-compiler/wiki/Generic-Types

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/472)*

**Comment by bryk** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/common/validators/types/type.js, line 40 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqRViyCXzEpTlaoZOz:-KBqrIOgBdJormjAiupw:-310778543) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/type.js#L40)):*
Hmm...

`Type` class says that isValid method accepts `T`, which is essentially saying it accepts everything.
`StringType extends Type` has method isValid that accepts only strings. This means that it is not a valid subclass, because base class said that all its child classes can accept anything.

If you change the signature to accept `{*}` and do the same in child classes, then it would work. 

Am I correct or do I get something wrong?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/472)*

**Comment by floreks** [comment]
Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/common/validators/types/type.js, line 40 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqRViyCXzEpTlaoZOz:-KBqt79BT3iNnod9T8QG:-2140389005) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/type.js#L40)):*
In JS we can't directly say in code that class is a specialization of concrete generic class and accepts only given type like in java `class A extends B<String>`. Closure Compiler gives this ability. It's very poor but still. I've annotated `Type` class with `@template T` to mark that this is a generic class and class `IntegerType` with `@extends {Type<number}` to mark that this is a specialization of class Type that accepts `number` instead of  template parameter `T`. 

You can take a look at above link to closure compiler Generic Types documentation. There is great example in section **Inheritance of Generic Type** with some description.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/472)*

**Comment by bryk** [comment]
Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/common/validators/types/type.js, line 40 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqRViyCXzEpTlaoZOz:-KBqyDUHTGDvhwxd-WrO:-1683945065) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/type.js#L40)):*
I still think that this is wrong. 


There's a map in the code: `/** @private {Map<Array<string, !./type.Type>>} */`. It contains elements of type `!./type.Type`, not `!./type.Type<string>` nor `!./type.Type<number>`.  Objects of instance `!./type.Type<number>` expect to be called with numbers, but they are actually not. This means that the inheritance here is wrong. 

Also, in your code ` isValid(value) { return (Number(value) === value && value % 1 === 0) || !value; }` you even check whether the argument is a number, while saying in JSDoc that is is always a number.  This is another evidence that you cannot use generic types here.

Did I convince you? :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/472)*

**Comment by bryk** [comment]
Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/common/validators/types/integertype.js, line 23 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqQblVHgf3Xtg6ygw0:-KBr-KMRWD5cKlN-GeMw:1582959945) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/integertype.js#L23)):*
But this is for object literals, not ES6 classes. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/472)*

**Comment by floreks** [comment]
Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/common/validators/types/integertype.js, line 23 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqQblVHgf3Xtg6ygw0:-KBr-WrdyzHIuwDb1pb7:-414051465) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/integertype.js#L23)):*
There is no specific JSDoc documentation for ES6 classes. I'm using this and documentation of closure compiler.

---

*[src/app/frontend/common/validators/types/type.js, line 40 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqRViyCXzEpTlaoZOz:-KBr07htnVj9_VQxWkUF:-1828797751) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/type.js#L40)):*
Ok, I know what you mean. :) We can not guarantee that type of variable provided to specific class will be as expected in JSDoc. Closure compiler also can not check that for sure. Instead we should expect all types and not override type of param at all.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/472)*

**Comment by floreks** [comment]
Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/frontend/common/validators/types/type.js, line 38 \[r4\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBr6W6TLxEBvD_H5dF1:-KBr6W6TLxEBvD_H5dF2:1139121701) ([raw file](https://github.com/kubernetes/dashboard/blob/43e563334767f4384f72642d29f1403e3da4f6f0/src/app/frontend/common/validators/types/type.js#L38)):*
This class can not be instantiated so this can be empty.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/472)*

**Comment by bryk** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/frontend/common/validators/types/integertype.js, line 23 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqQblVHgf3Xtg6ygw0:-KBrQhg__XPM8jt2qaoo:1481402361) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/integertype.js#L23)):*
Yes, no worries. But this annotation is for arbitrary objects `{}`. ES6 classes are defined by the language and `constructor` method always constructs the class. "the @constructs tag allows you to document that a particular **function** will be used to construct instances of that class."

---

*[src/app/frontend/common/validators/types/type.js, line 40 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBqRViyCXzEpTlaoZOz:-KBrR5TG7DraiyKE6-AV:231503701) ([raw file](https://github.com/kubernetes/dashboard/blob/7265c7eaaddc1d952ecb3e8631d3ecc9f33c2a11/src/app/frontend/common/validators/types/type.js#L40)):*
Awesome, thanks for bearing with me :) 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/472)*

**Comment by bryk** [comment]
Reviewed 4 of 7 files at r1, 4 of 7 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/common/validators/validate_directive.js, line 17 \[r4\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBrSAc14kNSECKNtN1J:-KBrSAc2o0i_vNZsrKi3:234616417) ([raw file](https://github.com/kubernetes/dashboard/blob/43e563334767f4384f72642d29f1403e3da4f6f0/src/app/frontend/common/validators/validate_directive.js#L17)):*
I meant to remove name and restrict sections from this docstring. They repeat the configuration in following lines. It is likely that they'll get out of sync when someone modifies the config. 

Opinion? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/472)*

**Comment by floreks** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/common/validators/validate_directive.js, line 17 \[r4\]](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-KBrSAc14kNSECKNtN1J:-KBrTZp3MyQml_rh0p4_:398414002) ([raw file](https://github.com/kubernetes/dashboard/blob/43e563334767f4384f72642d29f1403e3da4f6f0/src/app/frontend/common/validators/validate_directive.js#L17)):*
Fine by me. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/472)*

**Comment by floreks** [comment]
PTAL

**Comment by bryk** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/472#-:-KBvp1qSooaoLBMe-HOO:980077423)*

**Comment by bryk** [comment]
Tests fail on IE. Can you fix?

**Comment by floreks** [comment]
You mean firefox. :) Sure I'll fix this. It's the same problem @batikanu has I believe.

**Comment by floreks** [comment]
Ok so 2 different things have failed. On IE units tests have failed and on Firefox some integration tests are flaky. I'll fix that also.

**Comment by bryk** [comment]
Thats great, thanks.

**Pull request merged**
