### PR TITLE
Localization of the DeployLabels and PortMappings

### PR DESCRIPTION
**Pull request by taimir**
Both of those sections are on the deploy from settings page.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/783)

### CODE REVIEW

**Comment by bryk** [comment]
:lgtm: One comment and let's merge. 

<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> #### Localization of the DeployLabels and PortMappings
> 
> Both of those sections are on the deploy from settings page.
> 
> 
> 
</details>


---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/deploy/deploylabel_controller.js, line 147 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/783#-KJ0maFknpXpckMzJozQ:-KJ0maFknpXpckMzJozR:-1166006432) ([raw file](https://github.com/kubernetes/dashboard/blob/a5345db8d675b082c1c81cef78175620bd4fada8/src/app/frontend/deploy/deploylabel_controller.js#L147)):*
> ```JavaScript
>   /** @export {string} @desc This warning appears when the key name of a specified kubernetes label (on the deploy page) does not match the required pattern.*/
>   MSG_DEPLOY_LABEL_KEY_NAME_PATTERN_WARNING: goog.getMsg(
>       `Label key name must be alphanumeric separated by '-', '_' or '.', optionally prefixed by a DNS subdomain and '/'`),
> ```

Split this into two lines and concat? In general, try to keep  lines 100 chars wide.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/783#-:-KJ0mjJERTcXJrQp4qYq:-594969378)*

**Comment by taimir** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/deploy/deploylabel_controller.js, line 147 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/783#-KJ0maFknpXpckMzJozQ:-KJ0pPbQ2ssAwK872j8A:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/a5345db8d675b082c1c81cef78175620bd4fada8/src/app/frontend/deploy/deploylabel_controller.js#L147)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Split this into two lines and concat? In general, try to keep  lines 100 chars wide.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/783)*

**Comment by bryk** [comment]
:lgtm:

<details><summary><i>Previously, codecov-io wrote…</i></summary>
> ## [Current coverage][cc-pull] is **95.21%**
> > Merging [#783][cc-pull] into [master][cc-base-branch] will increase coverage by **0.43%**
> 
> 1. File `...ereader_directive.js` (not in diff) was modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/33d02484a969810125bcf61ab6d3bfa38f3f9673/changes?src=pr#7372632F6170702F66726F6E74656E642F6465706C6F792F66696C657265616465725F6469726563746976652E6A73) 
>   - Misses `-6` 
>   - Partials `0` 
>   - Hits `+6`
> 
> ```diff
> @@             master       #783   diff @@
> ==========================================
>   Files           177        177          
>   Lines          1396       1400     +4   
>   Methods           0          0          
>   Messages          0          0          
>   Branches          0          0          
> ==========================================
> + Hits           1323       1333    +10   
> + Misses           73         67     -6   
>   Partials          0          0          
> ```
> 
> > Powered by [Codecov](https://codecov.io?src=pr). Last updated by [6cbbb2a...33d0248][cc-compare]
> [cc-base-branch]: https://codecov.io/gh/kubernetes/dashboard/branch/master?src=pr
> [cc-compare]: https://codecov.io/gh/kubernetes/dashboard/compare/6cbbb2a214344cd6b97f2c7a3c9a968503148bcb...33d02484a969810125bcf61ab6d3bfa38f3f9673
> [cc-pull]: https://codecov.io/gh/kubernetes/dashboard/pull/783?src=pr
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/783#-:-KJ4M3VtbTsUr75INPr4:1417088721)*

**Comment by bryk** [comment]
Please rebase. We have conflicts. 

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/783#-:-KJ4M6FfxB1tzgwQALVk:1403030854)*

**Comment by taimir** [comment]
PTAL

**Comment by bryk** [comment]
:lgtm:

<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> PTAL
</details>


---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/783#-:-KJBMMr7y-WZjdfsZa82:1417088721)*

**Pull request merged**
