### PR TITLE
Release 1.0.0-beta1

### PR DESCRIPTION
**Pull request by bryk**
It's been a long time since last release and we've done a lot of nice
things. Some people have been using versioned release, so let's publish
changes to the wild.

Changes since last release:
https://github.com/kubernetes/dashboard/compare/v0.1.0...b217638a038496d5d24525e085d59d02d9e64cde

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/410)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks @cheld Can you take a look?

**Comment by floreks** [comment]
LGTM

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/410#-:-KB8J8Afc4zAXSuHxetT:676834233)*

**Comment by cheld** [comment]
LGTM

**Comment by bryk** [comment]
Thanks. Will merge soon.

**Comment by bryk** [comment]
Btw, does any of you want to submit addon update to the K8s core? I can certainly do this, but if you want visibility/fun around the core, then claim this task :)

**Pull request merged**
