### PR TITLE
App bar actions split into global and view specific.

### PR DESCRIPTION
**Pull request by bryk**
Applied based on comments from:
https://github.com/kubernetes/dashboard/issues/908

Screenshot:
selection_124

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1214)

### CODE REVIEW

**Comment by bryk** [comment]
@romlein I didn't go with the gray `+ create` button since it makes the button look disabled. We can iterate on this later, but now, just white button looks better (IMO).

**Comment by bryk** [comment]
@digitalfishpond Can you review this?

**Comment by romlein** [comment]
@bryk `+ Create` button styling is correct; it should be white not gray. That's what's in the [mockups](https://invis.io/XZ7RITOQD#/183364877_1-4_1280). Am I missing something?

**Comment by digitalfishpond** [comment]
One question and then :lgtm: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1214#-:-KRXBjkYPYL2NJ8_4Olu:b-dutvgr)*

**Comment by bryk** [comment]
> @bryk + Create button styling is correct; it should be white not gray. That's what's in the mockups. Am I missing something?

@romlein My mistake. I was talking about page-specific buttons like "Scale".

**Comment by bryk** [comment]
Thanks @digitalfishpond for review. Merging. 

---

Reviewed 44 of 44 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1214#-:-KRXUoje1HnL9ACkQKky:ble4db1)*

**Pull request merged**
