### PR TITLE
Zerostate cards for empty resources in details pages

### PR DESCRIPTION
**Pull request by digitalfishpond**
Show a zerostate card rather than no card in details pages when there are no instances of a given resource.
(#1095)

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1132)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm Are you reviewing this?

**Comment by maciaszczykm** [comment]
@bryk No, cannot do it at the moment.

**Comment by bryk** [comment]
Ok, I'll take this

**Comment by bryk** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1132#-:-KPNZjnQvtB0f4K7p3zE:bnfp4nl)*

**Pull request merged**
