### PR TITLE
Backend code for deployment lists and workloads

### PR DESCRIPTION
**Pull request by bryk**
Frontend will follow soon.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/716)

### CODE REVIEW

**Comment by floreks** [comment]
We definitely need to refactor code related to replication controllers. I can take care of that. Functions used by more than 1 package should go to the common package.

---

Reviewed 7 of 9 files at r1.
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/backend/handler/apihandler.go, line 27 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/716#-KH4KTlTZyraS6hKkiCY:-KH4KTlTZyraS6hKkiCZ:-1102438694) ([raw file](https://github.com/kubernetes/dashboard/blob/23e2f78822fcad60de2699189d46b6917468fd94/src/app/backend/handler/apihandler.go#L27)):*
Should we follow this `resourceDeployment` pattern everywhere or only where it's needed?

I think it would be good to be consistent on that.

---

*[src/app/backend/resource/deployment/deploymentcommon.go, line 26 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/716#-KH4LLUng_XUFeA-Dg9W:-KH4LLUng_XUFeA-Dg9X:915248898) ([raw file](https://github.com/kubernetes/dashboard/blob/23e2f78822fcad60de2699189d46b6917468fd94/src/app/backend/resource/deployment/deploymentcommon.go#L26)):*
It looks like common function, not only deployment common.

What do you think?

---

*[src/app/backend/resource/deployment/deploymentcommon.go, line 42 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/716#-KH4LYjQemaLy8i_eLc4:-KH4LYjQemaLy8i_eLc5:1680122012) ([raw file](https://github.com/kubernetes/dashboard/blob/23e2f78822fcad60de2699189d46b6917468fd94/src/app/backend/resource/deployment/deploymentcommon.go#L42)):*
It looks kind of weird that function related to deployments returns `ControllerPodInfo` structure. Shouldn't it be just `PodInfo`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/716#-:-KH4MNf_Rtq-IyfI4-ji:7242806)*

**Comment by bryk** [comment]
All done. PTAL. 

---

Review status: 2 of 20 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/backend/handler/apihandler.go, line 27 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/716#-KH4KTlTZyraS6hKkiCY:-KH4SD9KL5rCkr23_Z0r:1473429747) ([raw file](https://github.com/kubernetes/dashboard/blob/23e2f78822fcad60de2699189d46b6917468fd94/src/app/backend/handler/apihandler.go#L27)):*
I'm elastic here, so if you have an opinion I can follow you. So far, my pattern was to not rename unless it is needed. I'm just lazy and I dont want to type too much ;) 

So, what should I do? 

---

*[src/app/backend/resource/deployment/deploymentcommon.go, line 26 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/716#-KH4LLUng_XUFeA-Dg9W:-KH4TgsRBVUtuWp9JC9j:-2081385415) ([raw file](https://github.com/kubernetes/dashboard/blob/23e2f78822fcad60de2699189d46b6917468fd94/src/app/backend/resource/deployment/deploymentcommon.go#L26)):*
Yeah, you're correct. I've extracted this to podinfo common file. Looks like a place for this. 

---

*[src/app/backend/resource/deployment/deploymentcommon.go, line 42 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/716#-KH4LYjQemaLy8i_eLc4:-KH4YLttnj_yqivbds6M:-966883997) ([raw file](https://github.com/kubernetes/dashboard/blob/23e2f78822fcad60de2699189d46b6917468fd94/src/app/backend/resource/deployment/deploymentcommon.go#L42)):*
Good idea, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/716#-:-KH4YP-ZU4e8Fi4qj0i6:-1498446823)*

**Comment by floreks** [comment]
:lgtm:

---

Reviewed 1 of 9 files at r1, 1 of 17 files at r2.
Review status: 3 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/backend/handler/apihandler.go, line 27 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/716#-KH4KTlTZyraS6hKkiCY:-KH4Z7ZwsTiLYcn_WTkw:-2109664524) ([raw file](https://github.com/kubernetes/dashboard/blob/23e2f78822fcad60de2699189d46b6917468fd94/src/app/backend/handler/apihandler.go#L27)):*
Ok, I'm a bit lazy also when it comes to renaming :) We can leave it this way unless we have to override.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/716#-:-KH4ZcnneUwjyjE5VSOg:1417088721)*

**Comment by floreks** [comment]
Let's wait for travis and we can merge.

---

Reviewed 12 of 17 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/716#-:-KH4ZuCwqsujug-RimWm:-258913872)*

**Pull request merged**
