### PR TITLE
fix issue #162 avoid arbitrary text in file upload input

### PR DESCRIPTION
**Pull request by batikanu**
Bugfix for issue #162. File input field is set to readonly to avoid arbitrary text input.

### CODE REVIEW

**Comment by bryk** [comment]
Thanks! Can you rebase?

**Comment by batikanu** [comment]
PTAL

**Comment by bryk** [comment]
Hmm... Can you add me to collaborators of your fork? With that I'll be able to update your branch and merge without rebasing

**Comment by batikanu** [comment]
I've added you as collaborator

**Pull request merged**
