### PR TITLE
fix property error in ReplicationControllerListComponent template

### LINKED ISSUE #3665: property error in ReplicationControllerListComponent template
##### Environment

```
Installation method: minikube
Kubernetes version: 1.13.4
Dashboard version: master (0a80b4a4)
Operating system: Ubuntu 18.04.2 LTS
Node.js version ('node --version' output): v8.15.1
Go version ('go version' output): go1.11.5 linux/amd64
```

##### Observed result

`rc.pods` property error inside ReplicationControllerListComponent template.
https://github.com/kubernetes/dashboard/blob/0a80b4a4f1526834c156369eff5b48ea4dcc1423/src/app/frontend/common/components/resourcelist/replicationcontroller/template.html#L78-L80

##### Expected result

It should be `podInfo` instead of `pods`.
```
<mat-cell *matCellDef="let rc"> 
   {{rc.podInfo.running}} / {{rc.podInfo.desired}} 
 </mat-cell> 
```

### PR DESCRIPTION
**Pull request by ajatprabha**
Fixes #3665

### CODE REVIEW

**Comment by jeefy** [comment]
Good eye, thanks for the fix!

/approve

**Comment by maciaszczykm** [comment]
Thanks!

**Pull request merged**
