### PR TITLE
Backend for generic delete code

### PR DESCRIPTION
**Pull request by bryk**
Next PR will introduce frontend for this

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/731)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you review?

**Comment by floreks** [comment]
Just 1 comment. 
Simple and neat. :lgtm_strong:

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> @floreks Can you review? </details>


---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/backend/resource/common/verber.go, line 43 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/731#-KHV-jZT1q3AJn5AGxjQ:-KHV-jZUjSMf8YrooabB:-778397150) ([raw file](https://github.com/kubernetes/dashboard/blob/eca67fd2ca6cf7fc2ae2e55c40be43d3763d7f21/src/app/backend/resource/common/verber.go#L43)):*
> ```Go
> 	apiPath, ok := kindToAPIPathMapping[kind]
> 	if !ok {
> 		errors.New("foo")
> ```

This message might be misleading :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/731#-:-KHV090bJtgt0xTyA0P6:-145628458)*

**Comment by floreks** [comment]
Fix travis first :)

**Comment by bryk** [comment]
Reviewed 8 of 17 files at r2.
Review status: 12 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/backend/resource/common/verber.go, line 43 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/731#-KHV-jZT1q3AJn5AGxjQ:-KHZC7Dl8Yo6T8t9xp-l:-87057941) ([raw file](https://github.com/kubernetes/dashboard/blob/eca67fd2ca6cf7fc2ae2e55c40be43d3763d7f21/src/app/backend/resource/common/verber.go#L43)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> This message might be misleading :)</details>
Yeah, forgot to export most recent changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/731)*

**Comment by bryk** [comment]
Reviewed 9 of 17 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/731)*

**Pull request merged**
