### PR TITLE
Japanese localization of namespace

### PR DESCRIPTION
**Pull request by Yamagami-Takuma**
Japanese localization of namespace.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/909)

### CODE REVIEW

**Comment by Yamagami-Takuma** [comment]
@f-higashi Can you review?

**Comment by f-higashi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[i18n/messages-ja.xtb, line 520 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/909#-KKMup4TvhNQhqB_DDQt:-KKMup4UyWopqeV9yTA9:-1705522031) ([raw file](https://github.com/kubernetes/dashboard/blob/20a8ed290e4321402614ccd71778ae12afd71c06/i18n/messages-ja.xtb#L520)):*
> ```
> 	<translation id="1510317375939332648" key="MSG_DEPLOYMENT_DETAIL_REVISION_HISTORY_NOT_SET_LABEL" source="/usr/local/google/home/bryk/src/github.com/dashboard/.tmp/serve/app-dev.js" desc="Label for the when revision history limit is not set.">未設定</translation>
> 	<translation id="7938484755085065281" key="MSG_DEPLOYMENT_DETAIL_ROLLING_STRATEGY_LABEL" source="/usr/local/google/home/bryk/src/github.com/dashboard/.tmp/serve/app-dev.js" desc="Label 'Rolling Update Strategy' for the deployment's rolling update strategy on the deployment details page.">ローリングアップデートストラテジー</translation>
> 	<translation id="8014136669527475668" key="MSG_NAMESPACE_NOT_SELECTED" source="/usr/local/google/home/bryk/src/github.com/dashboard/.tmp/serve/app-dev.js" desc="Text for dropdown item that indicates that no namespace was selected">すべてのユーザのネームスペース</translation>
> ```

You should remove `の`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/909)*

**Comment by Yamagami-Takuma** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[i18n/messages-ja.xtb, line 520 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/909#-KKMup4TvhNQhqB_DDQt:-KKMvaCKN3KTXskYSrN5:1920760566) ([raw file](https://github.com/kubernetes/dashboard/blob/20a8ed290e4321402614ccd71778ae12afd71c06/i18n/messages-ja.xtb#L520)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> You should remove `の`.
</details>
I fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/909)*

**Comment by f-higashi** [comment]
:lgtm:

@maciaszczykm 
You can merge this

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/909#-:-KKMy1_oTo25iAWBBlnI:1997196358)*

**Pull request merged**
