### PR TITLE
Make API container fully stateless and independent of frontend

### LINKED ISSUE #7445: Helm chart - Setting settings.clusterName forces settings.itemsPerPage to 0 if not set explicitly
### What happened?

When deploying the dashboard into a vCluster, where the metrics services aren't available, the dashboard is unable to list any resources.  
Screen Shot 2022-09-12 at 11 08 43 AM

And when listing `Pod`s:

Screen Shot 2022-09-12 at 11 10 04 AM

In the dashboard `Pod`'s logs - 

```
2022/09/12 15:11:06 [2022-09-12T15:11:06Z] Incoming HTTP/1.1 GET /api/v1/pod/openunison?itemsPerPage=0&page=1&sortBy=d%!C(MISSING)creationTimestamp request from 192.168.2.112: 
2022/09/12 15:11:06 Getting list of all pods in the cluster
2022/09/12 15:11:06 [2022-09-12T15:11:06Z] Outcoming response to 192.168.2.112 with 200 status code
2022/09/12 15:11:06 Internal error occurred: No metric client provided. Skipping metrics.
2022/09/12 15:11:06 Getting pod metrics
2022/09/12 15:11:06 Internal error occurred: No metric client provided. Skipping metrics.
2022/09/12 15:11:06 [2022-09-12T15:11:06Z] Outcoming response to 192.168.2.112 with 200 status code
```

However, if I try to get pods using the same user:

```
k get pods -n openunison
NAME                                             READY   STATUS      RESTARTS   AGE
openunison-operator-6cb7444cc6-jhvqj             1/1     Running     0          9d
openunison-orchestra-8dcc5dbd7-44jzl             1/1     Running     0          9d
kube-oidc-proxy-orchestra-68c66857f9-fqcpz       1/1     Running     0          9d
ouhtml-orchestra-login-portal-7fcb97b996-mzbcx   1/1     Running     0          9d
check-certs-orchestra-27712920-2dzb9             0/1     Completed   0          2d13h
check-certs-orchestra-27714360-2bmf2             0/1     Completed   0          37h
check-certs-orchestra-27715800-ghwqk             0/1     Completed   0          13h
```

The integration with dashboard is via an impersonating reverse proxy.

### What did you expect to happen?

pods should be listed

### How can we reproduce it (as minimally and precisely as possible)?

probably the easiest way: https://www.tremolosecurity.com/post/vcluster-enterprise-authentication

### Anything else we need to know?

The vCluster has no metrics deployed

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox

### Kubernetes Dashboard version

NAME                	NAMESPACE           	REVISION	UPDATED                                	STATUS  	CHART                      	APP VERSION kubernetes-dashboard	kubernetes-dashboard	1       	2022-09-02 18:08:46.044357215 +0000 UTC	deployed	kubernetes-dashboard-5.10.0	2.6.1

### Kubernetes version

1.23

### Dev environment

_No response_

### PR DESCRIPTION
**Pull request by floreks**
# Breaking change

This PR introduces a couple of important changes to how Kubernetes Dashboard generally works. It will require a clean installation once released.

## API container
It is now fully stateless, meaning it does not rely on Kubernetes resources to run. It will always require an authorization token to be present to authorize the request. It is no longer possible for the API container to use its own SA privileges to skip authorization. All arguments that were frontend specific have either been removed or moved to the [Web container](#web-container).

- The JWE encrypted token has been removed completely and we now rely fully on standard JWT tokens. This change has significantly simplified the auth flow.
- The Web container now manages Settings ConfigMap
- CSRF key is now generated in memory and not stored in a Secret. Our chart configuration will handle sticky session configuration to make sure that requests made by the user are always forwarded to the same container.
The plugin system has been removed as it was outdated and not working anymore. Currently, there is no plan to reintroduce it as it would require too much effort to maintain.

## Auth container
Authentication logic is now handled by the new dashboard auth container. Currently, it only exposes `/login` endpoint. We will also add support for OIDC with OAuth flow and `/me` endpoint in the future.

### Go backend
- The backend now handles frontend settings and uses ConfigMap to store them.
- Settings backend has been updated to handle merge with default options properly in case ConfigMap does not contain all available options.
- Replaced `restful-go` with `gin` as main web framework

### Angular frontend
Since API requires the user to always provide `Authorization: Bearer <token>` now, there is no way to skip login and act as a Dashboard.

- Removed support for authentication options other than `token`
- Removed support for `skip` login option
- Slightly updated login view
- Fixed an issue with zero state not being correctly displayed on some pages

## Kong gateway
Since the number of our containers is growing as we split parts of the logic, we have decided to use a gateway that will connect all of them and ensure the Dashboard is working properly. There were a couple of reasons to choose Kong:

- Open Source with proper license
- Support for DBless configuration
- Easily configurable
- Popular
- Single container gateway when running in DBless mode

It will now be a required dependency that we use to expose the Dashboard. Users can then reconfigure it or use another proxy in front of it. It will simply act as a single point when accessing the Kubernetes Dashboard.

## Metrics scraper
- Changed `sqlite` Go dependency to used driver implementation that does not require `CGO_ENABLED=1` during the build. It is a pure Go implementation.

## Dev pipeline
Master `Makefile` located in project root now exposes couple of global targets that are forwarded to correct modules.

- `build` - builds locally all go modules and angular frontend and stores it in `<MODULE_DIR>/.dist` directories
- `check` - runs static checks for every module (linting, license, i18n, etc.)
- `clean` - removes all temporary directories such as `.tmp` and `.dist`
- `coverage` - runs units tests with coverage for all modules
- `fix` - same as `check` just with `--fix` option.
- `test` - runs unit tests for all modules

To test the application there are now 2 targets:

- `serve` - Starts the development version of the application using docker compose. All modules are running in docker with live reload enabled thanks to `air` (Go) and `ng serve` (Angular). Exposes Dashboard frontend on `http://localhost:8080`
- `run` - Starts the production version of the application using docker compose. Exposes Dashboard frontend on `http://localhost:8080` and `https://localhost:8443`.

## Other changes

- CI Codecov configuration has been updated to work with our deploy token (previously tokenless)
- Prettier is now our only formatting tool, it replaces js-beautify that was used for HTML formatting, and also provides formatting that was removed from Stylelint a while ago. 
- CD release pipeline has been disabled for now (updated after this PR gets merged)
- All the containers are now using `klog` as the base logger. `--api-log-level` arg have been replaced by `--v` and expects a log level number (0-5).

Fixes #7445.

### CODE REVIEW

**Comment by shu-mutou** [comment]
could you devide PR for bumping golang to 1.22?

**Comment by floreks** [comment]
is there any reason to split that into a separate PR?

**Comment by shu-mutou** [comment]
K8s v1.30 will bump golang to 1.22, so if this PR is going to take a long time, I thought it would be better to do it separately.
I would like to update the development environment too, and I think it would be easier to review if this PR was made smaller, so it would be happy if you could separate it.
If you'd like, I'll create PR for bumping golang to v1.22. :smile:

**Comment by maciaszczykm** [comment]
I would keep it as it is done already.

**Comment by floreks** [comment]
Go version configured in go.mod files used by dependencies does not have any impact on us. It is only the minimum version of Go required to build the application.

This change is very minimal and does not have any other impact than forcing devs to use specific Go version to compile Dashboard.

**Comment by shu-mutou** [comment]
@floreks @maciaszczykm Thank you for explanations! Got it and looking forward to it!

**Review by maciaszczykm — APPROVED** [review]

**Comment by Daveydave101** [comment]
# run

**Pull request merged**
