### PR TITLE
Logs Auto Scroll

### LINKED ISSUE #2610: On logs refresh logs window should be scrolled to the bottom
Window stays at the same position and scrollbar moves up.

zrzut ekranu z 2017-11-22 14-27-23

### LINKED ISSUE #3509: Support following logs
Picked the last issue from #1828.

### PR DESCRIPTION
**Pull request by eloyekunle**
Update the Logs view to support autoscroll when Logs refresh.

Closes #2610

### CODE REVIEW

**Comment by maciaszczykm** [comment]
It does not solve #3509. The original issue with more context is https://github.com/kubernetes/dashboard/issues/1083. I will take a look tomorrow.

**Comment by maciaszczykm** [comment]
Works fine for page refresh, but not when switching pages. It is quote uncomfortable at the moment, but newest logs are at the end. Can you scroll also on page changes?

And remove #3509 from fixed issues please.

**Comment by eloyekunle** [comment]
I've removed #3509, I'll have to thrash that on another PR.

The current behavior is it scrolls only when the user is already at the bottom of the logs viewer. This is to avoid a situation where you're trying to read something higher up in the page but the logs keep scrolling down during auto-refresh.

Currently, when you switch pages, you arrive at the top of the target page so it doesn't scroll because you're not at the bottom.

What do you think?

**Comment by floreks** [comment]
I'd say that on page change to next one we should stay on top, but on page change to the previous one, we should go to the bottom to make it feel like you can continue reading without scrolling manually.

**Comment by eloyekunle** [comment]
Okay, so:

- Navigation to previous pages should go to the bottom.
- Add new option to follow logs.

Sounds good.

**Comment by jeefy** [comment]
Also it looks like you have a conflict in `src/app/frontend/logs/template.html` 

When you make your additional changes, please resolve that before pushing. :) 

Thanks!

**Comment by eloyekunle** [comment]
Implemented:

- Option to follow logs. This adds a new icon.
- Scroll to logs bottom when navigating to previous page.
- Scroll to logs top when navigation to next page.

**Comment by jeefy** [comment]
@eloyekunle Your latest changes broke some HTML formatting. 

See https://travis-ci.org/kubernetes/dashboard/jobs/496191334#L297

You can test these CI checks locally by running `npm run check` (and others, see `package.json` for the other options)

After that quick formatting fix I'll give it one more look and lgtm it. :) Thanks!

**Comment by eloyekunle** [comment]
@jeefy Thanks, I've fixed the HTML formatting.

**Pull request merged**
