### PR TITLE
Propagate apiclient to YAML deploy pipeline

### LINKED ISSUE #395: apiserver-host paramter not propagated to deploy-from-yaml
Hi there,

I'm using the dashboard and the apiserver-host option (https://github.com/kubernetes/dashboard/blob/master/src/app/backend/dashboard.go#L28). Unfortunately this looks like this option is not propagated in the whole code. 

I'm currently using the piece of code : https://github.com/kubernetes/dashboard/blob/0df77fbc03048e36f26eae74f2aaa6d75d853e9c/src/app/backend/deploy.go#L276-L296

the factory call try to connect to localhost:8080 which fail in my case. I have not manage to find a workaround in go for now. To make it work I have to have on another layer (/etc/hosts hack or proxy ...)

### PR DESCRIPTION
**Pull request by bryk**
I tested it on my in-cluster installation and it worked.

Fixes #395

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/409)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks @maciaszczykm Can you review?

**Comment by maciaszczykm** [comment]
To test it I've deployed kubernetes-dashboard.yaml on `serve:prod` and tried to access it. Unfortunately there is following error:

image

Intresting thing is path `/usr/local/google/home/bryk/src/...:35`, as you can see it's probably coming from yours setup. However, I'm not sure if this test was accurate in this case... @floreks has similar problem with it.

**Comment by bryk** [comment]
Yeah. kubernetes-dashboard.yaml is wrong. Add `-amd64` suffix to image name and test.

**Comment by floreks** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/409)*

**Comment by maciaszczykm** [comment]
Strange... It tries to connect with wrong API:

image

image

I've modified image to `gcr.io/google_containers/kubernetes-dashboard-amd64:canary`.

**Comment by bryk** [comment]
Ok, I'll be investigating this tomorrow.

**Comment by bryk** [comment]
Can you try once more? Delete old RC and recreate new one with image: `gcr.io/google_containers/kubernetes-dashboard-amd64:canary`

**Comment by maciaszczykm** [comment]
Yes, but unfortunately result is still the same:

image

image

``` yaml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: kubernetes-dashboard-canary
    version: canary
  name: kubernetes-dashboard-canary
  namespace: kube-system
spec:
  replicas: 1
  selector:
    app: kubernetes-dashboard-canary
    version: canary
  template:
    metadata:
      labels:
        app: kubernetes-dashboard-canary
        version: canary
    spec:
      containers:
      - name: kubernetes-dashboard-canary
        image: gcr.io/google_containers/kubernetes-dashboard-amd64:canary
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-dashboard-canary
  name: dashboard-canary
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 9090
  selector:
    app: kubernetes-dashboard-canary
```

**Comment by bryk** [comment]
Strange, but on my cluster it works.

When the UI starts, I see logs:
```
[bryk@bryk dashboard (yaml-propagate)]$ kubectl logs kubernetes-dashboard-698oa --namespace=kube-system
2016/02/23 08:41:21 Starting HTTP server on port 9090
2016/02/23 08:41:21 Creating API server client for https://10.167.240.1:443
2016/02/23 08:41:21 Creating in-cluster Heapster client
```

What is your k8s master version? Can you give me logs?

**Comment by maciaszczykm** [comment]
@bryk More details:

```
✔ ~/workspace/dashboard [issue-template|…53⚑ 1] 
09:49 $ kubectl logs kubernetes-dashboard-canary-pu9if --namespace kube-system
2016/02/23 09:00:34 Starting HTTP server on port 9090
2016/02/23 09:00:34 Creating API server client for http://localhost:8080
2016/02/23 09:00:34 Creating in-cluster Heapster client
2016/02/23 09:06:49 Incoming HTTP/1.1 GET /api/v1/replicationcontrollers request from 172.17.0.1:38771
2016/02/23 09:06:49 Getting list of all replication controllers in the cluster
2016/02/23 09:06:49 Get http://localhost:8080/api/v1/replicationcontrollers: dial tcp [::1]:8080: getsockopt: connection refused
2016/02/23 09:06:49 Outcoming response to 172.17.0.1:38771 with 500 status code
2016/02/23 09:09:07 Incoming HTTP/1.1 GET /api/v1/replicationcontrollers request from 172.17.0.1:51523
2016/02/23 09:09:07 Getting list of all replication controllers in the cluster
2016/02/23 09:09:07 Get http://localhost:8080/api/v1/replicationcontrollers: dial tcp [::1]:8080: getsockopt: connection refused
2016/02/23 09:09:07 Outcoming response to 172.17.0.1:51523 with 500 status code
✘-127 ~/workspace/dashboard [yaml-propagate|…53⚑ 1] 
10:19 $ kubectl version
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.6.915+3e04a45a95220e", GitCommit:"3e04a45a95220e3d3e23b41582433fa8a6475033", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
```

**Comment by floreks** [comment]
For me it works just fine. I have same results as @bryk

```
2016/02/23 09:51:36 Starting HTTP server on port 9090
2016/02/23 09:51:36 Creating API server client for https://10.0.0.1:443
2016/02/23 09:51:36 Creating in-cluster Heapster client
2016/02/23 09:52:08 Incoming HTTP/1.1 GET /api/v1/replicationcontrollers request from 172.26.33.39:58252
```

I've used new yaml file from #409

**Comment by maciaszczykm** [comment]
Important detail from my side is, that I'm using `gulp local-up-cluster` to create cluster and `gulp serve:prod` to serve dashboard.

**Comment by bryk** [comment]
> Important detail from my side is, that I'm using gulp local-up-cluster to create cluster and gulp serve:prod to serve dashboard.

Ah, yeah. Local cluster is broken, as it does not have service accounts. That's why the client falls back to defaults. Can you test this on a "real" cluster?

local-up-cluster will be fixed once https://github.com/kubernetes/kubernetes/pull/21486 is released.

**Comment by maciaszczykm** [comment]
@bryk Okay. @floreks tested on local cluster. LGTM

**Comment by bryk** [comment]
Awesome, thank you.

**Pull request merged**
