### PR TITLE
Run local-up-cluster k8s clusters as kyperkube Docker image

### PR DESCRIPTION
**Pull request by bryk**
This speeds up our Travis CI infra by like 50% and deletes lots of code (which is a benefit).

Learn more at: http://kubernetes.io/v1.1/docs/getting-started-guides/docker.html

### CODE REVIEW

**Comment by bryk** [comment]
@zreigz

**Comment by bryk** [comment]
Can you review?

**Comment by zreigz** [comment]
yes

**Comment by zreigz** [comment]
Wow it  looks really great. Let me test is more deeply on fresh environment. I will finish on Monday. I thing also other person should take a look this because it's quite major change.

**Comment by zreigz** [comment]
I have no comments. It looks and works very nice. It really good job.
LGTM

**Comment by bryk** [comment]
@cheld Can you review?

**Comment by bryk** [comment]
@floreks Can you look at this?

**Comment by floreks** [comment]
Sure. I've actually checked it yesterday but somehow forget to comment. :) It looks great. I think we can merge.

**Pull request merged**
