### PR TITLE
Add external traffic policy to chart service

### PR DESCRIPTION
**Pull request by Keydrain**
Minor update to add `externalTrafficPolicy` to the dashboard service. Let me now if there is anything else needed or suggested for this change.

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@Keydrain can you sign the CLA so we will take a look?

@desaintmartin Can you take a look?

**Review by desaintmartin — CHANGES_REQUESTED** [review]
Thanks! 
Could you bump minor version in Chart.yaml? According to semver, this is new feature.

**Review by maciaszczykm — APPROVED** [review]

**Comment by maciaszczykm** [comment]
@Keydrain Can you solve the conflicts?

**Comment by maciaszczykm** [comment]
@Keydrain Can you solve conflicts?

**Comment by maciaszczykm** [comment]
> Thanks! 
> Could you bump minor version in Chart.yaml? According to semver, this is new feature. 

^

**Review by maciaszczykm — APPROVED** [review]
/lgtm
/approve

**Comment by maciaszczykm** [comment]
I've updated the branch and set the correct version.

/lgtm
/approve

**Comment by maciaszczykm** [comment]
@desaintmartin Do you know why lint fails?

**Comment by floreks** [comment]
> [Error: INSTALLATION FAILED: Service "kubernetes-dashboard-jcfmau9vl7" is invalid: spec.externalTrafficPolicy: Invalid value: "Cluster": may only be set when `type` is 'NodePort' or 'LoadBalancer'](https://github.com/kubernetes/dashboard/actions/runs/3600307502/jobs/6066615621#step:11:43)

**Comment by maciaszczykm** [comment]
Closing as inactive. @Keydrain feel free to reopen if you want to move forward with this.

**Pull request closed without merging**
