### PR TITLE
add resourcekind componentstatus

### PR DESCRIPTION
**Pull request by zouyee**
add resource kind :componentstatus

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Why do we need that?

**Comment by zouyee** [comment]
@maciaszczykm  using this api, we could inspect the cluster‘s situation，like that

**Comment by maciaszczykm** [comment]
Yeah, but Dashboard is the UI and not Kubernetes proxy. We don't need it if we won't display it in the UI. To make it useful you need to implement frontend part.

**Comment by zouyee** [comment]
I will fix it which will take a few times, because i  am weak in angularjs2

**Comment by maciaszczykm** [comment]
Closing as stale. Please reopen when rest of needed logic will be implemented.

**Pull request closed without merging**
