### PR TITLE
Restyle deploy page to make it look alike other pages

### LINKED ISSUE #1147: Deploy (aka "create") page has incorrect title.
Now it is `deployFile`, which should be changed to something human-readable.

### PR DESCRIPTION
**Pull request by bryk**
And fix breadcrumbs. Fixes #1147

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1159)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm @floreks Can you review?

**Comment by maciaszczykm** [comment]
I'll do it.

**Comment by floreks** [comment]
Travis fails due to some formatting issues.

**Comment by maciaszczykm** [comment]
Now deploy view looks good:



To fix #1147 breadcrumbs for logs should also be updated:



Also right padding in log card should be added.

---

Reviewed 6 of 9 files at r1.
Review status: 6 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[build/dependencies.js, line 96 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1159#-KQKWgsnanoHYvn-9ljL:-KQKWgsnanoHYvn-9ljM:b-gctfpo) ([raw file](https://github.com/kubernetes/dashboard/blob/7fe04b58e3d7cfa260ea3a14831b5c1dada9000c/build/dependencies.js#L96)):*
> ```JavaScript
>                 `Run: 'gulp update-${packageManager}-dependencies', then '${packageManager
>                 } install' to update` +
>                 ' dependencies.\n'));
> ```

Looks a bit strange. I suppose it's formatter fault. Could it be done like in below snippet?

``` js
`Run: 'gulp update-${packageManager}-dependencies', then '${packageManager
} install' to update dependencies.\n`));
```

---

*[src/app/frontend/deploy/deploy_stateconfig.js, line 100 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1159#-KQKXMLXxV1tr64MpVOX:-KQKXMLXxV1tr64MpVOY:bmhcg42) ([raw file](https://github.com/kubernetes/dashboard/blob/7fe04b58e3d7cfa260ea3a14831b5c1dada9000c/src/app/frontend/deploy/deploy_stateconfig.js#L100)):*
> ```JavaScript
> const i18n = {
>   /** @type {string} @desc Title for app deploy form */
>   MSG_BREADCRUMBS_DEPLOY_APP_LABEL: goog.getMsg('Create'),
> ```

Shouldn't this label be more descriptive?

---

*[src/app/frontend/deploy/deploy_stateconfig.js, line 103 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1159#-KQKXTNZwkGgsyREHsex:-KQKXTNZwkGgsyREHsey:b2nreh6) ([raw file](https://github.com/kubernetes/dashboard/blob/7fe04b58e3d7cfa260ea3a14831b5c1dada9000c/src/app/frontend/deploy/deploy_stateconfig.js#L103)):*
> ```JavaScript
> 
>   /** @type {string} @desc Title for upload YAML form */
>   MSG_BREADCRUMBS_DEPLOY_FILE_LABEL: goog.getMsg('Upload'),
> ```

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1159#-:-KQKY4SgB-PbpcoeJIgE:b-dztxdn)*

**Comment by bryk** [comment]
PTAL 

Didn't add the right padding, as it is not that trivial in the logs view (the view requires separate polish on its own). 

---

Review status: 3 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[build/dependencies.js, line 96 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1159#-KQKWgsnanoHYvn-9ljL:-KQKlDnwGUYSwi2ZOfVr:bhilzht) ([raw file](https://github.com/kubernetes/dashboard/blob/7fe04b58e3d7cfa260ea3a14831b5c1dada9000c/build/dependencies.js#L96)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> Looks a bit strange. I suppose it's formatter fault. Could it be done like in below snippet?
> 
> ``` js
> `Run: 'gulp update-${packageManager}-dependencies', then '${packageManager
> } install' to update dependencies.\n`));
> ```
> 
</details>
Fixed. clang on my mac does weird things recently...

---

*[src/app/frontend/deploy/deploy_stateconfig.js, line 100 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1159#-KQKXMLXxV1tr64MpVOX:-KQKlIED-ajArKz7bS_R:b-ns008o) ([raw file](https://github.com/kubernetes/dashboard/blob/7fe04b58e3d7cfa260ea3a14831b5c1dada9000c/src/app/frontend/deploy/deploy_stateconfig.js#L100)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> Shouldn't this label be more descriptive?
</details>
Done. PTAL

---

*[src/app/frontend/deploy/deploy_stateconfig.js, line 103 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1159#-KQKXTNZwkGgsyREHsex:-KQKlJRjWHBca4JWmzVg:b-ns008o) ([raw file](https://github.com/kubernetes/dashboard/blob/7fe04b58e3d7cfa260ea3a14831b5c1dada9000c/src/app/frontend/deploy/deploy_stateconfig.js#L103)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> Same as above.
</details>
Done. PTAL

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1159#-:-KQKmwaD_JlyEfyRc2eu:bm3hehf)*

**Comment by maciaszczykm** [comment]
Review status: 3 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/deploy/deploy_stateconfig.js, line 100 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1159#-KQKXMLXxV1tr64MpVOX:-KQKoImSUb9W2XihTNVZ:b-98avb0) ([raw file](https://github.com/kubernetes/dashboard/blob/7fe04b58e3d7cfa260ea3a14831b5c1dada9000c/src/app/frontend/deploy/deploy_stateconfig.js#L100)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Done. PTAL
</details>
I rather meant changing `Create` to something else, for example `Create new application` :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1159)*

**Comment by floreks** [comment]
:lgtm:

---

Reviewed 1 of 9 files at r1, 3 of 6 files at r2.
Review status: 7 of 10 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1159#-:-KQLMwP1yuiPmyQp-8ZU:bnfp4nl)*

**Comment by bryk** [comment]
Review status: 6 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/deploy/deploy_stateconfig.js, line 100 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1159#-KQKXMLXxV1tr64MpVOX:-KQLU6ZqQt2Dm5SDQRle:ba3bysp) ([raw file](https://github.com/kubernetes/dashboard/blob/7fe04b58e3d7cfa260ea3a14831b5c1dada9000c/src/app/frontend/deploy/deploy_stateconfig.js#L100)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> I rather meant changing `Create` to something else, for example `Create new application` :)
</details>
Talked offline and decided to go with "Create an app".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1159)*

**Comment by bryk** [comment]
Reviewed 1 of 9 files at r1, 1 of 6 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1159)*

**Comment by bryk** [comment]
Will merge once travis is happy. 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1159#-:-KQLUNRN0fVGQX0mpkK4:b-tu1v5b)*

**Pull request merged**
