### PR TITLE
renamed replica set to replication controller

### PR DESCRIPTION
**Pull request by GertiPoppel**
@maciaszczykm @floreks Please review
This pull request is related to https://github.com/kubernetes/dashboard/issues/276

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Wow, that's a big change. Please fix travis and I'll test it on my side.

**Comment by maciaszczykm** [comment]
Please do not change all files, i.e. `Godeps` must not be changed as it's not our code.

**Comment by bryk** [comment]
Yeah, dont modify Godeps.

**Comment by bryk** [comment]
PTAL

**Comment by GertiPoppel** [comment]
PTAL
I have reverted the Godeps files - sorry for this.

**Comment by bryk** [comment]
LGTM. Will do final testing and then merge. Thanks!

**Comment by bryk** [comment]
This does not work on `gulp serve`. Nor on `gulp serve:prod`. Please fix.

**Comment by batikanu** [comment]
It worked for me after running gulp clean

**Comment by batikanu** [comment]
Before clean replicasetdetail.go was still in the tmp directory. After clean it disappeared.

**Comment by GertiPoppel** [comment]
PTAL

**Comment by bryk** [comment]
LGTM. Can I merge?

**Comment by cheld** [comment]
Pretty impressive code change for a non-coder :)

@bryk Only a small formatting issue left. Gerti already left. It is such a big change set. I would like to have it merged as quick as possible. Can you merge anyway and we fix later?

**Comment by luxas** [comment]
This makes dashboard user-friendly, in the beginning I had to think about what a Replica Set is... is it a Replication Controller, does it differ in anyway or is it a dashboard specific thing?

With this change it's clear from the beginning. Thanks

**Comment by bryk** [comment]
@luxas Replica Set is "the new Replication Controller". In beta for 1.2 k8s release. But this isn't going to be popularized anytime soon, so we're renaming our UI to Replication Controllers.

**Comment by GertiPoppel** [comment]
PTAL - formatting has been fixed.

**Comment by bryk** [comment]
Merging. Thanks a lot @GertiPoppel for this change :)

**Comment by cheld** [comment]
@bryk 

BTW: did you suggest to change source code or just documentation? Don't get me wrong, it is nice to have consistent naming. I was just surprised about all the changes :)

**Comment by bryk** [comment]
I suggested changing both code and docs. The reason is that replication controller -> replica set was going to be just rename in K8s core. While, in reality, it is two similar but separate objects. Our UI shows only replication controllers, so let's state it in the code and docs.

**Pull request merged**
