### PR TITLE
Add metric graphs to remaining views

### PR DESCRIPTION
**Pull request by wjywbs**
Part of #3866.

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Is it ready for a review?

**Comment by wjywbs** [comment]
Yes.

**Comment by maciaszczykm** [comment]
Will you prepare the rest of the graphs?

**Comment by wjywbs** [comment]
I did all the straight forward ones. The rest may need some fixes on the backend like #4145, and I'm not working on that now.

**Pull request merged**
