### PR TITLE
Added some missing localizations

### PR DESCRIPTION
**Pull request by taimir**
Additionally introduced a directive that can compile other kd-directives nested in the i18n messages.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/963)

### CODE REVIEW

**Comment by taimir** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/common/components/i18n/i18n_directive.js, line 23 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/963#-KLGhT53ZjZ0_ytfPstU:-KLGhT53ZjZ0_ytfPstV:-2075358129) ([raw file](https://github.com/kubernetes/dashboard/blob/1f9379df7bd171d9b0c129b6a7c27a1f41e6ec0b/src/app/frontend/common/components/i18n/i18n_directive.js#L23)):*
> ```JavaScript
>  * @ngInject
>  */
> export default function i18nDirective($compile) {
> ```

Introduced this rather unwillingly. Maybe someone has a better idea of how to avoid recompiling at run-time?

To me it seems like there's only to options: either recompile or just live with messages that are not perfectly interpolated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/963)*

**Comment by bryk** [comment]
Reviewed 3 of 9 files at r1.
Review status: 3 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/common/components/i18n/i18n_directive.js, line 28 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/963#-KLGoWwJ24GpmL8Ayr3p:-KLGoWwJ24GpmL8Ayr3q:295492961) ([raw file](https://github.com/kubernetes/dashboard/blob/1f9379df7bd171d9b0c129b6a7c27a1f41e6ec0b/src/app/frontend/common/components/i18n/i18n_directive.js#L28)):*
> ```JavaScript
>     scope: {message: '@'},
>     link: function(scope, element) {
>       scope.$watch('message', function(i18nMessage) {
> ```

Hmm... I dont think we should watch for changes. IMO just render the directive once and that's all. Our translations do not change at runtime.

@digitalfishpond @maciaszczykm What do you think? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/963)*

**Comment by bryk** [comment]
*[src/app/frontend/common/components/i18n/i18n_directive.js, line 30 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/963#-KLGomty7oRV8o1HyBcg:-KLGomty7oRV8o1HyBch:-828778179) ([raw file](https://github.com/kubernetes/dashboard/blob/1f9379df7bd171d9b0c129b6a7c27a1f41e6ec0b/src/app/frontend/common/components/i18n/i18n_directive.js#L30)):*
> ```JavaScript
>       scope.$watch('message', function(i18nMessage) {
>         if (!i18nMessage) return;
>         let rendered = $compile(`<span>${i18nMessage}</span>`)(scope);
> ```

Do we need span? Did you test without it? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/963)*

**Comment by taimir** [comment]
Review status: 3 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/common/components/i18n/i18n_directive.js, line 30 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/963#-KLGomty7oRV8o1HyBcg:-KLGot4WKcVR3oKyFPXv:2142269487) ([raw file](https://github.com/kubernetes/dashboard/blob/1f9379df7bd171d9b0c129b6a7c27a1f41e6ec0b/src/app/frontend/common/components/i18n/i18n_directive.js#L30)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Do we need span? Did you test without it? 
</details>
Didn't work without it, I'll retest it once more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/963)*

**Comment by taimir** [comment]
Review status: 3 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/common/components/i18n/i18n_directive.js, line 28 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/963#-KLGoWwJ24GpmL8Ayr3p:-KLGrJHcrnD0QYZ_MhIg:-77436922) ([raw file](https://github.com/kubernetes/dashboard/blob/1f9379df7bd171d9b0c129b6a7c27a1f41e6ec0b/src/app/frontend/common/components/i18n/i18n_directive.js#L28)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Hmm... I dont think we should watch for changes. IMO just render the directive once and that's all. Our translations do not change at runtime.
> 
> @digitalfishpond @maciaszczykm What do you think? 
</details>
Oh definitely, I overlooked this one.

---

*[src/app/frontend/common/components/i18n/i18n_directive.js, line 30 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/963#-KLGomty7oRV8o1HyBcg:-KLGqZI4h7r36iV525y-:1315972089) ([raw file](https://github.com/kubernetes/dashboard/blob/1f9379df7bd171d9b0c129b6a7c27a1f41e6ec0b/src/app/frontend/common/components/i18n/i18n_directive.js#L30)):*
So if I do not open with an html tag, I get an error:
>
>Looking up elements via selectors is not supported by jqLite! See: http://docs.angularjs.org/api/angular.element
>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/963)*

**Comment by maciaszczykm** [comment]
Review status: 3 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/common/components/i18n/i18n_directive.js, line 28 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/963#-KLGoWwJ24GpmL8Ayr3p:-KLH-KWiAaPjlJ77ifgU:366406509) ([raw file](https://github.com/kubernetes/dashboard/blob/1f9379df7bd171d9b0c129b6a7c27a1f41e6ec0b/src/app/frontend/common/components/i18n/i18n_directive.js#L28)):*
<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> Oh definitely, I overlooked this one.
</details>
Agree with @bryk.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/963)*

**Comment by bryk** [comment]
Last comments, otherwise looks nice :) 

---

Review status: 3 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/common/components/i18n/i18n_directive.js, line 18 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/963#-KLH5RpFoiPr9prk9sXO:-KLH5RpGd7z8PTIrP0bi:-828265994) ([raw file](https://github.com/kubernetes/dashboard/blob/9457b2d010e336cc45efdd99a831fed9a01eac3a/src/app/frontend/common/components/i18n/i18n_directive.js#L18)):*
> ```JavaScript
>  * Directive which can render i18n messages that contain angular directives
>  * as placeholders.
>  *
> ```

Can you maybe add a small example usage? It is not abvious. 

---

*[src/app/frontend/common/resource/deleteresource_controller.js, line 83 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/963#-KLH6Kfo_meN-HaMAZLm:-KLH6KfpbgnWz2VCd27e:1292147492) ([raw file](https://github.com/kubernetes/dashboard/blob/9457b2d010e336cc45efdd99a831fed9a01eac3a/src/app/frontend/common/resource/deleteresource_controller.js#L83)):*
> ```JavaScript
>         {
>           'resourceKindName': resourceKindName,
>           'elipsisStart': `<kd-middle-ellipsis display-string="`,
> ```

Why to have this here? We could move this to the translation text. It is similarly translator-unfriendly as the {$elipsisStart}. All translated projects I've worked so far had HTML markup allowed in messages and it worked fine :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/963#-:-KLH7GBkeLj8pXRhhwdi:-905703981)*

**Comment by taimir** [comment]
Review status: 3 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/common/resource/deleteresource_controller.js, line 83 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/963#-KLH6Kfo_meN-HaMAZLm:-KLH908q1CyH3UzsKNCN:234931590) ([raw file](https://github.com/kubernetes/dashboard/blob/9457b2d010e336cc45efdd99a831fed9a01eac3a/src/app/frontend/common/resource/deleteresource_controller.js#L83)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Why to have this here? We could move this to the translation text. It is similarly translator-unfriendly as the {$elipsisStart}. All translated projects I've worked so far had HTML markup allowed in messages and it worked fine :) 
</details>
Fair enough, I myself was unsure if the additional placeholders bring any benefit with them. I'll simplify it :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/963)*

**Comment by taimir** [comment]
Review status: 3 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/common/components/i18n/i18n_directive.js, line 28 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/963#-KLGoWwJ24GpmL8Ayr3p:-KLQppZMgDB87fRmy-Ej:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/1f9379df7bd171d9b0c129b6a7c27a1f41e6ec0b/src/app/frontend/common/components/i18n/i18n_directive.js#L28)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> Agree with @bryk.
</details>
Done.

---

*[src/app/frontend/common/components/i18n/i18n_directive.js, line 18 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/963#-KLH5RpFoiPr9prk9sXO:-KLQpmqNJwShKVS9O7ee:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/9457b2d010e336cc45efdd99a831fed9a01eac3a/src/app/frontend/common/components/i18n/i18n_directive.js#L18)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Can you maybe add a small example usage? It is not abvious. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/963)*

**Comment by bryk** [comment]
One more thing. Run `gulp build` to rebuild messages with their latest version :) 

---

Reviewed 4 of 9 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/963#-:-KLQuBf2-dFkPj9hEjJl:-1920038257)*

**Comment by taimir** [comment]
Oh right, I just changed one of them ... hah

---

Review status: 7 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/963#-:-KLR0LrwRV795RxRbktr:-163454259)*

**Comment by taimir** [comment]
PTAL

---

Review status: 7 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/963#-:-KLR1MQlzviCjell28VF:676965300)*

**Comment by bryk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/963#-:-KLR4awsumk_XGfJBXZm:1417088721)*

**Pull request merged**
