### PR TITLE
Release v1.8.0

### LINKED ISSUE #2597: User panel bug
image

Only signout option should be available.

### PR DESCRIPTION
**Pull request by maciaszczykm**
- [x] update API versions in YAML files using versions from https://kubernetes.io/docs/api-reference/v1.8/ as the release is compatible with 1.8.x only
- [x] update versions in the code
- [x] https://github.com/kubernetes/dashboard/pull/2516#issuecomment-344891224
- [x] tests with HEAD image
- [x] fix #2597 
- [x] Update screenshot in README

### CODE REVIEW

**Comment by maciaszczykm** [comment]
**TODO:** Check if it works without match labels and new apps/v1beta2 client.

**Comment by floreks** [comment]
**TODO**: Update official yamls similar to head yamls (use auto generate certificate feature).

**Comment by bryk** [comment]
Is this ready for testing?

**Comment by floreks** [comment]
Yes. We have already tested it.

**Comment by floreks** [comment]
LGTM

**Comment by bryk** [comment]
Ok, deferring this to Monday.

**Comment by bryk** [comment]
@floreks Should I wait for #2617 ?

**Comment by floreks** [comment]
#2617 is not a proper fix. I have updated already the yaml in this PR. It is ready to merge.

**Pull request merged**
