### PR TITLE
Style fix

### PR DESCRIPTION
**Pull request by maciaszczykm**
Fixed styles:

- updated `Create a new image pull secret` dialog to use `md-dialog-content` instead of `md-content`
- fixed issue #303, please check it for more details

### CODE REVIEW

**Comment by bryk** [comment]
This does not fix the problem. Try scrolling down on replica sets list page and clicking logs menu.

**Comment by maciaszczykm** [comment]
@bryk I'll check. At least it seems to fix issue with option pickers.

**Comment by bryk** [comment]
Try looking at `z-index`. The catch-all container for popups seems to be at z-index: 50.

**Comment by maciaszczykm** [comment]
> This does not fix the problem. Try scrolling down on replica sets list page and clicking logs menu.

Could you send a screenshot of problem? It seems to work for me:

image

**Comment by bryk** [comment]
You're right. Sorry for the mess. I've probably opened wrong instance. Too many dashboards at the same time...

**Comment by bryk** [comment]
LGTM

**Comment by maciaszczykm** [comment]
Okay, then we shouldn't set `z-index`, because it could move toolbar in front of shadow which is created during dialog opening. Situation with too many dashboards happen to us, so for you it must be even worse :)

**Pull request merged**
