### PR TITLE
Make delete RC button less verbose and inline with RC title.

### LINKED ISSUE #465: "Delete replication controller" button too verbose
The button is very verbose. Perhaps we should rename it to "delete" and better indicate that this page is about RCs (if this confuses users). 

selection_036

@floreks @cheld @maciaszczykm

### PR DESCRIPTION
**Pull request by bryk**
Fixes #465 
selection_038

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/470)

### CODE REVIEW

**Comment by bryk** [comment]
@cheld @floreks Can you review?

**Comment by floreks** [comment]
I think @maciaszczykm will not like this solution ;)

**Comment by maciaszczykm** [comment]
@bryk How about removing delete label too and leaving only icon? Currently it's incosistent with edit pencil.

**Comment by floreks** [comment]
I agree with @maciaszczykm

**Comment by bryk** [comment]
selection_039

I like your suggestion. PTAL

**Comment by bryk** [comment]
We can alternatively move this to the `Name` section. Opinions?

**Comment by floreks** [comment]
Sounds good to me. It will be event more specific, just like `edit`.

**Comment by maciaszczykm** [comment]
@bryk I was going to make such proposal, LGTM.

**Comment by bryk** [comment]
Now it looks like this, can you take another look?
selection_041

**Comment by maciaszczykm** [comment]
LGTM :+1:

**Pull request merged**
