### PR TITLE
Make deploy pages go back to previous state

### LINKED ISSUE #884: YAML/app deploy cancel should go back to previous page, not workloads
YAML/app deploy cancel should go back to previous page, not workloads. Currently when you hit cancel on that page you always get redirected to workloads.

### PR DESCRIPTION
**Pull request by bryk**
Fixes #884

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/890)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm Can you review this?

**Comment by maciaszczykm** [comment]
@bryk Code looks good. However, tests need update. I'll test it soon.

**Comment by maciaszczykm** [comment]
Please fix Travis and if you agree with behavior described in one of my comments, then :lgtm: 

<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> @bryk Code looks good. However, tests need update. I'll test it soon.
</details>


---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/deploy/deployfromfile_controller.js, line 97 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/890#-KK8uMd1Pr2px0ZW34Nj:-KK8uMd1Pr2px0ZW34Nk:1711857803) ([raw file](https://github.com/kubernetes/dashboard/blob/0c9a44c91b9dd64f3316ff5d72ea4a42258281b2/src/app/frontend/deploy/deployfromfile_controller.js#L97)):*
> ```JavaScript
>               this.errorDialog_.open('Deployment has been partly completed', response.error);
>             }
>             this.kdHistoryService_.back(workloads);
> ```

Hmm... It code it looks like it should redirect to previous state, but when I was testing on `serve:prod` after successful deploy I was always redirected to workloads view. Is it expected behavior? 

---

*[src/app/frontend/deploy/deployfromfile_controller.js, line 119 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/890#-KK8uj-odAz8J5QsRCAc:-KK8uj-odAz8J5QsRCAd:-1340585311) ([raw file](https://github.com/kubernetes/dashboard/blob/0c9a44c91b9dd64f3316ff5d72ea4a42258281b2/src/app/frontend/deploy/deployfromfile_controller.js#L119)):*
> ```JavaScript
>    * @export
>    */
>   cancel() { this.kdHistoryService_.back(workloads); }
> ```

Works good!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/890#-:-KK8uoMMAF35khRsjwor:126629750)*

**Comment by bryk** [comment]
Yeah... Integration tests. I'll fix them :)

**Comment by bryk** [comment]
Review status: 6 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/deploy/deployfromfile_controller.js, line 97 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/890#-KK8uMd1Pr2px0ZW34Nj:-KKJSbePUm8IR4NE_EcK:-1783143306) ([raw file](https://github.com/kubernetes/dashboard/blob/0c9a44c91b9dd64f3316ff5d72ea4a42258281b2/src/app/frontend/deploy/deployfromfile_controller.js#L97)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> Hmm... It code it looks like it should redirect to previous state, but when I was testing on `serve:prod` after successful deploy I was always redirected to workloads view. Is it expected behavior? 
</details>
Maybe you were on workloads view?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/890)*

**Comment by maciaszczykm** [comment]
I'll retest it tommorow.

**Comment by bryk** [comment]
Merging.

---

Reviewed 2 of 4 files at r2, 2 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/890#-:-KKhntWbLUaFZkL-mkcx:1751543806)*

**Comment by bryk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/deploy/deployfromfile_controller.js, line 97 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/890#-KK8uMd1Pr2px0ZW34Nj:-KKhnwrUCcPEuaV-ByyK:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/0c9a44c91b9dd64f3316ff5d72ea4a42258281b2/src/app/frontend/deploy/deployfromfile_controller.js#L97)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Maybe you were on workloads view?
</details>
Done.

---

*[src/app/frontend/deploy/deployfromfile_controller.js, line 119 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/890#-KK8uj-odAz8J5QsRCAc:-KKhnw_j1hpp-DXg1W7l:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/0c9a44c91b9dd64f3316ff5d72ea4a42258281b2/src/app/frontend/deploy/deployfromfile_controller.js#L119)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> Works good!
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/890)*

**Pull request merged**
