### PR TITLE
你好，能够帮助我一下吗

### PR DESCRIPTION
**Pull request by kfzly**
我照官方教程一直没法编译，你能帮帮我吗

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Few things:

1. We can barely understand you using translator. Can you use English?
2. You need to sign the CLA to contribute. I see, that commits are from other account. Can you solve it?
3. We would like to keep only translation files and your change includes more files, could you tell us why?

Thank you in advance.

**Comment by kfzly** [comment]
i can't build dashbord you can help me? i use requirements-installation.md

**Comment by kfzly** [comment]
i can't build dashbord you can help me? i use requirements-installation.md @maciaszczykm

**Comment by floreks** [comment]
[Docker](https://docs.docker.com/engine/installation/linux/ubuntu/)
[Go](https://golang.org/doc/install#install)
[NVM (Node + npm)](https://github.com/creationix/nvm#install-script)
Java - on ubuntu you can run `sudo apt-get install default-jre`

After everything is intalled run:
`npm install -g gulp`

Clone dashboard with `git clone ...`

Go to dashboard directory and run `npm install`

Then try to run `gulp build` or `gulp serve`. It should work.

**Comment by kfzly** [comment]
@floreks Thanks! you can give me your email address

**Comment by floreks** [comment]
It's in my profile

**Comment by maciaszczykm** [comment]
Closing it as stale. Unfortunately there is no progress and we have no understanding of these changes. Please reopen if you will be willing to explain it to us and sign the CLA.

> Few things:
>
> 1. We can barely understand you using translator. Can you use English?
>2. You need to sign the CLA to contribute. I see, that commits are from other account. Can you solve it?
>3. We would like to keep only translation files, but your change includes more files, could you tell us why?

**Pull request closed without merging**
