### PR TITLE
Add more details and redesign replica set details view

### PR DESCRIPTION
**Pull request by bryk**
* Add more details: name & namespace, service name
* Refresh the view on replicas change
* Overall design refresh of the left menu

selection_012

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm Can you review?

**Comment by maciaszczykm** [comment]
@bryk Of course, sorry for delay.

**Comment by maciaszczykm** [comment]
As you can see on image below, there is an issue with styling of message cells in events table. Perhaps you could update it in this pull request (it's probably not connected to it, but it would be nice thing to do)? Otherwise, I can create pull request for it.

image

`Replica set` and `Services` labels should have bigger top and bottom margins in my opinion. 

There is an information about desired number of pods, but there is no information about their current number. This information is only present in edit pods number dialog.

I didn't notice any issues in the code. PTAL

**Comment by bryk** [comment]
> Replica set and Services labels should have bigger top and bottom margins in my opinion.

Yeah, sounds good. How about adding $baseline-grid (8xp) to the top?

**Comment by bryk** [comment]
> There is an information about desired number of pods, but there is no information about their current number. This information is only present in edit pods number dialog.

How about adding a new section called, like, `Pod statuses` which will have info `3 running, 4 waiting`.

**Comment by bryk** [comment]
> As you can see on image below, there is an issue with styling of message cells in events table. Perhaps you could update it in this pull request (it's probably not connected to it, but it would be nice thing to do)? Otherwise, I can create pull request for it.

Can you create a separate PR with this? Sounds like a small task.

**Comment by maciaszczykm** [comment]
> Can you create a separate PR with this? Sounds like a small task.

Yes, of course.

**Comment by maciaszczykm** [comment]
> Yeah, sounds good. How about adding $baseline-grid (8xp) to the top?

Sounds okay, should be fine.

**Comment by maciaszczykm** [comment]
> How about adding a new section called, like, Pod statuses which will have info 3 running, 4 waiting?

Yeah, something like pods status (not sure which name would be better) would be more intuitive I think.

**Comment by bryk** [comment]
New version. PTAL. 

selection_013

**Comment by maciaszczykm** [comment]
LGTM :)

**Comment by floreks** [comment]
New version look really nice. Pod statuses is really useful. It's good that you've added reload on dialog close. I've found 2 small style issues.

screenshot from 2016-01-19 13-38-48

The pencil should be a bit lower. Centered with the text. Now it's higher over the bottom of the text.

When status of pods is waiting only then there is just comma hanging on the end.

**Comment by bryk** [comment]
PTAL. I've fixed the comma issue and aligned the pencil with bottom text.

**Comment by bryk** [comment]
Also, renamed `waiting` to `pending` to use official API wording.

**Comment by floreks** [comment]
Perfect. LGTM :)

**Comment by bryk** [comment]
Thanks for the review!

**Pull request merged**
