### PR TITLE
Pamper pod list view: a few usability fixes

### PR DESCRIPTION
**Pull request by bryk**
1. Removed cluster IP colum - it is little useful there
2. Made status column ellipsable
3. Adjusted default widths and scaling factors for all columns - now age and restarts are small and no grow, others grow as needed
4. Made sparklines 80px wide - we don't need anything more for 15 points of data anyway

### CODE REVIEW

**Comment by bryk** [comment]
@rf232 Can you review this?

**Comment by bryk** [comment]
Is:

image


Was: 
image

**Comment by rf232** [comment]
Resolve podcardlist.html, but LGTM

**Comment by bryk** [comment]
Merged, PTAL

**Pull request merged**
