### PR TITLE
Bump husky from 5.1.2 to 5.1.3

### PR DESCRIPTION
**Pull request by damingerdai**
Update to husky version 5.1.3 to better support windows usage.

### CODE REVIEW

**Comment by damingerdai** [comment]
*npm run check:license*  will failed for new folder `.husky`. Is it necessary to ignore？

**Comment by damingerdai** [comment]
assign @maciaszczykm

**Comment by damingerdai** [comment]
@floreks 
husky5 is different from husky4. the husky5 need the new config file.
my pr is to upgrade husky5 with their corresponding hook file.
the more detail please visit the [docs](https://dev.to/typicode/what-s-new-in-husky-5-32g5)

**Comment by floreks** [comment]
@damingerdai sorry. That is true. We are using new husky on a different project and I have forgotten that it requires this new directory right now. Feel free to create a PR to initialize and move the config from `package.json` to the husky dir.

**Pull request closed without merging**
