### PR TITLE
Use ISO8601 date format everywhere

### LINKED ISSUE #1470: Dashboard should present standardised dates (or make it an option)
#### Issue details

I really would like to see ISO8601 dates in the dashboard.

##### Environment

```
Dashboard version: 1.4.0
Kubernetes version: NA
Operating system: NA
Node.js version: NA
Go version: NA
```

##### Steps to reproduce
Install v1.4.0, navigate anywhere in the UI, observe date formats

##### Observed result
23/11/16 HH:MM

##### Expected result
2016-11-23 HH:MM

##### Comments
If someone points me in the right direction and agrees that ISO8601 is the one true way <TM> I'm happy to try to make a pull request out of it.

### PR DESCRIPTION
**Pull request by mrwacky42**
Fixes #1470.

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Hey! Two things:

1. To fix CLA issues, please click details button next to failed check.
2. What about putting format variable in global app config? Eventually making time filter to make sure, that with every change we should modify only one bit of code?

https://github.com/kubernetes/dashboard/blob/fda85eff6a007e49fe7f0f34875f07a4b249260e/src/app/frontend/common/appconfig/appconfig_service.js

**Comment by maciaszczykm** [comment]
Please update frontend tests too, because they are failing right now.

**Comment by bryk** [comment]
@mrwacky42 I think we have conflicts. Can you resolve?

**Comment by mrwacky42** [comment]
@bryk - rebased to master.

**Comment by mrwacky42** [comment]
@bryk - rebased & merged.

**Comment by bryk** [comment]
@mrwacky42 Thanks! Merging.

**Pull request merged**
