### PR TITLE
Separate commands from output in docs/user

### PR DESCRIPTION
**Pull request by ydFu**
* Separate commands from output in docs/user

* Add the Code blocks in the Markdown spec to make docs/user easy to read.

Fix 'Highlighting code blocks in docs '(#5805)

Signed-off-by: ydFu <ader.ydfu@gmail.com>

### CODE REVIEW

**Comment by shu-mutou** [comment]
Let's unify `bash` into `shell`.
Could you apply this to `docs/user/accessing-dashboard/README.md` also?

**Comment by shu-mutou** [comment]
See also #5805, please apply it into other docs if you have time.

**Comment by ydFu** [comment]
> Let's unify `bash` into `shell`.
> Could you apply this to `docs/user/accessing-dashboard/README.md` also?

Thank you for suggesting me,I have adjusted as suggested.

> See also #5805, please apply it into other docs if you have time.

Thank you for the invitation,I will try my best help `kubernetes/dashboard` to do it.
@shu-mutou

**Comment by shu-mutou** [comment]
/lgtm
thanks!

**Pull request merged**
