### PR TITLE
Show loading spinner on first page view

### LINKED ISSUE #827: Loading spinner does not work for first page view

### PR DESCRIPTION
**Pull request by bryk**
Fixes #827

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/870)

### CODE REVIEW

**Comment by bryk** [comment]
@digitalfishpond Can you review this? :)

**Comment by digitalfishpond** [comment]
Code looks good to me.  The spinner works :) :lgtm: 

<details><summary><i>Previously, codecov-io wrote…</i></summary>
> ## [Current coverage][cc-pull] is **93.92%**
> > Merging [#870][cc-pull] into [master][cc-base-branch] will increase coverage by **0.32%**
> 
> 1. File `...ereader_directive.js` (not in diff) was modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/dbfec7755ea5d190f25f2623c7344bd3f47f8c34/changes?src=pr#7372632F6170702F66726F6E74656E642F6465706C6F792F66696C657265616465725F6469726563746976652E6A73) 
>   - Misses `-6` 
>   - Partials `0` 
>   - Hits `+6`
> 
> ```diff
> @@             master       #870   diff @@
> ==========================================
>   Files           223        223          
>   Lines          1874       1876     +2   
>   Methods           0          0          
>   Messages          0          0          
>   Branches          0          0          
> ==========================================
> + Hits           1754       1762     +8   
> + Misses          120        114     -6   
>   Partials          0          0          
> ```
> 
> > Powered by [Codecov](https://codecov.io?src=pr). Last updated by [6cc2410...dbfec77][cc-compare]
> [cc-base-branch]: https://codecov.io/gh/kubernetes/dashboard/branch/master?src=pr
> [cc-compare]: https://codecov.io/gh/kubernetes/dashboard/compare/6cc2410eea552f729484123dce9d23be0e591b3a...dbfec7755ea5d190f25f2623c7344bd3f47f8c34
> [cc-pull]: https://codecov.io/gh/kubernetes/dashboard/pull/870?src=pr
</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/870#-:-KJuFtRJbJuB0eQgEn2e:-122645295)*

**Comment by digitalfishpond** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/870)*

**Comment by bryk** [comment]
Awesome, thanks!

**Pull request merged**
