### PR TITLE
Fix "contribute" link

### PR DESCRIPTION
**Pull request by ApsOps**
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/865)

### CODE REVIEW

**Comment by ApsOps** [comment]
I signed it!

**Comment by floreks** [comment]
It was moved from main repo directory to /.github/contributing.md 
Could you change that instead of removing?

**Comment by ApsOps** [comment]
@floreks Done!

**Comment by bryk** [comment]
@ApsOps Thanks for this first contribution! :) Let us know if you need any help

**Comment by bryk** [comment]
@floreks Can you merge when done reviewing?

**Comment by floreks** [comment]
@ApsOps Awesome! Thanks. :lgtm:

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> @floreks Can you merge when done reviewing? 
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/865#-:-KJtKDUT5FtSi9FsK48K:1484315218)*

**Pull request merged**
