### PR TITLE
Update Angular to v16

### LINKED ISSUE #8101: Bump Angular and switch to Vite builds
### What should be cleaned up or changed?

See https://blog.angular.io/angular-v16-is-here-4d7a28ec680d.

### Why is this needed?

To keep dependencies up to date and speed up builds.

### PR DESCRIPTION
**Pull request by maciaszczykm**
Closes #8101.

### CODE REVIEW

**Review by floreks — APPROVED** [review]
/lgtm

**Comment by shu-mutou** [comment]
I also checked this in my development environment and this works fine.
But I also faced error as same as CI. So I tried to increase timeout value for cypress, it was not effective. I'm keeping on investigating this error now.

**Comment by shu-mutou** [comment]
I found the Air starts to rebuild while cypress running. We may need to configure `.air.toml`, I guess.

**Comment by shu-mutou** [comment]
I confirmed that the number of the Air rebuilds is same as the number of screenshots (includes its folder).

**Comment by shu-mutou** [comment]
Also, I confirmed `touch modules/web/cypress/screenshots/test` triggered rebuild backend server that was started by `make serve`.

**Comment by shu-mutou** [comment]
I tried some changes in  https://github.com/kubernetes/dashboard/blob/master/modules/api/.air.toml#L21 , but the `.air.toml` file didn't seem to work as documented, not also as we expected. :disappointed: 
It's time to finish work. See you!

**Comment by maciaszczykm** [comment]
Thanks @shu-mutou for taking care of e2e.

**Pull request merged**
