### PR TITLE
Fix url in README.md

### PR DESCRIPTION
**Pull request by Behoston**
Resolves: #3441.

### CODE REVIEW

**Comment by maciaszczykm** [comment]
You need to sign the CLA.

**Comment by Behoston** [comment]
> You need to sign the CLA.

I know. Already done :)

**Comment by Behoston** [comment]
.

**Comment by Behoston** [comment]
I signed CLA, but commit has a secondary email address.

**Comment by floreks** [comment]
You would need to reopen and commit with a different mail. @maciaszczykm will take care of this. Anyway, thanks you for such a quick reaction!

**Comment by maciaszczykm** [comment]
Sorry, we have to fix this ASAP. Done in #3443.

**Comment by Behoston** [comment]
> Sorry, we have to fix this ASAP. Done in #3443.

NP :)

**Pull request closed without merging**
