### PR TITLE
Localization of common components

### PR DESCRIPTION
**Pull request by taimir**
Localization of all the common components, excluding `resource`.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/796)

### CODE REVIEW

**Comment by taimir** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/common/components/labels/labels.html, line 23 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/796#-KJBZIiMpq-NOCuk53VZ:-KJBZIiMpq-NOCuk53V_:371287583) ([raw file](https://github.com/kubernetes/dashboard/blob/8ee1b3c9934c879116e5019c3981ffaa5f396465/src/app/frontend/common/components/labels/labels.html#L23)):*
> ```HTML
> <div class="kd-labels kd-labels-switch" ng-show="labelsCtrl.isMoreAvailable()"
>      ng-click="labelsCtrl.switchLabelsView()">
>   {{labelsCtrl.isShowingAll() ? labelsCtrl.i18n.MSG_LABELS_SHOW_LESS_TOOLTIP : labelsCtrl.i18n.MSG_LABELS_SHOW_ALL_TOOLTIP}}
> ```

Can I do a multi-line binding in angular? This line needs to be shorter ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/796)*

**Comment by bryk** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/common/components/actionbar/actionbardeleteitem.html, line 21 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/796#-KJEhxtzWjGcwPQms3K2:-KJEhxtzWjGcwPQms3K3:2080288906) ([raw file](https://github.com/kubernetes/dashboard/blob/8ee1b3c9934c879116e5019c3981ffaa5f396465/src/app/frontend/common/components/actionbar/actionbardeleteitem.html#L21)):*
> ```HTML
>   <md-icon class="kd-actionbar-icon-button">delete</md-icon>
>   <md-tooltip md-direction="bottom">
>     {{::$ctrl.i18n.MSG_ACTION_BAR_DELETE_TOOLTIP}} {{::$ctrl.resourceKindName}}
> ```

Btw, in goog.getMsg you can add "holes" to fill values in. The holes may be moved around in different languages. E.g., you can have the message to be: "Delete {}". And the {} is replaced in code with resourceKindName. This is important, since some languages have "verb then noun" and some "noun then verb". 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/796)*

**Comment by taimir** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/common/components/actionbar/actionbardeleteitem.html, line 21 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/796#-KJEhxtzWjGcwPQms3K2:-KJEtzT0dUwPXXtzZ_CV:790284538) ([raw file](https://github.com/kubernetes/dashboard/blob/8ee1b3c9934c879116e5019c3981ffaa5f396465/src/app/frontend/common/components/actionbar/actionbardeleteitem.html#L21)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Btw, in goog.getMsg you can add "holes" to fill values in. The holes may be moved around in different languages. E.g., you can have the message to be: "Delete {}". And the {} is replaced in code with resourceKindName. This is important, since some languages have "verb then noun" and some "noun then verb". 
</details>
Oh yeah, you're totally right. I know about the `{}` placeholders, but I just forgot that even for 2-word expressions the order of the words might still change...

I wanted to discuss this interpolation problem, actually. In dashboard we sometimes have text in the form:

```{html}
Text starts here <some code, e.g. {{ctrl.name}}> text continues here <some link> text ends. 
```

Now on a couple of occasions I tried placing the code that's in between as `{}` placeholders in the message variable. Then I can use `ng-bind-html` directive to render this MSG_ variable which contains some html code. 

This works fine if the code does not contain e.g. a binding like `{{ctrl.name}}`. But if there are some bindings, they are just displayed directly and not evaluated. I investigated this for a while and found a solution on StackOverflow which uses a directive to essentially reevalute those bindings before rendering. It looks like this:

```{js}
export default angular.module('compile', [], function($compileProvider) {
  $compileProvider.directive('compile', function($compile) {
    return function(scope, element, attrs) {
      scope.$watch(
          function(scope) { return scope.$eval(attrs.compile); },
          function(value) {
            element.html(value);
            $compile(element.contents())(scope);
          });
    };
  });
});
```

And can be used like this to render a variable which contains some angular bindings in it:

```{html}
<span compile="::ctrl.i18n.MSG_SOME_VARIABLE"></span>
```

Can you think of a cleaner solution to this? I am not confident I know all of the implications of the recompilation above...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/796)*

**Comment by bryk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/common/components/actionbar/actionbardeleteitem.html, line 21 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/796#-KJEhxtzWjGcwPQms3K2:-KJFS9-QoYP1dVQhRmDX:1989603813) ([raw file](https://github.com/kubernetes/dashboard/blob/8ee1b3c9934c879116e5019c3981ffaa5f396465/src/app/frontend/common/components/actionbar/actionbardeleteitem.html#L21)):*
<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> Oh yeah, you're totally right. I know about the `{}` placeholders, but I just forgot that even for 2-word expressions the order of the words might still change...
> 
> I wanted to discuss this interpolation problem, actually. In dashboard we sometimes have text in the form:
> 
> ```{html}
> Text starts here <some code, e.g. {{ctrl.name}}> text continues here <some link> text ends. 
> ```
> 
> Now on a couple of occasions I tried placing the code that's in between as `{}` placeholders in the message variable. Then I can use `ng-bind-html` directive to render this MSG_ variable which contains some html code. 
> 
> This works fine if the code does not contain e.g. a binding like `{{ctrl.name}}`. But if there are some bindings, they are just displayed directly and not evaluated. I investigated this for a while and found a solution on StackOverflow which uses a directive to essentially reevalute those bindings before rendering. It looks like this:
> 
> ```{js}
> export default angular.module('compile', [], function($compileProvider) {
>   $compileProvider.directive('compile', function($compile) {
>     return function(scope, element, attrs) {
>       scope.$watch(
>           function(scope) { return scope.$eval(attrs.compile); },
>           function(value) {
>             element.html(value);
>             $compile(element.contents())(scope);
>           });
>     };
>   });
> });
> ```
> 
> And can be used like this to render a variable which contains some angular bindings in it:
> 
> ```{html}
> <span compile="::ctrl.i18n.MSG_SOME_VARIABLE"></span>
> ```
> 
> Can you think of a cleaner solution to this? I am not confident I know all of the implications of the recompilation above...
> 
</details>
See docs for goog.getMsg. So, basically, for the example:
`Text starts here <some code, e.g. {{ctrl.name}}> text continues here <some link> text ends. `

the MSG is:
this.MSG_FOO = goog.getMsg('My super text {$name}, foo bar baz http://google.com', {'name': this.name});

```js
/**
 * Gets a localized message.
 *
 * This function is a compiler primitive. If you give the compiler a localized
 * message bundle, it will replace the string at compile-time with a localized
 * version, and expand goog.getMsg call to a concatenated string.
 *
 * Messages must be initialized in the form:
 * <code>
 * var MSG_NAME = goog.getMsg('Hello {$placeholder}', {'placeholder': 'world'});
 * </code>
 *
 * This function produces a string which should be treated as plain text. Use
 * {@link goog.html.SafeHtmlFormatter} in conjunction with goog.getMsg to
 * produce SafeHtml.
 *
 * @param {string} str Translatable string, places holders in the form {$foo}.
 * @param {Object<string, string>=} opt_values Maps place holder name to value.
 * @return {string} message with placeholders filled.
 */
goog.getMsg = function(str, opt_values) {
  ...
};
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/796)*

**Comment by bryk** [comment]
*[src/app/frontend/common/components/actionbar/actionbardeleteitem.html, line 21 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/796#-KJEhxtzWjGcwPQms3K2:-KJFSnz9UECbtCcUGzXx:899818854) ([raw file](https://github.com/kubernetes/dashboard/blob/8ee1b3c9934c879116e5019c3981ffaa5f396465/src/app/frontend/common/components/actionbar/actionbardeleteitem.html#L21)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> See docs for goog.getMsg. So, basically, for the example:
> `Text starts here <some code, e.g. {{ctrl.name}}> text continues here <some link> text ends. `
> 
> the MSG is:
> this.MSG_FOO = goog.getMsg('My super text {$name}, foo bar baz http://google.com', {'name': this.name});
> 
> ```js
> /**
>  * Gets a localized message.
>  *
>  * This function is a compiler primitive. If you give the compiler a localized
>  * message bundle, it will replace the string at compile-time with a localized
>  * version, and expand goog.getMsg call to a concatenated string.
>  *
>  * Messages must be initialized in the form:
>  * <code>
>  * var MSG_NAME = goog.getMsg('Hello {$placeholder}', {'placeholder': 'world'});
>  * </code>
>  *
>  * This function produces a string which should be treated as plain text. Use
>  * {@link goog.html.SafeHtmlFormatter} in conjunction with goog.getMsg to
>  * produce SafeHtml.
>  *
>  * @param {string} str Translatable string, places holders in the form {$foo}.
>  * @param {Object<string, string>=} opt_values Maps place holder name to value.
>  * @return {string} message with placeholders filled.
>  */
> goog.getMsg = function(str, opt_values) {
>   ...
> };
> ```
</details>
The problem is that such messages are hard to put in `const i18n = {}`. They need to be in ctrl to access its variables. 

Does this help? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/796)*

**Comment by taimir** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/common/components/actionbar/actionbardeleteitem.html, line 21 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/796#-KJEhxtzWjGcwPQms3K2:-KJFTP4_DeIuLp-vOSov:283848168) ([raw file](https://github.com/kubernetes/dashboard/blob/8ee1b3c9934c879116e5019c3981ffaa5f396465/src/app/frontend/common/components/actionbar/actionbardeleteitem.html#L21)):*
Yep, that's one issue right there.

And are you sure this will actually work? The doc says:

>If you give the compiler a localized message bundle, it will replace the string at compile-time with a localized version, and expand goog.getMsg call to a concatenated string.

But `this.name` will dynamically change during run-time, and the messages are compiled to string just once in the very beginning (by the closure compiler). So the messages won't be updated when `this.name` changes? Is my understanding correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/796)*

**Comment by bryk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/common/components/actionbar/actionbardeleteitem.html, line 21 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/796#-KJEhxtzWjGcwPQms3K2:-KJFhgdCA6SNKrXEivlF:1448962311) ([raw file](https://github.com/kubernetes/dashboard/blob/8ee1b3c9934c879116e5019c3981ffaa5f396465/src/app/frontend/common/components/actionbar/actionbardeleteitem.html#L21)):*
<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> Yep, that's one issue right there.
> 
> And are you sure this will actually work? The doc says:
> 
> >If you give the compiler a localized message bundle, it will replace the string at compile-time with a localized version, and expand goog.getMsg call to a concatenated string.
> 
> But `this.name` will dynamically change during run-time, and the messages are compiled to string just once in the very beginning (by the closure compiler). So the messages won't be updated when `this.name` changes? Is my understanding correct?
</details>
We can move this to a getter. I.e., 

```js
getFoo() {
  let MSG_FOO = goog.getMsg('...');
  return MSG_FOO;
}
```

or we can move this to a goog.i18n.MessageFormat, like
```js
let MSG=goog.getMsg(
    '{COUNT, plural, =1 {1 foo} other {# foos}}');
return new goog.i18n.MessageFormat(MSG).format({'COUNT': this.count});
```

What do you think? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/796)*

**Comment by bryk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/common/components/labels/labels.html, line 23 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/796#-KJBZIiMpq-NOCuk53VZ:-KJFid3JI6RAdbXsG3U0:-505221539) ([raw file](https://github.com/kubernetes/dashboard/blob/8ee1b3c9934c879116e5019c3981ffaa5f396465/src/app/frontend/common/components/labels/labels.html#L23)):*
<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> Can I do a multi-line binding in angular? This line needs to be shorter ...
</details>
AFAIK you can have. Please test and verify :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/796)*

**Comment by taimir** [comment]
Review status: 7 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/common/components/actionbar/actionbardeleteitem.html, line 21 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/796#-KJEhxtzWjGcwPQms3K2:-KJZle0shA9BWInvewzB:1066334659) ([raw file](https://github.com/kubernetes/dashboard/blob/8ee1b3c9934c879116e5019c3981ffaa5f396465/src/app/frontend/common/components/actionbar/actionbardeleteitem.html#L21)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> We can move this to a getter. I.e., 
> 
> ```js
> getFoo() {
>   let MSG_FOO = goog.getMsg('...');
>   return MSG_FOO;
> }
> ```
> 
> or we can move this to a goog.i18n.MessageFormat, like
> ```js
> let MSG=goog.getMsg(
>     '{COUNT, plural, =1 {1 foo} other {# foos}}');
> return new goog.i18n.MessageFormat(MSG).format({'COUNT': this.count});
> ```
> 
> What do you think? 
> 
> 
</details>
Ah, what a relief - I just tried it out again and this will work :) I misunderstood the doc, the placeholders are evaluated at runtime, only the rest of the text is compiled to a string in the very beginning - very cool, just like it should be!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/796)*

**Comment by taimir** [comment]
PTAL, we can move forward with this

**Comment by bryk** [comment]
Reviewed 5 of 7 files at r2.
Review status: 12 of 14 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/common/components/actionbar/actionbardeleteitem.html, line 21 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/796#-KJEhxtzWjGcwPQms3K2:-KJZui79vOnBvX5XoK85:160362412) ([raw file](https://github.com/kubernetes/dashboard/blob/8ee1b3c9934c879116e5019c3981ffaa5f396465/src/app/frontend/common/components/actionbar/actionbardeleteitem.html#L21)):*
<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> Ah, what a relief - I just tried it out again and this will work :) I misunderstood the doc, the placeholders are evaluated at runtime, only the rest of the text is compiled to a string in the very beginning - very cool, just like it should be!
</details>
:) 

---

*[src/app/frontend/common/components/actionbar/actionbardeleteitem_component.js, line 71 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/796#-KJZumz1pISrjA6QrPhP:-KJZumz1pISrjA6QrPhQ:-43870718) ([raw file](https://github.com/kubernetes/dashboard/blob/a67fdca3b798f3b2ee701a58e3bf8c02677791ef/src/app/frontend/common/components/actionbar/actionbardeleteitem_component.js#L71)):*
> ```JavaScript
>     /** @export {string} @desc Generic "Delete some resource" tooltip text which appears over the delete icon on the global action bar. */
>     let MSG_ACTION_BAR_DELETE_TOOLTIP =
>         goog.getMsg('Delete {$resourceName}', {resourceName: this.resourceKindName});
> ```

We need to have resourcename in parens, e.g., `'resourceName'`. This is due to renaming. 

---

*[src/app/frontend/deploy/deploylabel_controller.js, line 144 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/796#-KJZv5BJ0ds4WJFbBCZ5:-KJZv5BJ0ds4WJFbBCZ6:-1917383864) ([raw file](https://github.com/kubernetes/dashboard/blob/a67fdca3b798f3b2ee701a58e3bf8c02677791ef/src/app/frontend/deploy/deploylabel_controller.js#L144)):*
> ```JavaScript
>     /** @export {string} @desc This warning appears when the key of a specified kubernetes label on the deploy page is not unique.*/
>     let MSG_DEPLOY_LABEL_KEY_NOT_UNIQUE_WARNING =
>         goog.getMsg('{$labelKey} is not unique.', {labelKey: this.label.key});
> ```

We need `'labelKey'`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/796)*

**Comment by taimir** [comment]
Review status: 11 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/common/components/actionbar/actionbardeleteitem_component.js, line 71 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/796#-KJZumz1pISrjA6QrPhP:-KJ_-bvou8HuITc7oTZR:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/a67fdca3b798f3b2ee701a58e3bf8c02677791ef/src/app/frontend/common/components/actionbar/actionbardeleteitem_component.js#L71)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> We need to have resourcename in parens, e.g., `'resourceName'`. This is due to renaming. 
</details>
Done.

---

*[src/app/frontend/deploy/deploylabel_controller.js, line 144 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/796#-KJZv5BJ0ds4WJFbBCZ5:-KJ_-epl4-hbfbEUlfvw:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/a67fdca3b798f3b2ee701a58e3bf8c02677791ef/src/app/frontend/deploy/deploylabel_controller.js#L144)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> We need `'labelKey'`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/796)*

**Comment by bryk** [comment]
Hmm... Can you take a look at conflicts and the coverage diff? It is strange.

**Comment by taimir** [comment]
PTAL

**Comment by bryk** [comment]
:lgtm:

<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> PTAL
</details>


---

Reviewed 1 of 7 files at r2, 11 of 11 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/796#-:-KJ_zahUJ9U_039j7X6w:1417088721)*

**Pull request merged**
