### PR TITLE
Ng migration update ng 6.0.7

### PR DESCRIPTION
**Pull request by owennewo**
I created this branch from ng-migration then merged my old changes too it.  Hence this PR request should be clean.  However package-lock.json was very messy (conflicted) and I chose to accept all my version as I'd updated many npm packages and ran angular cli update.  

Superficially this merge works (npm start against local minikube ok and jasmine tests ok).   However I haven't tested extensively.

### CODE REVIEW

**Comment by owennewo** [comment]
Hey @austbot @maciaszczykm @pengx17 and others
Here is the new PR targeting the ng-migration branch.

**Comment by maciaszczykm** [comment]
I will check later. Did you test it?

**Comment by maciaszczykm** [comment]
I am still experiencing some issues when running it, perhaps it is caused by different Node.js version. Which one are you using?

**Comment by maciaszczykm** [comment]
```
maciaszczykm @ ~ $ node --version
v10.5.0
```

**Comment by maciaszczykm** [comment]
I've formatted files.

**Comment by maciaszczykm** [comment]
/lgtm

I was able to finally run it, seems to not work on newest Node.js (worked with v8.11.3). It still has few minor issues like different fonts in a few places, but we can fix it later as it seems to be quite important change.

**Comment by maciaszczykm** [comment]
@owennewo @austbot Thank you guys :)

**Pull request merged**
