### PR TITLE
deploy from file integration tests added

### PR DESCRIPTION
**Pull request by batikanu**
It includes the tests in deploy from file view except uploading a file.

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/421)

### CODE REVIEW

**Comment by bryk** [comment]
@taimir Can you review?

**Comment by maciaszczykm** [comment]
I've also done pretty much investigation in this matter (as @bryk advised me in #346) and it seems, that we may have problems with testing file upload. Usually it's done like this:

``` javascript
this.filePickerQuery = by.id('kd-upload-file-picker');
this.filePicker = element(this.filePickerQuery);
this.filePicker.sendKeys(absolutePath);
```

Where `kd-upload-file-picker` is `id` attribute of input with `type="file"`. It works, but in our case this input has attribute `style="display:none"`, because other input is visible in the UI. This complicates everything. We need to set `file.name` and `file.content` before clicking deploy button and it doesn't happen after update of invisible input and there is a problem with updating visible one.

It's first time when I'm using Protractor, so if one of you have more experience with it, please help.

Generally in this integration test we should deploy from `.yaml` file and check if application is working correctly, at the moment it's only basic check, that needs to be enhanced.

BTW. As a file to upload we can use:

``` javascript
var fileToUpload = '../../deploy/kubernetes-dashboard-canary.yaml',
absolutePath = path.resolve(__dirname, fileToUpload);
```

And on Firefox there is some issue with element visibility, which doesn't occur on Chrome. It also needs to be fixed to make tests on saucelabs pass.

**Comment by bryk** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/integration/deploy/deployfromfile_test.js, line 28 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-KBIXuDDQUP7fqhvfZuX:-KBIXuDEr-GZ_KaFdlBA:1746932171) ([raw file](https://github.com/kubernetes/dashboard/blob/8a2b28b2a6b622bbab080aba301581c254ad6947/src/test/integration/deploy/deployfromfile_test.js#L28)):*
This should not be in integration test. This should be in unit tests (which probably is done already).

What should be done is upload file -> see that there were no errors -> see that app is deployed 

@maciaszczykm Opinions? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/421)*

**Comment by maciaszczykm** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/integration/deploy/deployfromfile_test.js, line 28 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-KBIXuDDQUP7fqhvfZuX:-KBIZXqwfJfxVqtiJ2gK:1615131640) ([raw file](https://github.com/kubernetes/dashboard/blob/8a2b28b2a6b622bbab080aba301581c254ad6947/src/test/integration/deploy/deployfromfile_test.js#L28)):*
I agree, at the moment it's not ready. For sure we need to test if file upload works, which is currently not done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/421)*

**Comment by bryk** [comment]
Do you need any help with this? You can make the input with `type="file"` to be invisible with `visibility: none` and width/height 1px. 

Does this help?
http://stackoverflow.com/questions/21305298/how-to-upload-file-in-angularjs-e2e-protractor-testing
https://github.com/angular/protractor/issues/612

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-:-KBMXodaRFgKLyThf-I_:-317023415)*

**Comment by taimir** [comment]
I think we identified the problem - the specified filename in one of the integration tests was wrong :) @batikanu will now wrap it up.

**Comment by batikanu** [comment]
@bryk I am waiting for pull request #420 to be merged because I need replication controller page object for clean ups after deploying a file not to duplicate it in my code.

**Comment by bryk** [comment]
The mentioned branch is merged :)

**Comment by batikanu** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/integration/deploy/deployfromfile_test.js, line 28 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-KBIXuDDQUP7fqhvfZuX:-KBrNeHHWdBkDvEFXHWk:610327451) ([raw file](https://github.com/kubernetes/dashboard/blob/8a2b28b2a6b622bbab080aba301581c254ad6947/src/test/integration/deploy/deployfromfile_test.js#L28)):*
Removed

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/421)*

**Comment by batikanu** [comment]
Ok I have updated the code

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-:-KBrP4BjY-gGcRUKfr01:-774833213)*

**Comment by bryk** [comment]
Looks really nice. PTAL. Last comments. 

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/test/integration/deploy/invalid-rc.yaml, line 1 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-KBrURz_vwXVS86cC1X7:-KBrURz_vwXVS86cC1X8:1063954856) ([raw file](https://github.com/kubernetes/dashboard/blob/77a0d5578df81131e7081c1f33cab03c8fd4b5c6/src/test/integration/deploy/invalid-rc.yaml#L1)):*
Nit: Can you add the boilerplate `copyright` here?

---

*[src/test/integration/deploy/valid-rc.yaml, line 1 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-KBrUM6k8dksatx9WflQ:-KBrUM6l_Y-tXJFxG9y-:1063954856) ([raw file](https://github.com/kubernetes/dashboard/blob/77a0d5578df81131e7081c1f33cab03c8fd4b5c6/src/test/integration/deploy/valid-rc.yaml#L1)):*
Nit: Can you add the boilerplate `copyright` here?

---

*[src/test/integration/stories/deploy _from_valid_file_test.js, line 1 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-KBrTexOL57bGd88NKH5:-KBrTexP6ML-KDhrACA9:930413355) ([raw file](https://github.com/kubernetes/dashboard/blob/77a0d5578df81131e7081c1f33cab03c8fd4b5c6/src/test/integration/stories/deploy _from_valid_file_test.js#L1)):*
Am I blind or this file has space inside? 

---

*[src/test/integration/stories/deploy _from_valid_file_test.js, line 70 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-KBrU2oc4VwoU5Zpf4Wt:-KBrU2oc4VwoU5Zpf4Wu:648552399) ([raw file](https://github.com/kubernetes/dashboard/blob/77a0d5578df81131e7081c1f33cab03c8fd4b5c6/src/test/integration/stories/deploy _from_valid_file_test.js#L70)):*
It is simpler to write: `then(deleteDialog.deleteAppButton.click)`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-:-KBrUVBo95ULXHoisG0U:-1749217860)*

**Comment by batikanu** [comment]
Review status: 5 of 8 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/test/integration/deploy/valid-rc.yaml, line 1 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-KBrUM6k8dksatx9WflQ:-KBrg6bKa6mXm4aJOkVs:676635175) ([raw file](https://github.com/kubernetes/dashboard/blob/77a0d5578df81131e7081c1f33cab03c8fd4b5c6/src/test/integration/deploy/valid-rc.yaml#L1)):*
Done

---

*[src/test/integration/stories/deploy_from_valid_file_test.js, line 70 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-KBrU2oc4VwoU5Zpf4Wt:-KBrgCtYG6k9oxCQ_fM3:1965836768) ([raw file](https://github.com/kubernetes/dashboard/blob/77a0d5578df81131e7081c1f33cab03c8fd4b5c6/src/test/integration/stories/deploy_from_valid_file_test.js#L70)):*
It fails in this form with error message (Failed: Cannot read property 'click' of undefined.)

---

*[src/test/integration/stories/deploy _from_valid_file_test.js, line 1 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-KBrTexOL57bGd88NKH5:-KBrY8XnrjI3nTuRgr_3:-592757349) ([raw file](https://github.com/kubernetes/dashboard/blob/77a0d5578df81131e7081c1f33cab03c8fd4b5c6/src/test/integration/stories/deploy _from_valid_file_test.js#L1)):*
Yes you have very good eyes :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/421)*

**Comment by batikanu** [comment]
Review status: 5 of 8 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/test/integration/deploy/invalid-rc.yaml, line 1 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-KBrURz_vwXVS86cC1X7:-KBs5IFB6NPSixr_MLJH:1174864564) ([raw file](https://github.com/kubernetes/dashboard/blob/77a0d5578df81131e7081c1f33cab03c8fd4b5c6/src/test/integration/deploy/invalid-rc.yaml#L1)):*
Yes I will add them

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/421)*

**Comment by bryk** [comment]
Add this to eslintrc in integrationtest folder to fix travis. 
```

  "env": {
    // Build files are written in node.
    "node": true
  },
```

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/test/integration/stories/deploy_from_valid_file_test.js, line 70 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-KBrU2oc4VwoU5Zpf4Wt:-KBvmXxjEYoPeh8b2OEx:-1465217438) ([raw file](https://github.com/kubernetes/dashboard/blob/77a0d5578df81131e7081c1f33cab03c8fd4b5c6/src/test/integration/stories/deploy_from_valid_file_test.js#L70)):*
OK, then nevermind. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-:-KBvo4oShg0riaPjz4Lc:-1606904791)*

**Comment by batikanu** [comment]
Done.

---

Review status: 7 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/integration/stories/deploy_from_valid_file_test.js, line 70 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-KBrU2oc4VwoU5Zpf4Wt:-KBwH1abndrvJPSmd1UW:5174689) ([raw file](https://github.com/kubernetes/dashboard/blob/77a0d5578df81131e7081c1f33cab03c8fd4b5c6/src/test/integration/stories/deploy_from_valid_file_test.js#L70)):*
ok

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-:-KBwHfWfyh2BezwgLusm:-499146009)*

**Comment by bryk** [comment]
Last comment. PTAL 

---

Reviewed 1 of 4 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/integration/zerostate/zerostate_po.js, line 27 \[r4\]](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-KBwQQ5Am7wnLJSXOU-_:-KBwQQ5Am7wnLJSXOU-a:-434266108) ([raw file](https://github.com/kubernetes/dashboard/blob/d07ec132bbec3a9b85e68b12d4f8c24a7396357b/src/test/integration/zerostate/zerostate_po.js#L27)):*
Remove the 10000 ms timeout. Rely on defaults to have consistent behavior across tests. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-:-KBwQig_qTIdUKGfVFEo:1492742309)*

**Comment by batikanu** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/integration/zerostate/zerostate_po.js, line 27 \[r4\]](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-KBwQQ5Am7wnLJSXOU-_:-KBwSA-UtQndOjM2PGkO:-2125515065) ([raw file](https://github.com/kubernetes/dashboard/blob/d07ec132bbec3a9b85e68b12d4f8c24a7396357b/src/test/integration/zerostate/zerostate_po.js#L27)):*
in production mode zerostate test fails because it is called before deletion of the rc is completed. Therefore I use a waiting condition. I removed the 10000ms

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/421)*

**Comment by batikanu** [comment]
PTAL

---

Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-:-KBwXSXIy78Zfs9pHe32:676965300)*

**Comment by bryk** [comment]
Thanks, :lgtm: 

---

Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/421#-:-KBwfWuN7reTECPSTCSu:1978909618)*

**Comment by bryk** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/421)*

**Comment by floreks** [comment]
@batikanu there are some problems on master related to this PR. Could you check?
https://travis-ci.org/kubernetes/dashboard/builds/113399982

**Comment by bryk** [comment]
Thanks @floreks for taking care of this

**Comment by batikanu** [comment]
I can't reproduce this error in my local machine.

**Pull request merged**
