### PR TITLE
Flickering replicationcontroller list view fixed

### PR DESCRIPTION
**Pull request by batikanu**
timeout is replaced with promise solution.
This should solve the #495 flickering effect in ui.

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/496)

### CODE REVIEW

**Comment by bryk** [comment]
Fix travis?

**Comment by batikanu** [comment]
Yes the tests have also problems I'm currently working on them.

**Comment by batikanu** [comment]
PTAL

**Comment by floreks** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/496#-:-KCLC4i3nYUs6_8VvTPH:980077423)*

**Pull request merged**
