### PR TITLE
Use client-go/dynamic instead client-go/deprecated-dynamic

### PR DESCRIPTION
**Pull request by shu-mutou**
Fixes: kubernetes/dashboard#3501

### CODE REVIEW

**Comment by floreks** [comment]
Cool!

@maciaszczykm should we also remove `deprecated-dynamic` package from the `Gopkg.lock` by applying `dep ensure`?

**Comment by maciaszczykm** [comment]
Yep, we should, but we can do it in the following PR.

**Comment by shu-mutou** [comment]
Removed deprecated-dynamic from Gopkg.lock and vendor. :wink:

**Pull request merged**
