### PR TITLE
Add graph card wrapper

### PR DESCRIPTION
**Pull request by floreks**
To match card style I've wrapped graphs around card component. It can be used without it also.

I've added title to the card but we can also get rid of it. I don't have any strong opinion on that.

With title:
zrzut ekranu z 2016-08-30 23-10-56

Without title:
zrzut ekranu z 2016-08-30 23-11-33

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1171)

### CODE REVIEW

**Comment by floreks** [comment]
I signed it!

**Comment by bryk** [comment]
I'm personally for a title in the card. 

I'd call it "Resource usage history". As "cumulative" implies aggregation type, which is not static. 

@PiotrDabkowski Can you review this? 

---

Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1171#-:-KQUZk_8z4Qsgv-Kj8nE:b-arli50)*

**Comment by PiotrDabkowski** [comment]
@bryk sure. Thank you for this commit, looks great! Just 2 small comments.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/common/components/graph/graphcard.html, line 17 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1171#-KQVgw26iSjEgBN-V47g:-KQVgw27yGOy3Cp_Ztdm:b-az19cc) ([raw file](https://github.com/kubernetes/dashboard/blob/d3a770c35fee5f75df0c2a90c58c9cc930d6b717/src/app/frontend/common/components/graph/graphcard.html#L17)):*
> ```HTML
> -->
> 
> <kd-content-card ng-if="$ctrl.shouldShowGraph()">
> ```

`kd-content-card` includes gray border, therefore the border I added manually to the `kd-graph` should be removed - line 146-152, file graph_component.js..

---

*[src/app/frontend/daemonsetlist/daemonsetlist_controller.js, line 44 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1171#-KQV9y4q7Lk49W_29y4D:-KQV9y4q7Lk49W_29y4E:b85q684) ([raw file](https://github.com/kubernetes/dashboard/blob/d3a770c35fee5f75df0c2a90c58c9cc930d6b717/src/app/frontend/daemonsetlist/daemonsetlist_controller.js#L44)):*
> ```JavaScript
> const i18n = {
>   /** @export {string} @desc Title for graph card displaying cumulative metrics of daemon sets. */
>   MSG_DAEMON_SET_LIST_GRAPH_CARD_TITLE: goog.getMsg('Cumulative resource usage'),
> ```

I think @bryk is right and the name `Resource usage history` is a better fit. However, it shows aggregated historical CPU/Memory usage ALL all resources on the list so what about a compromise - `Cumulative resource usage history`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1171#-:-KQVDN3iXYTWIZrfe4NJ:bhd8r0q)*

**Comment by floreks** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/common/components/graph/graphcard.html, line 17 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1171#-KQVgw26iSjEgBN-V47g:-KQVkD5ws7d2mJ6Xdaij:b-uh5a24) ([raw file](https://github.com/kubernetes/dashboard/blob/d3a770c35fee5f75df0c2a90c58c9cc930d6b717/src/app/frontend/common/components/graph/graphcard.html#L17)):*
<details><summary><i>Previously, PiotrDabkowski (Piotr Dabkowski) wrote…</i></summary>
> `kd-content-card` includes gray border, therefore the border I added manually to the `kd-graph` should be removed - line 146-152, file graph_component.js..
</details>
I'll do that. Thanks.

---

*[src/app/frontend/daemonsetlist/daemonsetlist_controller.js, line 44 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1171#-KQV9y4q7Lk49W_29y4D:-KQVjyLqPvXjfV6MgfOd:b-dw66jb) ([raw file](https://github.com/kubernetes/dashboard/blob/d3a770c35fee5f75df0c2a90c58c9cc930d6b717/src/app/frontend/daemonsetlist/daemonsetlist_controller.js#L44)):*
<details><summary><i>Previously, PiotrDabkowski (Piotr Dabkowski) wrote…</i></summary>
> I think @bryk is right and the name `Resource usage history` is a better fit. However, it shows aggregated historical CPU/Memory usage ALL all resources on the list so what about a compromise - `Cumulative resource usage history`?
</details>
I agree. `Cumulative` indicates that it's sum of all resources on the list. I'd go with your proposal.

@bryk what do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1171)*

**Comment by bryk** [comment]
@floreks LGMT. Apply comments and let's merge

**Comment by floreks** [comment]
PTAL

**Comment by bryk** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1171#-:-KQZfIVllZ776N6PROyQ:bnfp4nl)*

**Comment by PiotrDabkowski** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1171#-:-KQZiahyVIxsa5mWAdnP:bnfp4nl)*

**Pull request merged**
