### PR TITLE
update gulp conf/serve to support api-log-level backend arg

### PR DESCRIPTION
**Pull request by jeefy**
Addresses #3193 

The one piece remaining in that issue is updating the wiki. As far as I know I don't have permissions to do it. :( Please correct me if I'm wrong! 

Thanks!

### CODE REVIEW

**Comment by floreks** [comment]
Please format files to make travis green.

**Comment by jeefy** [comment]
Derp! My bad. Fixed/squashed/pushed the fix. Test should come up green now. :) Thanks!

**Comment by maciaszczykm** [comment]
@floreks Have you opened Wikis for all people?

**Pull request merged**
