### PR TITLE
Prepare hyperkube for 1.3

### PR DESCRIPTION
**Pull request by cheld**
Update below
----------------------------
Not to be merged. FYI only. @maciaszczykm, @floreks, @bryk 

I tried make a couple of changes that will be required for Hyperkube 1.3.  Unfortunately, I was not able to fix travis.

I have currently no idea how I could debug travis easily. Not applying the changes has the following consequences after 1.3:
- The included dashboard of hyperkube will crash during start-up
- Sky-dns will crash during start up

Both are not too important for us, currently. Maybe we fix later

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/969)

### CODE REVIEW

**Comment by cheld** [comment]
I will close after you have taken notice and not continue

**Comment by bryk** [comment]
I like this. If travis is happy, we can merge this, IMO

**Comment by cheld** [comment]
Unfortunately, only my workstation is happy, but not travis.

**Comment by cheld** [comment]
I assume if I setup exactly the same debian version as travis, then I could reproduce....

**Comment by bryk** [comment]
Let's see what travis says...

**Comment by bryk** [comment]
Ok, I see. Travis fails. How about you disable all other gulp tasks and just do `gulp local-up-cluster`. Then dump docker logs to see what is happening with all the containers we run. Then maybe dump what the prober sees (the thing that logs "waiting for...").

What do you think?

**Comment by cheld** [comment]
Ok, I have an idea....

**Comment by cheld** [comment]
@bryk PTAL

**Comment by cheld** [comment]
Ok, hold on I have a better idea....

**Comment by cheld** [comment]
Ok sorry, no better idea...PTAL

**Comment by bryk** [comment]
:) Let me know when ready to review

**Comment by cheld** [comment]
PTAL

**Comment by bryk** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/969#-:-KLzNzUfow36YvIU8O5a:1417088721)*

**Pull request merged**
