### PR TITLE
Resource limits frontend implementation

### PR DESCRIPTION
**Pull request by batikanu**
Frontend implementation for resource limits part of namespace details. 
Includes also backend fixes

### CODE REVIEW

**Comment by floreks** [comment]
Add related section to admin page.

**Comment by batikanu** [comment]
Please see #1285 for admin section. PTAL

**Comment by bryk** [comment]
@batikanu Is this ready for review? Somehow it got stuck in our review queue and nobody looks at this. Can you rebase so that me or somebody else can review? :)

Sorry for such delay, btw...

**Comment by batikanu** [comment]
Yes  sure I will rebase it :)

**Comment by batikanu** [comment]
@bryk this should be ready for review if nothing fails in travis :)

**Comment by bryk** [comment]
:)

**Comment by batikanu** [comment]
Double header is solved and dashes are added :)

**Comment by bryk** [comment]
LGTM! I'm sad this took so long to review...

**Pull request merged**
