### PR TITLE
Backend for workloads and replica set list pages

### PR DESCRIPTION
**Pull request by bryk**
Initial, but working, implementation. Will evolve in future. You can
check this out on /api/v1/workloads

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/678)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm Can you review? I can rebase on your renaming PR.

**Comment by maciaszczykm** [comment]
You can rebase it now. I'm reviewing it.

**Comment by bryk** [comment]
Rebased. PTAL

**Comment by maciaszczykm** [comment]
Please register new test packages and update one comment.

Works fine.

:lgtm: after fixing mentioned issues.

---

Reviewed 1 of 10 files at r1, 12 of 14 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/backend/resource/replicationcontroller/replicationcontrollercommon.go, line 154 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/678#-KGHN4Jv7Ig4WdhRTnGB:-KGHN4Jv7Ig4WdhRTnGC:1701140393) ([raw file](https://github.com/kubernetes/dashboard/blob/6b75021dedd1d689c4ba35f1ad51c28207c48349/src/app/backend/resource/replicationcontroller/replicationcontrollercommon.go#L154)):*
This comment should start with uppercase.

---

*[src/test/backend/resource/replicaset/replicasetlist_test.go, line 15 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/678#-KGHQEGxlFalec8lnllW:-KGHQEGxlFalec8lnllX:332545902) ([raw file](https://github.com/kubernetes/dashboard/blob/6b75021dedd1d689c4ba35f1ad51c28207c48349/src/test/backend/resource/replicaset/replicasetlist_test.go#L15)):*
New test packages need to be registered in `/build/conf.js`till we found better way to execute tests. Please update `testCommandArgs` variable.

---

*[src/test/backend/resource/workload/workloads_test.go, line 15 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/678#-KGHPxY2AePHlUe7ndTC:-KGHPxY2AePHlUe7ndTD:332545902) ([raw file](https://github.com/kubernetes/dashboard/blob/6b75021dedd1d689c4ba35f1ad51c28207c48349/src/test/backend/resource/workload/workloads_test.go#L15)):*
New test packages need to be registered in `/build/conf.js`till we found better way to execute tests. Please update `testCommandArgs` variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/678#-:-KGHQM5jP-zzeNnWW4tG:-589264846)*

**Comment by bryk** [comment]
*[src/test/backend/resource/replicaset/replicasetlist_test.go, line 15 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/678#-KGHQEGxlFalec8lnllW:-KGHUJ7nzK1NT48WM6K1:-1250273359) ([raw file](https://github.com/kubernetes/dashboard/blob/6b75021dedd1d689c4ba35f1ad51c28207c48349/src/test/backend/resource/replicaset/replicasetlist_test.go#L15)):*
Hmmm.... I tested this and it worked:
```bash
[bryk@bryk dashboard (workloads-backend)]$ gulp backend-test
[13:21:45] Requiring external module babel-core/register
[13:21:47] Using gulpfile ~/src/github.com/dashboard/gulpfile.babel.js
[13:21:47] Starting 'package-backend-source'...
[13:21:47] Finished 'package-backend-source' after 73 ms
[13:21:47] Starting 'backend-test'...
?   	github.com/kubernetes/dashboard	[no test files]
?   	github.com/kubernetes/dashboard/client	[no test files]
ok  	github.com/kubernetes/dashboard/handler	0.123s
?   	github.com/kubernetes/dashboard/resource/common	[no test files]
ok  	github.com/kubernetes/dashboard/resource/container	0.118s
ok  	github.com/kubernetes/dashboard/resource/event	0.116s
?   	github.com/kubernetes/dashboard/resource/namespace	[no test files]
ok  	github.com/kubernetes/dashboard/resource/replicationcontroller	0.722s
?   	github.com/kubernetes/dashboard/resource/secret	[no test files]
ok  	github.com/kubernetes/dashboard/validation	0.150s
```

What can you say about this? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/678)*

**Comment by bryk** [comment]
*[src/test/backend/resource/replicaset/replicasetlist_test.go, line 15 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/678#-KGHQEGxlFalec8lnllW:-KGHUWIs1SQxFatHfA59:-336610196) ([raw file](https://github.com/kubernetes/dashboard/blob/6b75021dedd1d689c4ba35f1ad51c28207c48349/src/test/backend/resource/replicaset/replicasetlist_test.go#L15)):*
I see. There's no workloads there. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/678)*

**Comment by bryk** [comment]
Review status: 5 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/backend/resource/replicationcontroller/replicationcontrollercommon.go, line 154 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/678#-KGHN4Jv7Ig4WdhRTnGB:-KGHWWe12YeSDiq1zgk_:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/6b75021dedd1d689c4ba35f1ad51c28207c48349/src/app/backend/resource/replicationcontroller/replicationcontrollercommon.go#L154)):*
Done.

---

*[src/test/backend/resource/replicaset/replicasetlist_test.go, line 15 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/678#-KGHQEGxlFalec8lnllW:-KGHWKNDvsLyJpdEhykC:-1772511321) ([raw file](https://github.com/kubernetes/dashboard/blob/6b75021dedd1d689c4ba35f1ad51c28207c48349/src/test/backend/resource/replicaset/replicasetlist_test.go#L15)):*
I have found a catch-all solution to this problem. PTAL

```js
    /**
     * Names of all backend packages prefixed with 'test' command.
     */
    testCommandArgs: [
      'test',
      'github.com/kubernetes/dashboard/...',
    ],
```

---

*[src/test/backend/resource/workload/workloads_test.go, line 15 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/678#-KGHPxY2AePHlUe7ndTC:-KGHWZPDzOldo3kyvBzf:-1296468877) ([raw file](https://github.com/kubernetes/dashboard/blob/6b75021dedd1d689c4ba35f1ad51c28207c48349/src/test/backend/resource/workload/workloads_test.go#L15)):*
PTAL my solution. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/678)*

**Comment by maciaszczykm** [comment]
:lgtm: 

---

Reviewed 2 of 14 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/backend/resource/replicaset/replicasetlist_test.go, line 15 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/678#-KGHQEGxlFalec8lnllW:-KGHXUOF4bIu2tlEqzMB:-1968891540) ([raw file](https://github.com/kubernetes/dashboard/blob/6b75021dedd1d689c4ba35f1ad51c28207c48349/src/test/backend/resource/replicaset/replicasetlist_test.go#L15)):*
Great! Thank you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/678#-:-KGHXbFsf6kq9QK-TrFC:980077423)*

**Pull request merged**
