### PR TITLE
Load apiserver config the same way kubectl does it

### PR DESCRIPTION
**Pull request by bryk**
Now it parses kubeconfig files when present

Try running `./dist/amd64/dashboard`. It should get info from your
kubectl file and use it.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/710)

### CODE REVIEW

**Comment by bryk** [comment]
@cheld Can you review?

**Comment by cheld** [comment]
Ah sure. But I am not in office tomorrow.

**Comment by cheld** [comment]
@bryk what is the use case for this change? 

I assume it is development and you work in two environments local and GCE.

You could have also run "kubectl --proxy", but this is even more convenient.

Should we drop the apiServerHost variable and document the new behavior? So, by default we use kubeconfig and if it is not correct you can override with variable.

**Comment by bryk** [comment]
> @bryk what is the use case for this change?

You can mount kubeconfig to a dashboard pod to connect it to any cluster. Currently it is not possible.

**Comment by bryk** [comment]
> Should we drop the apiServerHost variable and document the new behavior? So, by default we use kubeconfig and if it is not correct you can override with variable.

We could do this, but I have nothing against keeping the apiserver-host param. We need to document new behavior, though.

**Comment by cheld** [comment]
So, you want to run Dashboard as a pod inside a cluster, but connect to a API server of a different cluster?

**Comment by bryk** [comment]
> So, you want to run Dashboard as a pod inside a cluster, but connect to an API server of a different cluster?

Not necessarily. Some people have different auth scheme than serviceaccounts. So allowing them to get config from kubeconfig is a door for all cluster setups that we currently don't support.

**Comment by cheld** [comment]
Ok, now I understand :)

LGTM

**Pull request merged**
