### PR TITLE
Japanese localization

### PR DESCRIPTION
**Pull request by Yamagami-Takuma**
@f-higashi Can you review?

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1211)

### CODE REVIEW

**Comment by f-higashi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[i18n/messages-ja.xtb, line 771 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1211#-KROpuLNxVAyKZRORIU_:-KROpuLNxVAyKZRORIUa:b-js5bz3) ([raw file](https://github.com/kubernetes/dashboard/blob/eb9b3317a8559ee6f00d089175744437f529c695/i18n/messages-ja.xtb#L771)):*
> ```
> 	<translation id="3098067826555563293" key="MSG_BREADCRUMBS_DEPLOY_FILE_LABEL" source="/Users/bryk/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Breadcrum label for the YAML upload form">アップロード</translation>
> 	<translation id="1050029015813261838" key="MSG_BREADCRUMBS_LOGS_LABEL" source="/Users/bryk/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Breadcrum label for the logs view.">ログ</translation>
> 	<translation id="6172878964647554384" key="MSG_GRAPH_CPU_USAGE_LEGEND_LABEL" source="/usr/local/google/home/pdabkowski/WebstormProjects/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Name of the CPU usage metric as displayed in the legend.">CPU使用率</translation>
> ```

`CPU使用量` is better.

---

*[i18n/messages-ja.xtb, line 791 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1211#-KROk5DA-517DWAouLAf:-KROk5DA-517DWAouLAg:bv7m9l7) ([raw file](https://github.com/kubernetes/dashboard/blob/eb9b3317a8559ee6f00d089175744437f529c695/i18n/messages-ja.xtb#L791)):*
> ```
> 	<translation id="6498658628164692931" key="MSG_PERSISTENT_VOLUME_CLAIM_INFO_CAPACITY_ENTRY" source="/home/denis/Projects/dashboard/.tmp/serve/app-dev.js" desc="Persistent volume claim info details section capacity entry.">容量</translation>
> 	<translation id="3083343767517422348" key="MSG_PERSISTENT_VOLUME_CLAIM_INFO_ACCESS_MODES_ENTRY" source="/home/denis/Projects/dashboard/.tmp/serve/app-dev.js" desc="Persistent volume claim info details section access modes entry.">アクセスモード</translation>
> 	<translation id="6751018699028607617" key="MSG_BREADCRUMBS_PERSISTENT_VOLUME_CLAIM_LABEL" source="/home/denis/Projects/dashboard/.tmp/serve/app-dev.js" desc="Label 'Persistent Volume Claims' that appears as a breadcrumbs on the action bar.">パーシステントボリュームクレーム</translation>
> ```

It is too long in menu.


How about  '永続ボリューム要求' ?

---

*[i18n/messages-ja.xtb, line 814 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1211#-KROr1CqFoUvrX8A2wQt:-KROr1CrUM_9fQu9hxLD:bshjpqq) ([raw file](https://github.com/kubernetes/dashboard/blob/eb9b3317a8559ee6f00d089175744437f529c695/i18n/messages-ja.xtb#L814)):*
> ```
> 	<translation id="8461739989984165230" key="MSG_PERSISTENT_VOLUME_INFO_LABELS_ENTRY" source="/home/urcan/wlm/dashboard/.tmp/serve/app-dev.js" desc="Persistent volume info details section labels entry.">ラベル</translation>
> 	<translation id="8470321484602284382" key="MSG_PERSISTENT_VOLUME_INFO_STATUS_ENTRY" source="/home/urcan/wlm/dashboard/.tmp/serve/app-dev.js" desc="Persistent volume info details section status entry.">状態</translation>
> 	<translation id="5432163362862565868" key="MSG_PERSISTENT_VOLUME_INFO_CLAIM_ENTRY" source="/home/urcan/wlm/dashboard/.tmp/serve/app-dev.js" desc="Persistent volume info details section claim entry.">クレーム</translation>
> ```

How about `要求`?

---

*[i18n/messages-ja.xtb, line 815 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1211#-KROrBBe8W_KhCbgFv90:-KROrBBe8W_KhCbgFv91:bwhzcwo) ([raw file](https://github.com/kubernetes/dashboard/blob/eb9b3317a8559ee6f00d089175744437f529c695/i18n/messages-ja.xtb#L815)):*
> ```
> 	<translation id="8470321484602284382" key="MSG_PERSISTENT_VOLUME_INFO_STATUS_ENTRY" source="/home/urcan/wlm/dashboard/.tmp/serve/app-dev.js" desc="Persistent volume info details section status entry.">状態</translation>
> 	<translation id="5432163362862565868" key="MSG_PERSISTENT_VOLUME_INFO_CLAIM_ENTRY" source="/home/urcan/wlm/dashboard/.tmp/serve/app-dev.js" desc="Persistent volume info details section claim entry.">クレーム</translation>
> 	<translation id="1762240497636256999" key="MSG_PERSISTENT_VOLUME_INFO_RECLAIM_POLICY_ENTRY" source="/home/urcan/wlm/dashboard/.tmp/serve/app-dev.js" desc="Persistent volume info details section reclaim policy entry.">リクレームポリシー</translation>
> ```

How about `再要求ポリシー`

---

*[i18n/messages-ja.xtb, line 853 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1211#-KRNYNqoU2QnI-vt4kwE:-KRNYNqoU2QnI-vt4kwF:b-8rgkt7) ([raw file](https://github.com/kubernetes/dashboard/blob/eb9b3317a8559ee6f00d089175744437f529c695/i18n/messages-ja.xtb#L853)):*
> ```
> 	<translation id="8063860999135146846" key="MSG_PVS_ISCSI_FS_TYPE_ENTRY" source="/home/urcan/wlm/dashboard/.tmp/serve/app-dev.js" desc="Persistent volume source info ISCSI section FS type entry.">FS種別</translation>
> 	<translation id="3550212833215007507" key="MSG_PVS_ISCSI_READ_ONLY_ENTRY" source="/home/urcan/wlm/dashboard/.tmp/serve/app-dev.js" desc="Persistent volume source info ISCSI section read only entry.">読み取り専用</translation>
> 	<translation id="3581027216053890095" key="MSG_PVS_CINDER_TITLE" source="/home/urcan/wlm/dashboard/.tmp/serve/app-dev.js" desc="Persistent volume source info cinder title.">シンダー</translation>
> ```

In horizon, Cinder is not translated. 
https://github.com/openstack/horizon/blob/7ec991e659cc64de7f7c1fbc22a173ba53cb124c/openstack_dashboard/locale/ja/LC_MESSAGES/django.po#L1275

'Cinder' is OK. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1211)*

**Comment by Yamagami-Takuma** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[i18n/messages-ja.xtb, line 791 at r1](https://reviewable.io:443/reviews/kubernetes/dashboard/1211#-KROk5DA-517DWAouLAf:-KRQwXl7M_NPUMr-E05F:b-msusp7) ([raw file](https://github.com/kubernetes/dashboard/blob/eb9b3317a8559ee6f00d089175744437f529c695/i18n/messages-ja.xtb#L791)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> It is too long in menu.
> 
> 
> How about  '永続ボリューム要求' ?
> 
</details>
OK.
I also modify the same word of other places.

---

*[i18n/messages-ja.xtb, line 814 at r1](https://reviewable.io:443/reviews/kubernetes/dashboard/1211#-KROr1CqFoUvrX8A2wQt:-KRQxT2fxPft018ogP_O:bvtzs66) ([raw file](https://github.com/kubernetes/dashboard/blob/eb9b3317a8559ee6f00d089175744437f529c695/i18n/messages-ja.xtb#L814)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> How about `要求`?
</details>
OK.
Also modify the same word of other places.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1211)*

**Comment by f-higashi** [comment]
:lgtm:

@maciaszczykm 
you can merge this :)

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1211#-:-KRQyPiqWdUhd5WCgDun:b-pc2ffb)*

**Comment by floreks** [comment]
Please rebase and I'll merge this :)

**Comment by Yamagami-Takuma** [comment]
Rebased! :)

**Comment by cheld** [comment]
@Yamagami-Takuma Awesome. Thanks

**Comment by digitalfishpond** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1211)*

**Comment by digitalfishpond** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1211#-:-KRSL0T5fhP0hbSzZ063:bg7igkv)*

**Comment by digitalfishpond** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1211)*

**Pull request merged**
