### PR TITLE
fix golint failures

### PR DESCRIPTION
**Pull request by FayerZhang**

### CODE REVIEW

**Comment by zehuaiWANG** [comment]
I don't think it's necessary to change “self” to “cell”, it's easy to know the know the meaning of "self" (it's also very common in other programming language, such like python),  conversely，difficult kind of object use the same wrold "cell" will be confused.

**Comment by floreks** [comment]
I know that golint does not like `self`, but we are ok with using that. Warnings are fine in this case.

**Comment by zehuaiWANG** [comment]
I think it should have a more specific specific name instead of just using "cell"， “cell" is also a generic name in this solution although it can pass golint，I think it also not well.

**Comment by FayerZhang** [comment]
> I agree with @floreks. It seems that golint does not like "self", but it just a warning, like a suggestion.

It's no need to fix the golint warnings.

**Pull request closed without merging**
