### PR TITLE
init Chinese translation

### PR DESCRIPTION
**Pull request by tangfeixiong**
This is a Chinese version,the work is in progress.
The preview Chinese dashboard

### CODE REVIEW

**Comment by tangfeixiong** [comment]
I signed it!

**Comment by bryk** [comment]
Thanks for contribution. CLA bot still has some complains. Can you try to fix it?

**Comment by bryk** [comment]
@Yamagami-Takuma Are you able to review this? :)

**Comment by xialonglee** [comment]
is that “命名空间" is better then "名字空间" ?
and i think "复本集" is a better name then "复制集" because “复本” often use for translation to the word "replication", "copy“ often translation to "复制"
 "持久性存储卷" is too long for "persistent volume" i think, you can use just "持久卷" as i suggested.

**Comment by tangfeixiong** [comment]
@xialonglee, thanks a lot, I will correct it in my next version

**Comment by Yamagami-Takuma** [comment]
@bryk  
Ah sorry, I don't know Chinese language...

**Comment by bryk** [comment]
Let's go ahead and merge this :)

@tangfeixiong Can you fix the problem with "cla/linuxfoundation — tangfeixiong needs CLA"?

**Comment by maciaszczykm** [comment]
>Let's go ahead and merge this :)

>@tangfeixiong Can you fix the problem with "cla/linuxfoundation — tangfeixiong needs CLA"?

@tangfeixiong Could you sign the CLA? Click on Details link in below section to do so.

**Comment by maciaszczykm** [comment]
@tangfeixiong To fix CLA issue you need to click on `Details` link there:

image

Then click on `Sign up to contribute to this project as an individual`:

image

And follow intructions, most probably you'll have to register.

**Comment by kfzly** [comment]
@tangfeixiong 能请教一下吗

**Comment by tangfeixiong** [comment]
feel free to

**Comment by kfzly** [comment]
@tangfeixiong 我按照requirements-installation.md里的教程来但是一直失败，我一学生英文也不大好。看到你编译成功了。如果可以，希望您能帮助我一下

**Comment by kfzly** [comment]
@tangfeixiong 能帮帮忙吗？方便留个联系方式吗

**Comment by tangfeixiong** [comment]
抱歉工作很忙，只看邮件，不用qq，不用weixin。
requirements-installation.md里涉及的技术信息量很大，我也无法解释：
1: 我从事Kubernetes2年多了，有熟练的部署经验，并不采用该md里的cluster provisioning路线。
2: 我只参考md里的nodejs部分。
3:
去年一直在使用golang对kubernetes编程，熟悉dashboard的golang部分代码，因此dashboard的kubernetes配置是按自己的方式，无法与你分享。

**Comment by maciaszczykm** [comment]
@tangfeixiong Are you willing to sign the CLA so we can merge it? Other people knowing Chinese might be encouraged to contribute if you will do it.

**Comment by zhouhaibing089** [comment]
To be honest, there are terms which is hard to be translated.

@tangfeixiong if you have problem with the CLA bits, I can pick it up.

**Comment by tangfeixiong** [comment]
yes, you can.

I have Google CLA used in Helm project, but it seems not working well as be
a current linux foundation CLA.

thanks

**Comment by maciaszczykm** [comment]
It finally works, after CI will pass I will merge it.

**Pull request merged**
