### PR TITLE
migrate apps/rbac/storage versions

### PR DESCRIPTION
**Pull request by zouyee**
fixes https://github.com/kubernetes/dashboard/issues/2454

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Tests failed like in your other pull requests. We can review after you will fix them.

**Comment by zouyee** [comment]
thanks, i will fix it later!

**Comment by floreks** [comment]
Some test are failing probably because of too old k8s cluster version. Please rebase to get #2463 changes in this PR. It might fix this issue.

**Comment by zouyee** [comment]
according the pic，kubernetes 1.7.5 would been used with minikube v0.2.3, which could not supported front  integration when request deploy list .

**Comment by maciaszczykm** [comment]
It is a good time to rebase because our CI is using Kubernetes 1.8 right now.

**Comment by zouyee** [comment]
I will rebase it later, thanks!

**Comment by maciaszczykm** [comment]
@zouyee We will do it on our own if you will not rebase. Please make sure, that CI is passing.

**Comment by maciaszczykm** [comment]
Closing as stale.

**Pull request closed without merging**
