### PR TITLE
Localization of Error, Events page, Logs Page

### PR DESCRIPTION
**Pull request by taimir**
Localization of these reusable parts of dashboard (mentioned in the commit message).

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/859)

### CODE REVIEW

**Comment by taimir** [comment]
@digitalfishpond do you feel like reviewing this one?

**Comment by digitalfishpond** [comment]
Small issue, but otherwise :lgtm: 

<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> @digitalfishpond do you feel like reviewing this one?
</details>


---

Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/frontend/events/eventcardlist_component.js, line 126 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/859#-KJo5dur_JC5F5npqASj:-KJo5dur_JC5F5npqASk:-1527336971) ([raw file](https://github.com/kubernetes/dashboard/blob/4639cba4bf85236cfc6df695c22f304436352410/src/app/frontend/events/eventcardlist_component.js#L126)):*
> ```JavaScript
>   formatDate(date) {
>     let filter = this.interpolate_(`{{date | date:'d/M/yy HH:mm':'UTC'}}`);
>     return filter({'date': date});
> ```

So you probably saw already that Travis is unhappy with this return type...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/859#-:-KJo88zcf7qb7GNNraH8:-541987270)*

**Comment by taimir** [comment]
OK, I'll probably have some time to look at this tomorrow.

<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> Small issue, but otherwise :lgtm: 
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/859#-:-KJpHlJg0hr9eaoySPt4:-2131476887)*

**Comment by bryk** [comment]
Can you rebase and fix travis?

**Comment by taimir** [comment]
Mhm, but I'm at uni during the whole day. I might be able to take a look at it some time this evening.

**Comment by bryk** [comment]
Ok, perfect :)

**Comment by taimir** [comment]
PTAL

**Comment by digitalfishpond** [comment]
Reviewed 2 of 6 files at r3.
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/events/eventcardlist_component.js, line 122 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/859#-KK82W6QYpaX-2pazLU5:-KK82W6QYpaX-2pazLU6:1570831878) ([raw file](https://github.com/kubernetes/dashboard/blob/31cc19cc17de0eb77b6dfca141c26febc9f74fa4/src/app/frontend/events/eventcardlist_component.js#L122)):*
> ```JavaScript
>    * @private
>    * @param  {string} date - to be formatted
>    * @return {*} the formatted date
> ```

Ok, the result of an interpolation can be a string, or an array, or a map of class names to boolean values. This (*) seems like a legitimate way around this to me... Any thoughts @florex @maciaszczykm ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/859)*

**Comment by taimir** [comment]
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/events/eventcardlist_component.js, line 122 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/859#-KK82W6QYpaX-2pazLU5:-KK85bSrVKL0nojI0ZMg:496603449) ([raw file](https://github.com/kubernetes/dashboard/blob/31cc19cc17de0eb77b6dfca141c26febc9f74fa4/src/app/frontend/events/eventcardlist_component.js#L122)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> Ok, the result of an interpolation can be a string, or an array, or a map of class names to boolean values. This (*) seems like a legitimate way around this to me... Any thoughts @florex @maciaszczykm ?
</details>
Right, so here (because of the use case) it is clear that the interpolation should return a string if I am not mistaken. I also thought of doing something like 
```{js}
return "${filter({'date': date})}";
```
to force it to a string just to make the return type clear. But it seemed too hacky to me ...

Glad to hear what you think about it guys.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/859)*

**Comment by digitalfishpond** [comment]
@florex @maciaszczykm could you have a quick look at the comment on eventcardlist-component.js?

<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> PTAL
</details>


---

Reviewed 2 of 6 files at r3, 2 of 2 files at r4, 1 of 1 files at r5.
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/859#-:-KK8ZyW5UFnw6rxellMj:344328338)*

**Comment by floreks** [comment]
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/events/eventcardlist_component.js, line 122 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/859#-KK82W6QYpaX-2pazLU5:-KKE1cYSS7rO_mVUvnVN:-2092179461) ([raw file](https://github.com/kubernetes/dashboard/blob/31cc19cc17de0eb77b6dfca141c26febc9f74fa4/src/app/frontend/events/eventcardlist_component.js#L122)):*
<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> Right, so here (because of the use case) it is clear that the interpolation should return a string if I am not mistaken. I also thought of doing something like 
> ```{js}
> return "${filter({'date': date})}";
> ```
> to force it to a string just to make the return type clear. But it seemed too hacky to me ...
> 
> Glad to hear what you think about it guys.
</details>
I'd go for simple solution and use filter directly instead of filtering through interpolate.

Inject `dateFilter` instead of `$interpolate`. Type can be taken from documentation, something like `{function((!Object|number|string), string=, string=): string}` should work.

Then change return type to `string` and function body to `return this.dateFilter_(date, 'd/M/yy HH:mm', 'UTC');`

Should work :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/859)*

**Comment by floreks** [comment]
Review status: 6 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/events/eventcardlist_component.js, line 99 \[r6\]](https://reviewable.io:443/reviews/kubernetes/dashboard/859#-KKE3TvZDC7j2V-m532q:-KKE3Tv_QIDUibgS9C79:-1628562268) ([raw file](https://github.com/kubernetes/dashboard/blob/4c33dee0861f2a2d522a6ab0a398875a4403d082/src/app/frontend/events/eventcardlist_component.js#L99)):*
> ```JavaScript
>         event was first seen (events page). */
>     let MSG_EVENTS_FIRST_SEEN_DATE_LABEL =
>         goog.getMsg('First seen at {$date} UTC', {'date': this.formatDate(date)});
> ```

To be in sync with #896 remove proceeding string `First seen at` and `Last seen at` from message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/859)*

**Comment by taimir** [comment]
Review status: 6 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/events/eventcardlist_component.js, line 99 \[r6\]](https://reviewable.io:443/reviews/kubernetes/dashboard/859#-KKE3TvZDC7j2V-m532q:-KKHzALqWjgIXQj4hJkD:-117331394) ([raw file](https://github.com/kubernetes/dashboard/blob/4c33dee0861f2a2d522a6ab0a398875a4403d082/src/app/frontend/events/eventcardlist_component.js#L99)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> To be in sync with #896 remove proceeding string `First seen at` and `Last seen at` from message.
</details>
Oh, really? Wasn't aware of the simplification. Then we're not gonna need those strings to be localized, fixing it now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/859)*

**Comment by taimir** [comment]
PTAL

**Comment by taimir** [comment]
@floreks can you check this out again? It's been sitting here for a while, and I don't think there's much more to it.

---

Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/events/eventcardlist_component.js, line 126 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/859#-KJo5dur_JC5F5npqASj:-KKghhmsw3ReQIVQEAHU:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/4639cba4bf85236cfc6df695c22f304436352410/src/app/frontend/events/eventcardlist_component.js#L126)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> So you probably saw already that Travis is unhappy with this return type...
</details>
Done.

---

*[src/app/frontend/events/eventcardlist_component.js, line 122 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/859#-KK82W6QYpaX-2pazLU5:-KKghi9vTUVIbtRmSjib:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/31cc19cc17de0eb77b6dfca141c26febc9f74fa4/src/app/frontend/events/eventcardlist_component.js#L122)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> I'd go for simple solution and use filter directly instead of filtering through interpolate.
> 
> Inject `dateFilter` instead of `$interpolate`. Type can be taken from documentation, something like `{function((!Object|number|string), string=, string=): string}` should work.
> 
> Then change return type to `string` and function body to `return this.dateFilter_(date, 'd/M/yy HH:mm', 'UTC');`
> 
> Should work :)
</details>
Done.

---

*[src/app/frontend/events/eventcardlist_component.js, line 99 \[r6\]](https://reviewable.io:443/reviews/kubernetes/dashboard/859#-KKE3TvZDC7j2V-m532q:-KKghiaLNHTH5-t4bRIj:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/4c33dee0861f2a2d522a6ab0a398875a4403d082/src/app/frontend/events/eventcardlist_component.js#L99)):*
<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> Oh, really? Wasn't aware of the simplification. Then we're not gonna need those strings to be localized, fixing it now.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/859#-:-KKghjc7lXRoRlmX1RhT:-579654033)*

**Comment by floreks** [comment]
:lgtm:

---

Reviewed 2 of 10 files at r1, 2 of 6 files at r3, 2 of 5 files at r7, 2 of 2 files at r10.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/859#-:-KKgnwnklb3AGFHwLR5I:1417088721)*

**Pull request merged**
