### PR TITLE
Reintroduce metrics and sparklines to pods

### LINKED ISSUE #825: Reintroduce heapster metrics in pod lists

### PR DESCRIPTION
**Pull request by bryk**
Fixes #825

Also, moved logs link into an incon in actions column.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/871)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you review?

**Comment by floreks** [comment]
I'll once I deal with my cluster (not working). :)

**Comment by bryk** [comment]
Is this possible that we'll have this by 3PM? I could then do a release.

**Comment by floreks** [comment]
Sure. I've fixed it and will do review now.

**Comment by floreks** [comment]
We could improve scaling on memory sparkline. Whether it uses 650Mi or 25Mi, whole sparkline is filled. For now :lgtm:. Tested and works.


<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Sure. I've fixed it and will do review now.
</details>


---

Reviewed 7 of 10 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/871#-:-KJuBEjRpX7hjZ5f1kSs:397948657)*

**Comment by bryk** [comment]
Awesome, thanks!

**Pull request merged**
