### PR TITLE
Add node allocated resources

### LINKED ISSUE #911: Display all node details
Elements to display:

- [x] basic details
- [x] conditions
- [x] pods
- [x] events
- [x] allocated resources
- [ ] addresses
- [ ] container images

### LINKED ISSUE #931: Link from pod details to node
This should be a link. It would surface the nodes view more. 
selection_088

### PR DESCRIPTION
**Pull request by maciaszczykm**
Added allocated resources details to node details view:

image

Capacity is now displayed in allocated resources card, it should be easier to read :)

Fixes #931.
Fixes #911 as nodes and addresses won't be added at the moment.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/930)

### CODE REVIEW

**Comment by bryk** [comment]
A few nitty comments. Will test now. 

---

Reviewed 8 of 10 files at r1.
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/nodedetail/nodeallocatedresources_component.js, line 18 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/930#-KKmo-S7vDjWf1eUhN_p:-KKmo-S8wx8KDiWJvyIF:978487135) ([raw file](https://github.com/kubernetes/dashboard/blob/d5ff39ebc3c5656c613f860fba37c19f07349727/src/app/frontend/nodedetail/nodeallocatedresources_component.js#L18)):*
> ```JavaScript
>  * @final
>  */
> export default class NodeAllocatedResourcesController {
> ```

Dont export classes as `default` as you cannot use them in type annotations then :) 

---

*[src/app/frontend/nodedetail/nodeallocatedresources_component.js, line 44 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/930#-KKmo9IB0lLnZKJNbzZa:-KKmo9IB0lLnZKJNbzZb:700344307) ([raw file](https://github.com/kubernetes/dashboard/blob/d5ff39ebc3c5656c613f860fba37c19f07349727/src/app/frontend/nodedetail/nodeallocatedresources_component.js#L44)):*
> ```JavaScript
>   templateUrl: 'nodedetail/nodeallocatedresources.html',
>   bindings: {
>     /** {!backendApi.NodeConditionList} */
> ```

Wrong type? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/930#-:-KKmoE48klgYDlJtbYUy:-449926796)*

**Comment by bryk** [comment]
LGTM when you fix address the comments. Please merge by yourself :) 

---

Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/930#-:-KKmrjUehnwpKxFgKJ5u:-1663048185)*

**Comment by maciaszczykm** [comment]
Fixes #931.

**Comment by maciaszczykm** [comment]
Review status: 7 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/nodedetail/nodeallocatedresources_component.js, line 18 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/930#-KKmo-S7vDjWf1eUhN_p:-KKmtL_vbQuJHwB3BhpZ:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/d5ff39ebc3c5656c613f860fba37c19f07349727/src/app/frontend/nodedetail/nodeallocatedresources_component.js#L18)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Dont export classes as `default` as you cannot use them in type annotations then :) 
</details>
Done.

---

*[src/app/frontend/nodedetail/nodeallocatedresources_component.js, line 44 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/930#-KKmo9IB0lLnZKJNbzZa:-KKmtMOuP_NpnhmM9mXJ:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/d5ff39ebc3c5656c613f860fba37c19f07349727/src/app/frontend/nodedetail/nodeallocatedresources_component.js#L44)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Wrong type? 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/930)*

**Comment by bryk** [comment]
Reviewed 2 of 10 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/poddetail/podinfo_component.js, line 40 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/930#-KKmx4wZ0wI1WV_RrQAO:-KKmx4w_QJYpjwIs8Dea:203760068) ([raw file](https://github.com/kubernetes/dashboard/blob/1321779e3dab279f2183c9347958a99a46802f7e/src/app/frontend/poddetail/podinfo_component.js#L40)):*
> ```JavaScript
>    * @export
>    */
>   getNodeDetailsHref() { return `#/${stateName}/${this.pod.nodeName}`; }
> ```

Use $state.href method :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/930)*

**Comment by maciaszczykm** [comment]
Waiting for CI.

---

Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/poddetail/podinfo_component.js, line 40 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/930#-KKmx4wZ0wI1WV_RrQAO:-KKmyx0bT1aAZ0dYmKhU:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/1321779e3dab279f2183c9347958a99a46802f7e/src/app/frontend/poddetail/podinfo_component.js#L40)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Use $state.href method :) 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/930#-:-KKmyt0GfYDRUQH0lj9p:1382645273)*

**Pull request merged**
