### PR TITLE
Add common pods list component

### PR DESCRIPTION
**Pull request by floreks**
I'll be refactoring resources lists to common components so it will be easier to create views for new resources.

This is pretty small. I've extracted rc pods to common pods list component.

Backend will for sure need adjustment to this style. Externs also should be renamed. Now everything is tied to replication controller.

Should we have 1 module for all resource lists (resourcelist module) or separate module for every resource list which will be added to component module?

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/714)

### CODE REVIEW

**Comment by bryk** [comment]
How about moving this to a folder adjacent to replicationcontrollerlist/ workloads/ and /replicasetlist? This is where RC and RS cards and lists are currently located. Pod list looks no different.

Later we could mimic folder structure we have on the backend. I.e., divide by resource/view name.

What's your opinion?

**Comment by floreks** [comment]
This pods list is actually different than other lists. It is not a view itself and it needs data from the outside to display anything. It is just a component that can display given pods list.

It's intended to be used on details pages of resources that pods are related to. Of course it could be used on pods list view page also.

If you've got better name for this component then we'll adjust it :)

These same components could be created for replicationcontrollerlist and replicasetlist and used on the list page and also on some details pages. This way change of this single component will be reflected on all pages where for example pod list is displayed.

**Comment by bryk** [comment]
> Same components could be created for replicationcontrollerlist and replicasetlist and used on the list page and also on some details pages. This way change of this single component will be reflected on all pages where for example pod list is displayed.

This is actually what currently happens. I.e., workloads list uses tables from replica set list view. And I like this idea a lot. I'm discussing the placement of this only.

I have no strong preference on whether the resource list components should be in common/ or in foolist/ folders. All I want is consistency - so all or nothing :)

So, what's your opinion? in common/ or in foolist/ folders?

**Comment by floreks** [comment]
Ahh, yes. I didn't notice that before. It will look better in podslist folder. Should it also be named `podscardlist`?

**Comment by bryk** [comment]
Perfect, thanks!

> Should it also be named podscardlist?

Yes, I think so.

**Comment by floreks** [comment]
PTAL

**Comment by bryk** [comment]
Reviewed 3 of 17 files at r1, 6 of 11 files at r2.
Review status: 4 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/podslist/podslist_module.js, line 15 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/714#-KH4NSoIzvGvhyz4Av4a:-KH4NSoJi-YU5mZj5Jvj:-1427558783) ([raw file](https://github.com/kubernetes/dashboard/blob/3aed4002983be21f3bd19e5d61c747bc7875bfdf/src/app/frontend/podslist/podslist_module.js#L15)):*
All these files should be podlistfoo, not pod_S_listfoo. This is because we're talking about pod list not pods list here. Can you rename? 

---

*[src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetail.html, line 28 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/714#-KH4NgYqJuP0bYPSWX4h:-KH4NgYqJuP0bYPSWX4i:-659061850) ([raw file](https://github.com/kubernetes/dashboard/blob/3aed4002983be21f3bd19e5d61c747bc7875bfdf/src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetail.html#L28)):*
I don't understand what's happening here. Why do we need this callback? podcardlist_component could just have this method. Can you remove this callback from here or explain why it is needed? :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/714)*

**Comment by floreks** [comment]
Review status: 4 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/podslist/podslist_module.js, line 15 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/714#-KH4NSoIzvGvhyz4Av4a:-KH4QG0MzfoAWo8WPfuo:1136925115) ([raw file](https://github.com/kubernetes/dashboard/blob/3aed4002983be21f3bd19e5d61c747bc7875bfdf/src/app/frontend/podslist/podslist_module.js#L15)):*
Ahh... gramma. Thanks :)

---

*[src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetail.html, line 28 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/714#-KH4NgYqJuP0bYPSWX4h:-KH4Qb5iL3ZNItIn338U:824207094) ([raw file](https://github.com/kubernetes/dashboard/blob/3aed4002983be21f3bd19e5d61c747bc7875bfdf/src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetail.html#L28)):*
That's what I thought at first but let's look at this function

```javascript
return this.state_.href(
        logsStateName,
        new LogsStateParams(
            this.stateParams_.namespace, this.stateParams_.replicationController, pod.name));
```

As you can see, currently logs are tied to replication controller and created link is based on rc name. We shouldn't make pod card list so closely coupled with this implementation detail because other resources don't necessarily need to use this information or these stateParams.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/714)*

**Comment by bryk** [comment]
Review status: 4 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetail.html, line 28 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/714#-KH4NgYqJuP0bYPSWX4h:-KH4ZPm-96j7H2zZfKNw:1643595308) ([raw file](https://github.com/kubernetes/dashboard/blob/3aed4002983be21f3bd19e5d61c747bc7875bfdf/src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetail.html#L28)):*
I see. How about removing the link to logs for now and fix this problem "correctly" in a next PR? E.g., to untie logs view from replication controllers. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/714)*

**Comment by floreks** [comment]
Review status: 4 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetail.html, line 28 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/714#-KH4NgYqJuP0bYPSWX4h:-KH4_hcxLVlsJMrzdwHV:-1506615842) ([raw file](https://github.com/kubernetes/dashboard/blob/3aed4002983be21f3bd19e5d61c747bc7875bfdf/src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetail.html#L28)):*
I was following example from angular component documentation :) This argument passing is kind of complicated but makes sense. https://plnkr.co/edit/?p=preview

< untie logs view from replication controllers

I'm not sure if we can do that. We'll need to get label selector from resource to get related pods and to get resource we're gonna need at least resource name. 

Second option is to redesign logs in such way that it displays only logs for single pod not for pods related to resource. Then we could create this link directly in pod card list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/714)*

**Comment by bryk** [comment]
Please do the rename and log an issue about the logs view that is tied to RCs. 

---

Reviewed 1 of 17 files at r1, 1 of 11 files at r2.
Review status: 6 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetail.html, line 28 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/714#-KH4NgYqJuP0bYPSWX4h:-KH4pfDc_Az6QEfO18sI:755312229) ([raw file](https://github.com/kubernetes/dashboard/blob/3aed4002983be21f3bd19e5d61c747bc7875bfdf/src/app/frontend/replicationcontrollerdetail/replicationcontrollerdetail.html#L28)):*
> I'm not sure if we can do that. We'll need to get label selector from resource to get related pods and to get resource we're gonna need at least resource name.

Yeah, and I think that's a good progress. Will allow to display logs from services, rcs, deployments, etc. Of course, a nice start is to start displaying logs only from one pod. We have list of pods anyway. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/714#-:-KH4q-T6V5sDy-MHLyGw:-1218770740)*

**Comment by floreks** [comment]
PTAL

**Comment by bryk** [comment]
:lgtm: Please merge. 

---

Reviewed 4 of 21 files at r1, 4 of 15 files at r2, 11 of 11 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/714#-:-KH50qQPT_ZRAcS54laM:-979563773)*

**Pull request merged**
