### PR TITLE
Add pod details page

### PR DESCRIPTION
**Pull request by digitalfishpond**
Details page for pods and corresponding tests #650

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/740)

### CODE REVIEW

**Comment by floreks** [comment]
Looks nice. Just a few comments.

<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> #### Add pod details page
> 
> Details page for pods and corresponding tests #650
> 
> 
> </details>


---

Reviewed 26 of 30 files at r1.
Review status: 22 of 26 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/backend/resource/deployment/deploymentlist.go, line 22 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHtB1vlmB4PJn82k9Gx:-KHtB1vlmB4PJn82k9Gy:1490864471) ([raw file](https://github.com/kubernetes/dashboard/blob/1c52d80ed36904fc2a52c3bfb9375c18ac7eeb28/src/app/backend/resource/deployment/deploymentlist.go#L22)):*
> ```Go
> 	"github.com/kubernetes/dashboard/resource/common"
> ```

Try to follow the rule and use only 1 empty line between blocks

---

*[src/app/backend/resource/pod/poddetail.go, line 27 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHtByunuyiW-4Eh2UIt:-KHtByunuyiW-4Eh2UIu:685142957) ([raw file](https://github.com/kubernetes/dashboard/blob/1c52d80ed36904fc2a52c3bfb9375c18ac7eeb28/src/app/backend/resource/pod/poddetail.go#L27)):*
> ```Go
> )
> 
> // Pod is a presentation layer view of Kubernetes Pod resource. This means
> ```

swap/Pod/Pod detail

---

*[src/app/backend/resource/pod/poddetail.go, line 53 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHtCAQwYDCMSGARQmVB:-KHtCAQwYDCMSGARQmVC:1406558623) ([raw file](https://github.com/kubernetes/dashboard/blob/1c52d80ed36904fc2a52c3bfb9375c18ac7eeb28/src/app/backend/resource/pod/poddetail.go#L53)):*
> ```Go
> }
> 
> func GetPodDetail(client k8sClient.Interface, heapsterClient client.HeapsterClient,
> ```

Document it please

---

*[src/app/frontend/poddetail/poddetail.html, line 22 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHtCMQnXrto29TUnHe1:-KHtCMQnXrto29TUnHe2:677854590) ([raw file](https://github.com/kubernetes/dashboard/blob/1c52d80ed36904fc2a52c3bfb9375c18ac7eeb28/src/app/frontend/poddetail/poddetail.html#L22)):*
> ```HTML
>       <md-tab label="Overview">
>         <kd-pod-info pod="::ctrl.podDetail"></kd-pod-info>
> ```

Remove empty line

---

*[src/app/frontend/poddetail/podinfo.html, line 38 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHtCaYx-cfcNGG9qNae:-KHtCaYx-cfcNGG9qNaf:-896578916) ([raw file](https://github.com/kubernetes/dashboard/blob/1c52d80ed36904fc2a52c3bfb9375c18ac7eeb28/src/app/frontend/poddetail/podinfo.html#L38)):*
> ```HTML
>     </kd-info-card-entry>
>     <kd-info-card-entry title="Images">
>       <div ng-repeat="image in $ctrl.pod.containerImages">
> ```

swap/$ctrl.pod.containerImages/::$ctrl.pod.containerImages

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-:-KHtDVVmROv8PgmZDckU:-895545089)*

**Comment by digitalfishpond** [comment]
Review status: 22 of 25 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/backend/resource/pod/poddetail.go, line 27 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHtByunuyiW-4Eh2UIt:-KHtF9E_pMbygxWkd675:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/1c52d80ed36904fc2a52c3bfb9375c18ac7eeb28/src/app/backend/resource/pod/poddetail.go#L27)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> swap/Pod/Pod detail</details>
Done.

---

*[src/app/backend/resource/pod/poddetail.go, line 53 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHtCAQwYDCMSGARQmVB:-KHtGaNjHhnlo564VeTu:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/1c52d80ed36904fc2a52c3bfb9375c18ac7eeb28/src/app/backend/resource/pod/poddetail.go#L53)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Document it please</details>
Done.

---

*[src/app/frontend/poddetail/poddetail.html, line 22 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHtCMQnXrto29TUnHe1:-KHtGj2AZGxXPUxuo32Q:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/1c52d80ed36904fc2a52c3bfb9375c18ac7eeb28/src/app/frontend/poddetail/poddetail.html#L22)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Remove empty line</details>
Done.

---

*[src/app/frontend/poddetail/podinfo.html, line 38 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHtCaYx-cfcNGG9qNae:-KHtH0-3IvFHrNGrVjpO:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/1c52d80ed36904fc2a52c3bfb9375c18ac7eeb28/src/app/frontend/poddetail/podinfo.html#L38)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> swap/$ctrl.pod.containerImages/::$ctrl.pod.containerImages</details>
Done.

---

*[src/app/backend/resource/deployment/deploymentlist.go, line 22 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHtB1vlmB4PJn82k9Gx:-KHtEPujTG-QormMm0Aq:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/1c52d80ed36904fc2a52c3bfb9375c18ac7eeb28/src/app/backend/resource/deployment/deploymentlist.go#L22)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Try to follow the rule and use only 1 empty line between blocks</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/740)*

**Comment by digitalfishpond** [comment]
PTAL

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Looks nice. Just a few comments.</details>


---

Review status: 22 of 25 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-:-KHtHWgHIzOh7xRBk9cS:676965300)*

**Comment by floreks** [comment]
Great! :lgtm:

@bryk could you take a look also?

<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> PTAL</details>


---

Reviewed 3 of 4 files at r2.
Review status: 24 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-:-KHtIu6rih146H9QoagB:-1342134210)*

**Comment by bryk** [comment]
This does not work on gulp serve:prod. Looks good otherwise. Please fix and let's merge :)
If you need help debugging this, let me know. 

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Great! :lgtm:
> 
> @bryk could you take a look also?</details>


---

Reviewed 26 of 30 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/backend/resource/pod/podcommon_test.go, line 24 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHtiMjEruIYxcFmDuDm:-KHtiMjEruIYxcFmDuDn:1740280682) ([raw file](https://github.com/kubernetes/dashboard/blob/d8d1ee45dd475dcdb2a944e25a9e60ed97f306f0/src/test/backend/resource/pod/podcommon_test.go#L24)):*
> ```Go
> 
> 	"github.com/kubernetes/dashboard/resource/common"
> 	//"app/backend/resource/pod"
> ```

Remove? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-:-KHtjkPFHP4FOo5lQFNZ:719360155)*

**Comment by digitalfishpond** [comment]
@bryk I am not getting any problems with gulp serve:prod... do you have any more clues?

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> This does not work on gulp serve:prod. Looks good otherwise. Please fix and let's merge :)
> If you need help debugging this, let me know. </details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-:-KHtn1qcoDTLn48akm1n:-655867235)*

**Comment by bryk** [comment]
I just dont see pod details page on serve:prod
I'll check again tomorrow morning, if needed.

<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> @bryk I am not getting any problems with gulp serve:prod... do you have any more clues?</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-:-KHtqBx-pcfullcncOsJ:-1129650542)*

**Comment by digitalfishpond** [comment]
Ah!, no, you are absolutely right. My bad. I will fix tomorrow morning.

**Comment by bryk** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHxlZ8Fy2nDApsPr12s:-KHxlZ8G2XM5jIn44Tua:-134056958) (no related file):*
Btw, this fails if pod has no labels. Can you ng-if this?
```html
    <kd-info-card-entry title="Labels">
      <kd-labels labels="::$ctrl.pod.objectMeta.labels"></kd-labels>
    </kd-info-card-entry>
```

---

*[src/app/frontend/poddetail/poddetail_controller.js, line 22 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHxqlaIv17VeUeqzTD4:-KHxqlaJGo22PKCFmq_B:1786354062) ([raw file](https://github.com/kubernetes/dashboard/blob/d8d1ee45dd475dcdb2a944e25a9e60ed97f306f0/src/app/frontend/poddetail/poddetail_controller.js#L22)):*
> ```JavaScript
>    * @param {!backendApi.PodDetail} podDetail
>    */
>   constructor(podDetail) {
> ```

Needs `@ngInject`

---

*[src/app/frontend/poddetail/poddetail_stateconfig.js, line 55 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHxsZNZGfbNfYYGirXV:-KHxsZNZGfbNfYYGirXW:425898087) ([raw file](https://github.com/kubernetes/dashboard/blob/d8d1ee45dd475dcdb2a944e25a9e60ed97f306f0/src/app/frontend/poddetail/poddetail_stateconfig.js#L55)):*
> ```JavaScript
>  * @param {!angular.$resource} $resource
>  * @return {!angular.Resource<!backendApi.PodDetail>}
>  */
> ```

Missing ngInject here

---

*[src/app/frontend/poddetail/poddetail_stateconfig.js, line 63 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHxsaSTQWlI6yO-Oiwe:-KHxsaSTQWlI6yO-Oiwf:425898087) ([raw file](https://github.com/kubernetes/dashboard/blob/d8d1ee45dd475dcdb2a944e25a9e60ed97f306f0/src/app/frontend/poddetail/poddetail_stateconfig.js#L63)):*
> ```JavaScript
>  * @param {!angular.Resource<!backendApi.PodDetail>} podDetailResource
>  * @return {!angular.$q.Promise}
>  */
> ```

Missing ngInject here

---

*[src/app/frontend/podlist/podcardlist_component.js, line 25 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHxqsIJcT9_n_6ZLlVK:-KHxqsIJcT9_n_6ZLlVL:384288731) ([raw file](https://github.com/kubernetes/dashboard/blob/d8d1ee45dd475dcdb2a944e25a9e60ed97f306f0/src/app/frontend/podlist/podcardlist_component.js#L25)):*
> ```JavaScript
>    * @ngInject
>    */
>   constructor($state) {
> ```

Needs `@param`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/740)*

**Comment by bryk** [comment]
Problem solved. See my comments.

Story how I found it. I saw that on scripts:prod there are no errors, and that when I want to see pod details page there is unknown error. This means that UI router ate some exception. This means that this is a problem with it. 

Then I added `console.log(event, toState, toParams, fromState, fromParams, error);` to error_module.js to verify this. I saw 'unknown provider' error which confirmed my suspicions. With this I realized that `export function getPodDetailResource($resource, $stateParams) {` have no ngInject :)

Have a nice day! 

<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> Ah!, no, you are absolutely right. My bad. I will fix tomorrow morning.</details>


---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-:-KHxsc_-UOLgj-DVV3yV:-15217503)*

**Comment by digitalfishpond** [comment]
Thank you so much for this :) PTAL

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Problem solved. See my comments.
> 
> Story how I found it. I saw that on scripts:prod there are no errors, and that when I want to see pod details page there is unknown error. This means that UI router ate some exception. This means that this is a problem with it. 
> 
> Then I added `console.log(event, toState, toParams, fromState, fromParams, error);` to error_module.js to verify this. I saw 'unknown provider' error which confirmed my suspicions. With this I realized that `export function getPodDetailResource($resource, $stateParams) {` have no ngInject :)
> 
> Have a nice day! </details>


---

Review status: 17 of 25 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHxlZ8Fy2nDApsPr12s:-KHy67OBP56Azue_F5a3:-499146009) (no related file):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Btw, this fails if pod has no labels. Can you ng-if this?
> ```html
>     <kd-info-card-entry title="Labels">
>       <kd-labels labels="::$ctrl.pod.objectMeta.labels"></kd-labels>
>     </kd-info-card-entry>
> ```
> </details>
Done.

---

*[src/app/frontend/poddetail/poddetail_controller.js, line 22 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHxqlaIv17VeUeqzTD4:-KHxy41QxWmQbNxsIk_6:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/d8d1ee45dd475dcdb2a944e25a9e60ed97f306f0/src/app/frontend/poddetail/poddetail_controller.js#L22)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Needs `@ngInject`</details>
Done.

---

*[src/app/frontend/poddetail/poddetail_stateconfig.js, line 55 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHxsZNZGfbNfYYGirXV:-KHxy2ss5WKXEZYdQHnV:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/d8d1ee45dd475dcdb2a944e25a9e60ed97f306f0/src/app/frontend/poddetail/poddetail_stateconfig.js#L55)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Missing ngInject here</details>
Done.

---

*[src/app/frontend/poddetail/poddetail_stateconfig.js, line 63 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHxsaSTQWlI6yO-Oiwe:-KHxy29ObH0Df2oo1GgJ:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/d8d1ee45dd475dcdb2a944e25a9e60ed97f306f0/src/app/frontend/poddetail/poddetail_stateconfig.js#L63)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Missing ngInject here</details>
Done.

---

*[src/app/frontend/podlist/podcardlist_component.js, line 25 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHxqsIJcT9_n_6ZLlVK:-KHxy1N98tdM3aEFDAHW:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/d8d1ee45dd475dcdb2a944e25a9e60ed97f306f0/src/app/frontend/podlist/podcardlist_component.js#L25)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Needs `@param`</details>
Done.

---

*[src/test/backend/resource/pod/podcommon_test.go, line 24 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-KHtiMjEruIYxcFmDuDm:-KHxy0XDWI3VdFe89W5j:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/d8d1ee45dd475dcdb2a944e25a9e60ed97f306f0/src/test/backend/resource/pod/podcommon_test.go#L24)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Remove? </details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-:-KHy6B1CQh51n9MvIm-X:839730464)*

**Comment by bryk** [comment]
:lgtm:

<details><summary><i>Previously, codecov-io wrote…</i></summary>
> ## [Current coverage][cc-pull] is **94.15%**
> > Merging [#740][cc-pull] into [master][cc-base-branch] will increase coverage by **0.38%**
> 
> 1. File `...ereader_directive.js` (not in diff) was modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/c0c734b2b2ed9bb48142d3a18b64e007fbebaabe/changes?src=pr#7372632F6170702F66726F6E74656E642F6465706C6F792F66696C657265616465725F6469726563746976652E6A73) 
>   - Misses `-6` 
>   - Partials `0` 
>   - Hits `+6`
> 
> ```diff
> @@             master       #740   diff @@
> ==========================================
>   Files           183        188     +5   
>   Lines          1459       1488    +29   
>   Methods           0          0          
>   Messages          0          0          
>   Branches          0          0          
> ==========================================
> + Hits           1368       1401    +33   
> + Misses           91         87     -4   
>   Partials          0          0          
> ```
> 
> > Powered by [Codecov](https://codecov.io?src=pr). Last updated by [d7b0cec...c0c734b][cc-compare]
> [cc-base-branch]: https://codecov.io/gh/kubernetes/dashboard/branch/master?src=pr
> [cc-compare]: https://codecov.io/gh/kubernetes/dashboard/compare/d7b0cec81c6c2d66796ba14b1f049f25a53fee20...c0c734b2b2ed9bb48142d3a18b64e007fbebaabe
> [cc-pull]: https://codecov.io/gh/kubernetes/dashboard/pull/740?src=pr</details>


---

Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/740#-:-KHyBq2ZBTY6PbjA21dS:1417088721)*

**Pull request merged**
