### PR TITLE
Remove `highlight.js`

### PR DESCRIPTION
**Pull request by shu-mutou**
`highlight.js` is not in use.

Ref: #6136

### CODE REVIEW

**Comment by shu-mutou** [comment]
/hold
Seems something wrong with installation of `@angular-devkit/build-angular`. Please wait for a while.

**Comment by floreks** [comment]
There is also a related entry in the `angular.json`. It has to be removed also.

**Comment by shu-mutou** [comment]
PTAL again. Thanks!

**Pull request merged**
