### PR TITLE
Refactor logs view

### LINKED ISSUE #1235: Logs are rendered in Roboto rather than Roboto Mono
##### Environment
```
Dashboard version: 95efdf3d699a102c4c7ce844af2e1cfc9f255abd
```

Similar to #1234, not sure if this is intentional or not. I'd *strongly* prefer that logs be shown in `Roboto Mono`.

2016-09-14-144211_5760x1200_scrot

### LINKED ISSUE #1236: HTML is not rendered for logs with colour attribute
#### Issue details

The logs with color attributes don't render anymore:

image

```
Dashboard version: 1.4.0
```

### LINKED ISSUE #1237: Tabulation and spacing is not respected when displaying log
#### Issue details

Logs should get displayed like this, respecting TAB and spaces:

image

But it gets displayed like this now:

image

```
Dashboard version: v1.4.0
```

### PR DESCRIPTION
**Pull request by maciaszczykm**
To do list:

- [x] remove logs toolbar
- [x] put logs in `kd-content-card`
- [x] switch logs font to monospace, closes #1235
- [x] i18n
- [x] selector styling
- [x] move style change icons to the right
- [x] implement footer for `kd-content-card` and use it
- [x] fix issue with disappearing selector without `!important` usage
- [x] render logs with color attributes (for example `\033[1;31m`), closes #1236
- [x] auto scroll to the bottom
- [x] fix tabulation issue in logs, closes #1237
- [x] fix tests
- [x] add missing `backendapi.PodContainerList` to fix `serve:prod` issue (was it tested before release?)

Current look:

image

Old look:

image

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1229)

### CODE REVIEW

**Comment by bryk** [comment]
Cool. That's first step of making this embed-able. 

What do you think about embedding this where appropriate (e.g., Pod details)  and providing links to separate full-page view like this?

**Comment by maciaszczykm** [comment]
@bryk That's really good idea. Since logs performance is a lot better thanks to pagination, we can do it without bigger performance impact. I'd suggest doing it in next pull request.

**Comment by bryk** [comment]
> I'd suggest doing it in next pull request, but I'll take it into consideration now.

Let's leave it for even further work. We should discuss this with @romlein and @Lukenickerson as this strongly relates to "what is inside a page" discussion.

**Comment by maciaszczykm** [comment]
PTAL

**Comment by bryk** [comment]
Can you make this auto-scroll-to-the-bottom?

**Comment by bryk** [comment]
Let us know when this can be reviewed :)

**Comment by maciaszczykm** [comment]
@bryk I'm not sure if we shouldn't change order of the logs. At the moment oldest logs are displayed first and you have to navigate to the newest ones. To do it you have to go to last page and then scroll to the bottom of it. 

I'd suggest displaying newest logs first. What do you think about it? 

CC @PiotrDabkowski

**Comment by bryk** [comment]
> I'd suggest displaying newest logs first. What do you think about it?


AFAIK this is what we do. Don't we?

**Comment by bryk** [comment]
I just verified that we start with oldest logs. We just need to scroll down.

**Comment by maciaszczykm** [comment]
@bryk True, my mistake.

**Comment by maciaszczykm** [comment]
Scrolling to bottom is done, but there is one general problem with it. Angular provides `md-top-index` attribute for `md-virtual-repeat-container` element and it has to point to top index, not bottom one. It's not so easy to calculate top index properly, but it works even if we send a little bit bigger number. 

I my implementation I've assumed, that number of logs visible at the same time is 40 and I'm working with that to at least try to be precise here. It works in most of the cases, but there are still the cases when scroll is not exactly at the bottom, but 1 or 3 lines from it.

PTAL.

**Comment by bryk** [comment]
Small help to make height dynamic. I made all ancestor containers height 100% and the content card flex, with logs view flex:1 

selection_129

**Comment by bryk** [comment]
Let me know when ready for rereview.

**Comment by gillesdemey** [comment]
@maciaszczykm would you mind including https://github.com/kubernetes/dashboard/issues/1237 in this PR?

**Comment by maciaszczykm** [comment]
@gillesdemey Sure.

**Comment by bryk** [comment]
@maciaszczykm I added code for full width & height. PTAL

**Comment by maciaszczykm** [comment]
@bryk Added code for #1237. Please rereview.

**Comment by bryk** [comment]
Please merge :)

**Comment by maciaszczykm** [comment]
@bryk Thanks! Done.

**Comment by edouardKaiser** [comment]
Any plan to release a 1.4.1 with this?
The current log view displaying in 1.4.0 is not very clear.

**Comment by gillesdemey** [comment]
@edouardKaiser This fix is already in the 1.4.0 release, it seems the tag was updated with a newer git hash.

If your dashboard replication controller is configured to use the 1.4.0 image you can just set the `imagePullPolicy` to `always` and delete the pod so the RC will pull the latest image.

**Comment by edouardKaiser** [comment]
Thanks @gillesdemey, you're right, perfect !

**Pull request merged**
