### PR TITLE
Initial e2e implementation of the deploy view

### PR DESCRIPTION
**Pull request by bryk**
Based on mocks:
https://github.com/kubernetes/dashboard/blob/master/designs/11-11-2015/08_deploy%20form.png

This change implements both backend and frontend for the view. This is
the approach I'll follow in the future.

Screenshot: 
deploy-form

### CODE REVIEW

**Comment by bryk** [comment]
@zreigz Take a look and do code review if have time

**Comment by bryk** [comment]
Thank you Sebastion for the review. PTAL

**Comment by bryk** [comment]
@SebastianM Oops, I've squashed my changes into one commit. This made your comments disappear. Will not do again.

**Comment by SebastianM** [comment]
@bryk No worries ;-), comments are still there: https://github.com/kubernetes/dashboard/commit/4a4569a3f15ab55b2189dab31e06c70bd4b5f655#commitcomment-14376697

Will respond to your comments this evening.

**Comment by bryk** [comment]
I'm going to merge this in order to move forward with other views. If you have any comments, I'm happy to resolve them asynchronously.

**Pull request merged**
