### PR TITLE
Japanese localization of ingress and category page

### PR DESCRIPTION
**Pull request by Yamagami-Takuma**
@f-higashi Can you review this?

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1213)

### CODE REVIEW

**Comment by f-higashi** [comment]
:lgtm:

@floreks @digitalfishpond 
You can merge this :)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1213#-:-KRT4zbBtG2FDGxq7LIh:bjqej6m)*

**Comment by bryk** [comment]
@f-higashi @Yamagami-Takuma Hey, are you available tomorrow or day after tomorrow? We'll still have a couple of new sentences to translate for the release :)

**Comment by f-higashi** [comment]
@bryk 
I'm OK today and tomorrow.

**Comment by Yamagami-Takuma** [comment]
@bryk  
I also OK.

**Pull request merged**
