### PR TITLE
Add action bars with delete and edit buttons to all detail pages

### PR DESCRIPTION
**Pull request by bryk**
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/839)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you take a look?

**Comment by floreks** [comment]
! comment. Rebase and we can merge. :lgtm:

<details><summary><i>Previously, codecov-io wrote…</i></summary>
> ## [Current coverage][cc-pull] is **94.60%**
> > Merging [#839][cc-pull] into [master][cc-base-branch] will decrease coverage by **<.01%**
> 
> 1. File `...ereader_directive.js` (not in diff) was modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/f2b97f0d686c0d5a27d98a3d1a69fd46fe1bea18/changes?src=pr#7372632F6170702F66726F6E74656E642F6465706C6F792F66696C657265616465725F6469726563746976652E6A73) 
>   - Misses `-6` 
>   - Partials `0` 
>   - Hits `+6`
> 
> ```diff
> @@             master       #839   diff @@
> ==========================================
>   Files           205        213     +8   
>   Lines          1673       1703    +30   
>   Methods           0          0          
>   Messages          0          0          
>   Branches          0          0          
> ==========================================
> + Hits           1583       1611    +28   
> - Misses           90         92     +2   
>   Partials          0          0          
> ```
> 
> > Powered by [Codecov](https://codecov.io?src=pr). Last updated by [7b9bf21...f2b97f0][cc-compare]
> [cc-base-branch]: https://codecov.io/gh/kubernetes/dashboard/branch/master?src=pr
> [cc-compare]: https://codecov.io/gh/kubernetes/dashboard/compare/7b9bf2147469eb70df1ad1eac5d8294e5d9c73bf...f2b97f0d686c0d5a27d98a3d1a69fd46fe1bea18
> [cc-pull]: https://codecov.io/gh/kubernetes/dashboard/pull/839?src=pr
</details>


---

Reviewed 61 of 64 files at r1, 1 of 1 files at r2, 2 of 3 files at r3.
Review status: 62 of 63 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[i18n/messages-ja.xtb, line 165 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/839#-KJdbSqh4x8H8MQBY3al:-KJdbSqh4x8H8MQBY3am:-2122455913) ([raw file](https://github.com/kubernetes/dashboard/blob/4beedf34a2df85b8447af91b3362e2c1eea3386b/i18n/messages-ja.xtb#L165)):*
> ```
> 	<translation id="8463528551217463399" key="MSG_EDIT_RESOURCE_DIALOG_UPDATE" source="/usr/local/google/home/bryk/src/github.com/dashboard/.tmp/serve/app-dev.js" desc="Label for update button">Update</translation>
> 	<translation id="6420130406957025720" key="MSG_YAML_EDIT_MENU_LABEL" source="/usr/local/google/home/bryk/src/github.com/dashboard/.tmp/serve/app-dev.js" desc="Label for YAML edit menu item.">View/edit JSON</translation>
> <<<<<<< f2da94863d68eaec9f1e7c2d61b2b7d9a57679eb
> ```

Merge leftover?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/839#-:-KJdd2Vh7cVji-GnnPxG:813986284)*

**Comment by bryk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[i18n/messages-ja.xtb, line 165 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/839#-KJdbSqh4x8H8MQBY3al:-KJdfGFEAC8usu2xXkZR:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/4beedf34a2df85b8447af91b3362e2c1eea3386b/i18n/messages-ja.xtb#L165)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Merge leftover?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/839)*

**Comment by bryk** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/839)*

**Pull request merged**
