### PR TITLE
Initial navigation menu for desktops

### PR DESCRIPTION
**Pull request by bryk**
And removal of middleellipsis logic to make this all work. Previous
middleellipsis implementation didn'q quite like that we have menu
sliding from the left.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1134)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm @digitalfishpond Can you review?

**Comment by bryk** [comment]
Demo: 

nav

**Comment by bryk** [comment]
@romlein @Lukenickerson Take a look at the demo.

**Comment by romlein** [comment]
@bryk looking good! I'll be able to get you spacing specs by EOD

**Comment by bryk** [comment]
@romlein Yep. I'll be asking specific questions about specs in following days.

**Comment by digitalfishpond** [comment]
one question and :lgtm: 

---

Reviewed 33 of 33 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/poddetail/containerinfo.html, line 26 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1134#-KPRjFj5jtg2F0hETdHI:-KPRjFj5jtg2F0hETdHJ:b-cdyqr2) ([raw file](https://github.com/kubernetes/dashboard/blob/a34f7214752c3adaec03b6e47d28781c5c237bec/src/app/frontend/poddetail/containerinfo.html#L26)):*
> ```HTML
>       <div ng-if="::container.env.length">
>         <div ng-repeat="env in ::container.env" layout="row">
>           <span>{{::env.name}}</span><span ng-if="env.valueFrom">
> ```

intentionally on the same line as the previous tag?

---

*[src/app/frontend/poddetail/containerinfo.html, line 31 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1134#-KPRj14ftzUKijAEYrGZ:-KPRj14ftzUKijAEYrG_:b-7jl26k) ([raw file](https://github.com/kubernetes/dashboard/blob/a34f7214752c3adaec03b6e47d28781c5c237bec/src/app/frontend/poddetail/containerinfo.html#L31)):*
> ```HTML
>               -->{{::$ctrl.i18n.getConfigMapLabel(env.valueFrom.configMapKeyRef)}}</a>)
>             </span>
>           </span><span>:&nbsp;</span>
> ```

same?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1134#-:-KPRkqEqcJOu7rMem_hu:b-c2mpyo)*

**Comment by bryk** [comment]
Thanks, merging :) 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/app/frontend/poddetail/containerinfo.html, line 26 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1134#-KPRjFj5jtg2F0hETdHI:-KPRqUGedIzfXjcXVvV-:b-c61mzy) ([raw file](https://github.com/kubernetes/dashboard/blob/a34f7214752c3adaec03b6e47d28781c5c237bec/src/app/frontend/poddetail/containerinfo.html#L26)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> intentionally on the same line as the previous tag?
</details>
Yes. We need this to avoid spacing between words. Without that we'd have, for example, `Cofnig Map : foo`. Notice the space after `:`. 

---

*[src/app/frontend/poddetail/containerinfo.html, line 31 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1134#-KPRj14ftzUKijAEYrGZ:-KPRqcwXb8Q4vnxhFnEt:bjp9ol3) ([raw file](https://github.com/kubernetes/dashboard/blob/a34f7214752c3adaec03b6e47d28781c5c237bec/src/app/frontend/poddetail/containerinfo.html#L31)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> same?
</details>
Ditto. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1134#-:-KPRqfPe-7Y5ePguXJqv:b-olum2k)*

**Pull request merged**
