### PR TITLE
Add node resource backend

### PR DESCRIPTION
**Pull request by maciaszczykm**
Added basic node resource backend. 

AFAIK nodes aren't assigned to namespaces, so I'll do more code refactoring soon.

Tests are still missing.

Connected to #821.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/860)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you review?

**Comment by maciaszczykm** [comment]
From http://kubernetes.io/docs/user-guide/namespaces/:

> ### Not All Objects are in a Namespace
Most kubernetes resources (e.g. pods, services, replication controllers, and others) are in a some namespace. However namespace resources are not themselves in a namespace. And, low-level resources, such as nodes and persistentVolumes, are not in any namespace. Events are an exception: they may or may not have a namespace, depending on the object the event is about.

That's why we need to refactor node code a bit.

**Comment by floreks** [comment]
I'll check it.

**Comment by floreks** [comment]
Minor comments. :lgtm:

<details><summary><i>Previously, codecov-io wrote…</i></summary>
> ## [Current coverage][cc-pull] is **94.05%**
> > Merging [#860][cc-pull] into [master][cc-base-branch] will increase coverage by **0.31%**
> 
> 1. File `...ereader_directive.js` (not in diff) was modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/0220c2b3adfc518251255404eb6395e03e30ad7d/changes?src=pr#7372632F6170702F66726F6E74656E642F6465706C6F792F66696C657265616465725F6469726563746976652E6A73) 
>   - Misses `-6` 
>   - Partials `0` 
>   - Hits `+6`
> 
> ```diff
> @@             master       #860   diff @@
> ==========================================
>   Files           230        230          
>   Lines          1902       1902          
>   Methods           0          0          
>   Messages          0          0          
>   Branches          0          0          
> ==========================================
> + Hits           1783       1789     +6   
> + Misses          119        113     -6   
>   Partials          0          0          
> ```
> 
> > Powered by [Codecov](https://codecov.io?src=pr). Last updated by [8f15e5c...0220c2b][cc-compare]
> [cc-base-branch]: https://codecov.io/gh/kubernetes/dashboard/branch/master?src=pr
> [cc-compare]: https://codecov.io/gh/kubernetes/dashboard/compare/8f15e5cf43dad877c454bad788ae8afb5ee97c3b...0220c2b3adfc518251255404eb6395e03e30ad7d
> [cc-pull]: https://codecov.io/gh/kubernetes/dashboard/pull/860?src=pr
</details>


---

Reviewed 6 of 6 files at r1, 10 of 10 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/backend/resource/node/nodedetail.go, line 71 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/860#-KJpOjMhiInC6QnwJ9v8:-KJpOjMhiInC6QnwJ9v9:532012030) ([raw file](https://github.com/kubernetes/dashboard/blob/0220c2b3adfc518251255404eb6395e03e30ad7d/src/app/backend/resource/node/nodedetail.go#L71)):*
> ```Go
> }
> 
> func getNodeDetail(node api.Node) NodeDetail {
> ```

Could we follow one style? `get` if we get something from outside and `to` if we just transform object. Other resources need some adjustment also.

---

*[src/app/backend/resource/node/nodelist.go, line 71 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/860#-KJpOETQu3QaiYM31lxW:-KJpOETQu3QaiYM31lxX:2070581620) ([raw file](https://github.com/kubernetes/dashboard/blob/0220c2b3adfc518251255404eb6395e03e30ad7d/src/app/backend/resource/node/nodelist.go#L71)):*
> ```Go
> }
> 
> func ToNodeList(nodes []api.Node) *NodeList {
> ```

This can be private if not used anywhere else. Some documentation would be nice also.

---

*[src/app/backend/resource/node/nodelist.go, line 83 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/860#-KJpOZfDZNMmbAW7FKg5:-KJpOZfDZNMmbAW7FKg6:1662569705) ([raw file](https://github.com/kubernetes/dashboard/blob/0220c2b3adfc518251255404eb6395e03e30ad7d/src/app/backend/resource/node/nodelist.go#L83)):*
> ```Go
> }
> 
> func ToNode(node api.Node) Node {
> ```

Same here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/860#-:-KJpP4xZG4LfDWo51-3j:1654311970)*

**Comment by maciaszczykm** [comment]
PTAL in 5 mins.

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Minor comments. :lgtm:
</details>


---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/backend/resource/node/nodedetail.go, line 71 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/860#-KJpOjMhiInC6QnwJ9v8:-KJpPQl7teyJu05DUJ4J:-623342586) ([raw file](https://github.com/kubernetes/dashboard/blob/0220c2b3adfc518251255404eb6395e03e30ad7d/src/app/backend/resource/node/nodedetail.go#L71)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Could we follow one style? `get` if we get something from outside and `to` if we just transform object. Other resources need some adjustment also.
</details>
Actually I've followed current style, which was used by other developers in other resources like Pet Sets or Replica Sets. Adjustments are needed application-wide so I'd suggest doing it in separate PR in all files.

When I've introduced Go report card I did pretty much refactoring and it seems we'll need another PR for it. `golint` is only at 69%, `gofmt`, `govet` and `misspell` aren't at 100% neither.

---

*[src/app/backend/resource/node/nodelist.go, line 71 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/860#-KJpOETQu3QaiYM31lxW:-KJpQfXDT2Ukpyfdc2B1:-2046962613) ([raw file](https://github.com/kubernetes/dashboard/blob/0220c2b3adfc518251255404eb6395e03e30ad7d/src/app/backend/resource/node/nodelist.go#L71)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> This can be private if not used anywhere else. Some documentation would be nice also.
</details>
Yeah, this can be modified. This is an issue in all other resources too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/860#-:-KJpS5t1Yq5dMbz92TMR:421496883)*

**Comment by floreks** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/860)*

**Pull request merged**
