### PR TITLE
Redesign errors on login page

### LINKED ISSUE #3904: Redesign errors displayed on login page
At the moment we are using simple component to display the error messages. It can be improved (see: `src/app/frontend/login/template.html:19`).

### PR DESCRIPTION
**Pull request by anshulahuja98**
Fix #3904 

Inspired from Error template in frontend/error

image

Suggestions welcome!

### CODE REVIEW

**Comment by maciaszczykm** [comment]
If it is inside card, don't use another one. Some warning message would be better.

You can use card outside, but still I have no idea how to make it look good.

The current version doesn't look good.

**Comment by anshulahuja98** [comment]
> If it is inside card, don't use another one. Some warning message would be better.
> 
> You can use card outside, but still I have no idea how to make it look good.
> 
> The current version doesn't look good.

Okay, I'll try out few more designs

**Comment by anshulahuja98** [comment]
1 more design idea with different placements

image

image

**Comment by maciaszczykm** [comment]
I think the nice idea would be using `<mat-error>` below input field.

**Comment by anshulahuja98** [comment]
I'll try that

**Comment by anshulahuja98** [comment]
image

Did it with `<mat-error>`
Pushing the code

**Comment by anshulahuja98** [comment]
Let me know your opinion on this.

**Comment by maciaszczykm** [comment]
Looks better, can we make it red?

Any opinions from you guys, @kubernetes/dashboard-maintainers?

**Comment by anshulahuja98** [comment]
image


Red probably looks better, I'll push that

**Comment by floreks** [comment]
It does look better. I think we can go with it for now.

**Comment by maciaszczykm** [comment]
I've restarted tests but it doesn't look like flake. Please check this if they will fail again.

**Comment by floreks** [comment]
One important thing. What about the scenario where user token expires and he is forced logged out. Error shown then will be definitely misleading if it will be under the input.

**Comment by anshulahuja98** [comment]
> I've restarted tests but it doesn't look like flake. Please check this if they will fail again.

Fixed the build

**Comment by anshulahuja98** [comment]
> One important thing. What about the scenario where user token expires and he is forced logged out. Error shown then will be definitely misleading if it will be under the input.

Umm, but it does point to filling the fields again, and if the error is descriptive enough already, I hope this won't be much of a problem, we can maybe even change the current error message.
Otherwise, I am open to suggestions as to how you would consider handling this specific form of error separately.

**Comment by anshulahuja98** [comment]
> Ye, this is the error message. The issue is that it's not really related in any way to the input fields. That's what might be confusing.

 I am open to suggestions as to how you would consider handling this specific form of error separately.

**Comment by floreks** [comment]
Not sure right now how we could improve on that. Possibly we need some designer to figure out a common way to display errors nicely.

/lgtm
/approve

**Pull request merged**
