### PR TITLE
Fix minor typo in resourcedetail infocard

### PR DESCRIPTION
**Pull request by rf232**

### CODE REVIEW

**Comment by bryk** [comment]
LGTM :) Please merge when travis is happy

**Comment by bryk** [comment]
And linux foundation CLA :)

**Comment by rf232** [comment]
Tricked the review plugin to reevaluate my Linux Foundation cla by force pushing the same change with an extra newline in the commit message

**Comment by IanLewis** [comment]
@rf232 There is an "Update Branch" button (or something like that) in the review plugin box you can press to have it re-evaluate everything.

**Comment by rf232** [comment]
@IanLewis thanks, guess I missed that button (A)

**Pull request merged**
