### PR TITLE
Resource card framework: add status and selecion info

### PR DESCRIPTION
**Pull request by bryk**
Re #630
Samples:

selection_064
selection_065

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/660)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm Can you review?

**Comment by maciaszczykm** [comment]
Tested on `serve:prod`, works good.

Two minor comments. 

:lgtm: 

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/common/components/resourcecard/resourcecardcolumn.scss, line 44 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/660#-KFirGkCLBuSne-jr84b:-KFirGkCLBuSne-jr84c:1349439729) ([raw file](https://github.com/kubernetes/dashboard/blob/a710f510e9333d290254fa7888c77e867e984fac/src/app/frontend/common/components/resourcecard/resourcecardcolumn.scss#L44)):*
`1` is not needed here?

---

*[src/app/frontend/common/components/resourcecard/resourcecardheadercolumn.scss, line 26 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/660#-KFirPX6HRdNmA3zVrOD:-KFirPX6HRdNmA3zVrOE:1349439729) ([raw file](https://github.com/kubernetes/dashboard/blob/a710f510e9333d290254fa7888c77e867e984fac/src/app/frontend/common/components/resourcecard/resourcecardheadercolumn.scss#L26)):*
`1` is not needed here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/660#-:-KFirtdOrUvnPqytorr5:-65989787)*

**Comment by bryk** [comment]
Done. Will merge soon. 

---

Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/common/components/resourcecard/resourcecardcolumn.scss, line 44 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/660#-KFirGkCLBuSne-jr84b:-KFmSR9DIgsD4FuD98h6:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/a710f510e9333d290254fa7888c77e867e984fac/src/app/frontend/common/components/resourcecard/resourcecardcolumn.scss#L44)):*
Done.

---

*[src/app/frontend/common/components/resourcecard/resourcecardheadercolumn.scss, line 26 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/660#-KFirPX6HRdNmA3zVrOD:-KFmSY-UM72apk1bjrni:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/a710f510e9333d290254fa7888c77e867e984fac/src/app/frontend/common/components/resourcecard/resourcecardheadercolumn.scss#L26)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/660#-:-KFmSe8O7H_2J7yW4cho:850226570)*

**Comment by bryk** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/660)*

**Pull request merged**
