### PR TITLE
Style fixes: center loading, fonts and internal error title

### LINKED ISSUE #1191: Fonts not loaded when UI is accessed through apiserver proxy
All fonts are downloaded from an invalid URL: `https://XX.XX.XX.XX/api/v1/proxy/namespaces/kube-system/services/fonts/roboto/Roboto-Regular.woff2 Failed to load resource: the server responded with a status of 404 ()`

### PR DESCRIPTION
**Pull request by bryk**
1. Centered loading spinner
2. Made fonts work on prod. Fixes #1191
3. Set breadcrumbs title for the internal error page

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1196)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm Can you review this?

**Comment by maciaszczykm** [comment]
PTAL

---

Reviewed 7 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/chrome/chrome.scss, line 31 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1196#-KQzBjbYtm8UXpLRbh0c:-KQzBjbYtm8UXpLRbh0d:b-3u4yb3) ([raw file](https://github.com/kubernetes/dashboard/blob/ad59b033db6af84aa87471a9f2a88a175fd4bc30/src/app/frontend/chrome/chrome.scss#L31)):*
> ```SCSS
> }
> 
> .kd-spinner {
> ```

It's centered only horizontally:



Tested on Chrome on Ubuntu.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1196#-:-KQzCURxD5H5dFbLZcUT:bb71pro)*

**Comment by bryk** [comment]
> It's centered only horizontally:

Yes, that was intentional. Vertical is hard and I'll do this later, if possible. Can we merge it as it is?

**Comment by maciaszczykm** [comment]
@bryk Yes. I'll add an issue for centering it vertically.

**Comment by bryk** [comment]
Will merge soon. 

---

Reviewed 6 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1196#-:-KR2TqzAa3_OBAhL7-yd:b-sxesbm)*

**Pull request merged**
