### PR TITLE
Persisten Volume Claim resource front and back ends

### PR DESCRIPTION
**Pull request by digitalfishpond**
Add Persistent Volume Claim resource to UI

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1202)

### CODE REVIEW

**Comment by digitalfishpond** [comment]
This PR still doesn't have tests for persistentvolumedetail_test.go. I am still working on them.

**Comment by bryk** [comment]
Looking good. Will finish review tomorrow. 

---

Reviewed 18 of 37 files at r1.
Review status: 16 of 39 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/backend/resource/persistentvolumeclaim/persistentvolumeclaimdetail.go, line 31 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1202#-KR3vNIFGOCJ8ehJx-DO:-KR3vNIFGOCJ8ehJx-DP:b-h0caaz) ([raw file](https://github.com/kubernetes/dashboard/blob/73393c1e8e5ebc0fce9dd5e81eefa9579fd8a222/src/app/backend/resource/persistentvolumeclaim/persistentvolumeclaimdetail.go#L31)):*
> ```Go
> 	Status      api.PersistentVolumeClaimPhase   `json:"status"`
> 	Volume      string                           `json:"volume"`
> 	Labels      map[string]string                `json:"labels"`
> ```

Isn't labels in ObjectMeta already?

---

*[src/app/externs/backendapi.js, line 1006 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1202#-KR3vTYEMXAyLapPf06u:-KR3vTYEMXAyLapPf06v:b-8oj83u) ([raw file](https://github.com/kubernetes/dashboard/blob/73393c1e8e5ebc0fce9dd5e81eefa9579fd8a222/src/app/externs/backendapi.js#L1006)):*
> ```JavaScript
>  * @typedef {{
>  *   objectMeta: !backendApi.ObjectMeta,
>  *   typeMeta: !backendApi.TypeMeta
> ```

Missing stuff? 

---

*[src/app/frontend/persistentvolumeclaimdetail/persistentvolumeclaiminfo_component.js, line 68 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1202#-KR48KSWLS7z0o1D-odL:-KR48KSWLS7z0o1D-odM:bl8m5ka) ([raw file](https://github.com/kubernetes/dashboard/blob/73393c1e8e5ebc0fce9dd5e81eefa9579fd8a222/src/app/frontend/persistentvolumeclaimdetail/persistentvolumeclaiminfo_component.js#L68)):*
> ```JavaScript
>   MSG_PERSISTENT_VOLUME_CLAIM_INFO_CAPACITY_ENTRY: goog.getMsg('Capacity'),
>   /** @export {string} @desc Persistent volume claim info details section access modes entry. */
>   MSG_PERSISTENT_VOLUME_CLAIM_INFO_ACCESS_MODES_ENTRY: goog.getMsg('Access Modes'),
> ```

I think Modes should be `modes`. Title case is discouraged for UI labels. Unless we're talking about something that has Some Fancy Name. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1202#-:-KR48bTl7QvsqHGkRjJN:b-y8ub8x)*

**Comment by digitalfishpond** [comment]
Ok, tests are now implemented.

**Comment by digitalfishpond** [comment]
Review status: 15 of 39 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/backend/resource/persistentvolumeclaim/persistentvolumeclaimdetail.go, line 31 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1202#-KR3vNIFGOCJ8ehJx-DO:-KR7SOsG_zwxY4lfROqi:b6czzup) ([raw file](https://github.com/kubernetes/dashboard/blob/73393c1e8e5ebc0fce9dd5e81eefa9579fd8a222/src/app/backend/resource/persistentvolumeclaim/persistentvolumeclaimdetail.go#L31)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Isn't labels in ObjectMeta already?
</details>
Yes, You're right.

---

*[src/app/externs/backendapi.js, line 1006 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1202#-KR3vTYEMXAyLapPf06u:-KR7bkVcot22mMO0ZQtY:b-896fix) ([raw file](https://github.com/kubernetes/dashboard/blob/73393c1e8e5ebc0fce9dd5e81eefa9579fd8a222/src/app/externs/backendapi.js#L1006)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Missing stuff? 
</details>
Done.

---

*[src/app/frontend/persistentvolumeclaimdetail/persistentvolumeclaiminfo_component.js, line 68 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1202#-KR48KSWLS7z0o1D-odL:-KR7bwzIxumpbOciSwF6:b-896fix) ([raw file](https://github.com/kubernetes/dashboard/blob/73393c1e8e5ebc0fce9dd5e81eefa9579fd8a222/src/app/frontend/persistentvolumeclaimdetail/persistentvolumeclaiminfo_component.js#L68)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> I think Modes should be `modes`. Title case is discouraged for UI labels. Unless we're talking about something that has Some Fancy Name. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1202)*

**Comment by bryk** [comment]
Cool! I'll verify now that this works on serve:prod

---

Reviewed 15 of 37 files at r1, 9 of 9 files at r2.
Review status: 38 of 39 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1202#-:-KR7eeonhf47dazPX_82:b-pdwe9i)*

**Comment by digitalfishpond** [comment]
Sorry about the hiccup there, Travis now happy again :)

---

Review status: 37 of 39 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1202#-:-KR7c_-Dl06jkmdzYJiE:b-nwgj7m)*

**Comment by bryk** [comment]
Can you add `-`s to empty places? 






Otherwise, :lgtm: 

---

Review status: 37 of 39 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1202#-:-KR7zvEhvKnimAmlC-48:b-wkknn5)*

**Comment by digitalfishpond** [comment]
PTAL

---

Review status: 36 of 39 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1202#-:-KR8bh__ikw-hVutRP8s:bb71pro)*

**Comment by digitalfishpond** [comment]
New conflicts resolved

---

Review status: 31 of 38 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1202#-:-KRCi47LoWYQF-9KphsK:bn2puf0)*

**Comment by bryk** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1202#-:-KRCvZK8m1PRqMOG_40G:bnfp4nl)*

**Pull request merged**
