### PR TITLE
Reintroduce zerostate

### PR DESCRIPTION
**Pull request by floreks**
This is a bit different concept of zerostate. It is displayed when there is nothing to show. We could add some links if needed. One thing I don't like is that on namespace change when there is nothing to display it will redirect to zerostate, but then after switching back to namespace with resources we have to click logo to be redirected to workloads page.

Probably namespace change event should be modified, so if current state is zerostate then try to reach last known page or workloads page.

Todo:
 - [x] Add support for all resources
 - [x] Add tests

zrzut ekranu z 2016-06-20 12-12-50

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/925)

### CODE REVIEW

**Comment by bryk** [comment]
Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/frontend/zerostate/zerostate.html, line 21 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/925#-KKhMcB0OgfpUTW-Gg6_:-KKhMcB1iNcgKmuu7-jO:-1889267603) ([raw file](https://github.com/kubernetes/dashboard/blob/6b8d41cfba0f9639350befe19bcc18db3cc9dcce/src/app/frontend/zerostate/zerostate.html#L21)):*
> ```HTML
>     <div class="kd-zerostate-message">
>       <md-icon class="material-icons kd-zerostate-icon">
>         info_outline
> ```

How about we make this less scary? I.e., don't show exclamation mark, but say "Hey, you just opened an empty cluster here. That's awesome. Please go <here> and <there> for more details how to add suff to it". Kind of what it previously was. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/925)*

**Comment by floreks** [comment]
How about

zrzut ekranu z 2016-06-20 13-02-56

**Comment by bryk** [comment]
Yeah, great progress. Wording is a bit informal, so let's iterate on it. But the general message is perfect: zerostate is not to scary people.

**Comment by bryk** [comment]
Review status: 0 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/daemonsetlist/daemonsetlist_stateconfig.js, line 43 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/925#-KKhjLiZoBxxJqHH676J:-KKhjLiZoBxxJqHH676K:600394508) ([raw file](https://github.com/kubernetes/dashboard/blob/6b8d41cfba0f9639350befe19bcc18db3cc9dcce/src/app/frontend/daemonsetlist/daemonsetlist_stateconfig.js#L43)):*
> ```JavaScript
>       },
>     },
>     views: {
> ```

Hmm... Let's think through this design, as it is going to stick with us for a while now. 

Current design has a few flaws:
1. It has url that persists, so I am able to send you a link to zerostate page. This should not be like this. Our list pages should only be linkable. Otherwise you can see zero state even when you have resources. 
2. All pages have the same zerostate content and actionbar. Should it be like this? 
3. The namespace selector issue

What do you think? I'll write a next comment soon. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/925)*

**Comment by bryk** [comment]
Review status: 0 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/daemonsetlist/daemonsetlist_stateconfig.js, line 43 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/925#-KKhjLiZoBxxJqHH676J:-KKhoE9-bAXnUAc7mIL0:81240632) ([raw file](https://github.com/kubernetes/dashboard/blob/6b8d41cfba0f9639350befe19bcc18db3cc9dcce/src/app/frontend/daemonsetlist/daemonsetlist_stateconfig.js#L43)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Hmm... Let's think through this design, as it is going to stick with us for a while now. 
> 
> Current design has a few flaws:
> 1. It has url that persists, so I am able to send you a link to zerostate page. This should not be like this. Our list pages should only be linkable. Otherwise you can see zero state even when you have resources. 
> 2. All pages have the same zerostate content and actionbar. Should it be like this? 
> 3. The namespace selector issue
> 
> What do you think? I'll write a next comment soon. 
> 
</details>
How about we use one of these solutions?
1. Dont have a separate state for zerostate. In the list template just do `<div ng-if="$ctrl.showZeroState()">Foo</div>`
2. Do the same solution for zerostates as we did for actionbar. So, configure it with `[zerostateViewName]` and add a variable to resolved data named, e.g., `showZeroState`. The zerostate would be then shown only when this var is true.

What do you think? Those both solutions solve the three problems above. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/925)*

**Comment by floreks** [comment]
I like second solution. Let's see how it works out.

**Comment by floreks** [comment]
I've prepared initial solution for service list view. I've wanted to avoid logic in controllers but it seems that we can't set custom data directly using resolves/state config.

@bryk what do you think?

**Comment by floreks** [comment]
PTAL

**Comment by bryk** [comment]
Looks awesome! Can you add tests so that all shouldShowFoo methods are covered? And address the minor comments I have? :) 

---

Reviewed 7 of 30 files at r2, 35 of 39 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/frontend/common/components/zerostate/zerostate_component.js, line 44 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/925#-KKn6wr1YICV3bqhzPgE:-KKn6wr237Kj0wwR4ohc:-1979076685) ([raw file](https://github.com/kubernetes/dashboard/blob/fddd23bcb3900ee0b055e9c504bd8899a15e7c3d/src/app/frontend/common/components/zerostate/zerostate_component.js#L44)):*
> ```JavaScript
>   /** @export {string} @desc Text which appears on zero state view under the title. It provides
>    *  to deploy view or offers user to take the Dashboard Tour. */
>   MSG_ZERO_STATE_TEXT: goog.getMsg(
> ```

Nice :) 

---

*[src/app/frontend/daemonsetlist/daemonsetlist.html, line 22 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/925#-KKn76t8KVgdE3Uf-03N:-KKn76t8KVgdE3Uf-03O:-1343209393) ([raw file](https://github.com/kubernetes/dashboard/blob/fddd23bcb3900ee0b055e9c504bd8899a15e7c3d/src/app/frontend/daemonsetlist/daemonsetlist.html#L22)):*
> ```HTML
>   </kd-content>
> </kd-content-card>
> <kd-zero-state ng-if="ctrl.shouldShowZeroState()"></kd-zero-state>
> ```

The controller does not have such method. Missing? 

---

*[src/app/frontend/daemonsetlist/daemonsetlist_component.js, line 30 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/925#-KKn73-qWHEpoPMwTHR-:-KKn73-r3S6JwAkbF4QE:1198708216) ([raw file](https://github.com/kubernetes/dashboard/blob/fddd23bcb3900ee0b055e9c504bd8899a15e7c3d/src/app/frontend/daemonsetlist/daemonsetlist_component.js#L30)):*
> ```JavaScript
>     /**
>      * Initialized from the scope.
>      * @export {!backendApi.DaemonSet}
> ```

DaemonSetList? 

---

*[src/app/frontend/servicelist/servicelist_stateconfig.js, line 34 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/925#-KKmOyjIBKYMgvHkFxnH:-KKmOyjIBKYMgvHkFxnI:1264630298) ([raw file](https://github.com/kubernetes/dashboard/blob/64c61a0947dd04c78f2cc91528f729863e234491/src/app/frontend/servicelist/servicelist_stateconfig.js#L34)):*
> ```JavaScript
>     resolve: {
>       'serviceListResource': getServiceListResource,
>       'serviceList': resolveServiceList,
> ```

Can we maybe add a boolean [showZeroState] here? It could use service list 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/925#-:-KKn7TidVJDERJ1t4HLC:152882067)*

**Comment by floreks** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/frontend/daemonsetlist/daemonsetlist.html, line 22 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/925#-KKn76t8KVgdE3Uf-03N:-KKn8Jzjasun9tZpq2i6:372924979) ([raw file](https://github.com/kubernetes/dashboard/blob/fddd23bcb3900ee0b055e9c504bd8899a15e7c3d/src/app/frontend/daemonsetlist/daemonsetlist.html#L22)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> The controller does not have such method. Missing? 
</details>
It's not missing. See other comment.

---

*[src/app/frontend/daemonsetlist/daemonsetlist_component.js, line 30 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/925#-KKn73-qWHEpoPMwTHR-:-KKn8yyFlDGpvwI2jRUf:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/fddd23bcb3900ee0b055e9c504bd8899a15e7c3d/src/app/frontend/daemonsetlist/daemonsetlist_component.js#L30)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> DaemonSetList? 
</details>
Done.

---

*[src/app/frontend/daemonsetlist/daemonsetlist_controller.js, line 32 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/925#-KKn8iCVrmDOTdvrT9VO:-KKn8iCVrmDOTdvrT9VP:1937727374) ([raw file](https://github.com/kubernetes/dashboard/blob/fddd23bcb3900ee0b055e9c504bd8899a15e7c3d/src/app/frontend/daemonsetlist/daemonsetlist_controller.js#L32)):*
> ```JavaScript
>    * @export
>    */
>   shouldShowZeroState() { return this.daemonSetList.daemonSets.length === 0; }
> ```

Here is method for `daemonsetlist` template :)

---

*[src/app/frontend/servicelist/servicelist_stateconfig.js, line 34 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/925#-KKmOyjIBKYMgvHkFxnH:-KKn9KJGQHuqyql181Yj:337065628) ([raw file](https://github.com/kubernetes/dashboard/blob/64c61a0947dd04c78f2cc91528f729863e234491/src/app/frontend/servicelist/servicelist_stateconfig.js#L34)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Can we maybe add a boolean [showZeroState] here? It could use service list 
</details>
Move logic from controller to resolve and inject into the controller, right? If so, then I will do it tomorrow. It's too much refactoring for today :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/925)*

**Comment by bryk** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/daemonsetlist/daemonsetlist.html, line 22 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/925#-KKn76t8KVgdE3Uf-03N:-KKqiGN6ASZiTFBxHKD-:1617893365) ([raw file](https://github.com/kubernetes/dashboard/blob/fddd23bcb3900ee0b055e9c504bd8899a15e7c3d/src/app/frontend/daemonsetlist/daemonsetlist.html#L22)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> It's not missing. See other comment.
</details>
Whoops. Sorry :) Didn'e see. 

---

*[src/app/frontend/servicelist/servicelist_stateconfig.js, line 34 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/925#-KKmOyjIBKYMgvHkFxnH:-KKqiNgJ1yN8154ORpyD:1271065294) ([raw file](https://github.com/kubernetes/dashboard/blob/64c61a0947dd04c78f2cc91528f729863e234491/src/app/frontend/servicelist/servicelist_stateconfig.js#L34)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Move logic from controller to resolve and inject into the controller, right? If so, then I will do it tomorrow. It's too much refactoring for today :)
</details>
No, that's fine. This was one of my stale comments that I didn't publish. And now when adding comments, it was published :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/925)*

**Comment by bryk** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/925#-:-KKqiaaS1rGJey_nvSz6:1417088721)*

**Pull request merged**
