### PR TITLE
[WIP] Fix git-describe in version.js

### PR DESCRIPTION
**Pull request by shu-mutou**
Fix error in `aio/scripts/version.js` .

### CODE REVIEW

**Comment by shu-mutou** [comment]
`git-describe` does not get tags in git repository.

**Comment by shu-mutou** [comment]
travis does not seems to fetch tags information, therefore git-describe fail to get tag info and semver.

**Comment by shu-mutou** [comment]
On travis, run `git tag` but `git describe --tags` does not return  with tag information.
@maciaszczykm Could you advice about this?

**Comment by floreks** [comment]
I have already fixed that. :slightly_smiling_face: We just needed to increase cloning depth of the git in the travis. It was set to `250` and we are over `300` commits in front of master. It was not able to get version.

**Comment by shu-mutou** [comment]
@floreks @maciaszczykm Thanks a lot!!

**Pull request closed without merging**
