### PR TITLE
[WIP] persistent volumes frontend implementation

### PR DESCRIPTION
**Pull request by batikanu**
It includes Persistent volume implementation of detail and list views. 

_To discuss_ 
- How to display multiple values in detail view and list ? For example access modes 
- Detail view
pvdetail

- List view
pvlist

- Will Claim be a link to the persistent volume claims ?

**Todo** 
- Frontend tests

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1135)

### CODE REVIEW

**Comment by maciaszczykm** [comment]
> How to display multiple values in detail view and list ? For example access modes

I'd list them one ofter another, i.e. `element1, element2, element3`, but we can also do it in separate lines:

```
element1
element2
element3
```

If we are displaying just names (strings, not objects), then I think there is no need for any additional component to display.

**Comment by maciaszczykm** [comment]
@batikanu How many statuses are possible for persistent volumes? If not too many, then maybe it would be better to change statuses into icons like we do it on other pages?

**Comment by maciaszczykm** [comment]
@batikanu If there aren't any claims or reasons I think we should display `-` instead of nothing in the cells.

**Comment by bryk** [comment]
> Will Claim be a link to the persistent volume claims ?

It should be. Are there many claims?

**Comment by bryk** [comment]
@maciaszczykm Will you review this?

**Comment by maciaszczykm** [comment]
Consider also previous comments. Add tests.

Looks good, a few things to make it even better.

---

Reviewed 20 of 28 files at r1.
Review status: 20 of 28 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/externs/backendapi.js, line 361 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1135#-KPX08K1pyFDea7rYhhJ:-KPX08K2xMYEsuprjTWT:b59pukb) ([raw file](https://github.com/kubernetes/dashboard/blob/40fe80fe5376743edcf8c34bb90999c62f5cf72d/src/app/externs/backendapi.js#L361)):*
> ```JavaScript
>  * }}
>  */
> backendApi.PersistentVolumeSource;
> ```

Do we need whole structure? Maybe it would be better to create wrapper on backend to send only important data here (if whole structure isn't needed)?

---

*[src/app/frontend/persistentvolumedetail/persistentvolumeinfo.html, line 64 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1135#-KPX0aY0X-gLbQinyAdq:-KPX0aY0X-gLbQinyAdr:b-yqnh51) ([raw file](https://github.com/kubernetes/dashboard/blob/40fe80fe5376743edcf8c34bb90999c62f5cf72d/src/app/frontend/persistentvolumedetail/persistentvolumeinfo.html#L64)):*
> ```HTML
>         </kd-info-card-entry>
>     </kd-info-card-section>
> </kd-info-card>
> ```

Missing new line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1135#-:-KPX1ZEUKAg1F-Blz7Sw:b-133ahf)*

**Comment by batikanu** [comment]
Review status: 20 of 28 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/externs/backendapi.js, line 361 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1135#-KPX08K1pyFDea7rYhhJ:-KPXBty2C4Zw9lzuZePY:bdjw2e) ([raw file](https://github.com/kubernetes/dashboard/blob/40fe80fe5376743edcf8c34bb90999c62f5cf72d/src/app/externs/backendapi.js#L361)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> Do we need whole structure? Maybe it would be better to create wrapper on backend to send only important data here (if whole structure isn't needed)?
</details>
Good point. Most of them are needed but I will modify it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1135)*

**Comment by bryk** [comment]
When is @batikanu back?

**Comment by maciaszczykm** [comment]
> When is @batikanu back?

CC @cheld

**Comment by cheld** [comment]
Tomorrow

**Comment by bryk** [comment]
@batikanu Can you resolve conflicts on this PR when you're back? We should merge this as soon as possible :)

**Comment by batikanu** [comment]
I'm on it :)

**Comment by batikanu** [comment]
Review status: 20 of 28 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/externs/backendapi.js, line 361 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1135#-KPX08K1pyFDea7rYhhJ:-KQQGVrDfMbfNyFZ7LCa:b-896fix) ([raw file](https://github.com/kubernetes/dashboard/blob/40fe80fe5376743edcf8c34bb90999c62f5cf72d/src/app/externs/backendapi.js#L361)):*
<details><summary><i>Previously, batikanu (Batikan Urcan) wrote…</i></summary>
> Good point. Most of them are needed but I will modify it. 
</details>
Done.

---

*[src/app/frontend/persistentvolumedetail/persistentvolumeinfo.html, line 64 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1135#-KPX0aY0X-gLbQinyAdq:-KQQH8Sm2yZAMeL2qdDT:b-896fix) ([raw file](https://github.com/kubernetes/dashboard/blob/40fe80fe5376743edcf8c34bb90999c62f5cf72d/src/app/frontend/persistentvolumedetail/persistentvolumeinfo.html#L64)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> Missing new line.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1135)*

**Comment by batikanu** [comment]
Conflicts are resloved. The tests and persistent volume claim links are still missing (working on it). I can create an extra pull request for these changes if it has to be merged urgently. 

---

Review status: 17 of 28 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1135#-:-KQQIK4uTkj-FPCkWaFX:barr48y)*

**Comment by bryk** [comment]
This PR is really cool. LGTM from me. 

If you expect to finish this within a few days, then let's add remaining work to this PR. If not, let's merge. Ok? 

---

Reviewed 5 of 28 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1135#-:-KQQqUsIe-0zCftuASdl:b9qf1m8)*

**Comment by bryk** [comment]
Btw, this does not work on `gulp serve:prod`. We're missing `ngInject` somewhere.

**Comment by batikanu** [comment]
Ok I think it is manageable within few days. 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1135#-:-KQQsahE8mBCixPwa1fe:b-ijaqs6)*

**Comment by bryk** [comment]
Btw, please add PV and PVC entries to the left hand nav menu

**Comment by batikanu** [comment]
I can add PVC related changes after PVC is implemented. 
PTAL

---

Review status: 20 of 37 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1135#-:-KQZzrwfNS4uaXrIpNQA:b-lfpqek)*

**Comment by bryk** [comment]
Testing and waiting for travis... 

---

Reviewed 14 of 28 files at r1, 17 of 17 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1135#-:-KQ_19vDpJyGOSQTM7wt:b-a72all)*

**Pull request merged**
