### PR TITLE
A couple of fixes in zerostate code

### PR DESCRIPTION
**Pull request by bryk**
1. Make the link include namespace that is selected. We should use
`$state` for all links, anyway.
1. Increase padding to make the information more prominent.
1. Add info that in order to see something you can change namespace.
1. Align external link icon vertically
1. Change wording to be similar to what we have in other places (e.g.,
"deploy a containerized app".

selection_089

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/936)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you take a quick look?

**Comment by floreks** [comment]
Mostly :lgtm:. I'm just not sure about this padding.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[i18n/messages-en.xtb, line 475 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/936#-KKqpIkS-jKY9WQH5qH7:-KKqpIkS-jKY9WQH5qH8:-207699184) ([raw file](https://github.com/kubernetes/dashboard/blob/758860abc6d457c1e9c30f3cad81b1610aeab992/i18n/messages-en.xtb#L475)):*
> ```
> 	<translation id="5154496218567149713" key="MSG_NODE_DETAIL_ALLOCATED_RESOURCES_PODS" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Label 'Pods' for the allocated resources table header on the node details page.">Pods</translation>
> 	<translation id="1538072409274591134" key="MSG_ZERO_STATE_TITLE" source="/home/floreks/Projects/dashboard/.tmp/serve/app-dev.js" desc="Title text which appears on zero state view.">There is nothing to display here</translation>
> 	<translation id="843228251260108399" key="MSG_ZERO_STATE_TEXT" source="/home/floreks/Projects/dashboard/.tmp/serve/app-dev.js" desc="Text which appears on zero state view under the title. It provides to deploy view or offers user to take the Dashboard Tour.">Let's <ph name="CREATE_NEW_LINK" /> create a new app <ph name="CREATE_NEW_CLOSE_LINK" /> or learn more and <ph name="OPEN_LINK" /> take the Dashboard Tour <ph name="LINK_ICON" /> <ph name="CLOSE_LINK" /></translation>
> ```

This one is stale now

---

*[src/app/frontend/common/components/zerostate/zerostate.html, line 19 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/936#-KKqpXsb39_j6PLa-kav:-KKqpXsb39_j6PLa-kaw:-2052315439) ([raw file](https://github.com/kubernetes/dashboard/blob/758860abc6d457c1e9c30f3cad81b1610aeab992/src/app/frontend/common/components/zerostate/zerostate.html#L19)):*
> ```HTML
> <kd-content-card>
>   <kd-content>
>     <div class="kd-zerostate-message" layout-padding>
> ```

Yeah. This padding seems huge now :) @maciaszczykm what do you think?

---

*[src/app/frontend/common/components/zerostate/zerostate_component.js, line 55 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/936#-KKqpNNjJgdF6XHkEY2y:-KKqpNNjJgdF6XHkEY2z:-2054118310) ([raw file](https://github.com/kubernetes/dashboard/blob/758860abc6d457c1e9c30f3cad81b1610aeab992/src/app/frontend/common/components/zerostate/zerostate_component.js#L55)):*
> ```JavaScript
>           ' to learn more',
>       {
>         'createNewLink': `<a href="${$state.href(deployAppStateName)}">`,
> ```

Nice! I've been looking for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/936#-:-KKqqcDKnfDr6xSvBupn:1501103016)*

**Comment by bryk** [comment]
PTAL

---

Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[i18n/messages-en.xtb, line 475 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/936#-KKqpIkS-jKY9WQH5qH7:-KKqur-Qy721yBIz9Enz:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/758860abc6d457c1e9c30f3cad81b1610aeab992/i18n/messages-en.xtb#L475)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> This one is stale now
</details>
Done.

---

*[src/app/frontend/common/components/zerostate/zerostate.html, line 19 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/936#-KKqpXsb39_j6PLa-kav:-KKqt8SHAjzvDhMY5PAz:442082680) ([raw file](https://github.com/kubernetes/dashboard/blob/758860abc6d457c1e9c30f3cad81b1610aeab992/src/app/frontend/common/components/zerostate/zerostate.html#L19)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Yeah. This padding seems huge now :) @maciaszczykm what do you think?
</details>
I dont have strong opinion on this. So I'll let @maciaszczykm decide and I'll do what you say. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/936#-:-KKqvL4cWyPOt97pExlT:676965300)*

**Comment by maciaszczykm** [comment]
For me @bryk's version with bigger padding looks better :)

**Comment by floreks** [comment]
Ok, then we can merge. :) LGTM

**Comment by bryk** [comment]
I actually though that stale lines are auto-removed. But yeah, adding removal of them should not be that hard. 

Merging. 

---

Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/936#-:-KKqxGxWeEwi5DYvtriT:1754587511)*

**Comment by bryk** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/936)*

**Pull request merged**
