### PR TITLE
Removed NodePort from deployment descriptor

### PR DESCRIPTION
**Pull request by cheld**
Tested one file (kubernetes-dashboard.yaml)

fixes https://github.com/kubernetes/dashboard/issues/1744

### CODE REVIEW

**Comment by cheld** [comment]
Codecov a bit confused?

**Comment by maciaszczykm** [comment]
@cheld Yes, it happens since we have it configured. We have switched to integration and there is a red check, but it shouldn't block merging. Also, having this icon is great.

**Comment by cheld** [comment]
@maciaszczykm well...I removed code and the coverage decreased in an area I did not touch...

**Comment by maciaszczykm** [comment]
@cheld Yes, I noticed. When pull requests did not change anything then it is a common problem.

**Pull request merged**
