### PR TITLE
Add approvers for 'de' translations.

### PR DESCRIPTION
**Pull request by headcr4sh**
This PR adds approvers for German translations.

@shu-mutou suggested to add the three whilst working on PR #4905 

- ✔️@headcr4sh I am interested in reviewing German translations of the dashboard.
- ✔️ @mkorbi  I already talked to him on Slack and he would be willing to take on this role.
- ✔️ @kgroschoff ~~I have not (yet) added you to the list because I wanted to ask first if that's ok for you.~~ left a comment further below an wrote that she'd like to help out as well

### CODE REVIEW

**Comment by headcr4sh** [comment]
> The following users are mentioned in OWNERS file(s) but are not members of the kubernetes org.
> 
> Once all users have been added as [members](https://git.k8s.io/community/community-membership.md#member) of the org, you can trigger verification by writing `/verify-owners` in a comment.
> 
> * headcr4sh
>   
>   * i18n/de/OWNERS

Whoops.
I am not really familiar with how maintainership works here. Anything that I must do to proceed?

**Comment by kgroschoff** [comment]
@headcr4sh Sure, I can help out with reviewing :)

**Comment by maciaszczykm** [comment]
Both of you need to apply for Kubernetes membership to make this happen. I can be one of the sponsors, but I am not sure how it works in terms of contributing requirements. You would have to check that.

**Comment by jeefy** [comment]
I can be the other sponsor. 

Typically there is a requirement to have existing contributions however I've seen cases where we're onboarding people for docs/translations to be approved. 

/cc @mrbobbytables for more context

**Comment by headcr4sh** [comment]
All right. I have requested membership in the Kubernetes org.
See https://github.com/kubernetes/org/issues/1633

I have declared both of you (@maciaszczykm and @jeefy) as sponsors.
Thans for your support.

**Comment by shu-mutou** [comment]
@kgroschoff Do you willing to become kubernetes member? If do you so, please submit PR like https://github.com/kubernetes/org/issues/1633.

**Comment by kgroschoff** [comment]
@shu-mutou Yes, sorry for the delay. https://github.com/kubernetes/org/issues/1663

**Pull request merged**
