### PR TITLE
Angular migration - pod exec state

### PR DESCRIPTION
**Pull request by pengx17**
Some TODOs:
- Toast service. Use Material Toast directly?
- SockJS fallbacks to regular xhr instead of websocket with local dev environment (windows 10). Not sure if there is something wrong at my side.

Here is a screenshot:
qq 20180724161110

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@pengx17 What's status of this pull request? I can see some TODOs in the first post and I don't know if it is ready for an review.

**Comment by pengx17** [comment]
@maciaszczykm I haven't got a clue how to fix the "fallback to XHR" issue right now since my Golang background is not solid enough to debug it.
And for the toast implementation, I don't know if there is a plan to bring in toast components into the dashboard.

I guess the exec functionality works overall and you can start to review it for the moment.

**Comment by maciaszczykm** [comment]
@pengx17 Can you rebase?

**Comment by maciaszczykm** [comment]
@pengx17 Friendly ping :)

**Comment by maciaszczykm** [comment]
Thanks a lot! Error handling could be improved with better messages (sometimes there is an error that container cannot be found) but we can do this in separate PR-s.

/lgtm

**Pull request merged**
