### PR TITLE
Japanese localization of Workloads, pet set and resources

### PR DESCRIPTION
**Pull request by Yamagami-Takuma**
Japanese localization of Workloads, pet set and resources.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/849)

### CODE REVIEW

**Comment by Yamagami-Takuma** [comment]
@f-higashi Can you review this?

**Comment by f-higashi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[i18n/messages-ja.xtb, line 113 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/849#-KJiHv4zLQFfOa7uLjSR:-KJiHv4zLQFfOa7uLjSS:1192278914) ([raw file](https://github.com/kubernetes/dashboard/blob/6baa7c57363d63cf57006641ec89e4436129c9a4/i18n/messages-ja.xtb#L113)):*
> ```
> 	<translation id="8275670389075054584" key="MSG_PODS_ARE_PENDING_TOOLTIP" source="/home/denis/Projects/dashboard/.tmp/serve/app-dev.js" desc="tooltip for pending pod card icon">One or more pods are in pending state</translation>
> 	<translation id="3543875874833788829" key="MSG_WORKLOADS_DEAMON_SETS_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label &quot;Daemon sets&quot;, which appears above the daemon sets list on the workloads page.">デーモンセット</translation>
> 	<translation id="5605659611398511623" key="MSG_WORKLOADS_DEPLOYMENTS_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label &quot;Deployments&quot;, which appears above the deployments list on the workloads page.">配備</translation>
> ```

In this sentense, you should use `デプロイメント`.
It is a type of resource.

---

*[i18n/messages-ja.xtb, line 132 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/849#-KJiKAiiMdUHUPyrpW26:-KJiKAij8Zw7YL809dwR:1518379943) ([raw file](https://github.com/kubernetes/dashboard/blob/6baa7c57363d63cf57006641ec89e4436129c9a4/i18n/messages-ja.xtb#L132)):*
> ```
> 	<translation id="5668446644812094754" key="MSG_SERVICE_DETAIL_LABELS_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label 'Labels' for the service labels in the details part (left) of the service details view.">ラベル</translation>
> 	<translation id="1483678895179795219" key="MSG_SERVICE_DETAIL_TYPE_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label 'Type' for the service type in the details part (left) of the service details view.">種類</translation>
> 	<translation id="3345086067441164496" key="MSG_SERVICE_DETAIL_CONNECTION_SUBTITLE" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Subtitle 'Connection' at the top of the column about network connectivity (right) at the service detail view.">接続</translation>
> ```

How about `接続情報`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/849)*

**Comment by Yamagami-Takuma** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[i18n/messages-ja.xtb, line 113 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/849#-KJiHv4zLQFfOa7uLjSR:-KJiTn0rz8B27Tk2IUdv:1920760566) ([raw file](https://github.com/kubernetes/dashboard/blob/6baa7c57363d63cf57006641ec89e4436129c9a4/i18n/messages-ja.xtb#L113)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> In this sentense, you should use `デプロイメント`.
> It is a type of resource.
</details>
I fixed.

---

*[i18n/messages-ja.xtb, line 132 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/849#-KJiKAiiMdUHUPyrpW26:-KJiTpQhh6rqdZpxcs54:1920760566) ([raw file](https://github.com/kubernetes/dashboard/blob/6baa7c57363d63cf57006641ec89e4436129c9a4/i18n/messages-ja.xtb#L132)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> How about `接続情報`
</details>
I fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/849)*

**Comment by f-higashi** [comment]
:lgtm: 

you can merge this :)

<details><summary><i>Previously, codecov-io wrote…</i></summary>
> ## [Current coverage][cc-pull] is **94.67%**
> > Merging [#849][cc-pull] into [master][cc-base-branch] will increase coverage by **0.33%**
> 
> 1. File `...ereader_directive.js` (not in diff) was modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/6baa7c57363d63cf57006641ec89e4436129c9a4/changes?src=pr#7372632F6170702F66726F6E74656E642F6465706C6F792F66696C657265616465725F6469726563746976652E6A73) 
>   - Misses `-6` 
>   - Partials `0` 
>   - Hits `+6`
> 
> ```diff
> @@             master       #849   diff @@
> ==========================================
>   Files           225        225          
>   Lines          1784       1784          
>   Methods           0          0          
>   Messages          0          0          
>   Branches          0          0          
> ==========================================
> + Hits           1683       1689     +6   
> + Misses          101         95     -6   
>   Partials          0          0          
> ```
> 
> > Powered by [Codecov](https://codecov.io?src=pr). Last updated by [ac6679b...6baa7c5][cc-compare]
> [cc-base-branch]: https://codecov.io/gh/kubernetes/dashboard/branch/master?src=pr
> [cc-compare]: https://codecov.io/gh/kubernetes/dashboard/compare/ac6679b537e17e6f664611f226bef9ebc8e48e3a...6baa7c57363d63cf57006641ec89e4436129c9a4
> [cc-pull]: https://codecov.io/gh/kubernetes/dashboard/pull/849?src=pr
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/849#-:-KJiX0r-9NDfOvw14msv:640782441)*

**Comment by maciaszczykm** [comment]
@Yamagami-Takuma please resolve conflicts caused by my last merge :)

**Comment by Yamagami-Takuma** [comment]
@maciaszczykm It's done :)

**Pull request merged**
