### PR TITLE
update hyperkube and use nsenter

### PR DESCRIPTION
**Pull request by cheld**
* update hyperkube and heapster
* clean up
* crazy hack to avoid shared mount propagation

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1157)

### CODE REVIEW

**Comment by bryk** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[build/hyperkube.sh, line 16 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1157#-KQK4rXf8xjkXu5hNM3p:-KQK4rXgCqmWkOaHi5C2:b33ov51) ([raw file](https://github.com/kubernetes/dashboard/blob/61da987b681d35fdd6ddb24c7fa6c8e53bb4aa68/build/hyperkube.sh#L16)):*
> ```Shell
> # limitations under the License.
> 
> # Starts local hypercube cluster in a Docker contai
> ```

Hmm.. Revert this line? I see typos. 

---

*[build/hyperkube.sh, line 40 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1157#-KQK4z1xhBlJ9Dibp7RA:-KQK4z1xhBlJ9Dibp7RB:bibiz8m) ([raw file](https://github.com/kubernetes/dashboard/blob/61da987b681d35fdd6ddb24c7fa6c8e53bb4aa68/build/hyperkube.sh#L40)):*
> ```Shell
>         --hostname-override="127.0.0.1" \
>         --address="0.0.0.0" \
>         --api-servers=http://localhost:8080 \
> ```

Revert back `${PORT}`?

---

*[build/hyperkube.sh, line 49 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1157#-KQK50WXYlVnGAA-0xga:-KQK50WXYlVnGAA-0xgb:bibiz8m) ([raw file](https://github.com/kubernetes/dashboard/blob/a1a09cf4daae5a1f84b3f225ddcb484e04034bad/build/hyperkube.sh#L49)):*
> ```Shell
> # Runs Heapster in standalone mode
> docker run --net=host -d gcr.io/google_containers/heapster:${HEAPSTER_VERSION} -port ${HEAPSTER_PORT} \
>     --source=kubernetes:http://127.0.0.1:${PORT}?inClusterConfig=false&auth=""
> ```

Revert back `${PORT}`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1157)*

**Comment by bryk** [comment]
PTAL 

---

Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1157#-:-KQK56ulYlwDuGUQboRy:b-833310)*

**Comment by cheld** [comment]
@bryk I felt the variable is suggesting that the port can be changed. However, this is not the case, Changing port requires a rebuild of hyperkube.

**Comment by cheld** [comment]
PTAL

**Comment by bryk** [comment]
Ok, now it makes sense. LGTM :) 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1157#-:-KQLQbzPsDuSO7_G75F5:bwwk65w)*

**Pull request merged**
