### PR TITLE
Add initial version of service list and service details pages

### PR DESCRIPTION
**Pull request by floreks**
This is pretty raw version of both pages but this PR is already pretty big. In next PR I'll add some actionbar actions and pods(only?) related to service.

Do we want deploy button to always go to deploy app form?

zrzut ekranu z 2016-05-09 16-03-37
zrzut ekranu z 2016-05-09 16-03-45

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/726)

### CODE REVIEW

**Comment by bryk** [comment]
Looks very nice. A few minor comments. Can you increase test coverage to 100%? 

<details><summary><i>Previously, codecov-io wrote…</i></summary>
> ## [Current coverage][cc-pull] is **93.59%**
> > Merging [#726][cc-pull] into [master][cc-base-branch] will increase coverage by **+<.01%**
> 
> 1. File `...ereader_directive.js` (not in diff) was modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/aa7788ab1da7ea578eb1e71eb7e6fbf7118e82a6/changes?src=pr#7372632F6170702F66726F6E74656E642F6465706C6F792F66696C657265616465725F6469726563746976652E6A73) 
>   - Misses `-6` 
>   - Partials `0` 
>   - Hits `+6`
> 
> ```diff
> @@             master       #726   diff @@
> ==========================================
>   Files           153        162     +9   
>   Lines          1315       1358    +43   
>   Methods           0          0          
>   Messages          0          0          
>   Branches          0          0          
> ==========================================
> + Hits           1230       1271    +41   
> - Misses           85         87     +2   
>   Partials          0          0          
> ```
> 
> > Powered by [Codecov](https://codecov.io?src=pr). Last updated by [8e96e76...aa7788a][cc-compare]
> [cc-base-branch]: https://codecov.io/gh/kubernetes/dashboard/branch/master?src=pr
> [cc-compare]: https://codecov.io/gh/kubernetes/dashboard/compare/8e96e76b507ba58ae24dbfcaf11e4978e568c921...aa7788ab1da7ea578eb1e71eb7e6fbf7118e82a6
> [cc-pull]: https://codecov.io/gh/kubernetes/dashboard/pull/726?src=pr</details>


---

Reviewed 21 of 31 files at r1.
Review status: 20 of 30 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/backend/resource/service/services.go, line 57 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOWIYMSY7MBDocq6f1:-KHOWIYMSY7MBDocq6f2:-1282702070) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/backend/resource/service/services.go#L57)):*
> ```Go
> 	// we will try to respect it or else fail the request.  This field can
> 	// not be changed by updates.
> 	// Valid values are None, empty string (""), or a valid IP address
> ```

The part:
```
If specified by the user
 +	// we will try to respect it or else fail the request.  This field can
 +	// not be changed by updates.
```
Is not needed here IMO 

---

*[src/app/backend/resource/service/services.go, line 105 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOWPgA4UwBnzqyAL0t:-KHOWPgA4UwBnzqyAL0u:494794189) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/backend/resource/service/services.go#L105)):*
> ```Go
> // GetServiceDetails returns api service object based on kubernetes service object
> func GetServiceDetails(service *api.Service) Service {
> 	return Service{
> ```

I'm wondering whether we should be using the same object for details and for lists. Lists have only basic props while details contain all stuff. 
This is separated for RCs. 

---

*[src/app/frontend/podlist/podcardlist.html, line 17 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOWgaHyxdv3kI4OHdG:-KHOWgaHyxdv3kI4OHdH:1735661521) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/frontend/podlist/podcardlist.html#L17)):*
> ```HTML
> -->
> 
> <kd-resource-card-list selectable="false" with-statuses="false">
> ```

Yeah, I did the same :D

---

*[src/app/frontend/podlist/podcardlist_component.js, line 58 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOWlXhhK1LvntGlJ_3:-KHOWlXhhK1LvntGlJ_4:1603703119) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/frontend/podlist/podcardlist_component.js#L58)):*
> ```JavaScript
>     'logsHrefFn': '&',
>     /** {boolean} */
>     'selectable': '<',
> ```

You added the params but not used them? 

---

*[src/app/frontend/servicedetail/servicedetailinfo.html, line 18 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOY25yXySUWFypyGtU:-KHOY25zPapdLgQcVcr2:-644713348) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/frontend/servicedetail/servicedetailinfo.html#L18)):*
> ```HTML
> 
> <kd-info-card>
>   <kd-info-card-header>Resource Details</kd-info-card-header>
> ```

Maybe "Service details"? Why hide this info? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-:-KHOYEeyOaFk3dyTeVib:412812771)*

**Comment by floreks** [comment]
Yeah, but there is no logic to test so I can only check if ctrl object was created :) 

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Looks very nice. A few minor comments. Can you increase test coverage to 100%? </details>


---

Review status: 20 of 30 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/app/backend/resource/service/services.go, line 105 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOWPgA4UwBnzqyAL0t:-KHOh7zSn5U3iYsZbotb:-381216835) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/backend/resource/service/services.go#L105)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> I'm wondering whether we should be using the same object for details and for lists. Lists have only basic props while details contain all stuff. 
> This is separated for RCs. </details>
Is there a reason why we can't have one resource object with details for list and details page? I believe memory/bandwith overhead is in this case very little and we do not need different structures.

---

*[src/app/frontend/podlist/podcardlist.html, line 17 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOWgaHyxdv3kI4OHdG:-KHOhmFT5PMiHjz73nL0:691891792) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/frontend/podlist/podcardlist.html#L17)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Yeah, I did the same :D</details>
Yep, It is better to leave pure list in here :)

---

*[src/app/frontend/podlist/podcardlist_component.js, line 58 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOWlXhhK1LvntGlJ_3:-KHOhvHPcdg8K8YUtXbc:1399291816) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/frontend/podlist/podcardlist_component.js#L58)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> You added the params but not used them? </details>
By default they are false so on details page I did not need to use them. I think that they will be used on pod list page.

---

*[src/app/frontend/servicedetail/servicedetailinfo.html, line 18 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOY25yXySUWFypyGtU:-KHOiqPUVbrb_wS9yJww:361013681) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/frontend/servicedetail/servicedetailinfo.html#L18)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Maybe "Service details"? Why hide this info? </details>
I don't have strong opinion on this. My thinking was that user already knows that he is on service details page so we do not have to show `Service Details` and more generic text would be fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-:-KHOjoEfmg_AUkU_u_3I:2127015983)*

**Comment by bryk** [comment]
Review status: 19 of 30 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/backend/resource/service/services.go, line 105 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOWPgA4UwBnzqyAL0t:-KHP7kP-dNKLNH8x9zF7:941323099) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/backend/resource/service/services.go#L105)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Is there a reason why we can't have one resource object with details for list and details page? I believe memory/bandwith overhead is in this case very little and we do not need different structures.</details>
Resource for a list contains a lot less info than for details. E.g., list of RCs contains its names, basic details and maybe some derived information. On the other hand, details of RC contain all information plus list of child pods, sibling services and owning deployments. On list pages this may make huge difference. 

---

*[src/app/frontend/servicedetail/servicedetailinfo.html, line 18 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOY25yXySUWFypyGtU:-KHPA_6-o806AJqw7lPF:1560804987) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/frontend/servicedetail/servicedetailinfo.html#L18)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> I don't have strong opinion on this. My thinking was that user already knows that he is on service details page so we do not have to show `Service Details` and more generic text would be fine.</details>
Ok, we can change it later for all resources. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/726)*

**Comment by bryk** [comment]
Test stuff anyway, it'll be easy to fill with better content later. 

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Yeah, but there is no logic to test so I can only check if ctrl object was created :) </details>


---

Review status: 19 of 30 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/frontend/podlist/podcardlist_component.js, line 58 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOWlXhhK1LvntGlJ_3:-KHPD5KW6pkIBoKTCZLv:-1758019822) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/frontend/podlist/podcardlist_component.js#L58)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> By default they are false so on details page I did not need to use them. I think that they will be used on pod list page.</details>
Yeah, but podcardlist.html nor any JS code don't use this params. This is dead code, basically. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-:-KHPCu6PQdqetVwst1n2:1635656792)*

**Comment by floreks** [comment]
Review status: 19 of 30 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/frontend/podlist/podcardlist_component.js, line 58 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOWlXhhK1LvntGlJ_3:-KHPGJ_7KzBDbzquAt6l:-208237539) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/frontend/podlist/podcardlist_component.js#L58)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Yeah, but podcardlist.html nor any JS code don't use this params. This is dead code, basically. </details>
oh... I've added them there but didn't use in template... you're right

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/726)*

**Comment by bryk** [comment]
Review status: 19 of 30 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/frontend/podlist/podcardlist_component.js, line 58 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOWlXhhK1LvntGlJ_3:-KHPMO3HSLRMXxA9i-RC:236303896) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/frontend/podlist/podcardlist_component.js#L58)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> oh... I've added them there but didn't use in template... you're right</details>
Ping me when ready for rereview. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/726)*

**Comment by floreks** [comment]
Review status: 14 of 32 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/backend/resource/service/services.go, line 105 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOWPgA4UwBnzqyAL0t:-KHPPfhlGnGD6jMdtPEo:685661696) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/backend/resource/service/services.go#L105)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Resource for a list contains a lot less info than for details. E.g., list of RCs contains its names, basic details and maybe some derived information. On the other hand, details of RC contain all information plus list of child pods, sibling services and owning deployments. On list pages this may make huge difference. </details>
Ok, I'll refactor services into servicelist and servicedetail as it's done for other resources and split to 2 structures `ServiceInfo` and `ServiceDetails`. in next PR. What do you think?

---

*[src/app/frontend/podlist/podcardlist_component.js, line 58 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOWlXhhK1LvntGlJ_3:-KHPPRLxBG1Ir2WlD6Je:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/frontend/podlist/podcardlist_component.js#L58)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Ping me when ready for rereview. </details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/726)*

**Comment by floreks** [comment]
PTAL

**Comment by bryk** [comment]
Last comments and let's merge. 

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> PTAL</details>


---

Reviewed 7 of 31 files at r1, 2 of 4 files at r2, 7 of 8 files at r3.
Review status: 30 of 32 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/backend/resource/service/services.go, line 57 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOWIYMSY7MBDocq6f1:-KHPWchNzr1UaOprymkQ:936788459) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/backend/resource/service/services.go#L57)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> The part:
> ```
> If specified by the user
>  +	// we will try to respect it or else fail the request.  This field can
>  +	// not be changed by updates.
> ```
> Is not needed here IMO </details>
Not done?

---

*[src/app/backend/resource/service/services.go, line 105 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOWPgA4UwBnzqyAL0t:-KHPWYs7OYZfWNIBQfls:-685795884) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/backend/resource/service/services.go#L105)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Ok, I'll refactor services into servicelist and servicedetail as it's done for other resources and split to 2 structures `ServiceInfo` and `ServiceDetails`. in next PR. What do you think?</details>
Next PR SGTM :) 

---

*[src/app/frontend/podlist/podcardlist.html, line 17 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHPXKndkH2UQjNQA03z:-KHPXKndkH2UQjNQA04-:1197550521) ([raw file](https://github.com/kubernetes/dashboard/blob/219a4041f404b76eca5adb8b7f52b1c00dbfb300/src/app/frontend/podlist/podcardlist.html#L17)):*
> ```HTML
> -->
> 
> <kd-resource-card-list selectable="::$ctrl.selectable" with-statuses="$::ctrl.withStatuses"
> ```

Typo here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-:-KHPXtHcOvMnFqjubNux:959610273)*

**Comment by floreks** [comment]
Review status: 30 of 32 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/backend/resource/service/services.go, line 57 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHOWIYMSY7MBDocq6f1:-KHPYKZVYKlwfv5K-EE-:1849105821) ([raw file](https://github.com/kubernetes/dashboard/blob/d046cfa2de83424c5f26847da26717a5ff28d66d/src/app/backend/resource/service/services.go#L57)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Not done?</details>
I've changed it. Maybe you're watching old changes from `r1` not `r3`?

---

*[src/app/frontend/podlist/podcardlist.html, line 17 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-KHPXKndkH2UQjNQA03z:-KHPZDi15iHv3ztrlHXl:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/219a4041f404b76eca5adb8b7f52b1c00dbfb300/src/app/frontend/podlist/podcardlist.html#L17)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Typo here. </details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/726)*

**Comment by floreks** [comment]
huh... conflicts everywhere. Should be fine now. PTAL

**Comment by bryk** [comment]
:lgtm: Looks lovely! 

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> huh... conflicts everywhere. Should be fine now. PTAL</details>


---

Reviewed 9 of 10 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-:-KHPyBJDI3lGU526wo18:-1911552231)*

**Comment by bryk** [comment]
Please merge. 

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> :lgtm: Looks lovely! </details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/726#-:-KHPyDuEfXSosA4TJTBB:-632367591)*

**Pull request merged**
