### PR TITLE
Fix canary YAML descriptor file

### LINKED ISSUE #415: 500 error  when use dashboard
image
image

and the rc.yaml
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: kubedash
  namespace: kube-system
  labels:
    k8s-app: kubernetes-dashboard 
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kubernetes-dashboard
  template:
    metadata:
      labels:
        k8s-app: kubernetes-dashboard
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kubernetes-dashboard
        image: gcr.io/google_containers/kubernetes-dashboard:canary
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 9090
        livenessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 5
```
service:
```
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
  labels:
    k8s-app: kubernetes-dashboard
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    k8s-app: kubernetes-dashboard 
  ports:
  - port: 50071
    targetPort: 9090
  type: LoadBalancer
  externalIPs:
  -  10.4.5.62
```

### PR DESCRIPTION
**Pull request by bryk**
Previously it didn't include amd64 suffix and was named improperly. Now
it is suffixed with -canary.

Fixes #415

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/412)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm Can you review?

**Comment by maciaszczykm** [comment]
@bryk I have got same problem as I've described in #409.

**Comment by maciaszczykm** [comment]
@bryk It works, tested in #409.

**Comment by bryk** [comment]
Yeah, thank you for the review :) Merging.

**Pull request merged**
