### PR TITLE
Add container image validation

### PR DESCRIPTION
**Pull request by f-higashi**
Added container image validation. #422

Please review it.

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/485)

### CODE REVIEW

**Comment by bryk** [comment]
Reviewed 24 of 26 files at r1.
Review status: 24 of 26 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/deploy/deployfromsettings.html, line 60 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/485#-KBwDZaJL1LNo_w0POQ-:-KBwDZaJL1LNo_w0POQ0:1760519000) ([raw file](https://github.com/kubernetes/dashboard/blob/93e011eae56cdfe5c4ef1e9a2986740116780415/src/app/frontend/deploy/deployfromsettings.html#L60)):*
Can you maybe include the reason here? 

---

*[src/app/frontend/deploy/validimagereference_directive.js, line 26 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/485#-KBwEGoh63hrm1q31B9t:-KBwEGoh63hrm1q31B9u:-278818523) ([raw file](https://github.com/kubernetes/dashboard/blob/93e011eae56cdfe5c4ef1e9a2986740116780415/src/app/frontend/deploy/validimagereference_directive.js#L26)):*
We need tests for this file. See uniquename_directive_test how to do this. Aim for 100% incremental coverage. 

---

*[src/app/frontend/deploy/validimagereference_directive.js, line 64 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/485#-KBwDlQhU60_5zM2m-m9:-KBwDlQhU60_5zM2m-mA:1532752163) ([raw file](https://github.com/kubernetes/dashboard/blob/93e011eae56cdfe5c4ef1e9a2986740116780415/src/app/frontend/deploy/validimagereference_directive.js#L64)):*
Should we assume it is valid? This is what we do with name validation. Check out how it is done and documented there.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/485)*

**Comment by bryk** [comment]
PTAL. All we need is more tests and one style comment.

---

Review status: 24 of 26 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/485#-:-KBwENGD5g1VaA8qZbET:-289564526)*

**Comment by f-higashi** [comment]
Review status: 24 of 28 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/deploy/deployfromsettings.html, line 60 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/485#-KBwDZaJL1LNo_w0POQ-:-KC00bX4b4xLE-9YgvxH:715205957) ([raw file](https://github.com/kubernetes/dashboard/blob/93e011eae56cdfe5c4ef1e9a2986740116780415/src/app/frontend/deploy/deployfromsettings.html#L60)):*
I added server response message.

---

*[src/app/frontend/deploy/validimagereference_directive.js, line 26 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/485#-KBwEGoh63hrm1q31B9t:-KC-xHj5AKjnb6VNd2vJ:329715659) ([raw file](https://github.com/kubernetes/dashboard/blob/93e011eae56cdfe5c4ef1e9a2986740116780415/src/app/frontend/deploy/validimagereference_directive.js#L26)):*
I added test for validimagereference.

---

*[src/app/frontend/deploy/validimagereference_directive.js, line 64 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/485#-KBwDlQhU60_5zM2m-m9:-KC-vQrvIy1TYjRuN-pr:1356583034) ([raw file](https://github.com/kubernetes/dashboard/blob/93e011eae56cdfe5c4ef1e9a2986740116780415/src/app/frontend/deploy/validimagereference_directive.js#L64)):*
It has no problem as a result of my check.

Resource action methods can be invoked with the following paramters:
  ```
  non-GET "class" actions: Resource.action([parameters], postData, [success], [error])
  ```
 https://code.angularjs.org/1.5.0/docs/api/ngResource/service/$resource

In this case, spec, '(validty)=>', and '()=>' are coressponding to postData, success callback, and error callback respectively.
And name validation code does not use err response. so err arugment is omitted.

But in this modifiction, I added err arugment to show server error message.


Does that answer your comment?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/485)*

**Comment by f-higashi** [comment]
PTAL

**Comment by bryk** [comment]
Last comments and PTAL. I'm very happy about the tests.

---

Reviewed 1 of 4 files at r2.
Review status: 25 of 28 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kubernetes/dashboard/485#-KC0Fe8UIjwHxCmES2Y5:-KC0Fe8Vs80lFrH696Gu:1830636066) (no related file):*
When I test this on my machine, there is huge jitter when entering, e.g, 'asdsadlas;'dl'sa;ld;;;;;;;;;' and then deleting it char by char. Can you add ng-model-options with debounce, the same as in name validation?

---

*[src/app/frontend/deploy/validimagereference_directive.js, line 26 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/485#-KBwEGoh63hrm1q31B9t:-KC0F0_iS29Fe--aCY2S:-1834867277) ([raw file](https://github.com/kubernetes/dashboard/blob/93e011eae56cdfe5c4ef1e9a2986740116780415/src/app/frontend/deploy/validimagereference_directive.js#L26)):*
Thanks!

---

*[src/app/frontend/deploy/validimagereference_directive.js, line 64 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/485#-KBwDlQhU60_5zM2m-m9:-KC0GqdS7771ox0PDrSh:-480046892) ([raw file](https://github.com/kubernetes/dashboard/blob/93e011eae56cdfe5c4ef1e9a2986740116780415/src/app/frontend/deploy/validimagereference_directive.js#L64)):*
Yes. 

---

*[src/app/frontend/deploy/validimagereference_directive.js, line 18 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/485#-KC0G8jyRb-e4S7RS-ya:-KC0G8jzqDdiKHLQKXGV:-128487988) ([raw file](https://github.com/kubernetes/dashboard/blob/a0740998176a770521394a534bfbaa94bbc982c1/src/app/frontend/deploy/validimagereference_directive.js#L18)):*
Hmm... This seems very generic. How about `invalidImageErrorMessage`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/485#-:-KC0Gn3doQuhkGHJPqyO:-1159268809)*

**Comment by f-higashi** [comment]
Review status: 24 of 28 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kubernetes/dashboard/485#-KC0Fe8UIjwHxCmES2Y5:-KC0OTAI4KoFBeVPUHqy:2098847762) (no related file):*
Thank you for your comment.
I set ng-model-options.

---

*[src/app/frontend/deploy/validimagereference_directive.js, line 18 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/485#-KC0G8jyRb-e4S7RS-ya:-KC0ODzODSoCMLRPKbIE:1223364544) ([raw file](https://github.com/kubernetes/dashboard/blob/a0740998176a770521394a534bfbaa94bbc982c1/src/app/frontend/deploy/validimagereference_directive.js#L18)):*
It's good.
I modified it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/485)*

**Comment by bryk** [comment]
Thank you for this. :lgtm: Merging :) 

---

Reviewed 1 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/485#-:-KC0_FMNw0imc7vDHJSh:-1552576779)*

**Comment by floreks** [comment]
@bryk @f-higashi this PR causes integration test `deploy not existing image` to fail.

**Comment by bryk** [comment]
Oh, is this really this one? Do you know the reason why is that?

**Comment by floreks** [comment]
Async validation of container image blocks deploy of not existing image `test`.

**Comment by f-higashi** [comment]
Async validation does not check whether image is existing or not in repository.

Which environment did tests fail?
If it is travis environment, can you tell me build id?

**Comment by floreks** [comment]
I'll once it's finished on my local repo. It wasn't clear before because deploy from file test was failing and all other test also because of that. Now it is disabled and it will fail on master.

**Comment by f-higashi** [comment]
Hmm..
I cannot reproduce it in my local machine.

This PR updated backend api.
So I needed 'gulp clean' after that under development.
Please  execute 'gulp clean' and try it once.

**Comment by floreks** [comment]
I'm always executing `gulp clean && gulp serve` on restart. Problem was elsewhere. Stopping serve does not kill backend and I've had multiple stale dashboard processes running in background. After killing them local tests have passed. Still there are some random fails of tests but probably not related to this.

**Comment by f-higashi** [comment]
Okay
Thanks for your investigation.

**Pull request merged**
