### PR TITLE
Japanese localization of DeployPage(#904) and NodePage(#930)

### PR DESCRIPTION
**Pull request by Yamagami-Takuma**
Japanese localization of #904 and #930

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/935)

### CODE REVIEW

**Comment by Yamagami-Takuma** [comment]
@f-higashi Can you review?

**Comment by f-higashi** [comment]
:lgtm_strong: 

@maciaszczykm 
you can merge this :)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/935#-:-KKpoVs2DtwB50Aqiuwu:484567563)*

**Comment by floreks** [comment]
Travis failed. Looks like stale build. I've restarted it and will merge once it passes.

**Comment by floreks** [comment]
Needs rebase

**Comment by Yamagami-Takuma** [comment]
Rebased.

**Pull request merged**
