### PR TITLE
Make chrome nav and breadcrumbs updade on navigation start

### PR DESCRIPTION
**Pull request by bryk**
Previously menu wont update until the spinner finished

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1160)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm Can you review?

**Comment by maciaszczykm** [comment]
I'll do it tommorow morning.

**Comment by maciaszczykm** [comment]
:lgtm: 

One thing, that can be updated (not exactly related to this pull request) is empty log card:



Can we display zerostate message if there are no logs?

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1160#-:-KQPW1ytuznwiRJTvLgz:bmo7h23)*

**Comment by bryk** [comment]
Spawned new issue.

**Comment by bryk** [comment]
Will merge soon.

**Comment by bryk** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1160)*

**Comment by bryk** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1160)*

**Pull request merged**
