### PR TITLE
Increase items per page in list views

### PR DESCRIPTION
**Pull request by woopstar**
Using the dashboard for quite a while now and it has become very annoying that the list views are only showing 10 items per page. I think we should increase the default.

If someone is able to, it would be even more awesome if you could have a drop down selector for each list view and change between some default values like 10, 20, 30, 40, 50, 100 etc.

### CODE REVIEW

**Comment by floreks** [comment]
We could probably increase it to 15 but IMO 30 is too much. Workloads page could get overloaded with so many objects. Currently we have 7 resources x 30 items per resource would give us 210 resources on single page.

@maciaszczykm WDYT?

**Comment by maciaszczykm** [comment]
@floreks I agree, we can switch to 15, but 30 is too much.

**Comment by maciaszczykm** [comment]
Also you need to sign the CLA.

**Comment by floreks** [comment]
@woopstar could you address our comments?

**Comment by woopstar** [comment]
Sorry. I will get the CLA signed and edit the pull request to be 15 items. I am just very busy at work, so will do it a bit later today.

**Comment by maciaszczykm** [comment]
@woopstar Will you be able to push it forward?

**Comment by bryk** [comment]
Yep, +1 :)

**Comment by maciaszczykm** [comment]
I have created pull request with requested changes, because CLA is missing here and there is no progress since a month.

**Comment by woopstar** [comment]
I have signed the CLA. What to do?

**Comment by maciaszczykm** [comment]
Sometimes it takes time to accept it, let's wait few minutes. Also, you need to change 30 to 15.

**Comment by woopstar** [comment]
Hmm. Now it says I have to sign the document, but when I go to the document from the e-mail, it says 404.

**Comment by woopstar** [comment]
Got it signed now at HelloSign. Lets see when the bot picks it up

**Pull request merged**
