### PR TITLE
New look and feel for the application

### LINKED ISSUE #832: Add action bar to all resource detail views

### PR DESCRIPTION
**Pull request by bryk**
* Made everything more compact
* Used bottons for actions in action bar
* Action bar is now unified across views

Fixes #832, 

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/863)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks @maciaszczykm Can you review?

**Comment by floreks** [comment]
Icons Edit/Delete feel a bit too big compared to the text. How about scaling them a bit or at least make text centered compared to the icon.

<details><summary><i>Previously, codecov-io wrote…</i></summary>
> ## [Current coverage][cc-pull] is **93.31%**
> > Merging [#863][cc-pull] into [master][cc-base-branch] will decrease coverage by **0.36%**
> 
> 1. 2 files (not in diff) in `src/app/frontend` were modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/4139df8807c16044bcee790a3cb9f99f1b128f94/changes?src=pr#7372632F6170702F66726F6E74656E64) 
>   - Misses `-3` 
>   - Hits `+3`
> 1. File `...buttons_component.js` was modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/4139df8807c16044bcee790a3cb9f99f1b128f94/changes?src=pr#7372632F6170702F66726F6E74656E642F636F6D6D6F6E2F636F6D706F6E656E74732F616374696F6E6261722F616374696F6E6261726C697374627574746F6E735F636F6D706F6E656E742E6A73) 
>   - Misses `+2` 
>   - Partials `0` 
>   - Hits `-2`
> 
> ```diff
> @@             master       #863   diff @@
> ==========================================
>   Files           225        218     -7   
>   Lines          1867       1839    -28   
>   Methods           0          0          
>   Messages          0          0          
>   Branches          0          0          
> ==========================================
> - Hits           1749       1716    -33   
> - Misses          118        123     +5   
>   Partials          0          0          
> ```
> 
> > Powered by [Codecov](https://codecov.io?src=pr). Last updated by [374385a...4139df8][cc-compare]
> [cc-base-branch]: https://codecov.io/gh/kubernetes/dashboard/branch/master?src=pr
> [cc-compare]: https://codecov.io/gh/kubernetes/dashboard/compare/374385ae748d743c65b92cf74605de80500dcbd9...4139df8807c16044bcee790a3cb9f99f1b128f94
> [cc-pull]: https://codecov.io/gh/kubernetes/dashboard/pull/863?src=pr
</details>


---

Review status: 0 of 89 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/common/components/contentcard/contentcard.scss, line 23 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/863#-KJoWHk4t6Mr_W_-Dfb_:-KJoWHk4t6Mr_W_-Dfba:-1989928038) ([raw file](https://github.com/kubernetes/dashboard/blob/4139df8807c16044bcee790a3cb9f99f1b128f94/src/app/frontend/common/components/contentcard/contentcard.scss#L23)):*
> ```SCSS
> 
> .kd-content-card {
>   padding-bottom: 1 * $baseline-grid;
> ```

Just `$baseline-grid` is fine :)

---

*[src/app/frontend/events/eventcardlist.scss, line 22 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/863#-KJoWZMDoPyIqubGzhl4:-KJoWZMDoPyIqubGzhl5:1689108809) ([raw file](https://github.com/kubernetes/dashboard/blob/4139df8807c16044bcee790a3cb9f99f1b128f94/src/app/frontend/events/eventcardlist.scss#L22)):*
> ```SCSS
> 
> .kd-replicationcontrollerevents-no-events {
>   margin: (4 * $baseline-grid) 0 (4 * $baseline-grid);
> ```

Due to changes in content card bottom margin is now not applied on events page where there are no events.


How about adding small padding on the bottom so that the text does not touch end of content card?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/863#-:-KJoXAIVHpon2eVYBDbn:557292577)*

**Comment by bryk** [comment]
PTAL. I've fixed issues and added more tests. 

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> 
> 
> Icons Edit/Delete feel a bit too big compared to the text. How about scaling them a bit or at least make text centered compared to the icon.
> 
</details>


---

Review status: 0 of 91 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/common/components/contentcard/contentcard.scss, line 23 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/863#-KJoWHk4t6Mr_W_-Dfb_:-KJozUPkKmBSFA_-PbHe:320492446) ([raw file](https://github.com/kubernetes/dashboard/blob/4139df8807c16044bcee790a3cb9f99f1b128f94/src/app/frontend/common/components/contentcard/contentcard.scss#L23)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Just `$baseline-grid` is fine :)
</details>
Yeah... Done. 

---

*[src/app/frontend/events/eventcardlist.scss, line 22 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/863#-KJoWZMDoPyIqubGzhl4:-KJozb3wCoPIeAL3Do1K:-2025663247) ([raw file](https://github.com/kubernetes/dashboard/blob/4139df8807c16044bcee790a3cb9f99f1b128f94/src/app/frontend/events/eventcardlist.scss#L22)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Due to changes in content card bottom margin is now not applied on events page where there are no events.
> 
> 
> How about adding small padding on the bottom so that the text does not touch end of content card?
</details>
Yeah, definitely. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/863#-:-KJpCZmd3YR01tBIvG6P:1670485566)*

**Comment by floreks** [comment]
Could you remove top padding from `resourcecardlistfooter.scss`? Paging will fit new look better.

**Comment by bryk** [comment]
Done. PTAL

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Could you remove top padding from `resourcecardlistfooter.scss`? Paging will fit new look better.
</details>


---

Review status: 0 of 92 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/863#-:-KJpODWVNt1Wn3_TuFhC:-1437751608)*

**Comment by floreks** [comment]
Perfect. :lgtm:. Let's wait for travis and we can merge.

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Done. PTAL
</details>


---

Review status: 0 of 92 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/863#-:-KJpPTt-AK8lVq8hC4WW:-266061283)*

**Pull request merged**
