### PR TITLE
Update breadcrumbs to show last 3 states for entire app

### PR DESCRIPTION
**Pull request by bryk**
Re #1268 

Demo: 
image

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you review this?

**Comment by floreks** [comment]
Code LGTM, however I am not able to test it today. @maciaszczykm could you test and confirm everything works as expected?

**Comment by maciaszczykm** [comment]
I'll test now.

**Comment by bryk** [comment]
> Persistent Volume Claims aren't listed under Storage, but Storage remains to be implemented.

Yes, correct.

**Pull request merged**
