### PR TITLE
Container details and envvars in pod details view

### PR DESCRIPTION
**Pull request by bryk**
EnvVars also link to config maps if a value comes from there.

Samples:
selection_093

selection_094

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1038)

### CODE REVIEW

**Comment by floreks** [comment]
One question, otherwise :lgtm: Will test now.

---

Reviewed 15 of 17 files at r1.
Review status: 15 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/backend/resource/pod/podcommon.go, line 48 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1038#-KMxtu3hVHQQRaN2oDdr:-KMxtu3i4btjAJSJDSIv:384701480) ([raw file](https://github.com/kubernetes/dashboard/blob/d1ae344a09912e96c4ad2ef2adf605969c6057a0/src/app/backend/resource/pod/podcommon.go#L48)):*
> ```Go
> }
> 
> func ToPodDetail(pod *api.Pod, metrics *MetricsByPod) PodDetail {
> ```

Why did you delete that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1038#-:-KMxw2hWC9sVRdDMP08j:1333913735)*

**Comment by bryk** [comment]
Review status: 15 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/backend/resource/pod/podcommon.go, line 48 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1038#-KMxtu3hVHQQRaN2oDdr:-KMy1n92sgc9FmoFVnFh:1418106204) ([raw file](https://github.com/kubernetes/dashboard/blob/d1ae344a09912e96c4ad2ef2adf605969c6057a0/src/app/backend/resource/pod/podcommon.go#L48)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Why did you delete that?
</details>
Now we talk to the api server to get configmaps to parse env vars. With that ToPodDetail would not be a standalone function anymore. So I decided to do this in just one function and test it. This was easier to implement, as there is no passing around of errors and clients. 

What do you think? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1038)*

**Comment by floreks** [comment]
Review status: 15 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/backend/resource/pod/podcommon.go, line 48 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1038#-KMxtu3hVHQQRaN2oDdr:-KMy6PHjiXgueqf35Mzs:-1126869406) ([raw file](https://github.com/kubernetes/dashboard/blob/d1ae344a09912e96c4ad2ef2adf605969c6057a0/src/app/backend/resource/pod/podcommon.go#L48)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Now we talk to the api server to get configmaps to parse env vars. With that ToPodDetail would not be a standalone function anymore. So I decided to do this in just one function and test it. This was easier to implement, as there is no passing around of errors and clients. 
> 
> What do you think? 
</details>
hmm... This could still be a standalone function. Similar to [this](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/replicationcontroller/replicationcontrollerdetail.go#L64) one. Get all data and then pass them to be combined somewhere else. Container parsing would go to `getPodContainers` and then all data would go to `ToPodDetail` to be combined into our `PodDetail` structure.

The reason why I prefer this way is that now `GetPodDetail` function is responsible for getting the data, parsing and converting into our structure, and it's easier to manage and refactor if responsibilities are separated.

What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1038)*

**Comment by bryk** [comment]
Review status: 15 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/backend/resource/pod/podcommon.go, line 48 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1038#-KMxtu3hVHQQRaN2oDdr:-KN0miY9RtocQSbstkNP:-1533935844) ([raw file](https://github.com/kubernetes/dashboard/blob/d1ae344a09912e96c4ad2ef2adf605969c6057a0/src/app/backend/resource/pod/podcommon.go#L48)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> hmm... This could still be a standalone function. Similar to [this](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/replicationcontroller/replicationcontrollerdetail.go#L64) one. Get all data and then pass them to be combined somewhere else. Container parsing would go to `getPodContainers` and then all data would go to `ToPodDetail` to be combined into our `PodDetail` structure.
> 
> The reason why I prefer this way is that now `GetPodDetail` function is responsible for getting the data, parsing and converting into our structure, and it's easier to manage and refactor if responsibilities are separated.
> 
> What do you think?
</details>
Yeah, so this was my initial idea. But then I realized that a pod rarely uses config maps for env vars, so this was an optimization to get only config maps that are used, instead of getting all config maps and in vast majority of cases using none. 

Is this a fair assumption? Can we maybe chat on slack? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1038)*

**Comment by bryk** [comment]
*[src/app/backend/resource/pod/podcommon.go, line 48 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1038#-KMxtu3hVHQQRaN2oDdr:-KN0nJSyWeaVWVtdPzsR:-1930886122) ([raw file](https://github.com/kubernetes/dashboard/blob/d1ae344a09912e96c4ad2ef2adf605969c6057a0/src/app/backend/resource/pod/podcommon.go#L48)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Yeah, so this was my initial idea. But then I realized that a pod rarely uses config maps for env vars, so this was an optimization to get only config maps that are used, instead of getting all config maps and in vast majority of cases using none. 
> 
> Is this a fair assumption? Can we maybe chat on slack? 
</details>
But yeah, I see that other pages get all resources, despite using a few of them. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1038)*

**Comment by bryk** [comment]
@floreks PTAL. I've converted all to resource channels, this is a big change. 

---

Review status: 12 of 21 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1038#-:-KN2NDovXZVmey6izgn2:-1061722354)*

**Comment by bryk** [comment]
Ping?

**Comment by floreks** [comment]
Reviewed 7 of 11 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1038)*

**Comment by floreks** [comment]
I've checked that already but forgot to comment. :) LGTM.

**Pull request merged**
