### PR TITLE
Bugfix #762 - nullpointer dereference at RS / Deployments lists

### PR DESCRIPTION
**Pull request by taimir**
see https://github.com/kubernetes/dashboard/issues/762

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/764)

### CODE REVIEW

**Comment by taimir** [comment]
@bryk PTAL

**Comment by bryk** [comment]
:lgtm: Awesome, thanks! 

<details><summary><i>Previously, codecov-io wrote…</i></summary>
> ## [Current coverage][cc-pull] is **95.22%**
> > Merging [#764][cc-pull] into [master][cc-base-branch] will increase coverage by **0.43%**
> 
> 1. File `...ereader_directive.js` (not in diff) was modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/36de9979b9365a3f7c850c2dcf24bbedca415eaa/changes?src=pr#7372632F6170702F66726F6E74656E642F6465706C6F792F66696C657265616465725F6469726563746976652E6A73) 
>   - Misses `-6` 
>   - Partials `0` 
>   - Hits `+6`
> 
> ```diff
> @@             master       #764   diff @@
> ==========================================
>   Files           175        175          
>   Lines          1360       1360          
>   Methods           0          0          
>   Messages          0          0          
>   Branches          0          0          
> ==========================================
> + Hits           1289       1295     +6   
> + Misses           71         65     -6   
>   Partials          0          0          
> ```
> 
> > Powered by [Codecov](https://codecov.io?src=pr). Last updated by [9a40438...36de997][cc-compare]
> [cc-base-branch]: https://codecov.io/gh/kubernetes/dashboard/branch/master?src=pr
> [cc-compare]: https://codecov.io/gh/kubernetes/dashboard/compare/9a404388f590a6f67288b4c8dc68aa40864c57bb...36de9979b9365a3f7c850c2dcf24bbedca415eaa
> [cc-pull]: https://codecov.io/gh/kubernetes/dashboard/pull/764?src=pr
</details>


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/764#-:-KISMrhsPM7fjzVspZCf:12164880)*

**Comment by bryk** [comment]
Travis tests have problems. Please fix

**Comment by taimir** [comment]
Yes, just doing that - I have to update the tests as well.

**Comment by taimir** [comment]
OK, tests are fine now :)

**Comment by bryk** [comment]
Thanks again! :) 

<details><summary><i>Previously, taimir (Atanas Mirchev) wrote…</i></summary>
> OK, tests are fine now :)
</details>


---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/764#-:-KISdtPVgjznq0xS25Hp:-928085468)*

**Pull request merged**
