### PR TITLE
Small layout fix for IE11

### PR DESCRIPTION
**Pull request by taimir**
As a follow-up of issue https://github.com/kubernetes/dashboard/issues/483

@floreks can you confirm this resolves it?

[Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/488)

### CODE REVIEW

**Comment by floreks** [comment]
Partially. Now it looks good on small screen but has some problems on bigger screen.

image

**Comment by taimir** [comment]
Ok, let me see ...

**Comment by taimir** [comment]
OK, I don't see a clear solution to this right now - IE11 shrinks `flex-basis` of children which are wrapped to 0 after the wrap takes place, even though I have specified it to be 1 explicitly. When the `flex-basis` is `auto` (of the children in the help section), we see the behaviour in the pic above: when things are wrapped they look fine, but not when in a bigger window.

**Comment by taimir** [comment]
@floreks I couldn't do it without forcing a `width: 100%` style. I know we try to avoid this, but here I do not see another solution. Can you check it now?

**Comment by floreks** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/deploy/helpsection/helpsection.scss, line 23 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/488#-KBwoEVjzfw53VgL52gK:-KBwoEVjzfw53VgL52gL:-947251157) ([raw file](https://github.com/kubernetes/dashboard/blob/3eee1f3bb887151d230027a60d9e804f46bc82b3/src/app/frontend/deploy/helpsection/helpsection.scss#L23)):*
I'd say that width 100% is not that bad and this may be our only option. IE has major problems with flexbox and proper calculation of elements size.

It looks good on all browsers now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/488#-:-KBwoFf-MrRUJfwWsjxS:980077423)*

**Comment by taimir** [comment]
@bryk PTAL

**Comment by bryk** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/488#-:-KBwu3Rn0F3diJIE8aPr:980077423)*

**Pull request merged**
