### PR TITLE
Japanese localization of PetSetDetail and breadcrumbs

### PR DESCRIPTION
**Pull request by Yamagami-Takuma**
Japanese localization of PetSetDetail and breadcrumbs.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/898)

### CODE REVIEW

**Comment by Yamagami-Takuma** [comment]
@f-higashi Can you review?

**Comment by f-higashi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[i18n/messages-ja.xtb, line 383 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/898#-KKBkF5qLRFLWxEEJkHm:-KKBkF5rKJJ0Xf9Xpyin:164909501) ([raw file](https://github.com/kubernetes/dashboard/blob/04fc22af6996fd3a8f3645b58190c826fc77a9da/i18n/messages-ja.xtb#L383)):*
> ```
> 	<translation id="1744394420157932960" key="MSG_BREADCRUMBS_DEPLOYMENTS_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label 'Deployments' that appears as a breadcrumbs on the action bar.">デプロイメント</translation>
> 	<translation id="7227892582140926602" key="MSG_DEPLOYMENT_DETAIL_MIN_READY_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label 'Min Ready Seconds' for the deployment on the deployment details page.">最小準備時間（秒）</translation>
> 	<translation id="7635451132574422294" key="MSG_DEPLOYMENT_DETAIL_REVISION_HISTORY_LABEL" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label for the deployment property on the deployment details page.">修正履歴制限</translation>
> ```

I cannot understand this japanese word.
How about `改版履歴上限数`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/898)*

**Comment by Yamagami-Takuma** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[i18n/messages-ja.xtb, line 383 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/898#-KKBkF5qLRFLWxEEJkHm:-KKBoMaXMnHJvmKBr4Bp:-1943745741) ([raw file](https://github.com/kubernetes/dashboard/blob/04fc22af6996fd3a8f3645b58190c826fc77a9da/i18n/messages-ja.xtb#L383)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> I cannot understand this japanese word.
> How about `改版履歴上限数`
</details>
It looks nice.
However it is a little hard to read because of continuously kanji.
So I inserted hiragana `の` between them, and deleted `数`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/898)*

**Comment by f-higashi** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[i18n/messages-ja.xtb, line 383 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/898#-KKBkF5qLRFLWxEEJkHm:-KKCCQhqu2Xp7RKaMg6O:1739129486) ([raw file](https://github.com/kubernetes/dashboard/blob/04fc22af6996fd3a8f3645b58190c826fc77a9da/i18n/messages-ja.xtb#L383)):*
<details><summary><i>Previously, Yamagami-Takuma wrote…</i></summary>
> It looks nice.
> However it is a little hard to read because of continuously kanji.
> So I inserted hiragana `の` between them, and deleted `数`.
</details>
Looks good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/898#-:-KKCCUOu8AikuS03lGZ5:980077401)*

**Comment by f-higashi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/898)*

**Pull request merged**
