### PR TITLE
Set QPS/Burst client defaults and modernise channels API

### PR DESCRIPTION
**Pull request by bryk**
The api modernization is to allow for testing.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/673)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you review?

**Comment by maciaszczykm** [comment]
Can we wait with this after I'll finish repackaging? If not, then please wait with further changes and I'll try to merge it with my changes. It can get hard to maintain...

**Comment by bryk** [comment]
@maciaszczykm You can review this and I'll submit this ASAP. Sounds good? This is mostly refactoring, so should be easy to merge.

**Comment by floreks** [comment]
Sure. I'll do it soon.

**Comment by bryk** [comment]
@maciaszczykm You can also send the repackaging PR. I'm fine with rebasing this, as long as it is done quickly :) I'll let you decide.

**Comment by floreks** [comment]
Great change. Just some minor typo. :lgtm_strong:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/backend/apiserverclient.go, line 27 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/673#-KGC_4pfDt5XlcHPrGUM:-KGC_4pfDt5XlcHPrGUN:-590660467) ([raw file](https://github.com/kubernetes/dashboard/blob/e81c4ebb497112cccf067692991fe9ed3182c3b7/src/app/backend/apiserverclient.go#L27)):*
typo, `enough`

---

*[src/app/backend/apiserverclient.go, line 29 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/673#-KGC_sFV-_YM5KGZMBQz:-KGC_sFV-_YM5KGZMBR-:1368799997) ([raw file](https://github.com/kubernetes/dashboard/blob/e81c4ebb497112cccf067692991fe9ed3182c3b7/src/app/backend/apiserverclient.go#L29)):*
Perfect! Thanks to this there is no more request throttling.

---

*[src/app/backend/apiserverclient.go, line 30 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/673#-KGC_9txJrhsp3Cm4_kB:-KGC_9txJrhsp3Cm4_kC:1854746597) ([raw file](https://github.com/kubernetes/dashboard/blob/e81c4ebb497112cccf067692991fe9ed3182c3b7/src/app/backend/apiserverclient.go#L30)):*
Same here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/673#-:-KGCarW_lM9XfpjsiYxx:1037286847)*

**Comment by maciaszczykm** [comment]
Okay, so let's merge this and refactoring will be next.

**Comment by bryk** [comment]
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/backend/apiserverclient.go, line 27 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/673#-KGC_4pfDt5XlcHPrGUM:-KGCguWSopePQpjWHz41:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/e81c4ebb497112cccf067692991fe9ed3182c3b7/src/app/backend/apiserverclient.go#L27)):*
Done.

---

*[src/app/backend/apiserverclient.go, line 29 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/673#-KGC_sFV-_YM5KGZMBQz:-KGCgwWYiufcGs6fA9ae:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/e81c4ebb497112cccf067692991fe9ed3182c3b7/src/app/backend/apiserverclient.go#L29)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/673)*

**Comment by bryk** [comment]
All done. Will merge soon.

**Pull request merged**
