### PR TITLE
Content card component skeleton

### PR DESCRIPTION
**Pull request by bryk**
It can be used on pages to display stuff.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/682)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you review?

**Comment by bryk** [comment]
selection_068

**Comment by floreks** [comment]
That's what I needed. :lgtm: 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/682#-:-KGMOK4_n_PCSgl6NPiR:2002125954)*

**Comment by floreks** [comment]
By the way. Shouldn't we have shadow between title and content? Some visual separation.

**Comment by bryk** [comment]
> By the way. Shouldn't we have shadow between title and content? Some visual separation.

Let's iterate on this. This is not final design. Just a common component that we can all use.

**Pull request merged**
