### PR TITLE
Localization of PetSetDetail and -List (additional)

### PR DESCRIPTION
**Pull request by taimir**
There were some leftover strings hiding in between the html tags. Had to seek them out and localize them :)
@floreks can you rev this?

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/858)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Please review.

**Comment by floreks** [comment]
Sure.

**Comment by floreks** [comment]
Great. :lgtm:. Rebase and I'll merge.

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Sure.
</details>


---

Reviewed 10 of 12 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/858#-:-KJo-_m-dUJm8I8oW30d:418908555)*

**Comment by taimir** [comment]
Done.

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Great. :lgtm:. Rebase and I'll merge.
</details>


---

Review status: 10 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/858#-:-KJo9pOrB6lkYOsVNZvx:-499146009)*

**Comment by bryk** [comment]
Please rebase and we can merge

**Comment by bryk** [comment]
Btw, we have a problem with continous conflitcs in the xtb files. This is because (I think) that every message is added to the end. Any ideas how to improve this?

**Comment by taimir** [comment]
The conflicts happen only when there are newly extracted messages on the upstream repo, and the dev has extracted some messages himself (which then go to the same place in the file the ones from the upstream went). Ahm, I don't think there's a way to fix this other than maybe trying to not have all messages in a single .xtb file, in an attempt to reduce the chance of this happening. Not sure if this is feasible at all, I'll have to investigate.

**Comment by bryk** [comment]
Still conflicts... :/

**Comment by taimir** [comment]
PTAL

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Still conflicts... :/ 
</details>


---

Review status: 6 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/replicasetlist/replicasetlistactionbar_controller.js, line 0 \[r5\]](https://reviewable.io:443/reviews/kubernetes/dashboard/858#-KK7uzgIQQDUlDe0x2VJ:-KK7uzgIQQDUlDe0x2VK:-2063249776) ([raw file](https://github.com/kubernetes/dashboard/blob/a9d40ae698f178150ccf0cd28566eb7618794cda/src/app/frontend/replicasetlist/replicasetlistactionbar_controller.js#L0)):*
Seems like this file was a leftover from before (it was not imported anywhere).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/858#-:-KK7v3sz9N7ThYDfRDAC:676965300)*

**Comment by floreks** [comment]
No conflicts yay :) We can merge.

**Pull request merged**
