### PR TITLE
Scope current API as v1 API.

### PR DESCRIPTION
**Pull request by bryk**
This is in preparation for release. After we do this, incompatible
changes to the api will be forbidden.

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you take a look?

**Comment by floreks** [comment]
LGTM

**Comment by bryk** [comment]
Travis is down. Merging without it.

**Comment by joeatwork** [comment]
Ah! I'm a bit late for this - I was hoping to get metrics as time series in before the API freeze.

**Comment by bryk** [comment]
Don't worry. This is presentation layer API. We scoped it with v1 to avoid future conflicts. We plan to increment api versions fast and often - whenever this is needed. Just think of it as a way to make sure the UI works during a rolling update.

**Comment by bryk** [comment]
Just let me know if you need any help :)

**Comment by joeatwork** [comment]
Thanks! I'll ask questions as they come up, and I'll make sure not to break any existing APIs.

**Pull request merged**
