### PR TITLE
Modernized RC list page

### PR DESCRIPTION
**Pull request by bryk**
What I did here:
* I copied old RC list code
* Changed all directives to angular 1.5 components
* Removed custom CSS styles
* Added missing tests

What is missing:
* Zerostate page
* responsiveness (this is a problem of the common component)
* Documentation

selection_071

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/686)

### CODE REVIEW

**Comment by bryk** [comment]
@floreks Can you review? I know this is big, but it is 100% tested and is mostly copy & paste & refactor.

**Comment by floreks** [comment]
I'm slowly going through this. :)

**Comment by floreks** [comment]
Looks really nice. I've few comments:


We should utilize labels space. When there are many labels they should be hidden. We've had this check before. I think it was for 5+ labels.


There is a bug connected to middle ellipsis formatting on this page. When we make browser small it will shorten text, but when we maximize if will not refresh until some text with tooltip is hovered or some other action on page is taken. Maybe this is due to one time binding? It works on actionbar.

Error messages are now in containers next to each other. Sometimes it's hard to say when one ends and the other one begins. Bigger padding? Different layout?


Also I'd add some delicate divider between content and footer with errors.

---

Reviewed 21 of 24 files at r1.
Review status: 21 of 24 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/common/components/resourcecard/resourcecardcolumn.scss, line 39 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/686#-KGRB42G-UDGXBldoXFs:-KGRB42HUoaCVmiubB5M:-57693378) ([raw file](https://github.com/kubernetes/dashboard/blob/014905b97fe74b09b941f7829056d8c89b3851a4/src/app/frontend/common/components/resourcecard/resourcecardcolumn.scss#L39)):*
hmm... I'm not seeing any difference without that.

---

*[src/app/frontend/replicationcontrollerlist/podlogsmenu.html, line 17 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/686#-KGR9HgQDT309J0mSJ-D:-KGR9HgQDT309J0mSJ-E:-1108824695) ([raw file](https://github.com/kubernetes/dashboard/blob/014905b97fe74b09b941f7829056d8c89b3851a4/src/app/frontend/replicationcontrollerlist/podlogsmenu.html#L17)):*
I'd add here `md-position-mode="target-right target" md-offset="0 25"`. It looks better when menu opens from the point where we clicked. Same for actions menu.

---

*[src/app/frontend/replicationcontrollerlist/replicationcontrollercard.html, line 22 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/686#-KGRD0QhJpdqXX7n5F-Q:-KGRD0QiCtcspAcUThx1:629908154) ([raw file](https://github.com/kubernetes/dashboard/blob/014905b97fe74b09b941f7829056d8c89b3851a4/src/app/frontend/replicationcontrollerlist/replicationcontrollercard.html#L22)):*
I'd use `md-direction` `top` or `right` here. Currently it exceeds left edge of the browser and beginning of the text is hidden.

Same for second tooltip.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/686#-:-KGRDpV223xoBIbslc1N:1293702729)*

**Comment by bryk** [comment]
> There is a bug connected to middle ellipsis formatting on this page. When we make browser small it will shorten text, but when we maximize if will not refresh until some text with tooltip is hovered or some other action on page is taken. Maybe this is due to one time binding? It works on actionbar.

I know. Should be fixable on middle ellipsis side. I'll log an issue.

> Error messages are now in containers next to each other. Sometimes it's hard to say when one ends and the other one begins. Bigger padding? Different layout?

There is one error message, AFAIK. Are you talking about data columns and the box with errors? 

---

Review status: 21 of 26 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/common/components/resourcecard/resourcecardcolumn.scss, line 39 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/686#-KGRB42G-UDGXBldoXFs:-KGRvDpF-5agXyJ6GAFe:-391764572) ([raw file](https://github.com/kubernetes/dashboard/blob/014905b97fe74b09b941f7829056d8c89b3851a4/src/app/frontend/common/components/resourcecard/resourcecardcolumn.scss#L39)):*
Yeah, this was for larger columns. You'd see the difference if there was only one button in the column. PTAL

---

*[src/app/frontend/replicationcontrollerlist/podlogsmenu.html, line 17 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/686#-KGR9HgQDT309J0mSJ-D:-KGRximtdH49UpO8CF1L:141491342) ([raw file](https://github.com/kubernetes/dashboard/blob/014905b97fe74b09b941f7829056d8c89b3851a4/src/app/frontend/replicationcontrollerlist/podlogsmenu.html#L17)):*
How about  just `md-position-mode="target-right target"`? I'm afraid of adding magic numbers (like 25) to templates. Now it looks sufficiently good, IMO 

---

*[src/app/frontend/replicationcontrollerlist/replicationcontrollercard.html, line 22 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/686#-KGRD0QhJpdqXX7n5F-Q:-KGRyXZmO0AvEMhiQHeE:1748645136) ([raw file](https://github.com/kubernetes/dashboard/blob/014905b97fe74b09b941f7829056d8c89b3851a4/src/app/frontend/replicationcontrollerlist/replicationcontrollercard.html#L22)):*
Used right. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/686#-:-KGRzgrr5ZsENZn6-CfE:-77406621)*

**Comment by bryk** [comment]
Now I see multiple errors. Problem fixed. PTAL


---

Review status: 21 of 26 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/686#-:-KGS19J7-X-2o86yMdup:-2042303851)*

**Comment by floreks** [comment]
Ok looks better now. How about adding some divider or at least some padding between footer and table row?

---

Reviewed 1 of 24 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/common/components/resourcecard/resourcecardcolumn.scss, line 39 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/686#-KGRB42G-UDGXBldoXFs:-KGS12HxwnGiHqkOJFI_:392827855) ([raw file](https://github.com/kubernetes/dashboard/blob/014905b97fe74b09b941f7829056d8c89b3851a4/src/app/frontend/common/components/resourcecard/resourcecardcolumn.scss#L39)):*
Ok. I see. LGTM

---

*[src/app/frontend/replicationcontrollerlist/podlogsmenu.html, line 17 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/686#-KGR9HgQDT309J0mSJ-D:-KGS0utNNB7zPyyu7z_w:1067535829) ([raw file](https://github.com/kubernetes/dashboard/blob/014905b97fe74b09b941f7829056d8c89b3851a4/src/app/frontend/replicationcontrollerlist/podlogsmenu.html#L17)):*
This will also work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/686#-:-KGS1R-Ji0ShVW6Tb0YI:-1000770477)*

**Comment by bryk** [comment]
8px padding. I like it: 


8px padding + 8px margin + delicate line: 


I'm not that fond of the delicate line, because it makes the footer look like a separate row, which it isn't. How about adding the padding? 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/686#-:-KGS2cLcK2gJEayWRr2m:1825231406)*

**Comment by floreks** [comment]
Only padding option looks better. Border line would have to start when the test starts to not indicate that this is new row.

**Comment by floreks** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/replicationcontrollerlist/replicationcontrollercard.html, line 36 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/686#-KGS48NQp8j-L4TewdH5:-KGS48NRM8dMSHktCmyk:-1064352012) ([raw file](https://github.com/kubernetes/dashboard/blob/aef9d8881386adaf9102814f65929b9e627a10ae/src/app/frontend/replicationcontrollerlist/replicationcontrollercard.html#L36)):*
Needs css :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/686)*

**Comment by bryk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/replicationcontrollerlist/replicationcontrollercard.html, line 36 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/686#-KGS48NQp8j-L4TewdH5:-KGW60mDu0ZqkqI4W1g7:-1597990880) ([raw file](https://github.com/kubernetes/dashboard/blob/aef9d8881386adaf9102814f65929b9e627a10ae/src/app/frontend/replicationcontrollerlist/replicationcontrollercard.html#L36)):*
Yeah, artifact from tests. Done by flipping elements.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/686)*

**Comment by bryk** [comment]
PTAL

**Comment by floreks** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r3.
Review status: 24 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/replicationcontrollerlist/replicationcontrollercard.html, line 36 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/686#-KGS48NQp8j-L4TewdH5:-KGW7iVZhSfG0eteCWcL:676926978) ([raw file](https://github.com/kubernetes/dashboard/blob/aef9d8881386adaf9102814f65929b9e627a10ae/src/app/frontend/replicationcontrollerlist/replicationcontrollercard.html#L36)):*
Nice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/686#-:-KGW7m4atrtwyootO82y:1417088721)*

**Comment by bryk** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/686)*

**Pull request merged**
