### PR TITLE
fix styling in dark mode

### PR DESCRIPTION
**Pull request by stritt**
Updated styling of dark theme to be on-brand for Kubernetes. See ticket #3176 for more details.

### CODE REVIEW

**Comment by stritt** [comment]
I signed it

**Comment by maciaszczykm** [comment]
We will take a look later. Thanks!

**Comment by maciaszczykm** [comment]
Can you change base to master and reopen?

**Comment by maciaszczykm** [comment]
@stritt Thanks!

**Comment by floreks** [comment]
Can you revert `package-lock.json` changes? You should use `npm ci` to install dependencies now instead of `npm i`, not to break it.

**Comment by floreks** [comment]
@stritt will you be updating it?

**Comment by jeefy** [comment]
@stritt Do you plan on reverting the package-lock.json changes (See @floreks comment above) and also resolving the `_theming.scss` conflicts?

Thanks! :)

**Comment by maciaszczykm** [comment]
There is a bit too much of overrides and custom styling in comparison to light mode.

**Comment by maciaszczykm** [comment]
To be more precise:
- It is a bit too dark.
- There are new elements like borders in the menu, it is different from light theme.
- Active menu entries are not highlighted anymore.

I'd like to keep it close to Material, not create new overrides.

**Pull request closed without merging**
