### PR TITLE
feat: support networking.k8s.io/Ingresses

### PR DESCRIPTION
**Pull request by rfvermut**
extensions/Ingresses are getting deprecated soon

### CODE REVIEW

**Comment by rfvermut** [comment]
Please verify CLA

**Comment by desaintmartin** [comment]
Thanks!
/assign

**Review by desaintmartin — CHANGES_REQUESTED** [review]
Could you bump minor version of the chart?

**Comment by rfvermut** [comment]
> Could you bump minor version of the chart?

sure. bumped to 4.1.0

**Review by desaintmartin — APPROVED** [review]

**Comment by desaintmartin** [comment]
Hmmm, dear bot, why are you blocking tests?
/ok-to-test

**Pull request merged**
