### PR TITLE
Add namespace column to resource cards

### PR DESCRIPTION
**Pull request by digitalfishpond**
Add namespace column to resource cards when more than one namespace is selected
#1030

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1063)

### CODE REVIEW

**Comment by digitalfishpond** [comment]
Haven't yet added tests, want to check this passes Travis first.

**Comment by digitalfishpond** [comment]
Ok, now working on tests

**Comment by digitalfishpond** [comment]
Tests added. PTAL.

**Comment by digitalfishpond** [comment]
Test coverage 100%, PTAL

**Comment by maciaszczykm** [comment]
@batikanu Can you review?

**Comment by batikanu** [comment]
sure I will take a look

**Comment by batikanu** [comment]
Reviewed 23 of 49 files at r1, 40 of 40 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/frontend/common/namespace/namespace_service.js, line 16 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-KNqGsIs_Wp4EPegw1Tg:-KNqGsItuiOJxhLAdXMZ:-1518599001) ([raw file](https://github.com/kubernetes/dashboard/blob/c331814a61dce17a93be6009b2fa89dfbdd4ec50/src/app/frontend/common/namespace/namespace_service.js#L16)):*
> ```JavaScript
> 
> /**
>  * Service class for registering namespace .
> ```

Extremely tiny thing, no space needed before dot :)

---

*[src/app/frontend/common/namespace/namespace_service.js, line 29 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-KNqOflzuGPt_At6Zqpa:-KNqOfm-3kNP5KQgONkA:1778744238) ([raw file](https://github.com/kubernetes/dashboard/blob/c331814a61dce17a93be6009b2fa89dfbdd4ec50/src/app/frontend/common/namespace/namespace_service.js#L29)):*
> ```JavaScript
> 
>   /**
>      * Getter for multipleNamespacesSelected_ flag.
> ```

@export ?

---

*[src/app/frontend/common/namespace/namespace_service.js, line 35 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-KNqOkba9vQSutSwOd-S:-KNqOkba9vQSutSwOd-T:1778744238) ([raw file](https://github.com/kubernetes/dashboard/blob/c331814a61dce17a93be6009b2fa89dfbdd4ec50/src/app/frontend/common/namespace/namespace_service.js#L35)):*
> ```JavaScript
> 
>   /**
>    * Switches the multipleNamespacesSelected flag.
> ```

@export ?

---

*[src/app/frontend/common/namespace/namespace_service.js, line 38 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-KNqIX3gDLfX1sUYsiSN:-KNqIX3hWq3YUarVSjej:-1095966316) ([raw file](https://github.com/kubernetes/dashboard/blob/c331814a61dce17a93be6009b2fa89dfbdd4ec50/src/app/frontend/common/namespace/namespace_service.js#L38)):*
> ```JavaScript
>    * @param {boolean} multipleSelected
>    */
>   setMultipleNamespacesSelected(multipleSelected) {
> ```

I would prefer something like below rather than having value as a service which has only getter and setter methods parameterized with direct value from outside.   

selectMultipleNamespaces() {
 this.multipleNamespacesSelected_ = true;
}
deselectMultipleNamespaces() {
  this.multipleNamespacesSelected_ = false;
}
isMultipleNamespacesSelected() { return this.multipleNamespacesSelected_; }

In this way the user of the service outside doesn't have to know what parameter to pass to enable or disable it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1063)*

**Comment by batikanu** [comment]
Some improvement PTAL

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-:-KNqTlLfZzuU4-MnAlcL:416484320)*

**Comment by floreks** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/frontend/common/namespace/namespace_service.js, line 29 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-KNqOflzuGPt_At6Zqpa:-KNqY-Xrm1ArA24FRp5u:-1890243305) ([raw file](https://github.com/kubernetes/dashboard/blob/c331814a61dce17a93be6009b2fa89dfbdd4ec50/src/app/frontend/common/namespace/namespace_service.js#L29)):*
<details><summary><i>Previously, batikanu (Batikan Urcan) wrote…</i></summary>
> @export ?
</details>
Actually services do not require @export annotation. We only need them in places where exported methods/vars are used in html templates. Service methods are not supposed to be used directly in there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1063)*

**Comment by bryk** [comment]
@maciaszczykm @floreks Can you be merging and reviewing PRs for the upcoming week? :) Thanks!

**Comment by floreks** [comment]
Of course :)

**Comment by digitalfishpond** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/frontend/common/namespace/namespace_service.js, line 38 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-KNqIX3gDLfX1sUYsiSN:-KO41TzX4w6_4hlTwbQV:119413179) ([raw file](https://github.com/kubernetes/dashboard/blob/c331814a61dce17a93be6009b2fa89dfbdd4ec50/src/app/frontend/common/namespace/namespace_service.js#L38)):*
<details><summary><i>Previously, batikanu (Batikan Urcan) wrote…</i></summary>
> I would prefer something like below rather than having value as a service which has only getter and setter methods parameterized with direct value from outside.   
> 
> selectMultipleNamespaces() {
>  this.multipleNamespacesSelected_ = true;
> }
> deselectMultipleNamespaces() {
>   this.multipleNamespacesSelected_ = false;
> }
> isMultipleNamespacesSelected() { return this.multipleNamespacesSelected_; }
> 
> In this way the user of the service outside doesn't have to know what parameter to pass to enable or disable it. 
</details>
Good point, but I disagree with suggested function names. Would you have any objections to 'setMultipleNamespacesSelectedTrue()' and 'setMultipleNamespacesSelectedFalse()' ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1063)*

**Comment by digitalfishpond** [comment]
*[src/app/frontend/common/namespace/namespace_service.js, line 38 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-KNqIX3gDLfX1sUYsiSN:-KO426xjNi2lQg9k--Mz:-1924867600) ([raw file](https://github.com/kubernetes/dashboard/blob/c331814a61dce17a93be6009b2fa89dfbdd4ec50/src/app/frontend/common/namespace/namespace_service.js#L38)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> Good point, but I disagree with suggested function names. Would you have any objections to 'setMultipleNamespacesSelectedTrue()' and 'setMultipleNamespacesSelectedFalse()' ?
</details>
This is not the function that selects or deselects. It's the function that sets the flag that only records whether multiple Namespaces have been selected or not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1063)*

**Comment by floreks** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/frontend/common/namespace/namespace_service.js, line 38 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-KNqIX3gDLfX1sUYsiSN:-KO435YRha55WrqR-93d:372397906) ([raw file](https://github.com/kubernetes/dashboard/blob/c331814a61dce17a93be6009b2fa89dfbdd4ec50/src/app/frontend/common/namespace/namespace_service.js#L38)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> This is not the function that selects or deselects. It's the function that sets the flag that only records whether multiple Namespaces have been selected or not.
</details>
I like this setter method. It describes correctly what it does. I'd however change name of getter to `areMultipleNamespacesSelected`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1063)*

**Comment by maciaszczykm** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/frontend/common/namespace/namespace_service.js, line 38 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-KNqIX3gDLfX1sUYsiSN:-KO43qCyh_P7BFaPH8xZ:722612229) ([raw file](https://github.com/kubernetes/dashboard/blob/c331814a61dce17a93be6009b2fa89dfbdd4ec50/src/app/frontend/common/namespace/namespace_service.js#L38)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> I like this setter method. It describes correctly what it does. I'd however change name of getter to `areMultipleNamespacesSelected`.
</details>
I'd leave `setMultipleNamespacesSelected(multipleSelected)` named like it is (woth same logic inside), but if we want to have 2 methods for it then perhaps we can use `setMultipleNamespacesSelected` and `setSingleNamespaceSelected`? I'd avoid words like `true`, `false` in names of the methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1063)*

**Comment by digitalfishpond** [comment]
*[src/app/frontend/common/namespace/namespace_service.js, line 38 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-KNqIX3gDLfX1sUYsiSN:-KO44QVVaJWJj0qzv2i7:-702417048) ([raw file](https://github.com/kubernetes/dashboard/blob/c331814a61dce17a93be6009b2fa89dfbdd4ec50/src/app/frontend/common/namespace/namespace_service.js#L38)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> I'd leave `setMultipleNamespacesSelected(multipleSelected)` named like it is (woth same logic inside), but if we want to have 2 methods for it then perhaps we can use `setMultipleNamespacesSelected` and `setSingleNamespaceSelected`? I'd avoid words like `true`, `false` in names of the methods.
</details>
Yes, I think that makes most sense. I will leave the setter with parameter and amend 'get...' to 'are...' now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1063)*

**Comment by digitalfishpond** [comment]
PTAL

---

Review status: 33 of 63 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-:-KO4AZYdHXLEP6u7t2Ch:676965300)*

**Comment by batikanu** [comment]
Review status: 33 of 63 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/app/frontend/common/namespace/namespace_service.js, line 38 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-KNqIX3gDLfX1sUYsiSN:-KO4BOz5HRsdBBiiig1R:-877179250) ([raw file](https://github.com/kubernetes/dashboard/blob/c331814a61dce17a93be6009b2fa89dfbdd4ec50/src/app/frontend/common/namespace/namespace_service.js#L38)):*
<details><summary><i>Previously, digitalfishpond (Denis Poisson) wrote…</i></summary>
> Yes, I think that makes most sense. I will leave the setter with parameter and amend 'get...' to 'are...' now.
</details>
Thank you for feedback. Actually I don't understand the need for a flag argument which only adds more complexity to the code if it is not really necessary. I like enable disable methods instead of flag arguments in general if they are possible to use. Please see the link regarding this discussion. http://martinfowler.com/bliki/FlagArgument.html (boolean setting method) This change is not dramatic in this case if you are happy with flag arguments then it is LGTM from my side.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1063)*

**Comment by digitalfishpond** [comment]
*[src/app/frontend/common/namespace/namespace_service.js, line 38 \[r3\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-KNqIX3gDLfX1sUYsiSN:-KO4Jn-hFk5kIn6iQVjo:-1443117879) ([raw file](https://github.com/kubernetes/dashboard/blob/c331814a61dce17a93be6009b2fa89dfbdd4ec50/src/app/frontend/common/namespace/namespace_service.js#L38)):*
<details><summary><i>Previously, batikanu (Batikan Urcan) wrote…</i></summary>
> Thank you for feedback. Actually I don't understand the need for a flag argument which only adds more complexity to the code if it is not really necessary. I like enable disable methods instead of flag arguments in general if they are possible to use. Please see the link regarding this discussion. http://martinfowler.com/bliki/FlagArgument.html (boolean setting method) This change is not dramatic in this case if you are happy with flag arguments then it is LGTM from my side.
</details>
Nice article :) So I understand the sentiment here, but I would say that this would be applicable when you are trying to set a flag from with the parameter of a function whose primary purpose is something else, but which affects the flag. Here the function has no other purpose than to set the flag within the decoupled service, and its name reflects that. I think therefore that two methods or one method with a parameter would come to the same, with the one method being the most widespread and expected pattern.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1063)*

**Comment by batikanu** [comment]
> not dramatic in this case if you are happy with flag arguments then it is LGTM from my side.

---

Review status: 33 of 63 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-:-KO4FWwlhLgzQNp6y9Ye:-1982704471)*

**Comment by batikanu** [comment]
It is not about how much code you write. You can also use only a variable instead of a class which only gets and sets a control variable which would be much shorter. If you see the article it also refers boolean setters at the bottom not only methods which do multiple things. If you hide direct access to a variable with getters and setters i would also avoid direct parameters from clients if they don't have to pass value. It is always more readable to say turnon() and turnoff() rather than turn (true) turn (false). 

---

Review status: 33 of 63 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-:-KO4VKGqXfTyvm4fr4B3:592610542)*

**Comment by floreks** [comment]
Review status: 33 of 63 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/configmaplist/configmapcard_component.js, line 47 \[r4\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-KO4YhINSZ8VRtPalQ9k:-KO4YhINSZ8VRtPalQ9l:1272533650) ([raw file](https://github.com/kubernetes/dashboard/blob/ca2987cd1e8d0961de19df58836858f13c2fe4e8/src/app/frontend/configmaplist/configmapcard_component.js#L47)):*
> ```JavaScript
> 
>     /** @export {boolean} */
>     this.isMultipleNamespaces = this.kdNamespaceService_.areMultipleNamespacesSelected();
> ```

Looking at `ctrl.isMultipleNamespaces` in html template I'm not sure what it means. I think wrapper method that returns this.kdNamespaceService_.areMultipleNamespacesSelected()` would be enough. In this case introducing new variable is not necessary as all the changes are reflected through service. 

@maciaszczykm what do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1063)*

**Comment by floreks** [comment]
One comment from me. Otherwise LGTM.

**Comment by maciaszczykm** [comment]
Review status: 33 of 63 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/configmaplist/configmapcard_component.js, line 47 \[r4\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-KO4YhINSZ8VRtPalQ9k:-KO4aeKSG39ZwbiaGKqa:-1793779) ([raw file](https://github.com/kubernetes/dashboard/blob/ca2987cd1e8d0961de19df58836858f13c2fe4e8/src/app/frontend/configmaplist/configmapcard_component.js#L47)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Looking at `ctrl.isMultipleNamespaces` in html template I'm not sure what it means. I think wrapper method that returns this.kdNamespaceService_.areMultipleNamespacesSelected()` would be enough. In this case introducing new variable is not necessary as all the changes are reflected through service. 
> 
> @maciaszczykm what do you think?
</details>
I agree, there is no need to introduce new variable if it's not needed like in this case. Implement wrapper method, because we need to `return this.kdNamespaceService_.areMultipleNamespacesSelected()` only there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1063)*

**Comment by digitalfishpond** [comment]
PTAL

---

Review status: 14 of 65 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/app/frontend/configmaplist/configmapcard_component.js, line 47 \[r4\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-KO4YhINSZ8VRtPalQ9k:-KO5KS_Tb7TkfbHxrceD:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/ca2987cd1e8d0961de19df58836858f13c2fe4e8/src/app/frontend/configmaplist/configmapcard_component.js#L47)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> I agree, there is no need to introduce new variable if it's not needed like in this case. Implement wrapper method, because we need to `return this.kdNamespaceService_.areMultipleNamespacesSelected()` only there.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-:-KO5KTyN-RCl8JKYH2a8:676965300)*

**Comment by maciaszczykm** [comment]
:lgtm:

---

Review status: 14 of 65 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1063#-:-KO5MOoo66EwIB5JiTV7:1417088721)*

**Pull request merged**
