### PR TITLE
Set first release version and fix gulp release pipeline

### PR DESCRIPTION
**Pull request by bryk**
I propose that we start with version 0.1 and use semantic versioning.

### CODE REVIEW

**Comment by bryk** [comment]
@cheld @floreks Can you take a look?

**Comment by floreks** [comment]
Starting version is fine. As for the semantic versioning I think more common format is:

`0.1.0-alpha.1` or `0.1.0-alpha-1`

I like first better. What do you think?

**Comment by lavvy** [comment]
I think I prefer the second option

**Comment by bryk** [comment]
I didn't want to add hyphen, because kubernetes addons have a requirement to not have it in the version (yeah, that's sad). So how about going with just `0.1.0` for start? This what http://semver.org/ advises for initial pre-release development.

**Comment by floreks** [comment]
Yeah, that's disappointing. I'd go with clean `0.1.0` then.

BTW. Does `0.1.0.alpha.1` look that bad?

**Comment by bryk** [comment]
> BTW. Does 0.1.0.alpha.1 look that bad?

It does not, but semver needs a dash between `FOO.BAR.BAZ` and `alpha.1`

**Comment by floreks** [comment]
Oh yeah. I see now. Due to our proxy I could not open semver page correctly...

**Comment by luxas** [comment]
The best version would be `v0.1.0-alpha.1` as Kubernetes core (e.g. `v1.2.0-alpha.7`), but `v0.1.0` is fine too
Are you OK with `v` in the beginning?

**Comment by floreks** [comment]
Fine by me

**Comment by lavvy** [comment]
Cool

**Comment by bryk** [comment]
Updated. PTAL.

**Comment by floreks** [comment]
LGTM

**Pull request merged**
