### PR TITLE
Increase version to v1.4.0 in preparation for release

### PR DESCRIPTION
**Pull request by bryk**
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1230)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm Can you review this and leave unmerged? I'll merge this manually.

**Comment by maciaszczykm** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1230#-:-KRcT7T8VbAov2dF18If:bnfp4nl)*

**Comment by maciaszczykm** [comment]
Ups... Created #1231 to revert changes if you need to merge manually. Sorry!

**Comment by bryk** [comment]
Uh, not a problem. I'll just need to take more care when tagging the release. No worries then and thanks!

**Pull request merged**
