### PR TITLE
Japanes localization of ConfigMap, Namespace, Secrets, and so on.

### PR DESCRIPTION
**Pull request by Yamagami-Takuma**
@f-higashi Can you review?

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1092)

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@f-higashi Let us know, when it will be ready to merge :)

**Comment by f-higashi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[i18n/messages-ja.xtb, line 693 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1092#-KOJJajjSt0vx0yTYiMr:-KOJJajkzucbX_4kRdCg:946565989) ([raw file](https://github.com/kubernetes/dashboard/blob/eb92398d87e8f7d317ddcc86c4832362253a6ea5/i18n/messages-ja.xtb#L693)):*
> ```
> 	<translation id="3413998140079456227" key="MSG_NAMESPACE_DETAIL_LABELS_LABEL" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Label 'Label selector' for the namespace's labels list on the namespace details page.">ラベル</translation>
> 	<translation id="7538864180606148657" key="MSG_BREADCRUMBS_NAMESPACES_LABEL" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Label 'Namespaces' that appears as a breadcrumbs on the action bar.">ネームスペース</translation>
> 	<translation id="2940798370079834880" key="MSG_NAMESPACE_LIST_CREATED_AT_TOOLTIP" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Tooltip 'Created at [some date]' showing the exact creation time of namespace."><ph naee="CREATION_DATE" /> に作成</translation>
> ```

name attribute was changed.

---

*[i18n/messages-ja.xtb, line 707 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1092#-KOJLDRI11DtG0HGjXxA:-KOJLDRJuPUQljlwOOXc:-873440085) ([raw file](https://github.com/kubernetes/dashboard/blob/eb92398d87e8f7d317ddcc86c4832362253a6ea5/i18n/messages-ja.xtb#L707)):*
> ```
> 	<translation id="6987669710926523285" key="MSG_NODE_LIST_READY_LABEL" source="/home/maciaszczykm/workspace/dashboard/.tmp/serve/app-dev.js" desc="Label 'Ready' which appears as a column label in the table of nodes (node list view).">準備完了</translation>
> 	<translation id="6987669710926523285" key="MSG_NODE_LIST_READY_LABEL" source="/usr/local/google/home/bryk/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Label 'Ready' which appears as a column label in the table of nodes (node list view).">準備完了</translation>
> 	<translation id="394136829343605455" key="MSG_RC_DETAIL_NUMBER_OF_PODS_INTEGER_WARNING" source="/usr/local/google/home/bryk/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="This warning appears when the specified pods count on the &quot;update number of pods&quot; dialog is not positive or non-integer.">レプリカセット数は0以上を設定してください</translation>
> ```

replicas is not only used 'レプリカセット(replica set)'.
I think it is '複製数'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1092)*

**Comment by Yamagami-Takuma** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[i18n/messages-ja.xtb, line 693 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1092#-KOJJajjSt0vx0yTYiMr:-KOJQRdh-x468koVvz3_:-471575429) ([raw file](https://github.com/kubernetes/dashboard/blob/eb92398d87e8f7d317ddcc86c4832362253a6ea5/i18n/messages-ja.xtb#L693)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> name attribute was changed.
</details>
I fixed it.

---

*[i18n/messages-ja.xtb, line 707 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1092#-KOJLDRI11DtG0HGjXxA:-KOJQY4H_2D_V8nmtfPD:-1326905228) ([raw file](https://github.com/kubernetes/dashboard/blob/eb92398d87e8f7d317ddcc86c4832362253a6ea5/i18n/messages-ja.xtb#L707)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> replicas is not only used 'レプリカセット(replica set)'.
> I think it is '複製数'.
</details>
I had misunderstood it. I fixed it.

---

*[i18n/messages-ja.xtb, line 708 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1092#-KOJOJEmr8PBK0v2nF-B:-KOJOJEmr8PBK0v2nF-C:1051852145) ([raw file](https://github.com/kubernetes/dashboard/blob/7807f6ef616493e0767225b7b877e7fb82566a9a/i18n/messages-ja.xtb#L708)):*
> 394136829343605455

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1092)*

**Comment by maciaszczykm** [comment]
@f-higashi @Yamagami-Takuma Is it ready to merge?

**Comment by Yamagami-Takuma** [comment]
@maciaszczykm 

I think @f-higashi will review the appearance on dashboard.
Please wait it.

**Comment by f-higashi** [comment]
:lgtm:

@Yamagami-Takuma
please resolve conflicts 

@maciaszczykm 
After that you can merge this :)

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1092#-:-KOy0Rj6OAqpHnQduVgQ:bdurmul)*

**Comment by Yamagami-Takuma** [comment]
I resolved conflicts.
@maciaszczykm You can merge this.

**Pull request merged**
