### PR TITLE
Upsert secret

### PR DESCRIPTION
**Pull request by anshulahuja98**
Basic form for issue #4255 

image

### CODE REVIEW

**Comment by floreks** [comment]
Few things:
1. Upsert is a very technical word. I wouldn't use that for the UI.
2. We don't really want to end up with tab per every resource. I'd rather want to see some kind of combobox to switch the resource type on already existing creation form and then show proper inputs to create that resource.

**Comment by anshulahuja98** [comment]
@floreks 
We can switch from using `Upsert`, I actually initially followed the terminology as mentioned in Issue #4255. Please suggest a suitable naming scheme for the same, I'll make the required changes.

This tab isn't for every resource, this is just an independent form to create secrets in a given namespace.
I probably didn't understand what exactly you meant by the second point.

**Comment by floreks** [comment]
I mean that we should use a `create from form` tab and add there some kind of selector to create resource this way. This is basically `create a secret from form` option. We can have a single tab + selector to create: App, Secret, Pod, Role, etc. I wouldn't add separate tab just to create new resource type.

**Comment by anshulahuja98** [comment]
Okay, I think I got it.
So you basically want to make changes to the current `create from form` option and add the method to create secrets using the method of just pasting the secret in plain text apart from the existing version which takes base64 encoded secrets.

This would just require changes in the CreateSecret dialog right?

**Comment by anshulahuja98** [comment]
Can we perhaps update the issue #4255 to reflect on what exactly is required.

**Comment by floreks** [comment]
> Okay, I think I got it.
So you basically want to make changes to the current create from form option and add the method to create secrets using the method of just pasting the secret in plain text apart from the existing version which takes base64 encoded secrets.
>
> This would just require changes in the CreateSecret dialog right?

No. When you open a `create from form` tab, there should be additional selector/combobox with options i.e. `Application|Secret|Role`. When you select a `Secret` it basically shows fields from your new tab `Upsert Secrets`. When you switch back to `Application` it shows the current status, etc.

**Comment by maciaszczykm** [comment]
We cannot accept it in the current form. It would have to be moved to the "create from form" tab as @floreks pointed out. Please reopen if you are willing to make such changes.  We will track from https://github.com/kubernetes/dashboard/issues/1600.

**Comment by anshulahuja98** [comment]
Okay!
I'll have a try at it again and let you know.

**Pull request closed without merging**
