### PR TITLE
Config map details and list frontend

### PR DESCRIPTION
**Pull request by bryk**
Addresses: #1011

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1019)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm Can you review?

**Comment by maciaszczykm** [comment]
I'll do it tommorow morning.

**Comment by maciaszczykm** [comment]
Tested on `serve:prod`. It works.

Two minor issues.

:lgtm: 

---

Reviewed 25 of 27 files at r1, 3 of 3 files at r2.
Review status: 28 of 30 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/configmapdetail/configmapdetail.html, line 29 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1019#-KMcsjCwAwK0EoPKyaYW:-KMcsjCx28lNKyGAmren:1767195132) ([raw file](https://github.com/kubernetes/dashboard/blob/e773adb891f6c8809f64043d3bb3516c1a88c43d/src/app/frontend/configmapdetail/configmapdetail.html#L29)):*
> ```HTML
>     </kd-info-card>
>   </md-content>
> </div>
> ```

In config map detail there is an visible style issue:



It should look like this:



---

*[src/app/frontend/configmaplist/configmapcard.html, line 46 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1019#-KMcrQloegroY4yIuAMt:-KMcrQlpocCXsvYKRTq1:2036589085) ([raw file](https://github.com/kubernetes/dashboard/blob/e773adb891f6c8809f64043d3bb3516c1a88c43d/src/app/frontend/configmaplist/configmapcard.html#L46)):*
> ```HTML
>       </kd-resource-card-menu>
>     </kd-resource-card-column>
>   </kd-resource-card-columns>
> ```

`kubectl get configmap` returns also `DATA` column. Could you return it here too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1019#-:-KMctA80ZVLvS0GZ7Rud:1612139321)*

**Comment by bryk** [comment]
All donw. Will merge when travis is happy. 

---

Review status: 27 of 30 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/configmapdetail/configmapdetail.html, line 29 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1019#-KMcsjCwAwK0EoPKyaYW:-KMdVpdOtqdMfhC7lYfs:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/e773adb891f6c8809f64043d3bb3516c1a88c43d/src/app/frontend/configmapdetail/configmapdetail.html#L29)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> In config map detail there is an visible style issue:
> 
> 
> 
> It should look like this:
> 
> 
> 
</details>
Done.

---

*[src/app/frontend/configmaplist/configmapcard.html, line 46 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1019#-KMcrQloegroY4yIuAMt:-KMdVTh0HtlwE729GSla:560399583) ([raw file](https://github.com/kubernetes/dashboard/blob/e773adb891f6c8809f64043d3bb3516c1a88c43d/src/app/frontend/configmaplist/configmapcard.html#L46)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> `kubectl get configmap` returns also `DATA` column. Could you return it here too?
</details>
I don't know what this column is... Do you? We can add it later, anyway. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1019#-:-KMdVyb_8I1rCbbgk69z:-887277147)*

**Comment by bryk** [comment]
Reviewed 26 of 27 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1019)*

**Comment by maciaszczykm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/app/frontend/configmaplist/configmapcard.html, line 46 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1019#-KMcrQloegroY4yIuAMt:-KMdXHy6HOR_ZuN2ZohA:-57400660) ([raw file](https://github.com/kubernetes/dashboard/blob/e773adb891f6c8809f64043d3bb3516c1a88c43d/src/app/frontend/configmaplist/configmapcard.html#L46)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> I don't know what this column is... Do you? We can add it later, anyway. 
</details>
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/describe.go#L2097

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1019)*

**Comment by bryk** [comment]
*[src/app/frontend/configmaplist/configmapcard.html, line 46 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1019#-KMcrQloegroY4yIuAMt:-KMdXbgEkD4kUwFnxR8b:-1777654054) ([raw file](https://github.com/kubernetes/dashboard/blob/e773adb891f6c8809f64043d3bb3516c1a88c43d/src/app/frontend/configmaplist/configmapcard.html#L46)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/describe.go#L2097
</details>
Yeah, but this is for details. In the list there is some other mistery value. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1019)*

**Comment by maciaszczykm** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/app/frontend/configmaplist/configmapcard.html, line 46 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1019#-KMcrQloegroY4yIuAMt:-KMdYpDkwmzSMiwe3eou:-1192786165) ([raw file](https://github.com/kubernetes/dashboard/blob/e773adb891f6c8809f64043d3bb3516c1a88c43d/src/app/frontend/configmaplist/configmapcard.html#L46)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Yeah, but this is for details. In the list there is some other mistery value. 
</details>
Okay, then let's leave it. We can add it in the future :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1019)*

**Pull request merged**
