### PR TITLE
Namespaces list and details

### LINKED ISSUE #1008: Namespaces list and details
I'll take care of namespace list and details.

### PR DESCRIPTION
**Pull request by maciaszczykm**
Added namespaces handling:

- [x] update backend
- [x] update namespace selector to work with new namespace structure
- [x] basic list view working like `kubectl get ns` with additional label data
- [x] basic details view
- [x] update JSDocs
- [x] update tests
- [x] integrate with backend pagination
- [x] list all events in namespace

Closes #1008.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1022)

### CODE REVIEW

**Comment by bryk** [comment]
Reviewed 9 of 43 files at r1.
Review status: 9 of 28 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/frontend/common/namespace/namespaceselect_component.js, line 135 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1022#-KMZQWM8bnVfLgYRMGvq:-KMZQWM9tn7EGrpcM2QX:-750445327) ([raw file](https://github.com/kubernetes/dashboard/blob/109d2ed60a2a8ca78e112037ab45468c4abfbd67/src/app/frontend/common/namespace/namespaceselect_component.js#L135)):*
> ```JavaScript
> 
>       return resource.get().$promise.then((/** !backendApi.NamespaceList */ namespaceList) => {
>         this.namespaces = Array.from(namespaceList.namespaces, n => n.objectMeta.name);
> ```

Can you just do `namespaceList.namespaces.map(n => ...);`? Array.from is not present on IE nor on Opera: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/from

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1022)*

**Comment by bryk** [comment]
Reviewed 17 of 43 files at r1.
Review status: 26 of 28 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/namespacedetail/namespacedetail.html, line 20 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1022#-KMZQidYdbI2rpRtDQdK:-KMZQidYdbI2rpRtDQdL:-30405976) ([raw file](https://github.com/kubernetes/dashboard/blob/109d2ed60a2a8ca78e112037ab45468c4abfbd67/src/app/frontend/namespacedetail/namespacedetail.html#L20)):*
> ```HTML
>   <md-content>
>     <md-tabs md-border-bottom md-dynamic-height>
>       <md-tab label="{{::ctrl.i18n.MSG_NAMESPACE_DETAIL_OVERVIEW_LABEL}}">
> ```

Should we have the overview tab, even when there is no other tabs? 

How about you add events to namespacedetail object? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1022)*

**Comment by maciaszczykm** [comment]
Review status: 26 of 28 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/common/namespace/namespaceselect_component.js, line 135 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1022#-KMZQWM8bnVfLgYRMGvq:-KMZTHh3CsZLbaPZVb7Q:317085835) ([raw file](https://github.com/kubernetes/dashboard/blob/109d2ed60a2a8ca78e112037ab45468c4abfbd67/src/app/frontend/common/namespace/namespaceselect_component.js#L135)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Can you just do `namespaceList.namespaces.map(n => ...);`? Array.from is not present on IE nor on Opera: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/from
</details>
I'll do it.

---

*[src/app/frontend/namespacedetail/namespacedetail.html, line 20 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1022#-KMZQidYdbI2rpRtDQdK:-KMZTK5XZhr7pr-BN1vy:235632645) ([raw file](https://github.com/kubernetes/dashboard/blob/109d2ed60a2a8ca78e112037ab45468c4abfbd67/src/app/frontend/namespacedetail/namespacedetail.html#L20)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Should we have the overview tab, even when there is no other tabs? 
> 
> How about you add events to namespacedetail object? 
</details>
I can do it, but which events do we want to display? From all namespace's resources? `kubectl` doesn't provide such functionality.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1022)*

**Comment by bryk** [comment]
Review status: 24 of 32 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/namespacedetail/namespacedetail.html, line 20 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1022#-KMZQidYdbI2rpRtDQdK:-KMZUJH-G0LxY3s1xjg-:1951917720) ([raw file](https://github.com/kubernetes/dashboard/blob/109d2ed60a2a8ca78e112037ab45468c4abfbd67/src/app/frontend/namespacedetail/namespacedetail.html#L20)):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> I can do it, but which events do we want to display? From all namespace's resources? `kubectl` doesn't provide such functionality.
</details>
Yes. All events in the namespace. Should be doable via API, just call `Events(namespace).List()`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1022)*

**Comment by maciaszczykm** [comment]
This PR is getting really big. I'll add connected resources like quotas and limits in another one. In this one only thing missing is now backed support for pagination.

**Comment by bryk** [comment]
Yep, this makes sense. Let me know when ready for rereview.

**Comment by maciaszczykm** [comment]
PTAL

**Comment by bryk** [comment]
Can you test NamespaceInfoController (all methods) NamespaceCardListController (that it initializes i18n correctly). 

PTAL, two small comments. 

---

Reviewed 2 of 7 files at r3, 18 of 26 files at r4, 4 of 5 files at r5, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kubernetes/dashboard/1022#-KN1vZetRHWBdKs_OrDa:-KN1vZetRHWBdKs_OrDb:-1390445657) (no related file):*
The first element in the list is misalinged:



Do you know why? Can you fix? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1022#-:-KN1v1IJSrC1f6DBoS82:2068350731)*

**Comment by maciaszczykm** [comment]
Added tests and status icons.

PTAL

---

Review status: 33 of 41 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kubernetes/dashboard/1022#-KN1vZetRHWBdKs_OrDa:-KN2cTu18ccQ2ZXlpvcn:-499146009) (no related file):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> The first element in the list is misalinged:
> 
> 
> 
> Do you know why? Can you fix? 
</details>
Done.

---

*[src/app/frontend/namespacedetail/namespacedetail.html, line 20 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1022#-KMZQidYdbI2rpRtDQdK:-KN2cVNvJ65SW-SAu7xZ:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/109d2ed60a2a8ca78e112037ab45468c4abfbd67/src/app/frontend/namespacedetail/namespacedetail.html#L20)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Yes. All events in the namespace. Should be doable via API, just call `Events(namespace).List()`. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1022#-:-KN2mFyC8jzDoLfsT-y5:-1039529468)*

**Comment by bryk** [comment]
Reviewed 8 of 8 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1022)*

**Comment by bryk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kubernetes/dashboard/1022#-KN1vZetRHWBdKs_OrDa:-KN6EdAwMBDNBPp1O89w:980077423) (no related file):*
<details><summary><i>Previously, maciaszczykm (Marcin Maciaszczyk) wrote…</i></summary>
> Done.
</details>
:lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1022)*

**Pull request merged**
