### PR TITLE
Japanese localization of Deploy page and status icons

### PR DESCRIPTION
**Pull request by Yamagami-Takuma**
@f-higashi Please review this! :)

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/841)

### CODE REVIEW

**Comment by f-higashi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[i18n/messages-ja.xtb, line 70 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/841#-KJdRWjBl9Lb4PtV9bz-:-KJdRWjCL2YBYPyDvJD2:1440244408) ([raw file](https://github.com/kubernetes/dashboard/blob/70183da4b287a37971bde7b13569d52d146d87a7/i18n/messages-ja.xtb#L70)):*
> ```
> 	<translation id="7560440547757208994" key="MSG_DEPLOY_SETTINGS_ENV_VARIABLES_USER_HELP" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="User help for the &quot;Environment variables&quot; section on the deploy from settings page.">コンテナ内で使われる環境変数が利用できます。値は $(VAR_NAME) 構文を使用して、他の変数を参照できます。</translation>
> 	<translation id="7026295428726247109" key="MSG_DEPLOY_SETTINGS_NUMBER_OF_PODS_INT_WARNING" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Appears to tell the user that the number of pods on the deploy from settings page must be non-negative or integer.">正数を入力してください</translation>
> 	<translation id="3664340326455185585" key="MSG_POD_IS_FAILED_TOOLTIP" source="/home/denis/Projects/dashboard/.tmp/serve/app-dev.js" desc="tooltip for failed pod card icon">ポッドがエラーです。</translation>
> ```

How about `ポッドにエラーが発生しています。`

---

*[i18n/messages-ja.xtb, line 71 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/841#-KJd8LCvOAGj7R979scw:-KJd8LCvOAGj7R979scx:829711693) ([raw file](https://github.com/kubernetes/dashboard/blob/70183da4b287a37971bde7b13569d52d146d87a7/i18n/messages-ja.xtb#L71)):*
> ```
> 	<translation id="7026295428726247109" key="MSG_DEPLOY_SETTINGS_NUMBER_OF_PODS_INT_WARNING" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Appears to tell the user that the number of pods on the deploy from settings page must be non-negative or integer.">正数を入力してください</translation>
> 	<translation id="3664340326455185585" key="MSG_POD_IS_FAILED_TOOLTIP" source="/home/denis/Projects/dashboard/.tmp/serve/app-dev.js" desc="tooltip for failed pod card icon">ポッドがエラーです。</translation>
> 	<translation id="6223633459559529643" key="MSG_POD_IS_PENDING_TOOLTIP" source="/home/denis/Projects/dashboard/.tmp/serve/app-dev.js" desc="tooltip for pending pod card icon">ポッドがペンディング状態です。</translation>
> ```

I think `待機状態` is better.

---

*[i18n/messages-ja.xtb, line 88 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/841#-KJdMAVndhj0jd6yXOZw:-KJdMAVovWV8kvP7vlo-:-241574494) ([raw file](https://github.com/kubernetes/dashboard/blob/70183da4b287a37971bde7b13569d52d146d87a7/i18n/messages-ja.xtb#L88)):*
> ```
> 	<translation id="6458313634738030070" key="MSG_DEPLOY_LABEL_KEY_NOT_UNIQUE_WARNING" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="This warning appears when the key of a specified kubernetes label on the deploy page is not unique."><ph name="LABEL_KEY" /> は一意ではありません。</translation>
> 	<translation id="5942949269312477924" key="MSG_DEPLOY_LABEL_KEY_PREFIX_PATTERN_WARNING" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="This warning appears when the key of a specified kubernetes label (on the deploy page) does not start with a proper prefix.">有効な DNS サブドメインプレフィックスではありません。例: my-domain.com</translation>
> 	<translation id="2202844148518919115" key="MSG_DEPLOY_LABEL_KEY_NAME_PATTERN_WARNING" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="This warning appears when the key name of a specified kubernetes label (on the deploy page) does not match the required pattern.">半角英数字、文中の '-' , '_' , '.' 、オプションで DNS サブドメインのプレフィックスと '/' が使用できます</translation>
> ```

It is bit difficult to understand.
How about `半角英数字、文中の '-' , '_' , '.' が使用できます。オプションとして DNS サブドメインと '/'をプレフィックスとしてつけることができます。`

---

*[i18n/messages-ja.xtb, line 89 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/841#-KJdNTMwXc2IQ45fvgu_:-KJdNTMx02TN3tJgfazX:-1875622827) ([raw file](https://github.com/kubernetes/dashboard/blob/70183da4b287a37971bde7b13569d52d146d87a7/i18n/messages-ja.xtb#L89)):*
> ```
> 	<translation id="5942949269312477924" key="MSG_DEPLOY_LABEL_KEY_PREFIX_PATTERN_WARNING" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="This warning appears when the key of a specified kubernetes label (on the deploy page) does not start with a proper prefix.">有効な DNS サブドメインプレフィックスではありません。例: my-domain.com</translation>
> 	<translation id="2202844148518919115" key="MSG_DEPLOY_LABEL_KEY_NAME_PATTERN_WARNING" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="This warning appears when the key name of a specified kubernetes label (on the deploy page) does not match the required pattern.">半角英数字、文中の '-' , '_' , '.' 、オプションで DNS サブドメインのプレフィックスと '/' が使用できます</translation>
> 	<translation id="5453986949828048308" key="MSG_DEPLOY_LABEL_KEY_PREFIX_MAX_LENGTH_WARNING" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="This warning appears when the key prefix of a specified kubernetes label (on the deploy page) is too long.">最大 253 文字です</translation>
> ```

`プレフィックスは最大 253 文字です`

---

*[i18n/messages-ja.xtb, line 90 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/841#-KJdOVi2Qhz9nTzzNlz4:-KJdOVi2Qhz9nTzzNlz5:-713813547) ([raw file](https://github.com/kubernetes/dashboard/blob/70183da4b287a37971bde7b13569d52d146d87a7/i18n/messages-ja.xtb#L90)):*
> ```
> 	<translation id="2202844148518919115" key="MSG_DEPLOY_LABEL_KEY_NAME_PATTERN_WARNING" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="This warning appears when the key name of a specified kubernetes label (on the deploy page) does not match the required pattern.">半角英数字、文中の '-' , '_' , '.' 、オプションで DNS サブドメインのプレフィックスと '/' が使用できます</translation>
> 	<translation id="5453986949828048308" key="MSG_DEPLOY_LABEL_KEY_PREFIX_MAX_LENGTH_WARNING" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="This warning appears when the key prefix of a specified kubernetes label (on the deploy page) is too long.">最大 253 文字です</translation>
> 	<translation id="704934282074920058" key="MSG_DEPLOY_LABEL_KEY_NAME_MAX_LENGTH_WARNING" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="This warning appears when the key name of a specified kubernetes label (on the deploy page) is too long.">最大 63 文字です</translation>
> ```

`ラベルのキー名は最大 63 文字です`

---

*[i18n/messages-ja.xtb, line 111 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/841#-KJdPdUVnPLJn-FIsopE:-KJdPdUVnPLJn-FIsopF:55359702) ([raw file](https://github.com/kubernetes/dashboard/blob/70183da4b287a37971bde7b13569d52d146d87a7/i18n/messages-ja.xtb#L111)):*
> ```
> 	<translation id="1660903123116357917" key="MSG_PORT_MAPPINGS_PROTOCOL_INVALID_WARNING" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="This warning appears when the user specifies an invalid protocol for a port mapping (in the port mappings section, on the deploy page).">不正なプロトコル</translation>
> 	<translation id="791270856930969272" key="MSG_PODS_ARE_FAILED_TOOLTIP" source="/home/denis/Projects/dashboard/.tmp/serve/app-dev.js" desc="tooltip for failed pod card icon">１つ以上のポッドがエラーです</translation>
> 	<translation id="8275670389075054584" key="MSG_PODS_ARE_PENDING_TOOLTIP" source="/home/denis/Projects/dashboard/.tmp/serve/app-dev.js" desc="tooltip for pending pod card icon">１つ以上のポッドがペンディング状態です</translation>
> ```

`待機状態`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/841)*

**Comment by Yamagami-Takuma** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[i18n/messages-ja.xtb, line 88 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/841#-KJdMAVndhj0jd6yXOZw:-KJdafvyBAn514pfWUHj:-1051827129) ([raw file](https://github.com/kubernetes/dashboard/blob/70183da4b287a37971bde7b13569d52d146d87a7/i18n/messages-ja.xtb#L88)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> It is bit difficult to understand.
> How about `半角英数字、文中の '-' , '_' , '.' が使用できます。オプションとして DNS サブドメインと '/'をプレフィックスとしてつけることができます。`
> 
</details>
Last sentence looks a little verbose.
How about `オプションで DNS サブドメインと '/' をプレフィックスとしてつけられます。`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/841)*

**Comment by f-higashi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[i18n/messages-ja.xtb, line 88 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/841#-KJdMAVndhj0jd6yXOZw:-KJdgbILR0pJowORVwyl:344222427) ([raw file](https://github.com/kubernetes/dashboard/blob/70183da4b287a37971bde7b13569d52d146d87a7/i18n/messages-ja.xtb#L88)):*
<details><summary><i>Previously, Yamagami-Takuma wrote…</i></summary>
> Last sentence looks a little verbose.
> How about `オプションで DNS サブドメインと '/' をプレフィックスとしてつけられます。`
</details>
I see.
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/841)*

**Comment by bryk** [comment]
@maciaszczykm Can you merge this when LGTMed?

**Comment by f-higashi** [comment]
:lgtm: 
you can merge this :)

<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> @maciaszczykm Can you merge this when LGTMed? 
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/841#-:-KJe069w1l1tC9tNlXCY:-1075459491)*

**Comment by maciaszczykm** [comment]
Hey @Yamagami-Takuma, could you resolve conflicts?

**Comment by Yamagami-Takuma** [comment]
@maciaszczykm Sure. It's done.

**Pull request merged**
