### PR TITLE
Fix travis break

### PR DESCRIPTION
**Pull request by rf232**
first commit fixes the break (hopefully, don't have IE11 around to test it :))

second commit enables the saucelabs to also run on pull requests, so we can see if this actually fixes the break

### CODE REVIEW

**Comment by rf232** [comment]
@olekzabl, @digitalfishpond, @maciaszczykm 

TIL: we run our tests on IE11, but not on Pull Requests, only on commits in master. Apparently my previous CL broke that. here a PR that fixes the tests

the second commit in the PR is a quick hack to get the IE11 tests to run on this PR, I'm not sure if we can keep this change or not. I don't know the details of why we don't use this on all PRs but that might be a different discussion, so I'm more than happy to revert that one before merging.

**Comment by maciaszczykm** [comment]
@rf232 In the past we had a lot of problems with flaky tests from sauce labs and we had to temporarily disable them on development banches. @bryk in pull request #593 did the change, that might get you more insight.

We can test if the issue still occurs.

Also +1 for first commit if Travis will pass.

**Comment by rf232** [comment]
grmbl, now unittests work even in IE11, but somehow the protractor tests (integration tests) fail to start the browser now.

**Comment by rf232** [comment]
run succeeded with ie11, removed second commit from pull request, ready for merging I think

**Pull request merged**
