### PR TITLE
Add pagination for pod and replica set list

### PR DESCRIPTION
**Pull request by floreks**
I've added frontend pagination based on this module: https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination

It's very light, has support for async data and is easy to style. For now I've added central service that returns max number of rows to display on the list. I'm planning to extend that and add select box to every list where we can choose i.e. 10/25/50/100 items to show + some easy search box to filter data on the list.

Todo:
- [x] Add tests
- [ ] Add support to all resource lists

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/852)

### CODE REVIEW

**Comment by bryk** [comment]
A few comments. I'm impressed by the beauty of this, looks really nice :) 

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> #### Add pagination for pod and replica set list
> 
> I've added frontend pagination based on this module: https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination
> 
> 
> 
> It's very light, has support for async data and is easy to style. For now I've added central service that returns max number of rows to display on the list. I'm planning to extend that and add select box to every list where we can choose i.e. 10/25/50/100 items to show + some easy search box to filter data on the list.
> 
> 
> 
> Todo:
> 
> - [ ] Add tests
> 
> - [ ] Add support to all resource lists
> 
> 
> 
> 
> 
> 
</details>


---

Reviewed 7 of 18 files at r1.
Review status: 7 of 18 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[bower.json, line 16 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjYJyAvoDB8DvpDpTR:-KJjYJyAvoDB8DvpDpTS:1985101531) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/bower.json#L16)):*
> ```JSON
>     "roboto-fontface": "~0.4.5",
>     "ng-jsoneditor": "angular-tools/ng-jsoneditor#~1.0.0",
>     "angularUtils-pagination": "angular-utils-pagination#^0.11.1"
> ```

Nit: change version to `~`

---

*[src/app/frontend/index_config.js, line 17 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjYPE6n_qqF1MbaE8g:-KJjYPE6n_qqF1MbaE8h:-1481142360) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/index_config.js#L17)):*
> ```JavaScript
> /**
>  * @param {!md.$mdThemingProvider} $mdThemingProvider
>  * @param {!{setPath: function(string)}} paginationTemplateProvider - This provider is related
> ```

Yeah, this needs externs and definition there.

---

*[src/app/frontend/index_config.js, line 23 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjZFuY1clZoE19Xmen:-KJjZFuY1clZoE19Xmeo:1120352243) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/index_config.js#L23)):*
> ```JavaScript
> export default function config($mdThemingProvider, paginationTemplateProvider) {
>   // Set pagination template
>   paginationTemplateProvider.setPath('common/pagination/pagination.tpl.html');
> ```

How about specifying pagination template in the template?

I.e., example 3 from the documentation:
```html
<dir-pagination-controls template-url="path/to/dirPagination.tpl.html"></dir-pagination-controls>
```

This looks nicer, because you don't have global state and template. And you don't need extertns, too. 

---

*[src/app/frontend/index_module.js, line 48 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjYUHETADkzAJsWXVg:-KJjYUHETADkzAJsWXVh:619447872) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/index_module.js#L48)):*
> ```JavaScript
>           'ngSanitize',
>           'ui.router',
>           'angularUtils.directives.dirPagination',
> ```

Should this be required only in the places it is used? I say yes. This should be required in the common components module. 

---

*[src/app/frontend/common/components/resourcecard/resourcecardlistfooter.js, line 16 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjYe58VoPAn_8As7N6:-KJjYe58VoPAn_8As7N7:527732347) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/common/components/resourcecard/resourcecardlistfooter.js#L16)):*
> ```JavaScript
> 
> /**
>  * Resource card columns component. See resource card for documentation.
> ```

Remove the comment, it is invalid. 

---

*[src/app/frontend/common/pagination/pagination.tpl.html, line 1 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjYkGd6fLK2LQjLVUi:-KJjYkGd6fLK2LQjLVUj:2100490043) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/common/pagination/pagination.tpl.html#L1)):*
> ```HTML
> <div ng-if="pages.length > 1 || !autoHide" class="kd-list-pagination">
> ```

Boilerplate copyright comment? 

---

*[src/app/frontend/common/pagination/pagination.tpl.html, line 1 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjYu7AGL3vBukdxTRZ:-KJjYu7AGL3vBukdxTR_:-655678514) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/common/pagination/pagination.tpl.html#L1)):*
> ```HTML
> <div ng-if="pages.length > 1 || !autoHide" class="kd-list-pagination">
> ```

Why the file name is `*.tpl.html`?  Can it be without `tpl`? 

---

*[src/app/frontend/common/pagination/pagination_service.js, line 18 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjZmbR2RRK1yZLQF8F:-KJjZmbR2RRK1yZLQF8G:-1242675101) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/common/pagination/pagination_service.js#L18)):*
> ```JavaScript
>  * @final
>  */
> export class PaginationService {
> ```

Why do we need this service anyway? Cannot we embed this const in a controller? Will there be a use for this in the future? 

---

*[src/app/frontend/common/pagination/pagination_service.js, line 20 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjZvmMMVYYWJXWG0rg:-KJjZvmMMVYYWJXWG0rh:-213015727) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/common/pagination/pagination_service.js#L20)):*
> ```JavaScript
> export class PaginationService {
>   constructor() {
>     /** @export {number} */
> ```

Can you explain in short what this is? 

---

*[src/app/frontend/common/pagination/pagination_service.js, line 21 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjZj-cGRQFPryt1-qx:-KJjZj-cGRQFPryt1-qy:325858613) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/common/pagination/pagination_service.js#L21)):*
> ```JavaScript
>   constructor() {
>     /** @export {number} */
>     this.rowsLimit = 20;
> ```

Make this `@private` and `@const`? 

---

*[src/app/frontend/podlist/podcardlist_component.js, line 103 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJj_5gA7GTx7u-lNs3i:-KJj_5gA7GTx7u-lNs3j:1604814900) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/podlist/podcardlist_component.js#L103)):*
> ```JavaScript
>    * @export
>    */
>   shouldShowFooter() { return this.podList.pods.length > this.paginationService.getRowsLimit(); }
> ```

Rename to `shouldShowPagination`? This is what it really does. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-:-KJj_FkSS4vSDPQ4836L:-103485971)*

**Comment by floreks** [comment]
Review status: 7 of 18 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/index_config.js, line 23 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjZFuY1clZoE19Xmen:-KJjeU6TAH5MhvJvJFBx:490158424) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/index_config.js#L23)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> How about specifying pagination template in the template?
> 
> I.e., example 3 from the documentation:
> ```html
> <dir-pagination-controls template-url="path/to/dirPagination.tpl.html"></dir-pagination-controls>
> ```
> 
> This looks nicer, because you don't have global state and template. And you don't need extertns, too. 
</details>
hmm... anyway we should have this path set in one place and use ctrl function to return it. I didn't want to put same fixed string in every resource list. It's easier to maintain if it's defined in one place only.

---

*[src/app/frontend/index_module.js, line 48 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjYUHETADkzAJsWXVg:-KJjf0FkSREcOpYzEUC6:-197000413) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/index_module.js#L48)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Should this be required only in the places it is used? I say yes. This should be required in the common components module. 
</details>
It is used in list components directly. `podcardlist` `replicasetcardlist`, etc. I can add it to these modules.

---

*[src/app/frontend/common/pagination/pagination.tpl.html, line 1 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjYu7AGL3vBukdxTRZ:-KJjg2MZ6OcX7BJoqpTj:-655417648) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/common/pagination/pagination.tpl.html#L1)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Why the file name is `*.tpl.html`?  Can it be without `tpl`? 
</details>
I've wanted to make it more noticeable that it is common template for pagination. We can leave it without `*.tpl.*`

---

*[src/app/frontend/common/pagination/pagination_service.js, line 18 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjZmbR2RRK1yZLQF8F:-KJjgw5NwtrwAepRr6gH:-1397867511) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/common/pagination/pagination_service.js#L18)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Why do we need this service anyway? Cannot we embed this const in a controller? Will there be a use for this in the future? 
</details>
My thinking was that we should have common configuration instead of defining same const in every controller. It is always easier to update if needed. Soon I'll be adding selector with options `10/25/50/100` to change number of visible rows on the list and I wanted to add configuration for that here. Does that make sense?

---

*[src/app/frontend/common/pagination/pagination_service.js, line 21 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjZj-cGRQFPryt1-qx:-KJjhdWzkQ069yQbW1Ie:-849058580) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/common/pagination/pagination_service.js#L21)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Make this `@private` and `@const`? 
</details>
Yep. I've noticed that after creating PR.

---

*[src/app/frontend/podlist/podcardlist_component.js, line 103 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJj_5gA7GTx7u-lNs3i:-KJjhiOYQzu_doUG9xEi:1886599087) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/podlist/podcardlist_component.js#L103)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Rename to `shouldShowPagination`? This is what it really does. 
</details>
Yeah, I guess for now `shouldShowPagination` fits better. If we add more components to the footer we can rename.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/852)*

**Comment by bryk** [comment]
Review status: 3 of 18 files reviewed at latest revision, 13 unresolved discussions.

---

*[src/app/frontend/index_config.js, line 23 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjZFuY1clZoE19Xmen:-KJjtNqDzK91Y-YOOvA8:567532180) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/index_config.js#L23)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> hmm... anyway we should have this path set in one place and use ctrl function to return it. I didn't want to put same fixed string in every resource list. It's easier to maintain if it's defined in one place only.
</details>
Yes sure, but I meant putting it in a common component, only once. 

Ca you create a self contained component for this? A component that can be used with no external deps. 

E.g.,
```html
<kd-resource-card-list-pagination></kd-resource-card-list-pagination>
```

---

*[src/app/frontend/common/components/resourcecard/resourcecardlistfooter_component.js, line 24 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjurRg-1KtKHkUhwF3:-KJjurRg-1KtKHkUhwF4:-1279546411) ([raw file](https://github.com/kubernetes/dashboard/blob/14915b579bb437b0184f3f75da896f35b8f7a66a/src/app/frontend/common/components/resourcecard/resourcecardlistfooter_component.js#L24)):*
> ```JavaScript
>   templateUrl: 'common/components/resourcecard/resourcecardlistfooter.html',
>   transclude: true,
>   require: {
> ```

Here, you can communicate with the ctrl to determine whether the pagination should be displayed. You should be able, e.g., to get all items. 

Should we chat on slack on this? 

---

*[src/app/frontend/common/components/resourcecard/resourcecardlistfooter.js, line 1 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjuWZk0FEkNKjs_fE0:-KJjuWZlfpKBXTHh9zYW:-1239812963) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/common/components/resourcecard/resourcecardlistfooter.js#L1)):*
> ```JavaScript
> // Copyright 2015 Google Inc. All Rights Reserved.
> ```

Add _component.js suffix? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/852)*

**Comment by floreks** [comment]
Review status: 2 of 21 files reviewed at latest revision, 15 unresolved discussions.

---

*[bower.json, line 16 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjYJyAvoDB8DvpDpTR:-KJkNYmLlO7Dq2gxjnxx:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/bower.json#L16)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Nit: change version to `~`
</details>
Done.

---

*[src/app/frontend/common/components/resourcecard/resourcecardlistfooter_component.js, line 1 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjuWZk0FEkNKjs_fE0:-KJl35MBQQeFU4asO2L_:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/common/components/resourcecard/resourcecardlistfooter_component.js#L1)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Add _component.js suffix? 
</details>
Done.

---

*[src/app/frontend/common/components/resourcecard/resourcecardlistfooter_component.js, line 16 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjYe58VoPAn_8As7N6:-KJl37jWs8hIVYVFmXZy:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/common/components/resourcecard/resourcecardlistfooter_component.js#L16)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Remove the comment, it is invalid. 
</details>
Done.

---

*[src/app/frontend/common/components/resourcecard/resourcecardlistfooter_component.js, line 24 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjurRg-1KtKHkUhwF3:-KJl38X9PZ59ZHA3UF2p:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/14915b579bb437b0184f3f75da896f35b8f7a66a/src/app/frontend/common/components/resourcecard/resourcecardlistfooter_component.js#L24)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Here, you can communicate with the ctrl to determine whether the pagination should be displayed. You should be able, e.g., to get all items. 
> 
> Should we chat on slack on this? 
</details>
Done.

---

*[src/app/frontend/common/components/resourcecard/resourcecardlistfooter_component.js, line 65 \[r5\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJl1nqmyy7b38PYmCBa:-KJl1nqmyy7b38PYmCBb:-58428203) ([raw file](https://github.com/kubernetes/dashboard/blob/b9d932cecce09563af8a4deb69c4f099c6b708c4/src/app/frontend/common/components/resourcecard/resourcecardlistfooter_component.js#L65)):*
> ```JavaScript
>    * @export
>    */
>   shouldShowFooter() {
> ```

It doesn't hide footer from html but by not applying css it makes it not visible, that's why I've chosen this name. We may change that if someone has better idea.

---

*[src/app/frontend/common/pagination/pagination.html, line 1 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjYkGd6fLK2LQjLVUi:-KJl3BZ_pq5hHYDxzd2O:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/common/pagination/pagination.html#L1)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Boilerplate copyright comment? 
</details>
Done.

---

*[src/app/frontend/common/pagination/pagination_service.js, line 20 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjZvmMMVYYWJXWG0rg:-KJl3CpVhtSgsW7OPMy2:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/common/pagination/pagination_service.js#L20)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Can you explain in short what this is? 
</details>
Done.

---

*[src/app/frontend/podlist/podcardlist.html, line 33 \[r5\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJl2IHvgkRKzUzrVgM4:-KJl2IHvgkRKzUzrVgM5:-1174670864) ([raw file](https://github.com/kubernetes/dashboard/blob/b9d932cecce09563af8a4deb69c4f099c6b708c4/src/app/frontend/podlist/podcardlist.html#L33)):*
> ```HTML
> 
>   <kd-resource-card
>           dir-paginate="pod in $ctrl.podList.pods | itemsPerPage: default"
> ```

It doesn't have to be `default` and it is not checked directly but it looks better this way. Unfortunately with decorator we can't omit this parameter. I didn't wanted to create new filter because decorator looks cleaner.

---

*[src/app/frontend/index_config.js, line 17 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjYPE6n_qqF1MbaE8g:-KJkNZCGcqyhQ4v7QS6b:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/index_config.js#L17)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Yeah, this needs externs and definition there.
</details>
Done.

---

*[src/app/frontend/index_config.js, line 23 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjZFuY1clZoE19Xmen:-KJl32aIoJMJWT_KS5Q2:-499146009) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/index_config.js#L23)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> Yes sure, but I meant putting it in a common component, only once. 
> 
> Ca you create a self contained component for this? A component that can be used with no external deps. 
> 
> E.g.,
> ```html
> <kd-resource-card-list-pagination></kd-resource-card-list-pagination>
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/852)*

**Comment by bryk** [comment]
Awesome, so I have no more comments to the logic.

1. Can you test the code?
1. I'll perform tests in a while to see how this works for real. Will note here how it went. 
1. Can you rebase? 

<details><summary><i>Previously, codecov-io wrote…</i></summary>
> ## [Current coverage][cc-pull] is **93.32%**
> > Merging [#852][cc-pull] into [master][cc-base-branch] will decrease coverage by **0.64%**
> 
> 1. File `...ereader_directive.js` (not in diff) was modified. [more](https://codecov.io/gh/kubernetes/dashboard/commit/b9d932cecce09563af8a4deb69c4f099c6b708c4/changes?src=pr#7372632F6170702F66726F6E74656E642F6465706C6F792F66696C657265616465725F6469726563746976652E6A73) 
>   - Misses `-6` 
>   - Partials `0` 
>   - Hits `+6`
> 
> ```diff
> @@             master       #852   diff @@
> ==========================================
>   Files           225        230     +5   
>   Lines          1841       1874    +33   
>   Methods           0          0          
>   Messages          0          0          
>   Branches          0          0          
> ==========================================
> + Hits           1730       1749    +19   
> - Misses          111        125    +14   
>   Partials          0          0          
> ```
> 
> > Powered by [Codecov](https://codecov.io?src=pr). Last updated by [de09004...b9d932c][cc-compare]
> [cc-base-branch]: https://codecov.io/gh/kubernetes/dashboard/branch/master?src=pr
> [cc-compare]: https://codecov.io/gh/kubernetes/dashboard/compare/de09004a19d6533adfc3b02f7c89379dff98c0f9...b9d932cecce09563af8a4deb69c4f099c6b708c4
> [cc-pull]: https://codecov.io/gh/kubernetes/dashboard/pull/852?src=pr
</details>


---

Reviewed 1 of 21 files at r1, 5 of 16 files at r2, 8 of 14 files at r3, 8 of 9 files at r4, 3 of 4 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/frontend/common/components/resourcecard/resourcecardlistfooter_component.js, line 65 \[r5\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJl1nqmyy7b38PYmCBa:-KJnpYcVBWxZFZxGX0fq:-1047550762) ([raw file](https://github.com/kubernetes/dashboard/blob/b9d932cecce09563af8a4deb69c4f099c6b708c4/src/app/frontend/common/components/resourcecard/resourcecardlistfooter_component.js#L65)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> It doesn't hide footer from html but by not applying css it makes it not visible, that's why I've chosen this name. We may change that if someone has better idea.
</details>
All right, I like this. 

---

*[src/app/frontend/common/pagination/pagination_service.js, line 18 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-KJjZmbR2RRK1yZLQF8F:-KJnq9NFRRGcMLCuN0l3:2074589152) ([raw file](https://github.com/kubernetes/dashboard/blob/af48810a345872590ca711884f2a61dee64e9cbb/src/app/frontend/common/pagination/pagination_service.js#L18)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> My thinking was that we should have common configuration instead of defining same const in every controller. It is always easier to update if needed. Soon I'll be adding selector with options `10/25/50/100` to change number of visible rows on the list and I wanted to add configuration for that here. Does that make sense?
</details>
All right. Sounds good :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-:-KJnqYTO7gAyhT8A42T9:-1910009529)*

**Comment by floreks** [comment]
Rebased. Working on tests now.

**Comment by bryk** [comment]
Ok, tested on my 1k pods and works perfect. 

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Rebased. Working on tests now.
</details>


---

Review status: 18 of 21 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-:-KJo3SFf8bsLvs9oAmTM:1436852735)*

**Comment by bryk** [comment]
Let me know when you have tests.

**Comment by floreks** [comment]
Added tests. Should I add support to all resources in this PR on in the next one?

**Comment by bryk** [comment]
:lgtm:

Let's merge this one and create a new PR for other pages. 

<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Added tests. Should I add support to all resources in this PR on in the next one?
</details>


---

Reviewed 1 of 16 files at r2, 1 of 3 files at r6, 6 of 7 files at r7, 2 of 2 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/852#-:-KJoyrT8PbGfR5abeQmC:2057828097)*

**Comment by bryk** [comment]
And btw, next, just add support for this on more pages. Don't make this even better :)

**Pull request merged**
