### PR TITLE
Replica set list page initial version

### PR DESCRIPTION
**Pull request by bryk**
Plus stub for details page.

This is long, but mostly boiler plate. Please sync and check how it
works.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/693)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm @floreks Can you review?

**Comment by floreks** [comment]
I'll take it.

**Comment by floreks** [comment]
Yeah. This is pretty similar to rc list. :lgtm:

I'm wondering if we could avoid using so much boiler plate code for similar resources.

---

Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/693#-:-KGWa5y-LcDY9GYFmi9G:423998480)*

**Comment by floreks** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/app/frontend/replicasetlist/replicasetlistactionbar.html, line 18 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/693#-KGWcZ9DXh6kJ-U1CaFv:-KGWcZ9DXh6kJ-U1CaFw:1614912086) ([raw file](https://github.com/kubernetes/dashboard/blob/9cb8ae56cef54b1fbc690869ff162e94addc6c03/src/app/frontend/replicasetlist/replicasetlistactionbar.html#L18)):*
Since this will be used in more than one view, how about we move it to `actionbar.scss` and change name to `kd-actionbar-icon`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/693)*

**Comment by bryk** [comment]
Re boilerplate: Yeah, I sometimes have feeling that this it much boilerplate. But lots of it is files header (should we remove it?). The rest is angular's boilerplate that it is hard to fight with.

But I actually quite like it. We've put most of the logic into common components already, so the boilerplate is doing little things or specific to views (which is OKay).

Look at Go language which is known to be very maintainable and secure. It favors boilerplate over overdesign. So when you look at K8s apiserver code, then you'd see that replica sets are handled separately from replication controllers - they have a lot of boilerplate too.

Finally, we have a lot of good tests (thanks!), so I'm pretty confident about this code. And when, at some point, we'll decide to reduce the boilerplate-ness, we'll have a way to verify that everything works - by tests. 

---

Review status: 25 of 32 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kubernetes/dashboard/693#-KGWrk1HJHCYrjEqqbvB:-KGWrk1IwPdXeW_8aU9p:676965300) (no related file):*
PTAL

---

*[src/app/frontend/replicasetlist/replicasetlistactionbar.html, line 18 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/693#-KGWcZ9DXh6kJ-U1CaFv:-KGWqalJoalmRYLLKQ1s:-244007965) ([raw file](https://github.com/kubernetes/dashboard/blob/9cb8ae56cef54b1fbc690869ff162e94addc6c03/src/app/frontend/replicasetlist/replicasetlistactionbar.html#L18)):*
Yeah, great idea. I've done this. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/693#-:-KGWqeQTAKv6z09j0it6:1589433909)*

**Comment by floreks** [comment]
For now it's not bad. I'd just keep and eye on that. It's always harder to refactor the code when there are many places with pretty much same logic and something small has to be fixed.

---

Review status: 25 of 32 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kubernetes/dashboard/693#-KGWrk1HJHCYrjEqqbvB:-KGX2OcKLe_n5c2gC_ZP:1417088721) (no related file):*
:lgtm:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/693#-:-KGX0WlsUdnCG6IkUo0H:-1039787339)*

**Comment by floreks** [comment]
Reviewed 6 of 7 files at r2.
Review status: 30 of 32 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/frontend/workloads/workloadsactionbar.html, line 20 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/693#-KGX2vwnaEZPmYE2Plxm:-KGX2vwnaEZPmYE2Plxn:903814503) ([raw file](https://github.com/kubernetes/dashboard/blob/37c54455ef7cbc419b8a7ee0dd1ac05d4ace013a/src/app/frontend/workloads/workloadsactionbar.html#L20)):*
I don't see other files for workloads. Accidental merge? :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/693)*

**Comment by bryk** [comment]
Reviewed 1 of 26 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/workloads/workloadsactionbar.html, line 20 \[r2\]](https://reviewable.io:443/reviews/kubernetes/dashboard/693#-KGX2vwnaEZPmYE2Plxm:-KGuxBrwQl4uD97E492H:108176549) ([raw file](https://github.com/kubernetes/dashboard/blob/37c54455ef7cbc419b8a7ee0dd1ac05d4ace013a/src/app/frontend/workloads/workloadsactionbar.html#L20)):*
Yeah, correct. I'll revert workloads code from this PR. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/693)*

**Comment by bryk** [comment]
Reviewed 24 of 26 files at r1, 6 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/693)*

**Comment by floreks** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/693#-:-KGuzh0iOaC_gx-PRYrO:1417088721)*

**Pull request merged**
