### PR TITLE
Update Korean l10n for Dashboard

### PR DESCRIPTION
**Pull request by seokho-son**
This PR is to update Korean localization (i18n/messages.ko.xlf) for dashboard. 
(related issue: #4259)

I found some missing Korean translations and updated them for dashboard release v2.

I am an approver and reviewer of Korean i18n contents in Kubernetes/website (SIG-Docs). 
I tried to follow Korean localization guideline used in localizing Kubernetes official docs.

Since I couldn't organize owners for i18n/ko/ in dashboard repo yet, I hope to cc to sig-docs-ko-reviews for checking any major issues in the Korean translation.
/cc @kubernetes/sig-docs-ko-reviews

cc @maciaszczykm @shu-mutou @floreks

### CODE REVIEW

**Comment by shu-mutou** [comment]
/hold
Please check and wait for merging #4700. Then rebase to it. Thanks. 😉

**Comment by shu-mutou** [comment]
#4700 already merged. please rebase to current master.

**Comment by seokho-son** [comment]
@shu-mutou, I did rebase and translated added contents as well. Please check it :) 
This PR needs LGTM. I hope to invite Korean reviewers to check any issue in Korean translation (@gochist could you help us?).
If you think the schedule for v2.0 release is urgent, I think this PR is good to go since only minor translations are involved in this PR)
Thank you !!

**Comment by gochist** [comment]
As a native Korean speaker, LGTM
/lgtm

**Comment by shu-mutou** [comment]
/hold cancel
@seokho-son @gochist Thanks!!

**Pull request merged**
