### PR TITLE
add me to approver of dashboard

### PR DESCRIPTION
**Pull request by tanjunchen**
I see that  @shu-mutou  has looking  for Chinese managers  for dashboard  translation. I want to do .
This PR add myself to zh/OWNERS.
There are my translations for kubernetes/website:
[translation](https://github.com/kubernetes/website/pulls/tanjunchen)
/assign @maciaszczykm 
/assign @hwdef 
/assign @shu-mutou 
Thanks.

### CODE REVIEW

**Comment by zehuaiWANG** [comment]
I am also willing to submit some pr for the Chinese version.

**Comment by hwdef** [comment]
/hold 
@shu-mutou 
@maciaszczykm 

Please review this PR.Thank you very much.

**Comment by hwdef** [comment]
@tanjunchen 
Thanks for your contribution for chinese translation.
welcome to dashboard/i18n/zh!

**Comment by shu-mutou** [comment]
/lgtm
Thank you for having interests for dashboard i18n!

**Pull request merged**
