### PR TITLE
Refactor RC backend and prepare for pagination support

### PR DESCRIPTION
**Pull request by floreks**
I've reafctored rc backend and a bit of frontend to match other resources coding style. Also I've added new endpoints in order to support pagination of related resources.

New style assumes that all related resources on detail pages will be exposed using following style:
`api/v1/<resource>/<namespace>/<resourceName>/<relatedResource>`

Newly exposed endpoints:
`api/v1/replicationcontroller/<namespace>/<resourceName>/pod`
`api/v1/replicationcontroller/<namespace>/<resourceName>/event`
`api/v1/replicationcontroller/<namespace>/<resourceName>/service`

Pagination support will be added in next PR.

#### TODO
- [x] Add tests
- [x] Add doc

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1023)

### CODE REVIEW

**Comment by bryk** [comment]
Looks nice. Please continue with your TODOs. 

---

Reviewed 34 of 38 files at r1.
Review status: 34 of 38 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/backend/resource/common/service.go, line 21 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1023#-KMZTCLTTInIu_Hz-rx8:-KMZTCLUCqe7BwUUfcTJ:677251276) ([raw file](https://github.com/kubernetes/dashboard/blob/9fd6b2b0a922eef016f0367b2fc294ef7494c8d4/src/app/backend/resource/common/service.go#L21)):*
> ```Go
> )
> 
> // TODO add doc
> ```

Yes.

---

*[src/app/externs/backendapi.js, line 32 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1023#-KMZTsI-hBSsyl8XN_hd:-KMZTsI-hBSsyl8XN_he:915840158) ([raw file](https://github.com/kubernetes/dashboard/blob/9fd6b2b0a922eef016f0367b2fc294ef7494c8d4/src/app/externs/backendapi.js#L32)):*
> ```JavaScript
>  *    page: number,
>  *    namespace: string,
>  *    name: (string|undefined)
> ```

What is this? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1023#-:-KMZU7IHdxGLCjUwZTJL:1938004169)*

**Comment by floreks** [comment]
Review status: 34 of 38 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/externs/backendapi.js, line 32 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1023#-KMZTsI-hBSsyl8XN_hd:-KMZUZXr8hdZYegpOBHt:1675545464) ([raw file](https://github.com/kubernetes/dashboard/blob/9fd6b2b0a922eef016f0367b2fc294ef7494c8d4/src/app/externs/backendapi.js#L32)):*
<details><summary><i>Previously, bryk (Piotr Bryk) wrote…</i></summary>
> What is this? 
</details>
This is added, so the detail pages can still use this structure. I can omit `name` property on structure creation and still compiler will accept jsdoc with this type. Like done in [here](https://github.com/kubernetes/dashboard/pull/1023/files#diff-87f93053b70815f71c8b77902f3256caR117).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1023)*

**Comment by bryk** [comment]
:lgtm: 

Please merge. 

---

Reviewed 2 of 38 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/externs/backendapi.js, line 32 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1023#-KMZTsI-hBSsyl8XN_hd:-KMcEUDpr0u0rfiIOaGk:-622821353) ([raw file](https://github.com/kubernetes/dashboard/blob/9fd6b2b0a922eef016f0367b2fc294ef7494c8d4/src/app/externs/backendapi.js#L32)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> This is added, so the detail pages can still use this structure. I can omit `name` property on structure creation and still compiler will accept jsdoc with this type. Like done in [here](https://github.com/kubernetes/dashboard/pull/1023/files#diff-87f93053b70815f71c8b77902f3256caR117).
</details>
Ok, sounds reasonable. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1023#-:-KMcEYm_uHB3w7k5gO73:1051675779)*

**Comment by floreks** [comment]
Added test

**Comment by bryk** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1023)*

**Pull request merged**
