### PR TITLE
Disable flaky tests until IE issue is resolved

### PR DESCRIPTION
**Pull request by floreks**
I'd propose to disable tests that fail on IE for now. I've investigated that and explained probable cause of that in #494. We should discuss that in there and find some solution.

@maciaszczykm @batikanu @bryk 

---
This change is [Review on Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/514)

### CODE REVIEW

**Comment by batikanu** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/514#-:-KCQzss5HKgHro9VqAeZ:1417088721)*

**Comment by batikanu** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/514)*

**Comment by maciaszczykm** [comment]
We should make master green now and then search for a solution for it. LGTM

**Comment by bryk** [comment]
Yeah, thanks!

**Pull request merged**
