### PR TITLE
Fix redirect-loop issue that happens on errors

### PR DESCRIPTION
**Pull request by bryk**
Previously to reprodce:
1. Start a proxy and a dev server
2. Kill the proxy
3. Open the UI
4. See that it is in a redirect loop

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1203)

### CODE REVIEW

**Comment by bryk** [comment]
@digitalfishpond Can you review this?

**Comment by digitalfishpond** [comment]
Travis seems unhappy...

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1203#-:-KR7zGuYoZiZszUUg5aC:bx81az0)*

**Comment by bryk** [comment]
Fixed. PTAL 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1203#-:-KR82IpaeBqOPrGc--ZM:b-73um0g)*

**Comment by digitalfishpond** [comment]
:lgtm:  :)

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1203#-:-KR86X4iIL4IVRNqjJCg:b4xxo5c)*

**Pull request merged**
