### PR TITLE
Sanitize our access to $location.search().namespace

### PR DESCRIPTION
**Pull request by rf232**
quick way to make sure we only show sanitized namespaces, perhaps research if this is intended behaviour of this select component and if we should do more.

#1361

### CODE REVIEW

**Comment by rf232** [comment]
hmm, quick manual testing shows that this works only half the times, (in a nice oscillating sequence)

**Comment by bryk** [comment]
> hmm, quick manual testing shows that this works only half the times, (in a nice oscillating sequence)

You say that the content is not sanitized sometimes?

**Comment by rf232** [comment]
yes, or at least later than needed.

**Comment by bryk** [comment]
Let me test this...

**Comment by rf232** [comment]
PTAL

**Pull request merged**
