### PR TITLE
Add related Services to Replica Set Details page

### PR DESCRIPTION
**Pull request by digitalfishpond**
Replica Set Details now includes a section with related Services
#1087

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1088)

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@batikanu Can you review?

@digitalfishpond Please remember to use `gofmt` on Go code.

**Comment by batikanu** [comment]
sure

**Comment by digitalfishpond** [comment]
Comment amended and Go code formatted with gofmt (thx for the heads up!)

---

Review status: 6 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/backend/resource/replicaset/replicasetdetail.go, line 41 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/1088#-KOAaTxvzNvoy3V_5RSP:-KOE5zrt5GXGelXMbUIZ:-1024374843) ([raw file](https://github.com/kubernetes/dashboard/blob/c2d6da4784ad5418458a528d325398d993f06ffa/src/app/backend/resource/replicaset/replicasetdetail.go#L41)):*
<details><summary><i>Previously, batikanu (Batikan Urcan) wrote…</i></summary>
> Service related Daemon Set or Replica Set?
</details>
Ah :) Well spotted!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1088#-:-KOE9KSVFtB0Sjn3-ZFh:73475077)*

**Comment by digitalfishpond** [comment]
PTAL

---

Review status: 6 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1088#-:-KOEg0VCGbTL-QgGR_sz:676965300)*

**Comment by maciaszczykm** [comment]
:lgtm:

---

Reviewed 1 of 11 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1088#-:-KOF1CbxVZZdXqlkjKC_:1417088721)*

**Pull request merged**
