### PR TITLE
Increase version to 1.4.0-beta1 in preparation for release

### PR DESCRIPTION
**Pull request by bryk**
This also synchronizes version numbers with the core
(i.e., we jump from 1.1 to 1.4).

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1155)

### CODE REVIEW

**Comment by bryk** [comment]
@maciaszczykm @floreks Can you review?

**Comment by maciaszczykm** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1155)*

**Comment by floreks** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1155#-:-KQ5SIzCkf9mYx5TLuqp:bnfp4nl)*

**Comment by cheld** [comment]
What about upgrading Hyperkube, too?

**Comment by maciaszczykm** [comment]
@cheld I think it's a task to be done in another pull request. Not connected to Dashboard release.

**Comment by bryk** [comment]
@cheld 
> What about upgrading Hyperkube, too?

What is the latest version of hyperkube? Do you have a link?

**Comment by floreks** [comment]
https://gcr.io/v2/google_containers/hyperkube/tags/list

Latest version is `v1.4.0-alpha.3`.

**Pull request merged**
