### PR TITLE
Translation namespace create page and image pull secret page to Japanese

### PR DESCRIPTION
**Pull request by Yamagami-Takuma**
Japanese translation of namespace create page and image pull secret page.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/804)

### CODE REVIEW

**Comment by f-higashi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[i18n/messages-ja.xtb, line 5 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/804#-KJIZDxFVZcX6g-F5oeV:-KJIZDxFVZcX6g-F5oeW:724084025) ([raw file](https://github.com/kubernetes/dashboard/blob/4229ad5e4a941701b894f2a23ee74f84b8ce38e2/i18n/messages-ja.xtb#L5)):*
> ```
> <translationbundle lang="ja">
> 	<translation id="1629323405372811987" key="MSG_NAMESPACE_CREATE_DIALOG_TITLE" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Create namespace dialog title. The message appears at the top of the dialog box.">新規ネームスペースの作成</translation>
> 	<translation id="7894572953642738628" key="MSG_NAMESPACE_CREATE_DIALOG_SUBTITLE" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Create namespace dialog subtitle. Appears right below the title.">新規ネームスペースはクラスターに追加されます</translation>
> ```

This is not natural.
I like  "新規ネームスペースをクラスターに追加します"

---

*[i18n/messages-ja.xtb, line 13 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/804#-KJIZrF0xPeD2SiqNwUS:-KJIZrF1-hFhFo6kItyr:-680384674) ([raw file](https://github.com/kubernetes/dashboard/blob/4229ad5e4a941701b894f2a23ee74f84b8ce38e2/i18n/messages-ja.xtb#L13)):*
> ```
> 	<translation id="4850098313852875572" key="MSG_NAMESPACE_CANCEL_ACTION" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="The text is put on the 'Cancel' button in the namespace creation dialog.">キャンセル</translation>
> 	<translation id="6489624424433759035" key="MSG_IMAGE_PULL_SECRET_CREATE_DIALOG_TITLE" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Create image pull secret dialog title. The message appears at the top of the dialog box.">新規イメージプルシークレットの作成</translation>
> 	<translation id="3382981767955244666" key="MSG_IMAGE_PULL_SECRET_CREATE_DIALOG_SUBTITLE" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Create image pull secret dialog subtitle. Appears right below the title.">新規イメージプルシークレットはクラスターに追加されます</translation>
> ```

I like "新規イメージプルシークレットをクラスターに追加します"

---

*[i18n/messages-ja.xtb, line 18 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/804#-KJIazxqOry-5LeNIrGu:-KJIazxrm0jCddXebWR3:957411883) ([raw file](https://github.com/kubernetes/dashboard/blob/4229ad5e4a941701b894f2a23ee74f84b8ce38e2/i18n/messages-ja.xtb#L18)):*
> ```
> 	<translation id="4127420758208322272" key="MSG_IMAGE_PULL_SECRET_NAME_LENGTH_WARNING" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="The text appears when the image pull secret name exceeds the maximal length.">最大 <ph name="MAX_LENGTH" /> 文字です</translation>
> 	<translation id="7263428501718162087" key="MSG_IMAGE_PULL_SECRET_NAME_REQUIRED_WARNING" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Warning which tells the user that the image pull secret name is required.">必須項目です</translation>
> 	<translation id="8342519402917559446" key="MSG_IMAGE_PULL_SECRET_CREATE_DIALOG_USER_HELP" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="User help text for the create image pull secret dialog. Directly after this text a specific namespace is specified.">指定した名前のシークレットはネームスペースのクラスターに追加されます</translation>
> ```

This is unnatual.
How about "指定した名前のシークレットは、次のネームスペースでクラスターに追加されます"

---

*[i18n/messages-ja.xtb, line 22 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/804#-KJIdE8Mq4RNrCXW8ln7:-KJIdE8NDa11jrsLeM7-:-251258610) ([raw file](https://github.com/kubernetes/dashboard/blob/4229ad5e4a941701b894f2a23ee74f84b8ce38e2/i18n/messages-ja.xtb#L22)):*
> ```
> 	<translation id="3432622161353334586" key="MSG_IMAGE_PULL_SECRET_DATA_REQUIRED_WARNING" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="Warning which tells the user that the image pull secret data is required.">必須項目です</translation>
> 	<translation id="6217421730854783216" key="MSG_IMAGE_PULL_SECRET_DATA_BASE64_WARNING" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="The text appears when the image pull secret data is not Base64 encoded.">Base64 エンコード化してください</translation>
> 	<translation id="7793557773608682327" key="MSG_IMAGE_PULL_SECRET_DATA_USER_HELP" source="/home/mirchev/go_workspace/src/github.com/kubernetes/dashboard/.tmp/serve/app-dev.js" desc="User help text for the input of the &quot;Image Pull Secret&quot; data.">シークレットを保持するためのデータを指定してください。値は .dockercfg ファイルの Base64 エンコードコンテンツです。</translation>
> ```

I think "シークレット" is "機密" in first sentense.

The second sentense is hard to understand.
 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/804)*

**Comment by Yamagami-Takuma** [comment]
I posted a request for review on a kubernetes.slack japanese channel.
https://kubernetes.slack.com/messages/jp-users/

**Comment by Yamagami-Takuma** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[i18n/messages-ja.xtb, line 5 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/804#-KJIZDxFVZcX6g-F5oeV:-KJIzOjem3q-_3YcQaEi:1641746019) ([raw file](https://github.com/kubernetes/dashboard/blob/4229ad5e4a941701b894f2a23ee74f84b8ce38e2/i18n/messages-ja.xtb#L5)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> This is not natural.
> I like  "新規ネームスペースをクラスターに追加します"
</details>
It looks good. I modified.

---

*[i18n/messages-ja.xtb, line 13 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/804#-KJIZrF0xPeD2SiqNwUS:-KJIzuBqK8VdbZU7MYTX:1176402249) ([raw file](https://github.com/kubernetes/dashboard/blob/4229ad5e4a941701b894f2a23ee74f84b8ce38e2/i18n/messages-ja.xtb#L13)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> I like "新規イメージプルシークレットをクラスターに追加します"
</details>
I modified.

---

*[i18n/messages-ja.xtb, line 18 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/804#-KJIazxqOry-5LeNIrGu:-KJIzySzXIR12s9lDbsh:-1860609237) ([raw file](https://github.com/kubernetes/dashboard/blob/4229ad5e4a941701b894f2a23ee74f84b8ce38e2/i18n/messages-ja.xtb#L18)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> This is unnatual.
> How about "指定した名前のシークレットは、次のネームスペースでクラスターに追加されます"
> 
</details>
It looks good. I modified as you write.
And I added a colon at the end of this sentence, because the namespace name is displayed after this sentence.

---

*[i18n/messages-ja.xtb, line 22 \[r1\]](https://reviewable.io:443/reviews/kubernetes/dashboard/804#-KJIdE8Mq4RNrCXW8ln7:-KJJ0tpk6TPY4fZLheRE:335417905) ([raw file](https://github.com/kubernetes/dashboard/blob/4229ad5e4a941701b894f2a23ee74f84b8ce38e2/i18n/messages-ja.xtb#L22)):*
<details><summary><i>Previously, f-higashi (higashi isao) wrote…</i></summary>
> I think "シークレット" is "機密" in first sentense.
> 
> The second sentense is hard to understand.
>  
</details>
I modified the first sentence.
And modified second sentence more understandable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/804)*

**Comment by bryk** [comment]
Please tell when the review is done so that we can merge :) Thanks!

**Comment by f-higashi** [comment]
LGTM

@bryk 
You can merge this :)

**Comment by floreks** [comment]
Great! Thanks.

**Pull request merged**
