### PR TITLE
Adjust fonts and styles

### PR DESCRIPTION
**Pull request by floreks**
Adjusted nav bar, breadcrumbs and app bar according to @romlein's suggestions ([1](https://github.com/kubernetes/dashboard/issues/908#issuecomment-245921422), [2](https://github.com/kubernetes/dashboard/issues/908#issuecomment-245959186)).

Changes:
- [x] Change primary navigation item height from 40px to 44px
- [x] Add 8px top padding to side nav content
- [x] Add 32px bottom padding to the last object in side nav
- [x] **Namespace**: Change dropdown arrow opacity to .54 and align to the edge of underline
- [x] **Namespace**: Change dropdown arrow left margin to 24px
- [x] **Namespace**: Change font to Roboto Mono Medium
- [x] **Namespace**: Change dropdown bottom border focus color from blue to gray (Should selection indication be completely removed?)
- [x] Change breadcrumbs font to Roboto Medium 18px
- [x] Change app bar height from 64px to 56px
- [x] Change kubernetes text to SVG logo

Needs clarification:
- [x] Material icon called keyboard arrow right should be used between levels of hierarchy rather than the > character (is it arrow between breadcrumbs?)
- [ ] **Namespace**: Remove default dropdown dialogue selection from item (could be hard as it's default angular material behavior)
- [ ] **Namespace**: Change height to 32px height (namespace text or namespace selector?)
- [ ] **Namespace**: Change bottom border spacing to 10px away from the text (could be hard as it's default spacing of `border-bottom` and `border-spacing` doesn't work here)

zrzut ekranu z 2016-09-11 22-08-28

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/1212)

### CODE REVIEW

**Comment by floreks** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/frontend/_variables.scss, line 25 at r1](https://reviewable.io:443/reviews/kubernetes/dashboard/1212#-KRPqTS3xR22RFZELpw2:-KRPqTS3xR22RFZELpw3:b-3fvyg0) ([raw file](https://github.com/kubernetes/dashboard/blob/753ac000c9c576debf21b12ff8e1eefffcc54987/src/app/frontend/_variables.scss#L25)):*
> ```SCSS
> $display-1-font-size-base: rem(3.4) !default;
> $headline-font-size-base:  rem(2.4) !default;
> $subhead-font-size-base-lg: rem(1.8) !default;
> ```

Should we use existing font sizes or can it stay this way?

---

*[src/app/frontend/chrome/chrome.scss, line 20 at r1](https://reviewable.io:443/reviews/kubernetes/dashboard/1212#-KRPqasQK1dN2i6NmIo7:-KRPqasQK1dN2i6NmIo8:brxlji9) ([raw file](https://github.com/kubernetes/dashboard/blob/753ac000c9c576debf21b12ff8e1eefffcc54987/src/app/frontend/chrome/chrome.scss#L20)):*
> ```SCSS
>   height: 5 * $baseline-grid;
>   margin-right: 1em;
>   width: 14 * $baseline-grid;
> ```

Feel free to find better values here for kubernetes logo.

---

*[src/app/frontend/common/namespace/namespaceselect.scss, line 62 at r1](https://reviewable.io:443/reviews/kubernetes/dashboard/1212#-KRPqwytLN7BLM6gW7Jh:-KRPqwyulev4mLo29QUw:b1dm9lq) ([raw file](https://github.com/kubernetes/dashboard/blob/753ac000c9c576debf21b12ff8e1eefffcc54987/src/app/frontend/common/namespace/namespaceselect.scss#L62)):*
> ```SCSS
>       &.kd-namespace-select {
>         .md-select-value {
>           border-bottom-color: $foreground-4;
> ```

Should we introduce new variable for this? `$foreground-x` may be misleading.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1212)*

**Comment by bryk** [comment]
>  Material icon called keyboard arrow right should be used between levels of hierarchy rather than the > character (is it arrow between breadcrumbs?)

It is this: 


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1212#-:-KRS17vFxAGmO6azsWs9:bdj87b)*

**Comment by bryk** [comment]
Can you align "Ingress" with the card?


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1212#-:-KRS2haW22_Cs_Gc-JNa:ba2dbm5)*

**Comment by bryk** [comment]
This is super cool! Can you apply my two comments and merge? Let's resolve the questions about namespaces asynchronously :) 

:lgtm: 

---

Reviewed 3 of 8 files at r1, 2 of 2 files at r2.
Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1212#-:-KRS3Xgqk4woo0AYq_N6:blpfeq3)*

**Comment by floreks** [comment]
Done

zrzut ekranu z 2016-09-12 09-30-58

**Comment by floreks** [comment]
I'll merge after travis passes.

**Comment by bryk** [comment]
:lgtm:

---

Reviewed 3 of 8 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/frontend/_variables.scss, line 25 at r1](https://reviewable.io:443/reviews/kubernetes/dashboard/1212#-KRPqTS3xR22RFZELpw2:-KRSMMVb7BmIURW-XbjU:b9flv14) ([raw file](https://github.com/kubernetes/dashboard/blob/753ac000c9c576debf21b12ff8e1eefffcc54987/src/app/frontend/_variables.scss#L25)):*
<details><summary><i>Previously, floreks (Sebastian Florek) wrote…</i></summary>
> Should we use existing font sizes or can it stay this way?
</details>
Seems fine. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/dashboard/1212#-:-KRSMR3Sp839AP9fKBhd:bnfp4nl)*

**Comment by romlein** [comment]
@floreks breadcrumb font should be Roboto Medium, not Roboto _Mono_ Medium.

**Pull request merged**
