### PR TITLE
Integrate build system tasks to make them work

### PR DESCRIPTION
**Pull request by bryk**
This is build integration commit after my recent set of separate changes with standalone tasks. Now, every task works and produces reliable output.

Here I, e.g., change paths so that files are served correctly and fix source maps in style tasks.

### CODE REVIEW

**Comment by bryk** [comment]
Don't mind travis errors. It is not configured yet.

**Comment by bryk** [comment]
Fixed travis errors. Now CI works.

**Comment by bryk** [comment]
@PeWu Can you take a look?

**Comment by PeWu** [comment]
LGTM

**Pull request merged**
