### PR TITLE
Fix format; "=>'

### PR DESCRIPTION
**Pull request by f-higashi**
clang-format updated to v1.0.36 which checks double quotation.

https://travis-ci.org/kubernetes/dashboard/builds/116048772

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/dashboard/532)

### CODE REVIEW

**Comment by cheld** [comment]
Thanks, nice - kind of....So, clang was updated to minor version 1.0.36 (because we use ~ in package.json). As a result our build broke and you fixed it, right? Hmm, what about Greenkeeper? If we would have specified a specific version, than Greenkeeper would have tested and suggested the update, right? 

Anyway, result is nice

**Comment by f-higashi** [comment]
> As a result our build broke and you fixed it, right?

yes.

Currently, we specifies gulp-clang-format which depends on clang-format and does not update recently.
In this case, Greenkeeper does not work maybe.

**Comment by floreks** [comment]
For me npm still download old version of `gulp-clang-format`. Even if I delete it still 1.0.23 is downloaded. Did you change the configuration? I'm using npm 3.8.0

**Comment by floreks** [comment]
I've cleared cache and removed all `clang-format` dependencies. New version is downloaded.

**Comment by floreks** [comment]
:lgtm:

---

Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kubernetes/dashboard/532#-:-KCtNpgbF6OfSb2ULnCE:1417088721)*

**Pull request merged**
